# 1. The Earliest Education

**Outline**

-   Even a brief survey of the history of education may greatly broaden one's view.
-   Starting with primitive man, we find that his training aims only at the necessities of life, and is acquired informally through the elders and the medicine-men.
-   In Oriental education, the next stage in progress, illustrated by India, a traditional knowledge is acquired through *memoriter* and imitative methods.
-   While Oriental, Jewish education afforded greater development of individuality, but it was late in organizing schools, *memoriter* in methods, and restricted in content.
-   Thus all education before the day of the Greeks was largely *nonprogressive.*

**The Value of the History of Education.** - The History of Education from the earliest times should contribute largely to one's breadth of view and prove a study of the greatest liberal culture. A record of typical instances of the moral, aesthetic, and intellectual development of man in all lands and at all periods should certainly enlarge one's vision and enable him to appreciate more fully the part that education has played in the progress of civilization. Such cultural values may be found even in a limited survey of the world's educational development.

**It's Treatment in This Book.** - And this is all that will be undertaken here. For, while valuable as a liberal study, the History of Education finds its justification chiefly in the degree to which it functions in the professional training of a teacher, and it will be necessary in a brief treatise to omit or pass over hastily much that might be of interest and value in a more complete account of the development of civilization. Therefore, the amount of space and the perspective afforded the various peoples, epochs, and leaders must here be determined in large measure by the part they have played in the evolution of educational institutions and practices, and by the light their history sheds upon the aim, organization, content, and method of education to-day. At times, too, the history of a single epoch, state, or educational leader will be selected as a type, to the exclusion of others equally important, and treated with considerable intensiveness, instead of describing all sides of the subject with encyclopaedic monotony. Now the first historical epoch to leave a real impress upon modern practice is that of Athens at its height. Hence a mere statement of the salient features of education preceding that period is all that can be afforded in this brief survey. A detailed account of the educational processes used by savage tribes, Oriental nations, and even Judaea may prove interesting and important in other connections, but it must here be largely curtailed.

**Primitive Education.** There is little to be noted in the training of the young among primitive peoples, save that it is intended largely for the satisfaction of immediate wants - food, clothing, and shelter. Naturally no such actual institution as a school has yet been evolved, but the training is transmitted informally by the parents. The method used is simply that of example and imitation, or, more specifically, 'trial and success.' But a more conscious and formal education is given at puberty through the 'initiatory ceremonies' (Fig. i). In these rites the youths are definitely instructed by the older men about their relation to the spirits and the totem animals, subordination to the elders, the relations of the sexes, the sacredness of the clansman's obligations, and other traditional usages. Strict silence is enjoined upon them concerning this information, and to impress it upon their minds, and test their endurance, they are required to fast for several days and are often tortured and mutilated. As the savage does not clearly distinguish between himself and the tribe to which he belongs, there is practically no development of individuality, and since the race has not yet learned to treasure its experience in writing, he has no record of past experience and is virtually tied to the present.

**Oriental Education.** - The nations of the ancient Orient - Egypt, Babylonia, Assyria, China, India, and Persia - may be said to represent the next higher stage in civilization. Their systems of education prepare mostly for vocations, and are not sufficiently advanced to undertake a training for manhood or citizenship. But since a division of labor has now been evolved, the training has become more clearly differentiated and fits for specific occupations. In this way, class divisions, or even castes, have generally arisen in society, and the young people are educated according to the position in life they desire, or are required to fill. As an illustration of this stage of development, we may consider somewhat in detail the social environment and education of India.

**India: Its Religion and Castes** - In India, largely as a result of the debilitating climate, there was formulated about 1200 B. C. a dreamy philosophy, according to which nothing except Brahma, the one universal spirit, really exists. While men would seem to be temporarily allowed a separate existence of their own, it was held that they should remain inactive as far as possible and seek an ultimate absorption into the great Eternal Spirit. Although somewhat modified by the infusion of Buddhism, between 500 B. C. and 500 A. D., and by the British occupation of the peninsula during the nineteenth century, this mystic and static religion still dominates in India. Connected with it is the caste system, by which the people are divided into four hereditary classes. These are (1) the *brahmins,* or sacerdotal class, which includes all those trained for law, medicine, teaching, and other professional occupations; (2) the warriors, or military and administrative caste; (3) the industrial group; and (4) the *sudras,* or menial caste. Altogether outside the social order are the *pariahs,* or outcasts. The caste system is exceedingly strict. One may fall into a lower caste, but he cannot rise, and loss of caste by one person in a family will degrade all the rest.

**The Hindu Education.** - Hence Hindu education has always endeavored to fill the pupils with the tenets of their religion, and so prepare them for absorption into the Infinite, rather than for activities in this life, and to preserve the caste system and keep all within the sphere of their occupation. The three upper castes are, therefore, supposed to gain a knowledge of certain sacred works, especially the four *Vedas* or books of 'knowledge,' the six *Angas* on philosophical and scientific subjects, and the *Code of Manu,* which is a collection of traditional customs; but few, outside the brahmin class, are ever allowed to take advantage of this opportunity. The warriors are expected to pay more attention to martial exercises, and the industrial caste to acquire through apprenticeship the arts necessary for its hereditary occupations. Sudras, pariahs, and women are generally allowed no education. Except the sudras, all the castes obtain elementary education from a study of the laws, traditions, and customs of the country through the medium of the family, and more recently through village schools held in the open air (Fig. 2). The higher education is largely carried on in brahminic colleges, called *parishads,* and, as also in the case of the elementary work, the teachers have to be brahmins. Since all learning has been preserved by tradition, the chief methods of instruction are those of memorizing and imitation. Even the later texts are so written as to be easily committed, and the lines are sung aloud by the pupils until they have memorized them. Writing is learned by imitating the teacher's copy on the sand with a stick, then on palm leaves with a stylus (Fig. 2), and finally on plane leaves with ink.

**Effect of the Hindu Education.** - Hence, among the Hindus education is forbidden to ninety-five per cent of the population, and, as far as it does exist, it is a mere stuffing of the memory. It concerns itself but little with mental culture or with preparation for real living. The brahmins have handed down considerable traditional learning, grammar, phonetics, rhetoric, logic, 'Arabic' notation, algebra, astronomy, and medicine, but new knowledge of any sort is barred. The Hindus still plow with sticks of wood, and their crops are harvested and threshed by devices equally primitive. They bake bricks, work metals, and weave cloth, but with the same kind of appliances that were used by their remote ancestors. Until recently, they have been greatly lacking in ambition, self-reliance, and personal responsibility, and have not yet come to any feeling of solidarity or national unity. To them prosperity and progress are foreign ideas.

**India as Typical of the Orient.** - The other countries of the ancient Orient never fixed their social classes in so hard and fast a manner, and have never included so elaborate a philosophy among the products of their culture. But India may well be considered broadly typical of the stage of development in the Orient. Certain common features appear in the education of all the nations there. In the system of each, the classes below the sacerdotal or priestly are given little intellectual education, and the women none at all, but both are trained by apprenticeship in their vocations. Actual schools, both elementary and higher, have been instituted; and the latter, except in China, are conducted at temples or priestly colleges by members of the sacerdotal class. The educational content is naturally traditional. It is, for the most part, ensured against change by being embalmed in sacred books, such as the *Vedas.* The educational method consists largely in the memorizing of the text and imitation of the copy set, and little attempt is made to give a reason for the customs and traditional knowledge taught. Hence, while individuality has begun to emerge, it is suppressed by every agency possible; and, although these peoples have largely overcome the primitive enslavement to nature and the present, they are completely in bondage to the past.

**Jewish Education.** - The Jews are classed among the nations of the Orient, but they formulated loftier aims and have exerted more influence upon modern ideals in education. While their theology greatly developed in the course of their history, from the first they held to an ethical conception of God, and the chief goal of their education was the building of moral and religious character. Not until after the Babylonish captivity (586-536 B. C), however, did they establish actual schools. Before that, children were given an informal training in the traditions and observances of their religion by their parents. But they brought back from Babylon the idea of institutions for higher training and started such schools through their synagogues. In the second century B. C. the founding of elementary schools also began, and eventually the Jews made education well-nigh universal. The beneficial effect of this training is seen in the respect shown by the Jews for their women, their kind treatment of children, and their reverence for parents. The defects of their education appear in the stereotyped and formal way in which the religious material came to be interpreted, and the consequent hostility to science and art, except as they threw light on some religious festival or custom. Although appeal was made to various types of memory, systems of mnemonics devised, and other good pedagogical features suggested, their methods of instruction were largely *memoriter.* The Jewish system of education, as a whole, afforded a greater development of personality than that of the other Oriental nations, and through it have been spread some of the world's most exalted religious conceptions. Nevertheless, it did not depart much from its traditions and the past, and to this extent it may be classed with the training of the primitive tribes and of the Oriental nations as predominantly *non-progressive.*

Supplementary Reading

For general works, see Graves, F. P., *History of Education before the Middle Ages* (Macmillan, 1909), chaps. I-XI; Monroe, P., *Text-book in the History of Education* (Macmillan, 1905), chaps. I-II. A general interpretation of the evolution of education in savagery and barbarism is also given in Laurie, S. S., *Pre-Christian Education* (Longmans, Green, 1909), pp. 1-207; Morgan, L. H., *Ancient Society* (Holt, 1907), Part I; and Taylor, H. O., *Ancient Ideals* (Macmillan, 1913), vol. I, chaps. I-V. An illustration of primitive training of especial interest to American students is found in Spencer, F. C., *Education of the Pueblo Child* (Columbia University, Department of Philosophy and Psychology, vol. 7, no. 1); and a detailed description of the puberty rites of a variety of savage tribes, in Webster, H., *Primitive Secret Societies,* (Macmillan, 1908), chaps. I-V. A more complete account of the Hindu philosophy and education appears in Dutt, R. C, *Civilization of India* (Dent, London), and Taylor, H. O., *Ancient Ideals* (Macmillan, 1913), vol. I, chaps. Ill and IV. A systematic statement of the Jewish training has been adapted from a German work, in Leipziger, H. M., *Education of the Jews* (New York Teachers College, 1890), and a more detailed account worked out in Spiers, B., *School System of the Talmud* (Stock, London, 1898).
