# 12. The Humanistic Education

**Outline**

-   By the fourteenth century there appeared an intellectual awakening, known as the *Renaissance.* It was accompanied by a 'revival of learning' and an education called 'humanistic'
-   Italy first showed evidence of the new movement. The characteristics of the Renaissance were embodied in Petrarch and Boccaccio, but little was done with the Greek classics until Chrysoloras came from Constantinople.
-   The tyrants of various cities often had humanistic schools started at their courts. Of these the most typical was that under Vittorino da Feltre. These schools eventually forced the universities to admit the humanities to their course. But humanism gradually degenerated into 'Ciceronianism.'
-   Humanistic education also gradually spread to the countries north of Italy, but it there took on more of a moral color. In France, the protection of Francis I encouraged the introduction of humanism into educational institutions by various scholars. The German universities likewise began to respond to humanistic influences.
-   The Hieronymians first introduced the classics into the schools, and Erasmus, who was trained by them, became the leader in humanistic education. Through other humanistic schools started by Sturm and others, the 'gymnasium,' the typical classical school of Germany, was evolved, and the humanistic education became fixed and formal.
-   In England the movement gradually developed at Oxford and Cambridge, and Colet started St. Paul's school, which became the model for all secondary schools. Humanism in England, however, soon retrograded into a formalism, and the 'grammar' and 'public' schools there are little changed to-day.
-   The first secondary schools in the American colonies were modeled after the grammar schools of the mother country.

**The Passing of the Middle Ages.** - It can now be seen that a new spirit had crept into European civilization, and that the Middle Ages were passing. We have previously noted (pp. 53 f.) that, in order to bring the German barbarians up to the level of the past, it was necessary for the Church to set an authoritative standard and repress all variation on the part of the individual. Yet such bondage of the human spirit was unnatural, and there were periodic tendencies to rebel against the sysMediajvaiism tem. In fact, mediaevalism contained within itself the germ Sits own germ of its own emancipation. During the eighth century there came about a new political order, which culminated in Charlemagne's revival of education. While conditions were never again as desperate after this stimulus, with the disruption of Charlemagne's empire another decline set in. But by the thirteenth century a new revival, material and intellectual, had also appeared. Several developments gave evidence of the expansion within, and assisted in producing it. The broadening of horizon through contact with the Moors, the development of scholasticism, the evolution of universities, the worldly appeal of chivalry, and the growth of cities, gilds, and commerce were all helping by accumulation to dispel the mediaeval spirit.

And by the fourteenth century a new dawn had been ushered in. The period that followed was marked by a general intellectual and cultural progress that began to free men from their bondage to ecclesiasticism and to induce them to look at the world about them. The adherence to an 'otherworldly' ideal, the restriction of learning, the reception of the teachings of the Church without investigation, and the conformity of the individual were by this time rapidly disappearing. Such tendencies were clearly being replaced by a genuine joy in the life of this world, a- broader field of knowledge and thought, a desire to reason and deal with all ideas more critically, and enlarged ideals of individualism. The days of mere absorption and assimilation had passed.

**The Renaissance and the Revival of Learning.** - This tremendous widening of horizon has been generally known as the *Renaissance* or 'new birth.' The term is used to indicate that the spirit of the Graeco-Roman development had returned, and that opportunity for expression was granted to the individual once more. But this period is also appropriately known as the 'Revival of Learning.' For, while the awakening preceded and was caused by internal factors, rather than by the recovery of classical literature and learning, intellectual freedom was very greatly heightened and forwarded after a restoration of the classics once began. The only food at hand that could satisfy the awakened intelligence of the times was the literature and culture of the classical peoples. The discovery that the writings of the ancient world were filled with a genuine vitality and virility, and that the old authors had dealt with world problems in a profound and masterly fashion, and with far more vision than had ever been possible for the mediaevalists, gave rise to an eager desire and enthusiasm for the classics that went beyond all bounds. A knowledge of classical literature had never altogether disappeared, and various works had been preserved by the monks and others. To search out the manuscripts of the Latin and Greek writers, the monasteries, cathedrals, and castles were now ransacked from end to end. The manuscripts found were rapidly multiplied, and the greatest pains taken to secure the correct form of every passage. The devotees of the new movement were generally called 'humanists,' and the training embodying the classics has since been termed 'humanistic education.'

**Causes of the Awakening in Italy.** - While the general tendency toward an awakening was apparent throughout Western Europe, it first became evident in Italy. This was due to the fact that Italy was at the time a seat of intellectual activity resulting from several factors. It was a storm center for civic and interstate quarrels, and, as a result of this political unrest, the citizens were kept constantly on the outlook for their own safety and interests, and their wits were greatly sharpened. Even the exile, into which one civic faction or another was constantly forced, had the effect of broadening their vision and bringing out the greatest possibilities within them. Again, the commercial intercourse of the Italian cities with other countries had, for various physiographic and historic reasons, become extraordinarily active. This tended to open the minds of the Italians, break up their old conceptions, free them of prejudice, and increase their thirst for learning. Furthermore, the ghost of the classic ages still haunted its old home. A knowledge of the Latin tongue had never ceased to exist in Italy, and many manuscripts of the Latin and Greek authors had been preserved. There was only needed an intellectual awakening sufficient to shake off the thraldom to the Church and produce an appreciation of classical literature and culture, in order to bring back this spirit of the past into real pulsating life.

**The Revival of the Latin Classics.** - The earliest of the great humanists was Petrarch (1304-1374). In him we find the very embodiment of the Renaissance spirit. He completely repudiated the 'otherworldly' ideal of mediaevalism, and was keenly aware of the beauties and joys of this life. He did not hesitate to attack the most hoary of traditions, nor to rely upon observation, investigation, and reason. He likewise felt a kinship with the thinkers and writers of the classic age, when independence and breadth were given more scope, and held that their works must be recovered before their spirit could be continued. This led to a tremendous enthusiasm for the Latin classics, and he spent much of his life in restoring ancient culture. He devoted himself during his extensive travels largely to collecting manuscripts of the old Latin writers, which previously had been widely scattered, and endeavoring to repair in them the ravages of time. And he inspired every one he met with a desire to gather and study the works of the classic authors. He also wrote a number of Latin works that were filled with the classic spirit. Among them were several collections of *Letters,* a work of erudition *On Famous Men,* and an epic poem in honor of Scipio Africanus that he called *Africa.* Some of his letters were indited to Cicero, Homer, and other classical authors as if they were still living. After he had been crowned as poet laureate by the University of Rome in 1341, he spent most of his time visiting various Italian cities and spreading the humanistic spirit. Of the younger scholars and literary men influenced by him probably the most noted was Boccaccio (1313-13 75). Through Petrarch this youthful poet developed a perfect passion for the ancient writers, and devoted the rest of his life to classical culture. He obtained a wide knowledge of the Latin writers, and searched out, preserved, and had copied as many manuscripts as possible.

**The Development of Greek Scholarship.** - With all this revival of Latin literature by the *coterie* of Petrarch, for some time there was little done with the Greek. That language had almost disappeared in Europe, and the greatest Greek authors were known only through Latin translations. But a knowledge of the Greek language and literature still persisted in the Eastern empire, and the humanists of Italy were, through the works of the Latin authors, constantly directed back to the writings of the Greeks. They became eager to read them in the original, and several humanists began the study of Greek. Nevertheless, Petrarch pathetically confessed: "Homer is dumb to me, while I am most certainly deaf to him." And while, with the aid of his Greek teacher, Boccaccio made a translation of Homer, it showed little real appreciation of the original. Not until Chrysoloras (1350-1415) came as an envoy from the Eastern emperor and was induced in 1396 to settle in Italy and teach Greek, was any systematic training possible. During the next sixteen years this man of learning taught in the leading centers, established schools, made translations of Greek authors, and wrote a Greek grammar. From his efforts sprang a number of famous scholars, such as Vergerio, Niccolo de' Niccoli, Bruni, and Guarino da Verona and his son. These men collected or copied hundreds of volumes, started libraries and schools, made excellent translations, wrote treatises on humanistic education, and trained a number of humanists, who became distinguished later.

**The Court Schools and Vittorino da Feltre.** - A powerful support for the work of these humanists resulted from the rivalry of the Italian cities. The princes at the head of these centers were often usurpers, and depended largely upon city pride to maintain their power. To appeal to the classical enthusiasm of their people, they did everything possible to propagate the humanistic movement and make their cities illustrious. Probably the most typical examples of these humanistic tyrants are found among the Visconti at Milan and the Medici at Florence. In some instances these court circles promoted the new learning informally, but often, where a scholar had been taken into the family of a prince as private tutor, children of the neighboring aristocracy were associated and a regular school was started. 'Court schools' of this sort soon existed at Florence, Venice, Padua, Pavia, Verona, Ferrara, and several other cities, but the best known of all was that organized by Vittorino da Feltre (1378-1446) at Mantua.

**The Court School at Mantua.** - Vittorino undertook this school at forty-five, when he had received the best possible education of the times in Latin, Greek, and mathematics, and had greatly distinguished himself as a teacher and a man of piety. He received into the school not only the royal princes and the scions of the leading Mantuan families, but, by special permission, the sons of his personal friends and promising boys of every degree. He dwelt with his pupils, and was most strict in his selection of masters and of attendants, that the morals of his pupils might be of the highest. Likewise, 'the father of his pupils,' as Vittorino held himself to be, looked out for their food, clothing, and health, and shared in their games, interests, and pleasures. It was his intention to secure for his pupils that harmonious development of mind, body, and morals that the old Greeks had known as a 'liberal education,' but he emphasized the practical and social side of the individual's efficiency, and wished to prepare his pupils for a life of activity and service rather than to create mere rhetoricians and pedants.

This he felt could be accomplished largely through a grammatical and literary study of the Greek and Roman writers. The pupils learned from the first to converse in Latin, and there were games with letters for the youngest and simple exercises to train them in clear articulation and proper accent and emphasis. Before they were ten, they were also drilled in memorizing and reciting with intelligence the easier portions of the classic authors. This elocutionary work, which was increased in length and difficulty as the boys grew older, gave them an excellent grasp of vocabulary, rhythm, and style. As they advanced, the pupils read a variety of Latin writers, and soon took up a study of the Greek authors and of the Church Fathers. The mathematical subjects were also taught with an enlarged scope, especially in their applications to drawing, mensuration, and surveying. Because of the lack of books, the teaching was carried on largely by dictation. Vittorino, however, carefully studied the ability, interests, and future career of his pupils, and selected the subjects and methods best suited to each intelligence. He thus inaugurated a thoroughly elastic course for the school. Physical and moral education were likewise insisted upon quite as fully as intellectual. Vittorino introduced especially fencing, wrestling, dancing, ball-playing, running, and leaping, in all of which he was himself an expert, but the purpose of these was to aid and stimulate the mental powers. He also by both precept and example inculcated piety, reverence, and religious observances. He believed, moreover, that truth and moral beauty could be derived not only from the Christian authors, but also, by means of expurgation, from the classic writings.

**The Relation of the Court Schools to the Universities.** - The court school at Mantua had thus a most potent influence upon the educational practice of the times, and trained a large number of distinguished ecclesiastics, statesmen, scholars, and rulers. It doubtless was broadly typical of the court schools and of the humanistic education of Italy in general. These court schools, while taking pupils very early, often retained them until they were twenty-one, and covered as much, if not more, ground than the arts course of the university. They were, in a way, competitors of the older institutions. A student might, for the sake of a degree, go from a court school to a university, but, as a rule, if what he wished were a general course, he would be satisfied with the greater prestige that came from being a pupil of one of the distinguished humanists that the court schools were generally able to retain at their head. In fact, the want of hospitality, if not actual hostility, of universities to the new learning, often stimulated the growth of court schools. In many instances where the university was especially conservative, a court school was set up by its side as a professed rival. Gradually, however, the humanistic training crept into all the universities of Italy, and the classical literature of the Greeks and Romans largely took the place of the former grammar, rhetoric, and dialectic. Before the close of the fifteenth century, Florence, Padua, Pavia, Milan, Ferrara, Rome, and other cities had admitted the humanities to their universities, and the other university seats were not long in following their example.

**Decadence of Italian Humanism.** - Toward the close of the fifteenth century, however, this liberal education of the humanists in Italy began to be fixed and formal. Until the middle of the century the ideals, content, and meaning of this training were constantly expanding, but after that time there was a gradual narrowing and hardening, and during the early years of the sixteenth century the degeneration became complete. As the subjectmatter became institutionalized, the literature of the Greeks and Romans failed more and more to be interpreted in terms of life. Emphasis was placed upon the form rather than the content of the classical writings, and grammatical drill was more and more emphasized as a means of formal discipline. Before long the course was limited largely to Cicero, and the new learning fell into that decadent state known as 'Ciceronianism.' It consisted simply in an attempt to teach a perfect style with Cicero as a model, and to give one a conversational knowledge of Ciceronian Latin. The structure, metaphors, and vocabulary of all Latin writing had to be copied from the phrases of Cicero, and the literature of the day became little more than a sequence of model passages from that author.

**The Spread and Character of Humanism in the Northern Countries.** - Such was the effect of the Renaissance upon education in the country of its birth. But the humanistic training could not be confined to Italy. By the middle of the fifteenth century, with the invention of printing, the texts of the classic authors were rapidly multiplied and spread everywhere. The Renaissance and the classic literature leaped the Alps, and made their way into France, the Teutonic countries, England, and elsewhere. At first, humanistic scholars wandered into the North, soon others were invited in large numbers by patrons of learning, and, at length, students from the Northern countries thronged into Italy for instruction. Towards the close of the fifteenth century the humanists outside the peninsula became very numerous, and during the sixteenth century the movement came to its height in the Northern lands.

But the character and effects of the Renaissance and humanism in the North differed greatly from those in the country of their origin. The peoples of the North, especially those of Germanic stock, were by nature more religious than the brilliant and mercurial Italians. With them the Renaissance led less to a desire for personal development, self-realization, and individual achievement, and took on more of a social and moral color. The prime purpose of humanism became the improvement of society, morally and religiously, and the classical revival pointed the way to obtaining a new and more exalted meaning from the Scriptures. Through the revival of Greek, Northern scholars, especially the German and English, sought to get away from the ecclesiastical doctrines and traditions, and turn back to the essence of Christianity by studying the New Testament in the original. This suggested a similar insight into the Old Testament, and an interest in Hebrew was thereby aroused. In consequence, to most people in the North a renewed study of the Bible became as important a feature of humanism as an appreciation of the classics.

**The Development of Humanism in France.** - In France humanism appeared early. In 1458 a professorship of Greek was established at the University of Paris, but the humanistic movement did not amount to much in France until it was stimulated by the expeditions of Charles VIII (1494) and Louis XII (1498) into Italy. These undertakings of the monarchs did not attain the military and political objects intended, but through them France came into direct contact with humanism at its sources, and a definite impression was made upon French art, literature, and education. Even then, owing to the conservatism of the university, the new learning met at first with formidable opposition. Happily, it found an influential patron in the youthful Francis I (f. 1515-1547).

**French Humanistic Educators and Institutions.** - Under the protection of Francis, many prominent humanistic scholars and educators, like Budseus (14681540), appeared, classical manuscripts were collected, Greek and Latin authors were translated, treatises on humanistic education were produced, and the College of France, with chairs of Greek, Hebrew, and Latin, was established (1530). Humanism was also introduced into various colleges in Paris and Bordeaux by such scholars and practical teachers as Corderius (1479-1564) and Ramus (1515-1572), and many text-books and editions of the classics were published. Soon most of the schools of France responded to the new training. It would hardly be possible to consider many of them, but a brief description of the course and administration in vogue at the College of Guyenne, taken from an account of one of its teachers, may prove illuminating. This college contained ten classes in secondary work, and two years more in philosophy, which partially overlapped the faculty of arts in the university. Latin and religion were taught throughout the secondary school, and Greek, mathematics, rhetoric, and declamation could be taken in the last three or four classes. The pupils were introduced to the rudiments of Latin through the vernacular, and developmental methods and enlivening disputations were used. Probably the general conditions here were typical of the French humanistic schools everywhere during the sixteenth century.

**Humanism in the German Universities.** - Before humanism was well established in France, however, it had also spread through the Teutonic countries. By the end of the sixteenth century the German universities had begun to adopt the new learning. In 1494 Erfurt established a professorship of Poetry and Eloquence, which covered the field of classic literature, and lectures on humanistic subjects were before long given in Leipzig, Heidelberg, Tubingen, Ingoldstadt, and Vienna. Likewise, a number of new universities, Wittenberg, Marburg, Konigsberg, and Jena, were started upon a humanistic basis, and before the middle of the sixteenth century humanism prevailed in practically all of the German universities.

**The Hieronymians and Their Schools.** - The earliest factor in Germanic humanism, however, appeared in the education furnished by the Hieronymians, or Brethren of the Common Lot. For the instruction of the poor, this order had started schools, or established teachers in institutions already existing, throughout the Netherlands, Germany, and France. At first, they stressed instruction in the Bible and the vernacular, but, as the Italian influence began to be felt in the upper countries, they broadened the course by the addition of classic literature and Hebrew, and the schools soon became recognized centers of humanism and intellectual interests. The pupils that were trained there strengthened the new learning as teachers in the universities and schools throughout Germany and the Netherlands. The first educator of importance to introduce humanism into the Hieronymian training seems to have been Wessel (1420-1489). He was preeminently interested in teaching, and among his earliest pupils of distinction were Agricola (1443-1485), who had a most potent influence in introducing classics, and Reuchlin (1455-1522), who taught the classics and Hebrew at various universities, and produced a monumental grammar and lexicon upon the latter subject. An even more noteworthy teacher was Wimpfeling (1450-1528), who became professor, dean, and rector at Heidelberg. He lectured upon the classical authors and the Church Fathers, and wrote a number of treatises upon education, in which he held to the attitude of Northern humanism that all learning is vain which does not lead to the advancement of mankind. But, while a true reformer, he never broke from the Church.

**Erasmus, Leader in the Humanistic Education of the North.** - A similar attitude was held by Erasmus (1467-1531), the greatest of the humanists trained by the Hieronymians. While he was bitterly opposed to the corruption and obscurantism of ecclesiastics, he believed that the remedy lay, not in a division of the Church, but in the study of the classics and the Church Fathers, and in the general removal of ignorance. Accordingly, to advance education, he assisted in the preparation of Lily's Latin grammar, translated into Latin the Greek grammar of Theodore of Gaza, and wrote a work on Latin composition, called *Be Copia Verborum et Rerum,* and an elementary text-book of Latin conversation on topics of the day, known as *Colloquies.* Similarly, he produced treatises on the New Testament, and popularized the Gospels and Church Fathers through paraphrases. Even better known are the satires that he wrote in Latin to reform the abuses and foibles of his times. His *Adages* and *Praise of Folly* mercilessly scored the absurdities and vices of the Church and the priesthood, and in his *Dialogue on Ciceronianism* he ridiculed some of the narrower tendencies into which humanism had fallen. He also made direct contributions to educational theory in his Latin treatises on *The Liberal Education of Children, The Right Method of Study,* and *Courteous Manners in Boys,* which are almost modern in some of their recommendations. Learning, morality, religion, and good manners, he held, must be trained together, and education must be open to everyone, according to his or her ability. It should be started in infancy by the mothers, and reading, writing, drawing, and some knowledge of familiar animals and objects taught by informal methods. At seven the boy is to be given a thorough training in the Scriptures, Church Fathers, and the classics, and the content rather than the language and form of these works is to be stressed.

**The Development of Gymnasiums: Melanchthon's Work.** - It can thus be seen what a profound effect the humanists trained in the Hieronymian schools had upon the Teutonic universities and other educational institutions. But there sprang up another set of schools, known as *Gymnasien,* that was an even more typical and lasting institutional development of the Northern Renaissance. These 'gymnasiums' grew largely out of the old cathedral and upper burgher schools, and were established for the benefit of the municipality, rather than for State and Church. Their development was gradual, but they were given their first definite shaping by Melanchthon (1497-1560). After a thorough humanistic training from his great-uncle, Reuchlin, and from the universities at Heidelberg and Tubingen, that scholar had become associated with Luther at the University of Wittenberg, and was requested by the Elector of Saxony in 1528 to organize the schools in his state. The 'Latin Schools,' which he planned for every town and village of the electorate, were divided into three classes, and the work in Latin and religion was adapted to the grade. Not even Greek or Hebrew appeared in the course; much less the vernacular, mathematics, science, and history. Nevertheless, it was from these municipal Latin schools, when the course had been somewhat modified and expanded, that the 'gymnasium' may be said to have sprung.

**Sturm at Strassburg.** - A further step in fixing the type and the first use of the term 'gymnasium' are found in the case of the classical school organized by Johann Sturm (1507-1589) at Strassburg in 1538. Here during his forty-five years as rector, Sturm worked out a gymnasial course of ten classes, upon which the pupils entered at six or seven years of age. The aim of this training he held to be 'piety, knowledge, and eloquence,' meaning by the last an ability to speak and write Latin readily. For 'piety,' the Lutheran catechism was studied in German for three years, and in Latin for three years longer. The *Sunday Sermons* were read in the fourth and fifth years, and the *Letters* of Jerome also in the fifth year, while the *Epistles* of St. Paul were carefully studied from the sixth year through the rest of the course. On the 'knowledge' and 'eloquence' side, Latin grammar was begun immediately and the drill continued for four years, during which the pupil passed gradually from memorizing lists of words used in everyday life and reading di- alogues that embodied them to the translation of Cicero and the easier Latin poets. In the fourth year exercises in style were begun, and this was accompanied by a grammatical and literary study of Cicero, Vergil, Plautus, Terence, Martial, Horace, Sallust, and other authors, together with letter writing, declamation, disputation, and the acting of plays. Greek was begun in the fifth year, and after three years of grammatical training, Demosthenes, the dramatists, Homer, and Thucydides were undertaken.

**Formalism in the Gymnasiums.** - This training, like that of the Italian humanists, soon became set, formal, and mechanical. While other authors than Cicero were read, the object was to acquire an ability to read, write, and speak Ciceronian Latin, and words, phrases, and expressions were carefully committed. The main emphasis throughout was upon form, with little regard for content, and the Latin and Greek were largely regarded as an end in themselves. Yet the gymnasium of Sturm was an enormous success, and was soon crowded with students. His pupils became the headmasters of all the most prominent schools, and through his wide correspondence with sovereigns and educators, the course of study formulated by Sturm became a model not only for Germany, but, in a sense, for the rest of Europe. At any rate, most of the existing secondary schools in Germany, and many founded later, became gymnasiums. The majority of the Hieronymian schools soon adopted the gymnasial course. This was also the case with the *Furstenschulen,* or 'princes' schools, ' a type of institution started in 1543 by Duke Moritz of Saxony to train wellprepared officials for Church and State at public expense, and afterward absorbed into the gymnasial system. And the gymnasiums have to-day changed but little from Sturm's organization. Owing to the later influence of realism, the addition of mathematics, modern languages, and the natural sciences has somewhat mitigated the amount of classics prescribed, but otherwise the German gymnasiums adhere to their formal humanism as tenaciously as in the sixteenth century.

**The Humanistic Movement in England: Greek at Oxford and Cambridge.** - In its northward march the humanistic education also effected profound changes in England. By the middle of the fifteenth century many former students of Oxford began to study at various humanistic centers in Italy. But the influence of such innovators was scarcely felt until Grocyn and Linacre, who had gone to Florence about 1488, undertook to introduce Greek into education upon their return home. Grocyn (1442-1519) became the first lecturer on Greek at Oxford, but he was greatly assisted in the humanistic training by Linacre (1460-1524), although his lectureship was nominally on medicine. Among their pupils were Erasmus, More, and Colet. Humanistic education did not reach Cambridge, however, until the close of the fifteenth century, but, with the progress of the sixteenth, that university rapidly overtook her sister institution. The real development began when Erasmus, while a professor of theology at Cambridge (1510-1514), consented also to lecture upon Greek as a labor of love. Erasmus was succeeded by a number of lecturers, and in 1540 the new *regius* professorship was held for four years each by the great teachers, Cheke (1514-1557) and Ascham (1515-1568).

**Humanism at the Court.** - As Cheke became private tutor to Prince Edward and Ascham to Princess Elizabeth, an Hellenic atmosphere was soon promoted in royal circles. A powerful assistance to the development of humanism was also found at. the court through the influence of More, who was especially close to Cardinal Wolsey, and so for a time to the king, Henry VIII. A number of treatises upon humanistic education were written by members of the court, like More and Vives; while Ascham produced his *Scholemaster,* a well-known work on teaching Latin and Greek by 'double translation.' This famous method consisted in having the child translate a passage into English, and then, after an hour, render it back into the original and have the master compare it with the text.

**Colet and His School at St. Paul's.** - The humanistic changes in English education, however, were not limited to the universities and the court. The schools also felt the effect of the new movement, and the most important factor in bringing this about was the foundation of St. Paul's School in 1509 by Colet. This scholar devoted most of the fortune left him by his father to establishing a humanistic school in St. Paul's churchyard, dedicated to 'the child Jesus.' The institution was thus an outgrowth of Northern humanism, and combined religious training with a study of the classics. In connection with certain Latin authors and Church Fathers, the pupils studied the catechism in English, the *Latin Grammar* of Lily, who was the first headmaster of the school, and the *De Copia* of Erasmus. St. Paul's school trained a long list of brilliant scholars, literary men, clergy, and statesmen, and became the immediate model for a host of other institutions. There were in existence at the time St. Paul's was founded some three hundred 'grammar' schools of various types. These had come down from the Middle Ages, and their chief purpose had been the training of young men for the priesthood. Their curriculum was usually of the mediaeval monastic type, but they soon felt the influence of the new school. Those which survived the general dissolution of ecclesiastical foundations by Henry VIII and Edward VI were gradually remodeled on the classical basis of St. Paul's. New schools were also established in accordance with the humanistic ideals.

**Humanism in the English 'Grammar' Schools.** - But the humanism of the 'grammar' schools in England, as in Italy and Germany, soon became narrow and formal. The purpose of humanistic education came to be not so much a real training in literature as a practical command of Latin as a means of communication in all lands and ages. Accordingly, the training became one of dictionaries, grammars, and phrase-books. Expressions and selections were culled from authors and treasured in notebooks, and the methods became largely *memoriter* and passive. The formalism into which the schools of England had thus fallen by the seventeenth century is depicted in Brinsley's *Ludus literarius: or the Grammar Schoole,* a work intended to ridicule and reform these conditions. It indicates that the training in Latin was devoted to drill in inflecting, parsing, and construing a fixed set of texts. Lily's *Grammar* was memorized by the pupils, and references to it were glibly repeated, with little understanding of their meaning. All conversation was based upon some phrase-book, like the *Colloquies* of Corderius, and a Latin theme had to be ground out each week.

**English 'Grammar' and 'Public' Schools To-day.** - Although reforms have since been made in many of these directions, the organization and the formal humanism of the English 'grammar' school have been preserved in principle even to this day. Mathematics, modern languages, and sciences have been added, and a 'modern side' has been established as an alternate for the old course, but the classics are still the emphasized feature, and, to a large degree, the drill methods prevail. But, while it was originally intended that the grammar schools should, by means of the endowment, be open to rich and poor alike, because of the great increase in expenses, necessary and unnecessary, there are now not many opportunities for any one in the lower classes of society to attend a grammar school. Similarly, a distinction has come to be drawn between 'grammar' and 'public' schools, although it is not a very clear one. In general, a 'public school' has a more aristocratic and wealthier patronage. Nine 'great public schools' were recognized by the Clarendon Commission in 1864, - Winchester (Fig. 17), Eton, St. Paul's, Shrewsbury, Westminster, Rugby, Harrow, Merchant Taylors', and Charterhouse; but several other old schools and a number of the stronger foundations of Victoria's reign are generally admitted, and many others claim the dignity of the name that would not be considered eligible outside of the immediate locality.

**The 'Grammar' Schools in the American Colonies.** - It was after these 'grammar' schools of the mother country that the first secondary schools in America were modeled and named. In many instances the fathers of the colonies, such as Edward Hopkins, William Penn, and Roger Williams, had been educated in the grammar schools of England, and naturally sought to model the institutions in their new home after them as nearly as the different conditions would permit. The Boston Latin (Grammar) School was founded as early as 1635 (Fig. 23), and other towns of Massachusetts, - Charlestown, Ipswich, Salem, Dorchester, Newbury, Cambridge, and Roxbury, also before long established grammar schools. Similarly, towns of Connecticut, Rhode Island, New York, Pennsylvania, Virginia, and the other colonies, had in many cases founded grammar schools before the close of the century. Moreover, the legislatures of Massachusetts (1647) and Connecticut (1650) soon ordered that a 'grammar' school be established in every town having one hundred families. The American grammar schools, like their prototypes, were secondary and sustained no real relation to the elementary schools. They were mostly intended to fit pupils for college, although sometimes the college had not yet been established, and thus to furnish a preliminary step to preparation for the Christian ministry. Hence their course consisted chiefly in reading the classics and the New Testament, and used among its texts Lily's *Grammar* and the *Colloquies* of Corderius. And while the hold of formal humanism upon secondary education was somewhat relaxed during the subsequent stages of the 'academy' and the 'high school,' the formal classical training was considered the only means of a liberal education until well into the nineteenth century.

**The Aim and Institutions of Humanistic Education.** - It can now be seen how far the ideals of humanism had departed from those of the mediaeval period. The 'otherworldly' aim, the monastic isolation, and the scholastic discussions had given way to the interests of this life, personal and social development, and a study of the classics. In the North the movement took on rather a different color from what it did in the peninsula that gave it birth. While Northern humanism was narrower in not concerning itself so much with self-culture, personal expression, and the various opportunities of life, it had a wider vision through interesting itself in society as a whole and in endeavoring to advance morality and religion. It was democratic and social in its trend, where Italian humanism was more aristocratic and individual.

In Italy the chief educational institutions resulting from the humanistic movement were the schools that arose at the brilliant courts of the city tyrants. These institutions were sometimes connected with the universities, and gradually the universities themselves were forced to admit the new learning to the curriculum. In the North a number of new institutions - Hieronymian schools, princes' schools, gymnasiums, and grammar schools - were developed from humanism, and the existing institutions soon showed the influence of the movement, but all of them stressed moral and religious studies, as well as classical. Everywhere the curriculum of the humanistic foundations consisted mostly in the mastery of Latin and Greek, but in the North the renewal of Greek meant also a study of the New and Old Testaments and the Church Fathers. Where the Italian Renaissance re-created the liberal education of Plato and Aristotle, Cicero and Quintilian, the movement in its Northern spread found in the classical revival a means of moral and religious training. But just as humanism in Italy by the beginning of the sixteenth century had degenerated into mere Ciceronianism, so the humanistic education in the North, after about a century of development, began to grow narrow, hard, and fixed. By the middle of the sixteenth century the spirit of criticism, investigation, and intellectual activity had begun to abate, and by the opening of the seventeenth humanism had been completely formalized. In the study of the classics all emphasis was placed upon grammar, linguistics, and style; form was preferred to content; and methods became *memoriter* and imitative. Humanism had largely performed its mission, and a new awakening was needed to revivify education and society in general.

**Supplementary Reading**

Graves, *During the Transition* (Macmillan, 1910), chaps. XIIXIV; Monroe, *Text-book* (Macmillan, 1905), chap. VI. An interesting interpretation of the Renaissance both in Italy and the North is found in Adams, G. B., *Civilization during the Middle Ages* (Scribner, 1894), chap. XV. An account of the movement, including its educational aspects in Italy, is found in Burckhardt, J., *Civilization of the Renaissance in Italy* (Sonnenschein, London, 1892; Macmillan), vol. I, especially part III; Symonds, J. A., *Renaissance in Italy* (Holt, Scribner), vol. II, especially chaps. Ill-VIII; or Symonds' *Short History of the Renaissance* (Holt, 1894), especially chaps. I and VII, and IX-XI. Woodward, W. H., gives us a vivid account of the educational work of *Vittorino da Fcltre and Other Humanist Educators* (Cambridge University Press, 1897), and of *Erasmus concerning Education* (Cambridge University Press, 1904), and of *Education during the Renaissance* (Cambridge University Press, 1906) as a whole. *Peter Ramus and the Educational Reformation of the Sixteenth Century* (Macmillan, 1912), by Graves, F. P., furnishes some idea of conditions in France. *The Italian Renaissance in England* (Columbia University Press, 1905), especially chap. I, is succinctly described by Einstein, L.; and an account of Colet and St. Paul's School can be found in Barnard, H., *English Pedagogy,* second series, pp. 49-117.