# 13. Educational Influences of the Reformation

**Outline**

-   Luther's educational positions are most fully revealed in his well-known *Letter* and *Sermon.* He holds that education should prepare for citizenship, and should be state-supported, and these recommendations were somewhat embodied in actual schools by his associates.
-   Zwingli was killed before he could greatly influence education, but the educational institutions of Calvin spread rapidly through Switzerland, France, Netherlands, Puritan England, and Scotland.
-   In England Henry VIII and Edward VI confiscated the property of some three hundred monastic and other ecclesiastical schools, but subsequently many of these were refounded.
-   The Jesuit colleges were organized to extend Catholic Christianity. The lower colleges were humanistic, and the higher taught 'philosophy' and theology. The teachers were trained, and the methods, though *memoriter* and emulative, were effective. The influence of the Jesuit colleges was phenomenal, but they have failed to meet new conditions.
-   The Port Royalists held that reason was more important than memory, but, while their 'little schools' stressed vernacular, logic, and geometry, they offered nothing beyond the best elements in the education of the past.
-   Elementary and industrial education was given an impulse for the Catholics by the schools of the Christian Brothers. They also opened training schools for teachers, and perfected the 'simultaneous' method.
-   Among the Protestants and some Catholics in Germany, Holland, Scotland, and certain of the American colonies, the Reformation inclined toward universal elementary education and control of the schools by the state. The secondary schools in Protestant countries also came largely under civic authorities, although the clergy still taught and inspected them; while Catholic secondary education was furnished mostly by the Jesuit colleges. In many instances the universities turned Protestant; and new universities, Protestant and Catholic, were founded.

**The Relation of the Reformation to the Renaissance.** - The series of revolts from the Catholic Church, generally known collectively as the 'Reformation,' may be regarded as closely connected with the Renaissance. As shown in the last chapter, humanism in the North led to a renewed study of the Scriptures and a reform of ecclesiastical doctrines and abuses, and took on a moral and religious color. Reformers arose, like Wimpfeling and Erasmus, who, while remaining within the Church, sought to purify it of corruption and obscurantism. But the Church at first stubbornly resisted all efforts at internal reform. Its immense wealth, large numbers, and training enabled it for a long time to thwart the spirit of the age, and a condition of ecclesiastical upheaval followed. Revolts against papal authority ensued in various parts of Europe north of Italy, and were furnished support by the awakened intellectual and social conditions of the sixteenth century. The result was the establishment of a church, or rather a set of churches, outside of Catholic Christianity. While each revolt had some peculiarities of its own, there were underlying them all certain general causes that indicated their relation to the Renaissance.

**The Revolt and Educational Works of Luther.** - Even the attitude of Martin Luther (1483-1546) seems to have been bound up with the tendencies of the day. Apparently he had at first no idea of breaking from the Church, and supposed that the ninety-five theses he nailed to the church door at Wittenberg (1517) were quite consistent with Catholic allegiance. But even before this he had attacked Aristotle and scholasticism with great vigor, appealing to primitive Christianity and the right Of free thought, and thus identified himself in spirit with the Northern Renaissance. And two years later, in his contest with Eck, when he was actually led to deny the authority of both pope and council, he was evidently relying upon the humanistic and individualistic atmosphere of the times.

When once he had revolted, Luther gave much of his time to promoting the reform and education of the masses by writing. All his works, whether religious or pedagogical, were clearly intended, in a broad sense, to be educational. After his condemnation at the Diet of Worms (1521), when he had taken refuge at the Wartburg, he undertook to awaken the minds and hearts of the common people by a translation of the Greek Testament. Contrary to general opinion, a large number of translations had preceded that of Luther, and their popularity must have proved suggestive to him, but his edition was unusually close to the colloquial language of the times. A dozen years later, he had completed a translation of the entire Bible, which contributed greatly to education by getting the masses to read and reflect. For the further instruction of the people, he also followed the fashion of the day in producing two catechisms, one for adults and the other for children, together with many tracts, addresses, and letters, filled with allusions to the organization and methods of education. But the documents which most fully reveal his educational positions are his *Letter to the Mayors and Aldermen of All Cities of Germany in behalf of Christian Schools* (1524), and his *Sermon on the Duty of Sending Children to School* (1530).

**Luther's Ideas on Education.** - The purpose of education, Luther everywhere holds, involves the promotion of the State's welfare quite as much as that of the Church. The schools were to make good citizens as well as religious men. Educational institutions should, on that account, be maintained a.t public expense for every one, - rich and poor, high and low, boys and girls, alike, and attendance should be compelled by the civic authorities. Realizing that some pupils may find it hard to give the time to school, Luther planned that "they should spend an hour or two a day in school, and the rest of the time in work at home, learn some trade and do whatever is desired, so that study and work may go on together." But he also desired a more academic course "for the brightest pupils, who give promise of becoming accomplished teachers, preachers, and workers." In any case, Luther naturally believed that the chief studies should be the Bible and the catechism. But, as a Northern humanist, he recommended the ancient languages - Latin, Greek, and Hebrew - for the light they would throw on the Scriptures and the patristic writers. He likewise approved of rhetoric and dialectic, which were very valuable subjects in those days of controversy; and he made a decided advance in advocating history, natural science, vocal and instrumental music, and gymnastic exercises. History is advised, not only, as was common with the humanists, for the sake of illustrating moral truth, but also for the purpose of understanding social institutions. The study of nature was intended to reveal "the wonders of Divine Goodness and the omnipotence of God." Gymnastics he considered of value both for the body and the soul, and music a means of "driving away all care and melancholy from the heart." The methods he recommended were equally rational. He would utilize the natural activity of children and not attempt to repress them, and would make use of concrete examples, wherever possible. Languages he would teach less by grammar than by practice. This belief in the importance of selecting the proper content and method in education led him to rate the function of the teacher as higher, if anything, than that of the preacher.

**The Embodiment of Luther's Ideas in Schools by His Associates.** - These recommendations of Luther were largely embodied in actual institutions by his associates. The year after his *Letter to the Mayors* was published, the Protestants were requested by the Count of Mansfeld to establish in Luther's native town, Eisleben, a school that should put his educational theories into practice, and this was performed by Melanchthon. The subsequent organization of Latin schools throughout the Electorate of Saxony, and the foundation of the gymnasium of Sturm at Strassburg upon the Protestant basis have already been touched upon (pp. 114 ff.). But of fully as much importance were the educational foundations of Bugenhagen (1485-1558). While engaged in reorganizing the churches in the cities and states of Northern Germany, by his general 'church orders' to each, he made ample provision for schools of the Lutheran type. For instance, at Hamburg in 1520 he organized a single Latin school with a rector and seven teachers, together with a German school for boys and one for girls in every parish. Eight years afterward, the 'church orders' of Brunswick provided two classical schools, two vernacular schools for boys, and four for girls, so located in the city that all children could conveniently reach a school. Within a half dozen years he made similar re- quirements for Liibeck, Minden, Gottingen, Soest, Bremen, Osnabriick, and other cities, and throughout some entire states of Germany, such as Holstein and his own native duchy of Pomerania. The educational other theories of Luther were also put into practice in a num- ber of schools taught by Trotzendorf, Neander, and other pupils of Melanchthon.

**The Revolt and Educational Ideas of Zwingli.** - The revolt under Zwingli (1484-1531) was more directly the outcome of Northern humanism than was that of Luther. Through Erasmus and others he had come to believe that there was little basis in the Bible for the traditional theology, and he carefully read the accounts himself in the original Greek and Hebrew. After he took charge of the cathedral at Zurich, he began his attack upon the dogmas and traditions of the Church, and, by securing the support of the town, managed in a fairly peaceful way to drop one form of the Church after another, until, within five years, he had abolished even the mass. Zwingli likewise made the extension of educational facilities a part of his reform. He founded a number of humanistic institutions, and introduced elementary schools into Switzerland. He also published a *Brief Treatise on the Christian Education of Youth* (1523), which recommended a course of studies not unlike that of Luther, except that, from his practical temperament, he did not mention history, but did add arithmetic and surveying.

**Calvin's Revolt and His Encouragement of Education.** - While endeavoring to spread his reforms, Zwingli was slain in the prime of life. His positions were maintained by his successor in the cathedral, but the work was soon overshadowed and merged in the movement of Calvin (1509-1564). Calvin's break with the Church, like that of French Protestants generally, also began through the influence of Northern Humanism and the study of the Greek Testament. He had, however, received an excellent legal and theological education, and did not content himself with merely attacking Catholic doctrine, but was the first Protestant to formulate an elaborate system of theology. The call of Calvin to reorganize the civil and religious administration of the city of Geneva gave him an excellent opportunity for working out his theories. Although he was much engrossed in religious disputes, he established 'colleges' at Geneva and elsewhere, and in other ways undertook to found schools and promote education. He succeeded, too, in persuading his former teacher, Corderius (see p. 111), to come to Switzerland, and organize, administer, and teach in the reformed colleges.

**The Colleges of Calvin.** - Corderius here wrote four books of *Colloquies,* with the purpose of training boys by means of conversation on timely topics to speak Latin with facility, and from this work we can learn much of the character of the Calvinistic colleges. Clearly the ideal was the 'learned piety' of Melanchthon, Sturm, and the other Northern humanists and Protestants. An attempt seems to have been made to teach Latin in such a way as to cultivate moral and religious life, and psalms were sung, public prayers offered, and selections from the Bible repeated each day. We also know that in the seven classes of a college at Geneva the pupils learned reading and grammar from the Latin catechism, and then studied Vergil, Cicero, Ovid, Caesar, Livy, and Latin composition. Greek seems to have been begun in the fourth year, and, beside classical Greek authors, the Gospels and Epistles were read. Likewise, as in the other Reformation schools, Logic and rhetoric were studied in the higher classes. The colleges of this type not only spread rapidly among Calvin's co-religionists in Switzerland and France, but, as Geneva became a city of refuge for all the oppressed, a regard for humanistic, religious, and universal education was absorbed by the persecuted Netherlanders, the English Protestants of Mary's time, and the Scotch under the leadership of Knox in the days of Mary, Queen of Scots (1505-1572).

**Henry VIII's Revolt and Its Effect upon Education.** - In England a revolt from the Church likewise occurred. This also may have been due in part to the investigative spirit of Northern humanism, but the immediate cause of the breach was the desire of Henry VIII (r. 1509-1547) to control the national Church that he might divorce his wife, and there was at first little change in doctrine. Once in ecclesiastical power, Henry began in 1536 to confiscate the monastic lands and property, and enlarged the scope of his operations until he had suppressed a large number of monastic, cathedral, collegiate, hospital, and other schools. During the reign (1547-1553) of his successor, Edward VI, the acts of suppression were extended to chantry and gild foundations, and it is estimated that, of the three hundred grammar schools that had come down in England from the Middle Ages, but few were not destroyed under Henry and Edward. Some, however, remained by the terms of the parliamentary acts of suppression, and popular sentiment caused others to be refounded. And during the reign of Elizabeth (1558-1603) and of the first two Stuart kings (1603-1649) these foundations were greatly increased out of royal funds or through the philanthropy of wealthy men. All of these schools, as we have seen (p. 118), following the example of St. Paul's, adopted the Northern ideals of humanism and furnished a curriculum of classics and religious training. The latter became based, of course, upon the teachings of the Church of England.

**Foundation of the Society of Jesus.** - We may now turn back to the Mother Church and see what efforts she was putting forth in behalf of education during the period of Protestant revolts. Both before and after the time of Luther there were reformers inside the Church who wished to improve its practices without changing its administration, but the Cathohcs in genefarfeit it their chief duty to crush the Protestant heresy and recover the ground they had lost. This resulted in a number of religious wars, in which both sides displayed great bitterness and cruelty. But a more effective and constructive instrument in advancing the interests of Catholicism was the organization of the 'Society of Jesus.' This order was founded by Ignatius de Loyola (1491-1556) in 1534. He persuaded six fellow-students at Paris to join with him in devoting themselves to the conversion of the heathen, and to strengthening the authority of the pope. Six years later, after considerable opposition, the new order was recognized by the pope and began to add rapidly to its numbers. The Jesuits have always striven first through missionary labors to extend Catholic Christianity throughout the world, and then by means of schools to hold their converts and educate all peoples to papal allegiance.

**Organization of the Jesuits.** - The organization of the Society of Jesus was outlined in its *Constitution.* This fundamental document of the order received its final revision shortly after Loyola's death, but the *Ratio Studiorum,* which was an expansion of Part IV of the *Constitution* and described the educational administration in detail, was not finally formulated until 1599. It thus summed up the experience of the Jesuit schools during more than sixty years. The admimstration of the society has always been of a military type. Loyola had originally started upon the career of a soldier, and did not believe that any system could be effective unless it were based upon implicit obedience to one's official superiors. At the head of the order is the 'general,' who is elected for life and has vast administrative powers. As the society spread, the countries that came under its control were divided into provinces, and at the head of the Jesuit interests in each of these districts is the 'provincial,' who is appointed by the general for three years. In each province there are various colleges, whose presiding officer, or 'rector,' is chosen for three years by the general, but is directly responsible to the provincial and reports to him. Similarly, within each college are 'prefects,' immediately subordinate to the rector, but selected by the provincial; and under the inspection of the prefects are the 'professors' or 'preceptors.'

**The Jesuit Colleges.** - The Jesuits have never engaged in elementary education, but have required that pupils know how to read and write before being admitted to any of their schools. This may have been brought about in the first place by the fact that the number of their teachers was limited, or that the public elementary school was just coming to be regarded as of importance, and secondary education of the humanistic type was everywhere dominant. The Jesuit educational organization has, therefore, consisted of 'lower colleges' with a gymnasial course, and of 'upper colleges,' which are of university grade. Boys are admitted to the lower colleges at from ten to fourteen years of age, and spend five or six years there. The first three classes were at first devoted to a careful study of Latin grammar, and a little of Greek; in the fourth year a number of the Greek and Latin poets and historians were read; while the last class, to which two years were usually given, took up a rhetorical study of the classical authors. Only slight variations in the curriculum have ever been allowed since the *Ratio Studiorum* was issued, until the revision in 1832. In that year work in mathematics, natural science, history and geography was added in the lower colleges, but the classics still compose the body of the course.

The full course of the upper colleges lasts seven or nine years, - the first three in 'philosophy,' followed by four or six in theology. The training in 'philosophy' now includes not only logic, metaphysics, psychology, ethics, and natural theology, but also work in algebra, geometry, trigonometry, analytics, calculus, and mechanics, and such natural sciences as physics, chemistry, geology, astronomy, and physiology. A successful completion of the course leads to the degree of Master of Arts. After the course in philosophy, most of the Jesuits teach in the lower colleges five or six years before going on with the work in theology. In the theological course four years are devoted to a study of the Scriptures, Hebrew, and other Oriental languages, together with Church history, canon law, and various branches of theology. After this one may elect a further training of two years, to review the work in philosophy and theology, and to prepare a thesis. After a public examination and defense of his thesis, the successful candidate is awarded the degree of Doctor of Divinity. Hence a complete Jesuit training will take from eighteen to twenty years, and a member of the order may be from thirty to thirty five years of age before completing his formal education.

**The Jesuit Methods of Teaching.** - The methods of teaching and the splendid qualification of the instructors were from the first distinctive features in the Jesuit colleges, especially when one considers how little attention up to their time had been given to the preparation of teachers. No one could teach in the lower colleges who had not passed through the course in philosophy, while professors in the universities had first to complete the theological course. Instruction was generally imparted orally, and then memorized or taken down in lecture notes. The method was the 'prelection,' which meant a preliminary explanation of the passage or lectures upon the topic under consideration by the teacher. It consisted in giving, first, the general meaning of the whole passage or proposition; then, a more detailed explanation of the construction or phraseology; next, similar thoughts in other authors; fourthly, 'erudition', or informational comment upon the passage; then, a study of the rhetorical figures; and finally, the moral lesson to be drawn. Obviously, with such a method, great stress would be placed upon memorizing, especially in the lower colleges. To fix subjects firmly in mind, short hours, few studies, and brief lessons were early found to be necessary. Likewise, reviews have always been frequent and systematic, and the Latin motto of the Jesuit method declares that "repetition is the mother of learning." Each day begins with a review of the preceding day's work, and closes with a review of the work just accomplished. Each week ends with a repetition of all that has been covered in that time, and the last month of every year reviews the course of the year. To maintain interest in the midst of so much memorizing and reviewing, many devices to promote emulation are used. The pupils are arranged in pairs as 'rivals,' whose business it is to check on the conduct and studies of each other (Fig. 18); and public 'disputations' between two sides are engaged in each week.

**Value and Influence of the Jesuit Education.** - The Jesuit system, then, seems to have been in advance of that in the schools at the time of its foundation. It was organized upon a systematic and thorough basis, and was administered by a set of splendidly trained teachers through the best methods that were known in that day. The schools were interesting and pleasant, and were free to all who had the ability and desire to attend. The Jesuit teachers, too, were indefatigable and devoted to their duty. The criticism that has been offered to this educational system is based on its insistence upon absolute authority and the consequent opposition to the development of individuality. The Jesuit courses, subjects, and methods have become somewhat uniform and fixed. In the lower colleges they depend largely upon memory and appeal to interest through a system of rivalry, honors, and rewards. Such a system is likely to tend toward a reproductive attitude in the pupil.

Nevertheless, the Jesuits furnished the most effective education during the latter half of the sixteenth, the entire seventeenth, and the early part of the eighteenth centuries. The growth of their schools was phenomenal. By the death of Loyola (1556) there were already one hundred colleges, and a century and a half later they had increased to seven hundred and sixty-nine institutions, spread throughout the world. The average number of students in attendance at any of these colleges during the seventeenth century was about three hundred, and in several of the larger centers there were between one and two thousand, and the famous College of Clermont (now *Lycie Louis le Grand*) at Paris is said to have run up to three thousand. At a modest estimate, there must have been some two hundred thousand students in the Jesuit colleges when they were at their height. Their graduates seem to have become prominent in every important activity of life, and included a large number of the noted authors, prelates, statesmen, and generals of the time. By the middle of the eighteenth century, however, the ideals and content of education had somewhat changed, and the Jesuits did not adapt their course to the new conditions. Moreover, the Jesuits seem to have become powerful, ambitious, and somewhat arrogant. They quarreled frequently with bishops, other monastic orders, governments, and universities. Finally, after they had been banished from France, Spain, and Portugal, in 1773 the pope himself dissolved the Society of Jesus. Forty years later the order was restored, but, owing to the development of educational ideals and organization and the increase of educational institutions, their work has never since become relatively as effective or held as important a place in education.

**The Organization of the Education of the Port Royalists.** - A type of Catholic education radically opposed to that of the Jesuits was created by a group of men belonging to the religious body known as the Jansenists. The doctrines of the Jansenists were formulated in 1621 by Cornelius Jansen, a professor in the University of Louvain. While striving to retain their place within the Church, the Jansenists opposed the prevailing doctrines of confession and penance, and adopted the rationalistic philosophy of Descartes. They also held that humanity is naturally corrupt, except as it is watched and guided, and that only a relatively few can be saved. These doctrines probably influenced a body of Jansenists that established a new departure in the way of education at the convent of Port Royal at Chevreuse. In 1643 the 'Port Royalists' endeavored to remove what few children they could from the temptations of the world to a school started in this convent. Similar institutions quickly sprang up in the vicinity and then spread through Paris. To carry out their ideal of careful oversight, these schools usually took only twenty to twenty-five pupils, and each master had under him five or six boys whom he never allowed out of his immediate supervision day or night. Hence these institutions were known as 'little schools.'

**The Port Royal Course and Method of Teaching.** - Since the Port Royalists held that character was of more importance than knowledge, and reason was to be developed rather than memory, these 'little schools' sought to impart an education that should be sound and lasting, rather than brilliant. Unlike the Jesuits, they did not start their pupils with Latin, but with the vernacular, since this was within their comprehension. As soon as they possessed a feeling for good literature, they began the study of Latin through a minimum grammar written in French, and soon took up the Latin authors, rendering them into the vernacular. Greek literature was treated in similar fashion. To train the reason, the older pupils were also taught logic and geometry. The course of study, however, was mostly literary, and had no regard for science or investigation. Port Royal presented the best elements of the education of the past, but did not see beyond it. The methods introduced some striking innovations. The leaders in the Port Royal education departed from the alphabetic plan in teaching their pupils to read, and developed a phonetic method. The Port Royalists also refused to permit the use of emulation and prizes in their schools, but their exclusion of rivalry resulted in indifference. They were never able to secure the energy, earnestness, and pleasing environment of the Jesuit colleges. They did, however, succeed in inculcating a general spirit of piety without the formal teaching of doctrine.

**Closing of the Port Royalist Schools and Its Effects.** - In 1661 the Port Royalist schools were closed by the order of Louis XIV through the influence of the Jesuits. But this act cost the Jesuits dearly. Not only did it lose them sympathy, but it furnished the Port Royalists occasion to issue tracts against Jesuitism that have injured its repute ever since. This closing of their schools also gave the Port Royalists the opportunity of becoming educators in a larger sense by producing a great variety of writings upon their system. Later on, too, Rollin (1661-1741), who was twice elected rector of the University of Paris, summarized in his *Treatise on Studies* the Port Royalist reforms wrought in that institution.

**La Salle and the Schools of the Christian Brothers.** - The Port Royalists were, however, like the Jesuits, engrossed with secondary and higher education, and gave little heed to the education of all the people in the rudiments. In fact, until toward the close of the seventeenth century, the Catholics generally did not succeed in inaugurating any effective or widespread movement toward elementary education. Numerous attempts before this were made through catechism schools and various reformers and religious orders, but teachers were scarce and often ignorant and poorly trained, and there was little progress before the organization of the Brothers of the Christian Schools through the self-sacrificing efforts of Jean Baptiste de la Salle (1651-1719). The organization sprang out of a group of five masters engaged in teaching schools for the poor in the city of Rheims in 1679, but it was not until three years later at Rheims, that La Salle completed his regulations, founded the brotherhood, and moved the members into a permanent home. The order flourished, and neighboring towns soon endeavored to secure its members as teachers in their schools for the poor. Within a year or two, four schools in and about Rheims were placed under masters trained in the house of the Christian Brothers, and a number of other institutions were soon organized in the vicinity upon the same basis.

But, being unable to supply the constant demands for his teachers that came from districts outside the towns, La Salle undertook to train boys who were sent him by the rural clergy, and were expected to return to their homes to teach after their training. To accomplish this, he established in 1684 a 'seminary for schoolmasters' in a wing of the house of the brotherhood, and two other seminaries were opened in neighboring towns the following year. Four years later La Salle opened a house for the brotherhood near Paris, and the Christian Brothers were speedily requested to take charge of the schools of several parishes. Despite the jealousy and opposition of the established order of schoolmasters and of many parties in Church and State, the schools and seminaries of the Brothers greatly increased in Paris, and were rapidly extended throughout France. At Paris also La Salle started the 'Christian academy,' in which drawing, geometry, and architecture were taught ambitious poor boys on Sunday, and introduced boarding colleges for higher secondary training. And these institutions likewise spread through France and the rest of Europe (Fig. 19). In 1705 La Salle retired to the estate known as Saint Yon, near Rouen, and there opened a home for the brotherhood. Here he also founded a famous boarding-school in which he trained boys for soldiery, farming, trade, and various other vocations. Before long he likewise organized in conjunction an industrial training for youthful delinquents, and both the vocational school and the 'protectory' soon became models for many similar institutions in France and elsewhere.

**The Aim, Curriculum, and Method of the Christian Brothers' Schools.** - The plan of the schools of the Christian Brothers was eventually worked out and crystallized in a fixed system under the title of *Conduct of Schools.* This code has not remained quite as definite and uniform as the *Ratio Studiorum* of the Jesuits, for changes and revisions are permitted, and modern methods and subjects have from time to time been introduced. Considerable latitude, moreover, has been allowed to the individual houses by the Superior General at the head of the order, and by the Brothers Visitors, who have charge of the districts. The educational aim of the Christian Brothers has been preeminently religious, and the chief means of attaining this have been strict vigilance, good example, and catechetical instruction. The course has included the studies of the best schools of the time, and added other more practical subjects. Besides the rudiments - reading, writing, and arithmetic - and religious instruction and good manners, mathematics, history, botany, geography, drawing, architecture, hydrography, navigation, and other technical subjects have often been taught, and in the industrial schools a manual and vocational training has been furnished. La Salle seems to have made a great advance, too, in educational economy by perfecting and applying the 'simultaneous' method, which had been practiced in a crude form by some of his forerunners. By this method is meant grading the children according to their capacity, and having those in each grade use the same book and follow the same lesson under a single master, instead of instructing each pupil individually, as was generally the custom then. Likewise, the seminaries or training schools of the Christian Brothers contributed much to the advancement of efficiency in teaching. For the first time teachers of ability and training were made possible for the elementary schools.

**Influence of the Schools of the Christian Brothers.** - The work of the Christian Brothers has met with steady growth and development. By the time of La Salle's death (1719), there had come to be twenty-seven houses of the order, with two hundred and seventy-four brothers, educating about nine thousand pupils. Before the close of the century these numbers had about quadrupled, and now they have increased nearly a hundredfold since the founder's day. During the nineteenth century these institutions were established in all the states of Europe, Asia, Northern Africa, and America. The educational system has been much modified and expanded, and now includes colleges, technical and industrial schools, academies and high schools, elementary and grammar schools, commercial schools, asylums, and protectories. Thus La Salle and his schools of the Christian Brothers have performed a great service for education in all lines, but especially in the promotion and enrichment of elementary training, which had previously been so neglected.

**Aim and Content of Education in the Reformation.** - It can now be seen that, as a result of the Reformation, the religious and theological aim of education at all stages became very prominent with Catholics and Protestants alike. In the elementary schools, beside the rudiments, the Scriptures, the Lord's prayer, the ten commandments, and the Catholic, Lutheran, Calvinist, or Anglican creed and catechism were taught, and, with the Protestants, also the hymns of the church. The courses in the secondary schools and universities contained large religious elements, as well as the formal humanism into which the Renaissance of the North had degenerated. Likewise, there was furnished in all universities a training in dialectic, rhetoric, and theology for the sake of efficient controversy with ecclesiastical opponents.

**Effect of the Reformation upon Elementary Schools.** - But while the Catholics were inclined to leave the organization of education in the hands of various religious bodies, the Protestants more often thought it wise to have its support and control administered by the princes and the state. Owing to this secular management and their position on universal education, the Protestants, with the exception of the Anglicans, who had altered but little in doctrine, were inclined to establish state school systems and hold to the duty of providing and requiring elementary education at public expense. In this way the germs of the modern tendency toward universal, free, and compulsory education began to appear, although they did not ripen until much later.

In the German states there were many illustrations of the spread of elementary education and civic control. As an immediate result of Luther's *Letter to the Mayors* in 1524, the city of Magdeburg united its parish schools under one management and adopted the Protestant ideals. So, in 1525, the school at Eisleben, organized upon a Protestant basis (see p. 128), included elementary as well as secondary work. Similar ideals and organization appear in the provision for 'German' schools in the 'Church orders' sent out by Bugenhagen (see pp. 128 i.) to the Protestant cities and states of Northern Germany. A further step was taken in 1528 when Melanchthon drew up a plan for schools throughout the entire Electorate of Saxony. This, the first state school system in history, was followed by one in Wiirtemberg, where in 1559 Duke Christopher adopted an improvement upon the Saxon plan, which called for a religious and elementary training for the children of the common people in every village of the duchy. Brunswick in 1569, and Saxony in 1580, followed the lead of Wiirtemberg in revising their school systems. Before the middle of the next century, a number of other states of Germany, such as Weimar, Hessen-Darmstadt, Mecklenburg, Holstein, Hessen-Cassel, and Gotha modeled elementary school systems after those of Saxony and Wiirtemberg. While the Catholics did not in general maintain public elementary education, the Christian Brothers and others undertook a great work in this direction, and Duke Albrecht V of Bavaria even ordered throughout his state the establishment of 'German' schools with instruction in reading, writing, and the Catholic creed. This organization of universal education continued its advance, despite the decimation and the general havoc upon finance and education wrought by the Thirty Years' War (1618-1648), and by the end of the eighteenth century practically every village throughout the German states had its *Volksschule* or 'people's school.' These institutions were under the direction of the pastor of each parish, and while actual conditions may often have been somewhat below the statutory level and in many cases were a wretched apology, every child not studying at a secondary school was in theory obliged, between the ages of six and thirteen, to attend one of these schools of the people (Fig. 20).

As a result of the Dutch Reformed movement, Holland also made early provision for instruction in religion, reading, and writing. The Church at various synods, and civic authorities in many statutes, recognized the need of universal training, and finally the great Synod of Dort, by a combination with the civil government, in 1618 required every parish to furnish elementary education for all. Similarly, through Knox, Scotland established elementary schools under the control of the parishes. Preliminary steps in this direction were taken by the Privy Council and the Scotch Parliament early in the seventeenth century, and in 1646 the parliament further enacted that there be "a Schoole founded, and a Schoole master appointed in every Parish," and provided that if a parish should fail in this duty, the presbytery should have power to establish the school and compel the parish to maintain it. Half a century later this school system was given over more fully to the control of the State, but even then much of the old connection with the Church was apparent. These schools gave instruction in readings writing, and religion, with the Bible as text, and have done a wonderful work in raising the level of intelligence and affording an opportunity to the children of the lower classes in Scotland. England herself continued to hold to aristocratic and 'selective' education, and gave little heed to the establishment of elementary schools; but the American colonies, as far as they were founded by Calvinists or Lutherans, provided early for elementary education (see p. 189). The Puritan towns of the Massachusetts colony established schools almost as soon as they were settled, and in 1647 the legislature enacted that all towns with fifty families should provide an elementary school. Connecticut followed the example three years later, and before the close of the century, similar action was taken by New Hampshire and Vermont (see pp. 197 and 199). Likewise, New Amsterdam and the villages of New Netherlands followed the example of the Mother Country and provided public schools in connection with each church through the support of the Dutch West India Company or of the civil and ecclesiastical bodies jointly (see pp. 193 f).

**Effect of the Reformation upon the Secondary Schools.** - While the development of elementary instruction and state systems of education was the most important educational outcome of the Reformation, the movement had a somewhat similar effect upon the humanistic secondary education of the time. In Protestant Germany the Latin schools and gymnasia came under the control of the princes and the State rather than the Church, and gradually became the backbone of the state school systems. But they stressed the religious element in their curriculum, and the direct management of education was simply transferred to Protestant ministers or leaders. The schools were still taught and inspected by representatives of the Church, but the form of the organization and administration of education was radically changed. In England there was a similar transfer of management to the Protestant clergy. The existence of the schools had to be authorized and their teachers licensed by the bishop, and they were at all times liable to visitation from ecclesiastical authority. The grammar schools, however, were never organized like the gymnasia, but each school remained independent of the rest and of any national combination. Nor were the Calvimstic colleges united into a national system, except where they came into Germany, when they were absorbed into the system of the gymnasia. The state system of education established by the Scotch parliament in the parishes, often gave secondary training, as well as elementary. And in America the establishment and control of the 'grammar' schools, inherited from the mother country, were vested in the authorities of the state and the several towns. On the other hand, the Catholic education in all countries found its secondary schools largely in the colleges of the Jesuits, and the subordination of the individual to authority and the Church was insisted upon.

**Influence of the Reformation upon the Universities.** - In the case of the universities, many remained loyal to Catholicism and a few new Catholic foundations grew out of the Reformation. All these adhered to the principle of submission to ecclesiastical authority. But the majority of the universities in the Protestant states of Germany followed their princes when they changed from the old creed to the new. Wittenberg, through its connection with Luther and Melanchthon, was the first German university to become Protestant, but others, like Marburg, Konigsberg, Jena, Helmstadt, and Dorpat followed rapidly. Altdorf and Strassburg were developed out of gymnasia. The English universities, Oxford and Cambridge, went over to Protestantism with the national Church. In America, too, Harvard and other early colleges were closely connected with the various commonwealths and with the Calvinistic or the Anglican communion, according to the colony.

**The Lapse into Formalism.** - There came to be both in Catholic and Protestant institutions a tendency to regard the subjects taught as materials for discipline rather than as valuable for their content. The studies largely became an end in themselves and were deprived of almost all their vitality. The curriculum of the institutions became fixed and stereotyped in nature, and education lapsed into a formalism but little superior to that of the mediaeval scholastics. The methods of teaching came to stress memory more than reason. The Protestants had claimed to depend less upon uncritical and obedient acceptance of dogma than upon the constant application of reason to the Scriptures, but they soon tended to emphasize the importance of authority and the repression of the individual quite as clearly as the Catholics, who definitely held that reason is out of place and unreliable as a final guide in education and life. Hence, except for launching the great conception of state support and control of education, the Reformation accomplished but little directly making for individualism and progress, either through the Catholic awakening or the Protestant revolts. Education fell back before long into the grooves of formalism, repression, and distrust of reason. There resulted a tendency to test life and the educational preparation for living by a formulation of belief almost as much as in the days of scholasticism.

**Supplementary Reading**

Graves, *During the Transition* (Macmillan, 1910), chap. XVXVI; Monroe, *Text-book* (Macmillan, 1905), chap. VII. An excellent interpretative account of the Reformation is that in Adams, G. B., *Civilization during the Middle Ages* (Scribner, 1894), chaps. XVI and XVII. Painter, F. V. N., furnishes a good translation of *Luther on Education* (Lutheran Publication Society, Philadelphia). Richard, J. W., gives a good account of *Melanchthon, the Protestant Preceptor of Germany* (Putnam, 1898), especially chaps. II-IV and VII; Watson, F., of *Maturinus Corderius, the Schoolmaster of Calvin* (School Review, vol. XII, nos. 4, 7, and 9); Graves, F. P., *Ramus and the Educational Reformation of the Sixteenth Century* (Macmillan, 1912) of conditions in France; and Leach, A. F., of the dissolution acts of Henry VIII and Edward VI in *English Schools at the Reformation* (Constable, London, 1896), pp. 58-122. On the side of Catholic education, one should read Schwickerath, R., *Jesuit Education* (Herder, St. Louis), chaps. Ill-VIII and XV-XVIII; Cadet, F., *Port Royal Education* (Bardeen, Syracuse, 1899; George Allen and Co., London) pp. 9-119; and Wilson, Mrs. R. F., *Christian Brothers* (London, 1883), which gives an epitome of Ravelet, A., *Life of La Salle.* The influence of the Reformation upon the German schools and universities, both Protestant and Catholic, is shown in Nohle E., *History of the German School System* (Report of the United States Commissioner of Education, 1897-98, vol. I), pp. 30-40; and Paulsen, F., *German Education* (Scribner, 1908), pp. 79-85.