# 15. Sense Realism and the Early Scientific Movement

**Outline**

-   In the seventeenth century scientific investigation developed rapidly, and led theorists to introduce science into the curriculum and to advocate a study of 'real things.'
-   Bacon undertook to formulate induction, and while he did not understand the importance of an hypothesis, he did much to rid the times of *a priori* reasoning.
-   On the basis of sense realism, Ratich anticipated many principles of modern pedagogy, but he was unsuccessful in applying his ideas.
-   Comenius (1) produced texts for teaching Latin objectively, (2) crystallized his educational principles in the *Great Didactic,* and (3) attempted an encyclopaedic organization of knowledge. He wished to make this knowledge part of the course at every stage of education, and, while he was not consistently inductive, he made a great advance in the use of this method.
-   Through sense realism, rudimentary science was introduced into the elementary schools; the *Ritterakademien* and the pietist schools stressed the subject; and professorships of science were founded in the universities.

**The Development of the Sciences and Realism.** - The realistic tendency did not pause with reviving the ideas represented by the words nor with the endeavor to bring the pupil into touch with the life he was to lead. The earlier realism seems to have been simply a stage in the process of transition from the narrow and formal humanism to a realism obtained through the senses, which may be regarded as the beginning of the modern movement to develop the natural sciences. Science had started to develop as early as the time of the schoolman, Roger Bacon (1214-1294), but for three centuries it was not kindly received. Even during the Renaissance the Church had continued to oppose it bitterly, because it tended to conflict with religious dogma, although this age did not object to the revival of the classics. Accordingly, the latter subject became strongly intrenched in educational tradition, and its advocates offered the most obstinate opposition to the sciences. Its numerous representatives struggled hard to keep the sciences out of education.

However, concomitant with the growth of reason and the partial removal of the theological ban, there was developed a remarkable scientific movement, with a variety of discoveries and inventions. For more than a millennium the Greek developments in astronomy and physics had been accepted as final, but toward the close astronomy of the sixteenth and during the seventeenth century these *dicta* were completely upset. The hypothesis of a solar system, which replaced the Ptolemaic interpretation, was published by Copernicus (1473-1543); Kepler (1571-1630) explained the motion of the planets by three simple laws; and, through the construction of a telescope, Galileo (1564-1642) revealed new celestial phenomena. Galileo also demonstrated that all bodies, allowing for the resistance of the air, fall at the same rate; by means of the barometer, Torricelli (1608-1647) and Boyle (1627-1691) proved the existing theories of a vacuum incorrect, and formulated important laws concerning the pressure of gases; and Guericke (1602-1686), inspired by their discoveries, succeeded in constructing an air-pump. Investigations of this kind paved the way for the formulation of the law of universal gravitation and the laws of motion by Sir Isaac Newton (1642-1727), which united the universe into a single comprehensive system and completed the foundations for modern mechanics.

Likewise, about the same time, the other great development in science among the Greeks,-anatomy and physiology, was completely revolutionized. Through the discovery of valves in the veins by means of dissection and vivisection, the hypothesis of the double circulation of the blood by Harvey (1578-1657), and the microscopic demonstrations by Malpighi (1628-1694) of the existence of capillaries connecting the veins and the arteries, the old theory of the motion of the blood through suction, which had been promulgated by Galen, was completely shattered, and a great impetus was given to investigations in anatomy and physiology. In consequence of this scientific progress, the educational theorists began to introduce science and a knowledge of real things into the curriculum. It came to be widely felt that humanism gave a knowledge only of words, books, and opinions, and did not even at its best lead to a study of real things. Hence, new methods and new books were produced, to shorten and improve the study of the classical languages, and new content was imported into the courses of study. The movement also included an attempt at a formulation of scientific principles in education and an adaptation to the nature of the child.

**Bacon and His Inductive Method.** - The new tendency, however, did not appear in education until after the time of Francis Bacon (1561-1626). The use of the scientific method by the various discoverers was largely unconscious, and it remained for Bacon to formulate method of the what he called the method of 'induction,' and by advocating its use, to point the way to its development as a scientific method in education. He is, therefore, ordinarily known as the first sense realist. He reacted from deductive logic, which was currently supposed to be the sole method of Aristotle, and took his cue in formulating a new method of reasoning from the many scientific workers of his time. He made a great advance in his rejection of the contemporary method of attempting to establish the first principles of a science, and then deducing from them by means of the syllogism all the propositions which that science could contain. However, his *Novum Organum,* or 'new instrument,' as he called his treatise, in endeavoring to create a method whereby anyone could attain all the knowledge of which the human mind was capable, undertook far too much, and resulted in a merely mechanical procedure. Briefly stated, his plan was, after ridding the mind of individual prejudices, to observe and carefully tabulate lists of all the facts of nature, and from these discover the underlying law by comparing the cases where a certain phenomenon appears and where it does not.

But by this method neither Bacon himself nor anyone else has ever made any real contribution to science. It does not follow that, because all observed cases under certain conditions produce a particular effect, every other instance not yet observed will necessarily have the same effect. The true method of induction, which was evident even in the work of Kepler, and came to be more so in the discoveries of Harvey and Newton, stresses rather the part played by scientific imagination, as it is manifested by men of genius in the forming of an hypothesis. The modern procedure is as follows: - When certain effects are observed, of which the cause or law is unknown, the scientist frames an hypothesis (i. e., makes a conjecture) to account for them; then he tests this hypothesis, by collecting facts and comparing with these facts the conclusions to which his hypothesis would lead; and, if they correspond or agree, he holds that his hypothesis has been confirmed or verified, and maintains that he has discovered the cause or law. Nevertheless, while Bacon did not formulate the inductive method of modern science, he largely helped to rid the times of an unwise dependence upon *a priori* reasoning, and he did call attention to the necessity of careful observation and experimentation, and thus opened the way for real inductive procedure. Probably no book ever made a greater revolution in modes of thinking or overthrew more prejudices than Bacon's *Novum Organum.*

**Bacon's Educational Suggestions and Influence.** - Bacon was not a teacher, and his treatment of educational problems appears in brief and scattered passages. While he offers isolated suggestions concerning the mental and moral training of the young, he plans no serious modification in the existing organization of schools. He does, however, in his *New Atlantis* imply an interest in promoting scientific research and higher education. In the ideal society depicted in that work, he describes an organization of scholars called 'Salomon's House,' whose members in their investigations anticipate much that scientists and inventors have to-day only just begun to realize. Among these anticipations were the variation of species, the infusion of serums, vivisection, telescopes, telephones, flying-machines, submarine boats, and steamengines. From this description Bacon would seem to believe that education should be organized upon the basis of society's gradually accumulating a knowledge of nature and imparting it to all pupils at every stage. At any rate, in his *Advancement of Learning,* he definitely suggests a wider course of study, more complete equipment for scientific investigation, a closer cooperation among institutions of learning, and a forwarding of 'unfinished sciences.' And such a plan of *pansophia,* or 'universal knowledge,' was specified in the educational creed of the later sense realists, who worked out the Baconian theory of education. Hence, while not skilled or greatly interested in education himself, Bacon influenced profoundly the writing of many who were, and has done much to shape the spirit of modern practice. His method was first applied directly to education by a German known as Ratich and, in a more effective way, by Comenius, a Moravian.

**Ratich's Methods.** - Ratich (1571-1635) probably became acquainted with the sense realism of Bacon while studying in England, and, when about forty years of age, undertook to found a system of education upon it. In linguistic training, like all realists, he insisted that one "should first study the vernacular" as an introduction to other languages. He also held to the principle of "one thing at a time and often repeated." By this he meant that, in studying a language, one should master a single book before taking up another. In his teaching at Köthen, as soon as his pupils knew their letters, they were required to learn *Genesis* thoroughly for the sake of their German. Each chapter was read twice by the teacher, while the pupil followed the text with his finger. When the pupils could read the book perfectly, they were taught grammar from it as a text. The teacher pointed out the various parts of speech and made the boys find other examples, and had them decline, conjugate, and parse. In taking up Latin, a play of Terence was treated in similar fashion. Others of the principles that he used in teaching language and grammar, and especially those which applied to education in general, were even more distinctly realistic. Such, for example, were his precepts, - "follow the order of nature" and "everything by experiment and induction," and his additional recommendation that "nothing is to be learned by rote." Thus Ratich not only helped shape some of the best methods for teaching languages, but anticipated the main principles of modern pedagogy. While, owing to obtrusive failings in character and experience, he was uniformly unsuccessful in his practice, he, nevertheless, stirred up considerable thought and stimulated many treatises of others. Thus, through Comenius, who carried out his principles more fully, this German innovator, unpractical as he was, became a spiritual ancestor to Pestalozzi, Froebel, and Herbart.

**Comenius: His Training and Work.** - John Amos Comenius (1592-1670) was born at Nivnitz, Moravia, and was by religious inheritance a staunch adherent of the Moravian Church. After a course in a Latin school, he spent a couple of years in higher education at the Lutheran College of Herborn and at the University of Heidelberg. In consequence of many vicissitudes in life, he lived and wrote in a number of places, and became acquainted with the work of a variety of men engaged in educational reform and advancement. While the problems with which they were dealing were similar to his own and largely influenced his educational positions, he far surpassed them all in scope of work and greatness of repute. His educational achievements were the outgrowth of sense realism, and appear in three directions: - (1) the series of texts for learning Latin; (2) his *Great Didactic;* and (3) his attempts to create an encyclopaedic organization of knowledge *(pansophia).*

**His Series of Latin Texts.** - The first of the famous texts that Comenius produced to facilitate the study of Latin was issued in 1631, and has generally been known by the name of *Janua Linguarum Reserata* (The Gate of Languages Unlocked). It was intended as an introductory book to the study of Latin, and consisted of an arrangement into sentences of several thousand Latin words for the most familiar objects and ideas. The Latin was printed on the right-hand side of the page, and on the left was given a translation in the vernacular. By this means the pupil obtained a grasp of all ordinary scientific knowledge and at the same time a start in his Latin vocabulary. In writing this text, Comenius may have been somewhat influenced by Ratich, a review of whose methods he had read at Herborn, but he seems to have been more specifically indebted both for his method and the felicitous name of his book to a Jesuit known as Bateus, who had written a similar work.

It was soon apparent that the *Janua* would be too difficult for beginners, and two years later Comenius issued his *Vestibulum* (Vestibule), as an introduction to it. While the *Janua* contained all the ordinary words of the language, - some eight thousand, there were but a few hundred of the most common in the *Vestibulum.* Later both of the works were several times revised, modified, and enlarged; and grammars, lexicons, and treatises were written to accompany them. He also published a third Latin reader, the *Atrium* (Entrance Hall), which took the pupil one stage beyond the *Janua.* We know, too, that he intended also to write a still more advanced work, to be called *Sapientiae Palatium* (Palace of Wisdom). This fourth book was to consist of selections from the best Latin authors, but it was never completed. He did, however, produce as a supplementary text-book a simpler and more extensive edition of the *Janua,* accompanied with pictures. Each object in the illustrations of this book was marked with a number corresponding to one in the text. This work, which he called *Orbis Sensualium Pictus* (The World of Sense Objects Pictured), is the first illustrated reading book on record (Fig. 21).

***The Great Didactic.*** - But these books on teaching Latin realistically were only part of the work that Comenius contemplated. During his whole career he had in mind a definite idea of the aim of education, and of what, in consequence, he wished the organization, subject-matter, and methods to be. His ideas on the whole question of education were formulated in his *Great Didactic* even before the *Janua* appeared, but the work was not published until 1657. In it he strove to assimilate all that was good in the realistic movement and use it as a foundation. He developed many of the principles and methods of Ratich, Bateus, and others, but he owed a greater debt for the suggestions he took from Bacon's *Advancement of Learning,* and even more from the *Encyclopedia* of Alsted, one of his teachers at Herborn. In the *Great Didactic* Comenius formulated an educational aim and constructed an educational organization of his own. Probably, as an outgrowth of his religious attitude, he held to 'knowledge, morality, and piety' as the ideals of education, and advocated universal education for 'boys and girls, both noble and ignoble, rich and poor.' His organization of education consisted of four-periods of six years each. The first period of instruction was that through infancy, or up to the age of six. It was to be given in the school of 'the mother's lap,' which should exist in every house. For childhood, or from six to twelve, was to be organized the 'vernacular schooL' which should appear in every hamlet and village. From that time up to eighteen comes the 'Latin school' to be maintained in every city; and, finally, for youth from eighteen to twenty-four, there should be a university in every kingdom or province. Such an organization would have made education universal, and would tend to bring about the custom of education according to ability, rather than social status, which was a suggestion some three centuries in advance of the times.

**His Encyclopaedic Arrangement of Knowledge.** - The rest of the works of Comenius may be regarded as amplifications of various parts of this *Great Didactic.* Besides the Janual series, which he seems to have written for the Latin school, he produced a set of texts for the vernacular school, which soon disappeared, and a handbook for the lowest work, called *The School of Infancy.* But the phase of the *Great Didactic* most often elaborated was the realistic one of *pansophia* or universal knowledge. This principle was not only exemplified in such works as the *Janua* and *Orbis Pictus* and in treatises he wrote upon astronomy and physics, but in various educational institutions that he undertook to found, and it remained the ruling passion throughout his life. In the *Great Didactic* he went so far as to hold that an encyclopaedic training should be given at every stage of education, - mother school, vernacular school, Latin school, and university.

But, while even in the mother school the infant was to make a beginning with geography, history, and various sciences, grammar, rhetoric, and dialectic, music, arithmetic, geometry, and astronomy, and the rudiments of economics, politics, ethics, metaphysics, and religion, his attainment was not expected to be as formidable as the names of the subjects sound. It was to consist merely in understanding simple causal, temporal, spatial, and numerical relations; in distinguishing sun, moon, and stars, hills, valleys, lakes, and rivers, and animals and plants; in learning to express oneself; and in acquiring proper habits. It was, in fact, not unlike the training of the modern kindergarten. In a similar way each succeeding stage is to enlarge the body of knowledge along all these lines. "The different schools are not to deal with different subjects, but should treat the same subjects in different ways; throughout graduating the instruction to the age of the pupil and the knowledge that he already possesses. In the earlier schools everything is taught in a general and undefined manner, while in those which follow the information is particularized and exact." Moreover, beyond the university, which, like the lower schools, was to make teaching its chief function, Comenius held it to be important that somewhere in the world there should be a 'didactic college' devoted to scientific investigation, in which learned men from all nations should cooperate. Such an institution would form a logical climax to his system of schools, bearing the same relation to them that the stomach does to the other members of the body by "supplying blood, life, and strength to all."

**The Method of Nature.** - The way in which this pansophic instruction should be given, Comenius also intended to have in full accord with sense realism. He insists that the 'method of nature' must be observed and followed, and then shows how nature accomplishes all things 'with certainty, ease, and thoroughness,' in what respects schools have deviated from the principles of nature, and how they can be rectified only by following her plans. These principles concerning the working of nature were laid down *a priori,* but it is probable that they had been previously worked out inductively from his schoolroom experience. At times, though, they were put in the form of fanciful analogies. For example, he declares that because a bird by nature hatches her young in the spring or early part of the year, schools have erred (1) in not requiring education to begin in the springtime of life, or boyhood, and (2) in not selecting the springtime of the day, or the morning hours, for study. But it is not remarkable that, with all his realistic tendencies, Comenius did not consistently employ induction. The natural sciences were young in his day, so that he did not altogether grasp their content and method, and he had partially inherited the scholastic notion that truth cannot be fully secured through the senses or by reason. It is sufficient merit that Comenius, for the first time in history, applied anything like induction to teaching. Moreover, in the application of his general method to the specific teaching of various lines, - sciences, reading, writing, singing, languages, morality, and piety, he utilized more fully the induction of Bacon. For example, after showing the necessity for careful observation in obtaining a knowledge of the sciences, he gives nine useful precepts for their study that are clearly the inductive result of his own experience as a teacher. Likewise, he insists that, in teaching the sciences, in order to make a genuine impression upon the mind, one must deal with realities rather than books. The objects themselves, or where this is not possible, such representations of them as can be conveyed by copies, models, and pictures, must be studied. After the same principle he formulates inductive rules and methods for instruction in the other subjects.

**The Influence of Comenius upon Education.** - Thus the work of Comenius was based primarily upon sense realism, but he added many modifications and new elements of his own. He may in the fullest sense be considered the great educational theorist and practical reformer of the seventeenth century. His practical ability is especially shown in the series of Latin text-books, which far excelled the works of several contemporaries on similar lines. The *Janua* was translated into a dozen European, and at least three Asiatic languages; the *Orbis Pictus* proved even more popular, and went through an almost unlimited number of editions in various tongues; and the whole series became for many generations the favorite means of introducing young people to the study of Latin. But the remarkable theoretical work of Comenius had little effect upon the schools of the period, and until about the middle of the nineteenth the *Great Didactic* was scarcely known. At that time, when this treatise of Comenius was brought to light by German investigators, it was discovered that the old realist of the seventeenth century had been the first to deal with education in a scientific spirit, and work out its problems practically in the schools. And the principles of Comenius were at the time unconsciously taken up by others and indirectly became the basis of modern education. His spirit appeared not only in the ideas of subsequent theorists - Francke, Rousseau, Basedow, Pestalozzi, Herbart, Froebel - but even in the actual curricula and methods of educational institutions.

**Realistic Tendencies in Elementary Schools.** - While the effect of sense realism upon the schools seems to have been slow and indirect, the movement was obvious even in the seventeenth century. In Germany there came a decided tendency throughout the elementary schools to increase instruction in the vernacular, as recommended by Ratich and Comenius, and to learn first the German grammar rather than the Latin. With this movement was joined the increase in universal and compulsory education urged by the reformers, and an introduction of elementary science, in addition to reading, writing, arithmetic, religion, and singing. At Weimar in 1619, through a pupil of Ratich, a new school system was organized; and in 1642, under the order of Duke Ernst, Andreas Reyher prepared a new course for Gotha, which afforded elementary instruction in the natural sciences, as well as the rudiments and religion. This work included teaching the children to measure with the hour-glass and sun-dial, to observe the ordinary plants and animals, and to carry on other objective studies of a simple character. Many other attempts at instruction in science were made elsewhere in the German states, both in private and public education, and the same tendency appeared in the states of Italy, and in France, Holland, and England.

**Secondary Schools.** - But the new realistic tendencies appeared also in secondary education. While in Germany it was not until the eighteenth century that there were any evidences of sense realism in the gymnasia, languages of neighboring countries and considerable science appeared in the *Ritterakademien* (see p. 157) by the middle of the seventeenth, and toward the end of the century in the schools of Francke and other 'pietists' at Halle were embodied all the realistic elements of Comenius. While the pietists adopted these ideas largely for their religious side, as a protest and reaction to the rationalistic *Ritterakademien,* they did not hesitate also to stress the science content and the study of the vernacular. In the secondary school known as the *Padagogium,* which he had started for well-to-do boys, Francke included training in the vernacular, mathematics, geography, natural science, astronomy, anatomy, and materia medica; and the *Realschule,* established by his colleague, Semler, went even more fully into the vernacular, mathematics, and the sciences, pure and applied. This realistic instruction of the pietists was brought by Hecker to Berlin, where he started his famous *Realschule* in 1747, and similar institutions soon spread throughout Prussia. In England, while very few of the grammar and public schools (see p. 120) as yet introduced even the elements of science into their course, the academies (see p. 157) were rich in sciences, mathematics, and the vernacular. This was also true of the academies that sprang up in America (see p. 158).

**The Universities.** - The universities were slower in responding to the movement of sense realism. As the result of its pietistic origin, however, the University of Halle was realistic almost from its beginning in 1692. Göttingen, the next institution to become hospitable to the tendency, did not start it until 1737. But soon afterward the movement became general, and by the end of the eighteenth century all the German universities - at least, all under Protestant auspices - had created professorships in the sciences. While the English universities, Oxford and Cambridge, were much slower than those of Germany in adopting the new subjects, and it was a century and a half before these institutions became known for their science, during the professorship of Isaac Newton (1669-1702) considerable was done toward making Cambridge mathematical and scientific, and in the course of the eighteenth century several chairs in the sciences were established. Besides formulating the law of gravitation, Newton lectured and wrote at Cambridge upon calculus, astronomy, optics, and the spectrum. He became one of the greatest mathematicians and physicists the world has known, and he did much to create a scientific atmosphere in other educational institutions, as well as Cambridge. America also felt the scientific impulse in its higher institutions. Some study of astronomy, botany, and physics was possible at Harvard even in the seventeenth century, and during the eighteenth Yale, Princeton, King's (afterward Columbia), Dartmouth, Union, and Pennsylvania all came to offer a little work in physics, and at times in chemistry, geology, astronomy, and biology. In his proposals for the prospective 'seminary' in New York (1753), which was destined to become Columbia University, and in the actual course of the academy at Philadelphia (later the University of Pennsylvania), over which he presided, Dr. William Smith put a most progressive program of sciences, including the rudiments of mechanics, physics, chemistry, geology, astronomy, botany, zoology, and physiology. But for half a century after this American institutions did little with the sciences as laboratory studies.

**Supplementary Reading**

Graves, *During the Transition* (Macmillan, 1910), chap. XVIII; and *Great Educators of Three Centuries* (Macmillan, 1912), chaps. II, IV, and VI; Monroe, *Text-book* (Macmillan, 1905), pp. 461-501. The following works are standard for the authors mentioned: Adamson, J. W., *Pioneers of Modern Education* (Macmillan, 1905), chap. Ill (Bacon); Barnard, H., *German Teachers and Educators,* pp. 343-370 (Ratich); Fowler, T., Bacon's *Novum Organum* (Oxford, Clarendon Press); Laurie, S. S., *John Amos Comenius* (Bardeen, Syracuse, 1892); Monroe, W. S., *Comenius* (Scribner, 1900); and Quick, R. H., *Educational Reformers* (Appleton, 1896), chap. IX (Ratich) and X (Comenius). An account of sense realism is afforded by Adamson, *op. cit.,* chap. I, and of its effect upon the schools by Barnard, *op. cit.,* pp. 302-317, and by Paulsen, F., *German Education* (Scribner, 1908), pp. 117-133.