# 16. Formal Discipline in Education

**Outline**

-   Locke is often classed with the advocates of realism or of naturalism, but the keynote to his thought is 'discipline.' This is to be obtained in intellectual training through mathematics; in moral training, through the control of desires by reason; and in physical training, through a 'hardening process.'
-   Locke has, therefore, often been viewed as the great advocate of the theory of formal discipline, according to which certain subjects yield a general power that may be applied in any direction, and should be studied by all.
-   This doctrine has greatly influenced education, but in the late nineteenth century there was a decided reaction from it. Recently this extreme reaction has been modified, and a position taken with which Locke's real attitude would seem to be in harmony.

**Locke's Work and Its Various Classifications.** - Because of their relation to an important topic in modern education, the theories of John Locke (1632-1704) should receive further attention than they have yet been given. No writer on education has been more variously classified than he. We have already seen (p. 154) that the general tenor of his *Thoughts concerning Education* would lead us to group him with the early realistic movement. There are also elements in this work that would seem to place him with the sense realists, and many of his ideas proved so similar and suggestive to Rousseau's thought (see p. 213), that he has sometimes been classed among the advocates of naturalism. But Locke's *Thoughts,* by which his educational position is often exclusively judged, were simply a set of practical suggestions for the education of a gentleman, written for a friend as advice in bringing up his son. They make clear his general sympathy with the current educational reform, but do not bring out his main point of view. His central thought appears more definitely through the philosophical principles in his famous *Essay concerning the Human Understanding,* and through the intellectual training suggested in his other educational work, *Conduct of the Understanding,* which was originally an additional book and application of the *Essay.*

**Locke's Disciplinary Theory in Intellectual Education.** - Probably Locke's underlying thought as to the proper method of intellectual, moral, and physical training may best be summed up in the word 'discipline.' This educational attitude is a natural corollary of his philosophic position. In his *Essay* he holds that ideas are not born in one, but that all knowledge comes from experience. The mind, he declares, is like 'white paper, or wax,' upon which impressions from the outside world are made through our senses. When the ideas are once in mind, it is necessary to determine what they tell us in the way of truth. Hence, to train the mind to make proper discriminations, he declares in the *Conduct of the Understanding* that practice and discipline are necessary. "Would you have a man reason well, you must use him to it betimes, exercise his mind in observing the connection of ideas and following them in train." As to the means of effecting this mental discipline, Locke holds: "Nothing does this better than mathematics, which therefore I think should be taught all those who have the time and opportunity, not so much to make them mathejnaticians as to make them reasonable, creatures, that having got the way of reasoning, which that study necessarily brings the mind to, they might be able to transfer it to other parts of knowledge as they shall have occasion." Similarly, he advises a wide range of sciences, "to accustom our minds to all sorts of ideas and the proper ways of examining their habitudes and relations; not to make them perfect in any one of the sciences, but so to open and dispose their minds as may best make them capable of any, when they shall apply themselves to it."

**Disciplinary Attitude in Moral and Physical Training.** - The same disciplinary conception of education underlies Locke's ideals of moral training: "That a man is able to deny himself his own desires, cross his own inclinations, and purely follow what reason directs as best, tho' the appetite lean the other way. This power is to be got and improved by custom, made easy and familiar by an early practice." And even more definitely disciplinary is the well-known 'hardening process,' which he recommends in physical training: "The first thing to be taken care of is that children be not too warmly clad or covered, winter or summer. The face, when we are born, is no less tender than any other part of the body. It is use alone hardens it, and makes it more able to endure the cold." He likewise advises that a boy's "feet be washed every day in cold water," that he "have his shoes so thin that they might leak and let in water," that he "play in the wind and sun without a hat," and that "his bed be hard."

**Origin, Significance, and Influence of the Theory of Formal Discipline.** - This emphasis upon discipline in training of every sort - intellectual, moral, physical - has often caused Locke to be regarded as the first great exponent of the educational doctrine of 'formal discipline.' That theory has been so widespread and important during the past two centuries as to require consideration here. During the Middle Ages and the early period of humanism Latin was not only of cultural, but of practical utilitarian value. It was the language of the Church and of diplomacy, and in it was locked up all the learning of the times. All guidance in science, literature, philosophy, and politics that received any consideration was couched in its terms. But with the decline of ecclesiastical influence, the development of vernacular languages, and the scientific awakening in the seventeenth century (see pp. 163 f.), this utilitarian argument for the study of Latin was largely swept away. Appeal was then made in behalf of the subject to the doctrine of 'formal discipline,' which was supported by the 'faculty' psychology of Aristotle. It was held that the study of Latin yields results out of all proportion to the effort expended, and gives a general power that may be applied in any direction. A similar claim was before long made for Greek and mathematics. Mathematics was declared to sharpen the 'faculty of reason,' while the classic languages were believed to improve the 'faculty of memory.' Consequently, it gradually came to be argued by formal disciplinarians that every one should take these all-important studies, regardless of his interest, ability, or purpose in life, since he would thus best prepare himself for any field of labor. All who proved unfitted for these particular subjects have, therefore, been supposed to be not qualified for the higher duties and responsibilities, and to be unworthy of consideration in higher education.

This doctrine of formal discipline has had a tremendous effect upon each stage of education in practically every country and during every period until recently. Even the scientists and advocates of a variety of other subjects, instead of arguing for content value and particular training, have made strenuous efforts to meet this argument by pointing out the formal discipline in their own studies (see pp. 404 f.). Excellent examples of the effect of this theory upon educational institutions are found in the formal classicism of the English grammar and public schools and universities and of the German gymnasiums. While in the United States a newer and more flexible society has enabled changes to be more readily made, as late as the last decade of the nineteenth century, Greek, Latin, and mathematics largely made up the staples in many high schools, colleges, and universities, and the husks of formal grammar were often defended in elementary education upon the score of formal discipline.

**Opposition to the Disciplinary Theory and More Recent Modification.** - At the beginning of the twentieth century, however, with the abandonment of the 'faculty psychology' and the development of educational theory, a decided reaction from the doctrines of formal discipline began among psychologists and common sense educators. It is now almost universally conceded that specific, rather than general, power is developed by the various studies, and no student is held to be unworthy of education or impervious to culture, simply because he is not adapted to the classics or mathematics. In consequence, the content of studies, rather than the process of acquisition has come to be emphasized, the curriculum has everywhere been broadened, and the principle of the election of subjects largely recognized. It has, however, been felt within the last half dozen years that in reacting from the old theory of formal discipline, educators went too far. While it is still held that emphasis must be laid upon the specific character of mental training, there are some generalized powers and values to be obtained. It is realized that "a general benefit can be derived from specific training in so far as the person trained has consciously wrought out in connection with the specific training a general concept of method, based upon the specific methods used in that training" (F. A. Hodge). Thus a student who has once realized the value of close reasoning through mathematical demonstrations is likely to develop a general concept of method, and can hardly be satisfied any longer with slovenly thinking in other fields; and the fine discriminations discovered in the classical authors, the balanced judgment used in historical method, and the accuracy required in the study of the sciences, may well be abstracted and tend to furnish a generalized ideal for other lines of endeavor.

**Locke's Real Position on Formal Discipline.** - It would seem as if this modified form of general power were all that Locke had in mind. He definitely concedes that "learning pages of Latin by heart, no more fits the memory for retention of anything else, than the graving of one sentence in lead makes it the more capable of retaining firmly any other characters." And while he holds that the method of reasoning in mathematics can be transferred 'to other parts of knowledge,' he declares that men who are reasonable in some things are often very unreasonable in others, and "men who may reason well in one sort of matters today may not do so at all a year hence." The generalized benefits that students may obtain from mathematics are simply that it "would show them the necessity there is, in reasoning, to separate all distinct ideas, and see the habitudes that all those concerned in the present inquiry have to one another, and to lay by those which relate not to the proposition in hand and wholly to leave them out of the reckoning. This is that which in other subjects is absolutely requisite to just reasoning." Thus Locke appears to be rather in harmony with modern educational theory than a thorough-going advocate of formal discipline. At any rate, it should be recognized that he did not defend, but vigorously assailed, the grammatical and linguistic grind in the English public schools. His attitude toward formal discipline seems to have sprung from his desire to root out the traditional and false, rather than to support the narrow humanistic curricula of the times.

**Supplementary Reading**

Graves, *During the Transition* (Macmillan, 1910), pp. 305-311; and *Great Educators* (Macmillan, 1912), chap. VI; Monroe, *Textbook* (Macmillan, 1905), chap. IX. For a more extended account of Locke, read his *Thoughts* and *Conduct,* and Fowler, T., *John Locke* (Macmillan, 1901). The literature of formal discipline is most extensive and the subject is still under discussion; but a good summary of all written up to 1911 is furnished in Heck,

W. H., *Mental Discipline and Educational Values* (John Lane, New York), and later articles can be found by consulting the index of *The American Psychological Review.* In a doctoral dissertation (University of Virginia), *John Locke and Formal Discipline,* Hodge, F. A., makes it clear that the common interpretation of Locke as a formal disciplinarian is unfair. The most typical of the earliest opposition to the disciplinary argument is probably found in Thorndike, E. L., *Educational Psychology* (Teachers College, New York, 1910), chap. VIII; the sanest discussion of the possible transfer of ideals appears in Bagley, W. C, *Educative Process* (Macmillan, 1905), chap. XIII; and the reaction to the reaction is best portrayed by Angell, Pillsbury, and Judd in *Educational Review,* vol. XXXVT, pp. 1-43. Lyans, C. K., in his article upon *Formal Discipline (Pedagogical Seminary,* vol. XXI, PP- 343\~393) makes a most careful analysis of the interpretations of the defenders and opponents of the theory, and gives a verythorough discussion of transfers.