# 20. Philanthropy in Education

**Outline**

-   In England, during the eighteenth century, there were numerous attempts to provide education for the poor through charityschools. The most important factor in maintaining these institutions was the Society for the Promotion of Christian Knowledge.
-   Among other organizations, there sprang up a Society for the Propagation of the Gospel in Foreign Parts, which supported schools throughout the American colonies, except Virginia. Charity schools were also maintained in America by various other agencies.
-   An attempt was likewise made by Raikes of Gloucester, England, to establish Sunday schools, for training the poor to read, and these institutions spread throughout the British Isles and America.
-   A system of instruction through monitors, developed by Lancaster and Bell, while formal and mechanical, furnished a sort of substitute for national education in England, and, spreading throughout the United States, paved the way for state support, and greatly improved the methods of teaching.
-   'Infant schools' for poor children also grew up during the nineteenth century in France, England, and the United States, and found a permanent place in the national systems, but they soon became formalized and mechanical.
-   Philanthropic education proved a first step toward universal and national education.

Reconstructive Tendencies of the Eighteenth Century. - The eighteenth century cannot be regarded altogether as a period of revolution and destruction. While<span id="ch20.xml#para.290.1.0.box.130.254.1263.798.q.60" class="gtxt_body"> such a characterization describes the prevailing tendencies, there were also social and educational forces that looked to evolution and reform rather than to a complete disintegration of society and a return to primitive living. Even in Rousseau, the arch-destroyer \^T and\^hT of traditions, we found many evidences of a recon- j~n~7~s~^'^£?^throi\>^' struction along higher lines, and such a positive movement was decidedly obvious in Basedow, Salzmann, and other philanthropinists. But in England reforms were especially apparent. In the land of the Briton, progress is proverbially gradual, and sweeping victories and Waterloo defeats in affairs of society and education are alike unwonted. The French tendency to cut short the social and educational process and to substitute revolution for evolution is out of accord ?"£especially</span>

in England.

with the spirit across the English Channel.

The Rise of Charity Schools in England. - And yet conditions in England at this time might well have incited people to revolution. Wages were low, employment was irregular, and the laboring classes, who num- wretched conbered fully one-sixth of the population, were clad in boring dass. rags, lived in hovels, and often went hungry. Opportunities for elementary education were rare. The few schools that remained after the Reformation had largely lost their endowments or had been perverted into secondary institutions, and had suffered from incompetent and negligent masters and from the religious upheaval of the times. It was as a partial remedy for this situation, that, toward the close of the seventeenth century, there sprang up a succession of 'charity schools,' in which children of the poor were not only taught, but boarded and sometimes provided with clothes, and the as remedy.^00^'

Foundation,

management,

books,

teachers,

and course.

boys were prepared for apprenticeship and the girls for domestic service. Probably about one thousand schools upon this general philanthropic basis had been established in England and Wales by the middle of the eighteenth century. Most of these had received substantial endowment, but numbers of them were maintained by private subscriptions.

The Schools of the S. P. C. K. - A factor that was even more important in opening charity schools was the 'Society for the Promotion of Christian Knowledge' (often abbreviated to S. P. C. K.). This society was founded in 1698 by Reverend Thomas Bray, D. D., and four other clergymen and philanthropists. As a rule, its schools were established, supported, and managed by local people, but the Society guaranteed their maintenance, and assisted them from its own treasury whenever a stringency in funds arose. The S. P. C. K. also inspected schools, and advised and encouraged the local managers, and furnished bibles, prayer books, and catechisms at the cheapest rates possible. It made stringent regulations of eligibility for its schoolmasters, requiring, in addition to the usual religious, moral, pedagogical, and age tests, that they be members of the Church of England and approved by the minister of the parish. Each master was expected to teach the children their catechism, and purge them of bad morals and manners, besides training them in reading, writing, and elementary arithmetic. The pupils were, moreover, clothed, boarded, and at times even lodged.

The number of charity schools of the S. P. C. K. grew by leaps and bounds, and by the close of the first decade there were eighty-eight within a radius of ten<span id="ch20.xml#para.292.1.0.box.129.228.1263.1556.q.60" class="gtxt_body"> miles of London. The gifts made had amounted to al- Development, most ten thousand pounds, and nearly one thousand boys and over four hundred girls had been sent out as apprentices. And before the middle of the eighteenth century the total number of these charity schools in England and Wales reached nearly two thousand, with about fifty thousand boys and girls in attendance. This increase in facilities for the education of the poor was not kindly received by many in the upper classes, who often felt that "there is no need for any learning at all for the meanest ranks of mankind: their business is to labour, not to think." But the charity schools had also XSScT ^and^ many warm supporters, and Addison even believed that as a result of them there would be "few in the next generation who will not at least be able to write and read, and have not an early tincture of religion." The benefactions for these institutions continued to increase for nearly half a century, but by the middle of the eighteenth century popular interest had waned. The sub- decadence, scriptions began to fall off, the system of inspection and the teaching became less effective, and the schools ceased to expand. Nevertheless, the S. P. C. K. had succeeded in impressing the Church of England with a sense of re- ^and^ influence, sponsibility for the establishment of a national school system upon a religious basis. Its schools were largely continued throughout the eighteenth century, and in most instances after 1811 were absorbed by the new educational organization of the English Church, the so-called 'National Society' (see p. 239).</span>

Other British Charity Schools. - These institutions of the Church of England society may be regarded as typical of British charity schools in general. There were, how<span id="ch20.xml#para.293.1.0.box.78.236.1269.43.q.60" class="gtxt_body">Nonconformist ever, also a dozen well-known foundations by non</span>

schools

conformists, including the 'Gravel Lane School' of Southwark, London, which was started over a decade before the S. P. C. K. was organized. And an interesting type of philanthropic institution known as 'cir'Circulating culating schools' was founded in Wales. These schools

schools.' .... , .. „ . .

simply aimed to teach pupils to read the Bible in Welsh, and when this had been accomplished in one neighborhood, the school was transferred to another. But a much more important organization was the offshoot of the S. P. C. K., that arose chiefly to carry on charity schools in the American colonies. This association, the 'Society for the Propagation of the Gospel in

fhe^U^s^da^p°G °^f^ ^Forei^g^n^ Parts,' (commonly known as S. P. G.), was

founded by Dr. Bray three years after the parent

society, but no schools were established for several

years.

The Charity Schools of the S. P. G - The first school

s\. p. <span style="font-variant:small-caps;">G. </span>»chooi of the S. P. G. was opened in New York City in 1700

in New York

City, - under William Huddleston, who had been conducting

a school of his own there. It was intended that the new school should follow the plan of the charity schools in England, but, while free tuition and free books were granted from the beginning, it was not until many years later that the means of clothing the children gratuitously was provided. Under different masters and with varying fortunes, the school was supported by the society until 1783, when the United States had finally cut loose from the Mother Country and started on a career of its own. Meanwhile Trinity Church had come more and more to take the initiative in the endowment and support of the school, and since the withdrawal of the<span id="ch20.xml#para.294.1.0.box.132.220.1232.98.q.60" class="gtxt_body"> society from America the institution has been known as now 'Trinity 'Trinity Church School.' School.'</span>

Schools of the same type were active throughout the colonies in the eighteenth century. We possess more or less complete accounts of these institutions in New York and all the other colonies, except Virginia, where ^0ther^ ^colonies^they were not believed to be needed. Except for size and local peculiarities, all of them closely resembled the school in New York City. The attendance ranged ^Attendanc^e. from eighteen or twenty pupils to nearly four times that number. Girls were generally admitted, and occasionally equalled or exceeded the boys in number. As a rule, children of other denominations were received on the same terms as those of Church of England members, and at times nearly one-half the attendance was composed of dissenters, but often those outside the Church were given secondary consideration, or the catechism was so stressed by the school that the dissenting children were withdrawn and rival schools set up. The character of the course of study in these charity schools is further £ooS!' ^and^ indicated by the books furnished by the society. In packets of various sizes it sent over horn-books, primers, spellers, writing-paper and ink-horns, catechisms, psalters, prayer books, testaments, and bibles. There is also some evidence that secondary instruction was carried on intermittently in the various centers by the missionaries or by the schoolmasters in conjunction with their elementary work.

Throughout its work in the American colonies the S. P. G. met with various forms of opposition. The dissenters, \^\^'p^0^\^\*^0^ Quakers, and others were often openly hostile through fear of the foundation of an established national church

Its devotion and generosity,

and influence upon universal education.

Organization,

course, and

similar to that of England, and both sides displayed considerable sectarianism and bigotry. After 1750 the opposition to the society increased in bitterness and became more general, owing to the feeling that its agents were supporting the king against the colonists. Yet its patronage of schools was most philanthropic and important for American education in the eighteenth century. While it insisted upon the interpretation of Christianity adopted by the Church of England, it stood first and foremost for the extension of religion and education to the virgin soil of America. It carried on its labors with devoted interest and showed great generosity in the maintenance of schools, and the support of schools in the colonies by the S. P. G. must have exerted some influence toward universal education.

Charity Schools among the Pennsylvania Germans. - During the eighteenth century the efforts of the S. P. G. were supplemented by the formation of minor associations and the establishment of other charity schools in various colonies. Perhaps the most noteworthy instance was the organization in 1753 of 'A Society for Propagating the Knowledge of God among the Germans,' and the maintenance of schools among the sects of Pennsylvania. These schools were managed by a general colonial board of six trustees, who visited the schools annually and awarded prizes for English orations and attainments in civic and religious duties. The course of study included instruction in "both the English and German languages; likewise in writing, keeping of common accounts, singing of psalms, and the true principles of the holy Protestant religion." Twenty-five schools were planned, but probably there were never more than half<span id="ch20.xml#para.296.1.0.box.132.228.1247.38.q.70" class="gtxt_body"> that number. The schools lasted only about a decade, as disappearance</span>

of S P K *C*

the Germans soon came to feel that this English school- schools." ing threatened their language, nationality, and institu- tions.

The ' Sunday School' Movement in Great Britain. - A variety of charity school, quite different from those already mentioned, sprang up toward the close of the century under the name of 'Sunday Schools.' To overcome the prevailing ignorance, vice, and squalor in the manufacturing center of Gloucester, England, Robert Foundation, Raikes in 1780 set up a school in Sooty Alley for the instruction of children and adults in religion and the rudiments. Six months later he started a new school in Southgate street, and soon had other schools established. He paid his teachers a shilling each Sunday to train the children to read in the Bible, spell, and write. This charity education, meager as it was, was attacked by °PP°^sltl0n^' many of the upper classes, and was often viewed with suspicion by the recipients themselves. Yet the new movement had warm supporters among the nobility and \^\^^cy^' ^and^ such reformers as Wesley, and the schools soon spread to London, and then throughout England, Wales, Ireland, Scotland, and the Channel Islands. A Sunday School Society was founded in 1785, and within a decade distributed nearly one hundred thousand spellers, twenty-five thousand testaments, and over five thousand bibles, and trained approximately sixty-five thousand pupils in one thousand schools.

The 'Sunday School' Movement in the United States. - The Raikes system of Sunday instruction was also soon introduced in America. The first school was or- ,. , ,

Individual

ganized m 1786 by Bishop Asbury at the house of Thomas centers

Crenshaw in Hanover County, Virginia, and within a quarter of a century a number of schools arose in various ar\^gmanent cities. Before long, permanent associations were also started to promote Sunday instruction. 'The First Day or Sunday School Society' was organized at Philadelphia in 1791, and during the first two decades of the nineteenth century a number of similar societies for secular instruction on Sunday were founded in New York, Boston, Philadelphia, and elsewhere. In 1823 these associations were all absorbed into a new and broader organization, known ever since as the 'American Sunday School Union.' At the start it published suitable reading-books, and furnished primers, spellers, testaments, and hymn-books to needy Sunday schools at a reasonable rate.

Value of the Instruction in 'Sunday Schools.' - Both in Great Britain and the United States, however, the Sunday schools gradually tended to abandon their prepare\^'the1 secular instruction and become purely religious. At varsai^0^educa- *\^^e^* ^sanle^ *\^^rae^* \*i^e^ teachers came to serve without pay *^tion^-* and to instruct less efficiently. And the value of the

secular teaching was not large at the best, as the work was necessarily limited to a few hours once a week. Raikes and all others interested in these institutions recognized their inadequacy as a means of securing universal education, and regarded them merely as auxiliary to a more complete system of instruction. But while a makeshift and by no means a final solution for national education, they performed a notable service for the times, and helped point the way to universal education. The Schools of the Two Monitorial Societies. - While philanthropic education started largely in the eighteenth<span id="ch20.xml#para.298.1.0.box.143.247.1249.1065.q.60" class="gtxt_body"> century, some of the schools continued well into the nineteenth. This was especially the case with the 'monitorial' system, started at Southwark in 1798. This district of London was thronged with barefoot and unkempt children; and Lancaster, the founder of the school, Lancaster undertook to educate as many as he could. His schoolroom was soon filled with a hundred or more pupils. In order to teach them all, he used the older pupils as assistants. He taught the lesson first to these 'monitors,' and they in turn imparted it to the others, who were divided into equal groups. Each monitor cared for a single group. The work was very successful from the first, but Lancaster, attempting to introduce schools of this kind throughout England, fell so recklessly into debt that an association had to be founded in 1808 to continue the work on a practical basis. Within half a dozen years Lancaster withdrew from the organization, but the association, under the name of the 'British and Foreign'^3^ and Foreign Society,' continued to flourish and found ^Society^; new schools.</span>

So successful was the Lancasterian work that the Church of England, fearing its nonsectarian influence upon education, in 1811 organized 'The National Society for Promoting the Education of the Poor in the Principles of the Established Church.' This long-named association was to conduct monitorial schools under the management of Doctor Andrew Bell, who had experi- National' mented with the system in India before Lancaster opened ^Soaet^yhis school. Although they had formed no part of Bell's original methods, the Anglican catechism and prayer book were now taught dogmatically in the schools founded by the National Society. Bell proved an admirable

director, and a healthy rivalry sprang up between the societies. Value of the Monitorial System in England. - The

th\^two\^ys" pl^ans^ of the two organizations were similar, but differed

^tems^- somewhat in details. Both used monitors and taught

writing by means of a desk covered with sand, but the system of Lancaster was animated by broader motives and had many more devices for teaching. It also instituted company organization, drill, and precision, and developed a system of badges, offices, rewards, and punishments. Monitorial instruction, however, was not

original"^6^ "° original with either Lancaster or Bell. It had long been used by the Hindus and others, although the work of the two societies brought it into prominence. It over

and mechani- emphasized repetition and recitation mechanics, and consisted of a formal drill rather than a method of instruction. Yet the monitorial schools were productive of some

Afforded sub- achievements. Most of them afforded a fair education in

stitute for national educa- th~e~ elementary school subjects and added some industrial and vocational training. They also did much to awaken the conscience of the English nation to the need of general education for the poor. The British and Foreign and the National Societies afforded a substitute, though a poor one, for national education in the days before England was willing to pay for general education, and they became the avenues through which such appropriations as the government did make were distributed. In 1833 the grant of £20,000, constituting the first government aid to elementary education, was equally divided between the two societies (see p. 388), and this method of administration was continued as the annual grant was<span id="ch20.xml#para.300.1.0.box.144.248.1265.799.q.60" class="gtxt_body"> gradually increased, until the system of public education was established. Likewise, in 1839, £10,000 for normal instruction was voted to the societies, and was used by the British and Foreign for its Borough Road Train- Training coling College, and by the National for St. Mark's Training College. These were followed by several other training institutions, established by each society through government aid. In 1870, when the 'board,' or public elementary, schools were at length founded, the schools of the British and Foreign Society, with their nonsec- foreign^and^ tarian instruction, fused naturally with them; but the \^bed^S^ "but institutions of the National Society, though transferred \^m\^them\*" to school boards in a few cases, have generally come to *^xlves^*constitute by themselves a national system on a voluntary basis.</span>

Results of the Monitorial System in the United States. - In the United States the monitorial system was introduced into New York City in 1806. The' Society for the Establishment of a Free School,' after investigating the best methods in other cities and countries, decided to try the system of Lancaster (see p. 260). The method was likewise introduced into the charity schools of Phila- ., ,. .

, Adoption by

delphia (see p. 261). The monitorial system then spread New York and rapidly through New York, Pennsylvania, Massachusetts, Connecticut, and other States. It is almost impossible to trace the exact extent of this organization in the United States, but before long it seems to have affected nearly all cities of any size as far south as Augusta (Georgia), and west as far as Cincinnati. There are still traces of its influence throughout this region, - in Hartford, New Haven, Albany, Washington, and Baltimore, as well as in the places already mentioned (Figs. 27, 28,

Introduced into high schools and academies.

Increased school facilities

and 29). In 1818 Lancaster himself was invited to America, and assisted in the monitorial schools of New York, Brooklyn, and Philadelphia. A dozen years later the system began to be introduced generally into the high schools and academies. Through the efforts of Dr. John Griscom, who had been greatly pleased with the monitorial high school of Dr. Pillans in Edinburgh, a similar institution was established in New York City in 1825, and the plan was soon adopted by a number of high schools in New York and neighboring states. Likewise, the state systems of academies in Maryland and in Indiana, which became high schools after the Civil War, were organized on this basis. For two decades the monitorial remained the prevailing method in secondary education. Training schools for teachers on the Lancasterian basis also became common.

In fact, the monitorial system was destined to perform a great service for American education. At the time of its introduction, public and free schools were generally lacking, outside of New England, and the facilities that existed were meager and available during but a small portion of the year. In all parts of the country illiteracy was almost universal among children of the poor. This want of school opportunities was rendered more serious by the rapid growth of American cities. 'Free school societies,' like that in New York City, formed to relieve the situation, came to regard the system of Lancaster, because of its comparative inexpensiveness, as a godsend for their purpose. And when the people generally awoke to the crying need of public education, legislators also found monitorial schools the cheapest way out of the difficulty, and the provision made for these schools

Fig. 27. - A monitorial school, with three hundred pupils and but one teacher.

gradually opened the road to the ever increasing expenditures and taxation that had to come before satisfactory schools could be established. Moreover, the Lancasterian schools were not only economical, but most effective, when the educational conditions of the times are taken into consideration. Even in the cities, the oneroom and one-teacher school was the prevailing type, and grading was practically unknown. The whole organization and administration were shiftless and uneconomical, and a great improvement was brought organiMt£^\>^n^ed^ about by the carefully planned and detailed methods of ^and^ ^methods^Lancaster. The schools were made over through his definite mechanics of instruction, centralized management, well-trained teachers, improved apparatus, discipline, hygiene, and other features.

But while the monitorial methods met a great educational emergency in the United States, they were clearly mechanical, inelastic, and without psychological foundation. Naturally their sway could not last long, and as °hra^P^M?ua?enlarged material resources enabled the people to make jj~l~°"t^'^~in~\^^nti^" greater appropriations for education, the obvious de- proved. fects of the monitorial system became more fully appreciated and brought about its abandonment. Before the middle of the century its work in America was ended, and it gave way to the more psychological conceptions of Pestalozzi and to those afterward formulated by Froebel and Herbart.

The 'Infant Schools' in France. - Another form of philanthropic education that came to be very influential during the nineteenth century and has eventually been merged in several national systems is that of the so-called 'infant schools.' The first recorded instance of these

development in Paris:

part of national system.

institutions occurred late in the eighteenth century through the attempt of a young Lutheran pastor named OberHn^ing^ ^with^ Oberlin to give an informal training to the small children in all the villages of his rural charge in northeastern France. This type of training was copied in Paris as early as 1801, but did not amount to much until its revival through the influence of a similar development in England a quarter of a century later. It then rapidly expanded, and in 1833 was adopted as part of the French national system of education. In 1847 ^a^ normal school was founded to prepare directresses and inspectors for these institutions, and in 1881 they became known as 'maternal schools,' and the present type of curriculum was adopted. Besides reading and writing, these schools have always included informal exercises in the mother tongue, drawing, knowledge of common things, the elements of geography and natural history, manual and physical exercises, and singing.

The • Infant Schools' in England. - Quite independently, though over a generation later than Oberlin, Robert Owen opened his 'infant school' in 1816 at New Lanark, Scotland. He was a philanthropic cottonspinner, and wished to give the young children of his operatives a careful moral, physical, and intellectual training. From the age of three they were taught in this school for two or three years whatever was useful and within their understanding, and this instruction was combined with much singing, dancing, amusement, and out-of-door exercise. They were not "annoyed with books," but were taught about nature and common objects through maps, models, paintings, and familiar conversation, and their "curiosity was excited so as to

Owen at New Lanark;

ask questions concerning them." To afford this informal training, Owen secured a "poor simple-hearted weaver, named James Buchanan, who at first could scarcely read, write, or spell," but who, by following the instructions of Owen literally, made a great success of the system. But when Buchanan, with the consent of Buchanan's

"" ' school in

Owen, had been transferred to London, to start a sim- London, ilar school for a group of peers and other distinguished philanthropists, his lack of intelligence reduced the training to a mere mechanical imitation of the procedure he had learned at New Lanark. Unfortunately, this London school became the model for Samuel Wilderspin, who was destined to become the leading exponent of infant schools. The schools of Wilderspin, while ~became~ ~model~ retaining some of the principles and devices of Owen, for wilder

^0^ \* *\^* spin, - formal

were much more formal and mechanical. He thought and me- too highly of 'books, lessons, and apparatus,' and con- founded instruction with education. He overloaded' the child with verbal information, depending upon the memory rather than the understanding. Before the child was six, it was expected that he had been taught reading, the fundamental operations in arithmetic, the tables of money, weights, and measures, a knowledge of the qualities of common objects, the habits of dif- ferent animals, the elements of astronomy, botany, and zoology, and the chief facts of the New Testament. Even the games were stereotyped, and the religious teach- ing most formal.

Wilderspin's first school was opened at Spitalfields, ~Spreadof~ London, and soon attracted a horde of visitors. He schools; then began lecturing upon the subject throughout the United Kingdom, often demonstrating his methods with

classes of children he had taken along, and organized Sodety-^Sch001^ ^in^f^ant^ schools everywhere. In 1824 an 'Infant School Society' was founded and through it several hundred schools were established. A dozen years later an organization for training infant school teachers, known as Coi^m^niT^d^ 'The Home and Colonial School Society,' was founded Society; at London by Reverend Charles Mayo, D. D., and

others. This society undertook to graft Pestalozzianism upon the infant school stock. While the combination resulted in some improvement of the infant schools, and real object teaching and sense training were more emphasized than they had been, the spirit of Pestalozzi was largely lost, and there was too much imitation of the formal instruction of older children, and there was an evident attempt to cultivate infant prodigies. Through these agencies infant schools spread rapidly in Great Britain, and were adopted as a regular part of the Part of public public system, when it was established in 1870 (p. 388). And four years later a marked advance was made through merging in them some of the methods and games of the kindergarten.

'infant Schools' in the United States. - Schools open to all younger children also sprang up in the United States during the first quarter of the nineteenth century. For many years they were nowhere regarded as an essential part of the public school system, and were managed separately, but about the middle of the century they were generally united. In 1818 Boston made its ma^St^°schoois' \*\*^rst^ ^a^PP^ro^P^r^i^a^tion for "primary schools, to provide instruction for children between four and seven years of age." These schools were divided into four grades, beginning with the study of the alphabet and closing<span id="ch20.xml#para.308.1.0.box.122.232.1048.422.q.70" class="gtxt_body"> with reading in the New Testament. Besides reading, writing, and spelling, sewing and knitting were taught the girls. A formal course and the monitorial method were employed until about 1840, when the primary schools became largely inoculated with the informal procedure of Pestalozzi. The primary schools were for a long time under a separate committee, but in 1854 the management was fused in a general city board.</span>

New York started an 'Infant School Society' in 1827. This organization opened two 'infant schools' for poor children between three and six years of age. One of 'Primary de

partments' in

these schools was located in the basement of a Pres- New York, byterian Church and the other in that of a monitorial institution belonging to the Public School Society (see p. 261). The Pestalozzian methods used in these infant schools greatly commended themselves, and in 1830 the Public School Society added them as 'primary departments' in all their buildings, but under separate management. A committee was appointed in 1832 to examine the Society's schools and suggest improvements. Upon the recommendation of two of this committee, who had inspected education in Boston, primary schools were established in rented rooms in sufficient numbers to be within easy reach for the young children. The subject-matter and methods were likewise made less formal.

In 1827 three 'infant schools' were also founded in Philadelphia and other centers of Pennsylvania through infant schools'

-r. , <span style="font-variant:small-caps;">Tt </span><span style="font-variant:small-caps;">T, </span>, *r . ,* , , in Philadelphia

Roberts Vaux. By 1830 the number of infant schools in the state had risen to ten, with two to three thousand pupils. As the numbers would indicate, the schools were largely organized upon the Lancasterian plan.<span id="ch20.xml#para.309.1.0.box.73.228.1267.691.q.60" class="gtxt_body"> Two years later a model infant school was started in Philadelphia, and in 1834 six others were organized. By 1837 there were thirty primary schools in Philadelphia centera^her^ alone. Several other cities started infant schools early. Hartford began them in 1827, and Baltimore in 1829. These institutions were in most cases fostered by the leading men of the community, and the ultimate service performed for American education by this form of philanthropy was considerable. Among other improvements, the infant schools developed a better type of schoolroom, secured separate rooms for different classes, intSoughTnfant traduced better methods and equipment, encouraged a schools. movement toward playgrounds, and brought women</span>

into the city schools of the United States.

The Importance of Philanthropic Education. - Many other types of charity school arose during the eighteenth century both in Great Britain and America, but the chief movements have been described, and sufficient has been said to indicate the important part in education played by philanthropy. The moral, religious, Purpose, and economic condition of the lower classes had been

sadly neglected, and by means of endowment, subscription, or organized societies, a series of attempts was made to relieve and elevate the masses through education. As a result, charity schools of many varieties and more or less permanent in character arose in all parts of the British Isles, the United States, and even location, France. In many instances the pupils were furnished

course, with lodging, board, and clothes. The curriculum in

these institutions was, of course, mostly elementary. It generally included reading, spelling, writing, and arithmetic, while a moral and religious training was given<span id="ch20.xml#para.310.1.0.box.141.245.1242.637.q.60" class="gtxt_body"> through the Bible, catechism, prayer book, and psalms, and sometimes through attendance at church under supervision of the master. Frequently industrial or vocational subjects were taught, or the pupils apprenticed to a trade or to domestic service. The course was usually most formal both in matter and method, but occasionally in the later types drawing, geography, nature study, physical exercises, and games were added, and the more informal methods of Pestalozzi or Froebel ^and^ methods. were partially employed. Sometimes the training was especially intended for and adapted to children under the usual school age.</span>

These efforts to improve social conditions by means of philanthropic education encountered various sorts of Various sorts

^r^ ^r^ of opposition.

opposition. Often the upper classes held that the masses should be kept in their place, and feared that any education at all would make them discontented and cause an uprising. The poor themselves, in turn, were often suspicious of any schooling that tended to elevate them, and were unwilling to stamp themselves as paupers. Moreover, the sectarian color that sometimes appeared in the religious training not infrequently repelled people of other creeds or kept the schools from receiving their children.

However, this philanthropic education may, in general, be considered a fortunate movement, although its greatest service consisted in paving the way for better things. In contrast to the negative phase of 'naturalism,' it f~°~\*^v^\^~t~j^t^on~a~T^ay^ represented a positive factor in the educational activities ^and^ public ed

*^r^ ^r^ ~m~* ucation.

of the century. Instead of attempting to destroy existing society utterly, it sought rather to reform it, and when the work of destruction gave opportunity for new<span id="ch20.xml#para.311.1.0.box.283.244.1050.421.q.60" class="gtxt_body"> ideals, it suggested and even furnished a reconstruction along higher lines. Hence philanthropy in education exercised an important influence in the direction of universal, national, and public training for citizenship. It was in many of its forms merged in such a system in several countries, and in succeeding chapters references to the S. P. C K., S. P. G., Sunday, monitorial, and infant schools will naturally appear.</span>

**Supplementary Reading**

Graves, *In Modern Times* (Macmillan, 1913), chap. III; and *Great Educators* (Macmillan, 1912), chap. XII; Parker, *Modern Elementary Education* (Ginn, 1912), pp. 101-107. Allen, W. O. B. and McClure, E., have presented *The History of the S. P. C. K.* (Christian Knowledge Society, London, 1001), and Pascoe, C. F., *Two Hundred Years of the S. P. G.* (Christian Knowledge Society, London, 1898), while Kemp, W. W., gives a detailed history of *The Support of Schools in Colonial New York by the S. P. G.* (Columbia University, Teachers College Contributions, no. 56, 1913), and Weber, S. E., of *The Charity School Movement in Pennsylvania* (Doctoral dissertation, University of Pennsylvania). Harris, J., furnishes a good description of *Robert Raikes; the Man and His Work* (Dutton, New York, 1899); Salmon, D., of *Joseph Lancaster* (Longmans, Green, 1004); Meiklejohn, J. M. D., of *An Old Educational Reformer, Dr. Andrew Bell* (Bardeen, Syracuse); and Salmon, D., and Hindshaw, W., of *Infant Schools, Their History and Theory* (Longmans, Green, 1904).