# 23. Development of Public Education in the United States

**Outline**

-   During the second quarter of the nineteenth century a third period in the educational history of America, marked by further democratization and a great expansion of public education, appeared.
-   It began with an awakening generally known as 'the revival of common schools,' which was most noticeable in New England. Here, owing to the attacks made upon him by reactionaries, Horace Mann was the most conspicuous reformer; while Henry Barnard, through his *American Journal of Education,* enabled educators to look beyond the educational experience of America. But the influence of this awakening was also felt in every other section of the United States.
-   It was followed by a steady growth in universal education, state support and control, local supervision, and the organization of normal schools in New England and the Middle states.
-   In the Northwest, common school advocates overcame the opposition of settlers from states not committed to public education, and in the further expansion of the United States progress in common school sentiment has kept pace with the settlement of the country.
-   The South made considerable progress during the early years of the awakening, and while the Civil War crushed its educational facilities, the struggle for public education has since been won.

**The Third Period in American Education.** - Interest in the improved methods of Pestalozzi and other reformers that was manifesting itself everywhere in the United States during the second quarter of the nineteenth century seems to have been but one phase of a much larger movement. It was about this time that a third period in American education, which was marked by the development of democratic ideals and the extension of state systems of public schools, may be said to have begun. During the period of 'transition,' we found (chap. XXI), half a dozen of the states had started an organization of common schools, and in a dozen others permanent school funds had been established, an influential minority of leading citizens were constantly advocating universal education, and public interest in the matter was evidently increasing- But the consummation of a regular system was still much hindered by sectarian jealousies, by the conception of public schools as institutions for paupers and the consequent custom of allowing private schools to share in public funds, by the unwillingness of the wealthy to be taxed locally for the benefit of other people's children, and, in New England, by the division of the system into autonomous districts and the interference of petty politics. Hence, while much progress had been made since the early days of 'transplantation' of European ideals and institutions, there was still much need of the expansion and further democratization that now began to appear. Of the rapid development that took place during this final period of Americanization, much was accomplished before the middle of the nineteenth century, but educational progress continued through the final decade.

**Early Leaders in the Common School Revival.** - The educational awakening with which the beginning of this third period seems to be marked, has been generally stop center known as 'the common school revival.' It first became evident during the latter part of the decade between 1830 and 1840, and had its storm center in Massachusetts and Connecticut. While it greatly furthered the cause of public education everywhere, because of the decadence into which New England had fallen, the demand for an educational awakening was strongest there. In this revival the most conspicuous figure was probably Horace Mann, but there were several leaders in the field before him, many were contemporaneous, and the work was expanded and deepened by others of distinction long after he withdrew from the scene. For a score of years before Mann appeared, definite preparation for the movement had been in progress, and the labors of the individuals and associations engaged in these endeavors should be briefly noted. Many of the reformers seem to have* *recommended an improvement in methods through the creation of an institution for training teachers, thus anticipating one of the greatest achievements of Mann. Actual attempts at a private normal school were even made by the Reverend Samuel R. Hall at Concord, Vermont (1823), Andover, Massachusetts (1830), and Plymouth, New Hampshire (1837).

A number of educational journals, moreover, published articles on schoolbooks, the methods of Lancaster, Pestalozzi, Neef, and Fellenberg, the infant and Sunday schools, physical education, European school systems, and a variety of other timely topics and reforms. Among these progressive publications were the *American Journal of Education,* edited by William Russell from 1826-1830, and then continued from 1831 to 1839, as the *American Annals of Education* under the editorship of William C. Woodbridge, and the *Quarterly Register,* published 1828-1843 by the 'American Educational Society.' The latest European ideas were also reported from first-hand observation by a number who had gone abroad to investigate. The most influential of these reports was *A Year in Europe,* written in 1819 by Professor John Griscom (see p. 292), who was a lecturer before several New York associations, including the Public School Society. Almost as widely read were the reports of William C. Woodbridge in 1824, and of Professor Calvin E. Stowe of Lane Theological Seminary, Cincinnati, in 1836.

**Work of James G. Carter.** - All these movements indicate the educational ferment that was going on. But the predecessor of Mann, who accomplished most for the common schools, and influenced that reformer most directly, was James G. Carter (1795-1849). Carter (Fig. 37) was a practical teacher and wrote continually on the need of a training institution to improve instruction in the public schools. These appeals proved very successful, and earned him the title of 'father of the normal schools.' After being elected to the legislature, he accomplished much by his zeal and skill in parliamentary tactics. In 1826 he secured an act by which each town as a whole was required to choose a regular committee, instead of the ministers and selectmen, to supervise the schools, choose text-books, and examine, certify, and employ the teachers. But the effect of this enactment was largely lost the following year by allowing the districts, as a compromise, to choose a committeeman, who should appoint the teachers. In 1826 he placed secondary education, then largely conducted by academies, more under public control through a law requiring each town of five hundred families to support a free English high school (Fig. 41), and every one of four thousand inhabitants to maintain a classical high school. Next, in 1834, Carter succeeded in getting a state school fund established from the proceeds of the sale of lands in the province of Maine and the state's claims against the federal government for military services. But his most fruitful victory was won in 1837, when he procured the passage of the bill for a State Board of Education, after it had been once defeated, by inducing the house to discuss it in 'committee of the whole.'

**Horace Mann as Secretary of the Massachusetts Board.** - By reason of his merits as an educator, his persistent efforts in behalf of educational reform, and his advocacy of the bill, it was assumed by most people that Carter would be chosen secretary of the new board. To their surprise, a lawyer named Horace Mann (17961859), at that time president of the senate, was selected for the post, but the choice is now known to have been most fortunate. By both heredity and training Mann (Fig. 38) was suffused with an interest in humanity and all phases of philanthropy and education. He possessed a happy combination of lofty ideals, intelligence, courage, enthusiasm, and legislative experience, which equipped him admirably for leadership in educational reform. The law proposed for the new Board of Education numerous duties in the way of collecting and spreading information concerning the common schools and of making suggestions for the improvement and extension of public education, but it provided no real powers, and the permanence and influence of the board depended almost wholly upon the intelligence and character of the new Secretary.

During his twelve years in the office, Mann subserved the interests of the state most faithfully. To awaken the people, he made an educational campaign through every portion of the state each year, but an even more effective means of disseminating his reforms was found in his series of *Annual Reports.* These documents were by law to give information concerning existing conditions and the progress made in the efficiency of public education each year, and they deal with practically every educational topic of importance at the time. Sometimes they seem commonplace, but it must be remembered that they were not so then, and that the work of Mann did much to render them familiar. They vitally affected school conditions everywhere in New England, and were read with great interest in all parts of the United States, and even in Europe. He also published semimonthly the *Massachusetts Common School Journal,* to spread information concerning school improvement, school law, and the proceedings of the State Board. But it consisted of only sixteen pages, and was not as valuable as some of the educational journals that had preceded it (see pp. 704 f.). Another medium in the improvement of educational facilities was Mann's general establishment of school libraries by state subsidy throughout Massachusetts. But probably the most permanent means of propagating his reforms came through securing the foundation of the first public normal schools in this country. Massachusetts was in 1838 induced to establish three schools, so located that all parts of the state might be equally served. The course in each school consisted in a review of the common branches from the teaching point of view, work in educational theory, and training in a practice school under supervision, and, while not largely attended, these institutions were a great success from the start.

The arduous and unremitting labors of Mann in instituting and promoting the various means of school reform made the greatest inroad upon his strength and financial resources. Moreover, he was for years violently assailed by reactionaries of all types. His controversy with the Boston schoolmasters was especially sharp. Mann's *Seventh Annual Report* (1843) gave an account of his visit to foreign schools, especially those of Germany, and praised with great warmth the 'Pestalozzian' (see p. 289) instruction without text-books, the enthusiastic teachers, the absence of artificial rivalry, and the mild discipline in the Prussian system. The report did not stigmatize the conservatism of the Boston schools or bring them into comparison with those of Berlin, but the cap fitted. The pedagogues were disquieted, and proceeded to answer savagely. But when the smoke of battle had cleared away, it was seen that the leaders of the old order had been completely routed. A more insidious attack was that led by the ultra-orthodox. The old schools of the Puritans, with their dogmatic religious teaching, had been steadily fading for more than a century before the new board had been inaugurated, but many narrow people were inclined to charge this disappearance to the reformer, whose liberal attitude in religion was well known. The assaults, however, were vigorously and successfully repelled by the Secretary. And while these controversies wore Mann out and probably led ultimately to his resignation, they had much to do with making his reputation as a great educator. They have even caused us at times to forget that he was but a striking figure in a general movement. Men like Carter were in the field long before him, and his co-worker, Barnard, served the cause of education for nearly half a century after Mann withdrew.

**The Educational Suggestions and Achievements of Mann.** - In surveying his educational positions, we find Mann's foremost proposition was that education should be universal and free. Girls should be trained as well as boys, and the poor should have the same opportunities as the rich. Public schools should furnish education of such a quality that the wealthy would not regard private institutions as superior. This universal education, however, should have as its chief aim moral character and social efficiency, and not mere erudition, culture, and accomplishments. And morality, he felt, would not be accomplished by inculcating sectarian doctrines. Mann was, however, mainly a practical, rather than a theoretical reformer, and to the material side of education he gave serious attention. He declared that school buildings should be well constructed and sanitary. This matter seemed to him so important that he wrote a special report upon the subject during his first year in office. He carefully discussed the proper plans for rooms, ventilation, lighting, seating, and other schoolhouse features, and insisted that the inadequate and squalid conditions which existed should be improved. As to methods, he maintained that instruction should methods, be based upon scientific principles, and not upon authority and tradition. He advocated the word method of reading, in the place of the uneconomical, artificial, and ineffective method of the alphabet, and the Pestalozzian object methods and oral instruction were introduced by him. He held that the work should be guided by able teachers, who had been trained in a normal school, and should be imparted in a spirit of mildness and kindness through an understanding of child nature. In the matter of the studies to be pursued, Mann was inclined to be exceedingly practical. In discussing educational values, he failed to see any reason "why algebra, a branch which not one man in a thousand ever has occasion to use in the business of life, should be studied by more than twenty-three hundred pupils, and bookkeeping, which every man, even the day laborer, should understand, should be attended to by only a little more than half that number." Similarly, he holds that of all subjects, save the rudiments, physiology should receive the most attention.

In order that these various reforms might be realized, Mann insisted frequently that the state should spare no labor or expense. But in a republic he felt that "education can never be attained without the consent of the whole people." It was a general elevation of ideals, effort, and expenditure that he sought, and for which he began his crusade. And the general progress that resulted in this period covers a wide range. During his secretaryship the appropriations made for public education in Massachusetts were more than doubled, and the proportion of expenditure for private schools in the state was, in consequence, reduced from seventy-five to thirtysix per cent of the total cost of education. The salaries of masters in the public schools were raised sixty-two per cent, and, although the number of women teachers had grown fifty-four per cent, the average of their salaries also increased fifty-one per cent. The school attendance enormously expanded, and a full month was added to the average school year. When Mann's administration began, but fourteen out of forty-three towns had complied with the high school law of 1826, but, by the middle of the century, fifty new high schools had been established. The efficiency of supervision was largely increased by making the compensation of the town visiting committees, established through Carter, compulsory by law. The first state normal schools at last appeared, and teachers' institutes, county associations, and public school libraries were given general popularity. Quite as marked was the improvement effected in the range and serviceability of the school studies, in text-books, methods of teaching, and discipline. Thus under the leadership of Horace Mann a practically unorganized set of schools, with diverse aims and methods, was welded into a well-ordered system with high ideals, and the people of Massachusetts renewed their faith in the common schools.

**Henry Barnard's Part in the Educational Awakening.** - But there was another important contribution to the awakening made by a New Englander, which was of a rather different nature from that connected with the influence of Horace Mann. Before that reconstruction of the common schools, which was responsible for the best elements in our national civilization, could be at all complete, it was necessary that America should have a better comprehension of what was being done in education elsewhere. The United States had for two centuries been undergoing a gradual transition from the institutional types transplanted from England and the Continent in colonial days, and was coming more and more to blossom out into democracy and the people's schools, but for a long time there was little knowledge of what was being done by the other countries that had by this time adopted similar ideals. Conceptions of universal and democratic education and of improved organization and methods had been slowly developing in Prussia and other German states, and had extended to France and elsewhere. A literature connected with the advanced theories of such reformers as Rousseau, the philanthropinists, Pestalozzi, and Fellenberg had likewise grown up in Europe. It was very important that America, now keenly alive to the need of educational reorganization, should become acquainted with all this, that the New World might secure the advantages of comparison, corroboration, and expansion of view from the work of older civilized peoples. Some reports on foreign education and translations of European treatises had already appeared (pp. 304 f.), but the time was now ripe for a more extensive and systematic exposition of European education and its application to popular education in America, and for a really capable scholar to bring these world views within the grasp of all classes of teachers and educational authorities. This literary representative of the awakening appeared at length in Henry Barnard (1811-1900), who is fully worthy of a place in the educational pantheon of America. Barnard (Fig. 39) made a brilliant record at Yale for general scholarship, and a position as assistant librarian during his last two years in college did much to afford him a wide grasp of bibliography. After graduation, he obtained a valuable experience in teaching, and, by travelling extensively in America and Europe, formed a broad acquaintance with educational institutions, libraries, galleries, and social conditions in all the leading states and nations.

**Barnard as Secretary of the Connecticut State Board.** - Two years after Barnard's return to Connecticut, he began his part in the educational awakening as Secretary of the new State Board of Commissioners of Common Schools, and undertook to do a work similar to that of Mann in Massachusetts. Throughout the eighteenth century Connecticut schools had been among the most efficient in the country, but since the income from the Western Reserve lands had begun in 1798, and especially since this had been increased by the United States deposit fund in 1836, public education had steadily declined. A state tax was still maintained, but all local effort was paralyzed through lack of exercise. Another factor in producing this decline was connected with the transferal of the management of the common schools from the town to the 'school society,' which was a species of district, almost identical with the parish of each Congregational church. The results of this ruinous policy had been revealed in an investigation made by the legislature, which showed that not one-half of the children of school age were attending the common schools, and that the teachers were poorly trained and supervision was neglected. Barnard at once began to urge many reforms, and in his reports and the *Connecticut Common School School journal Journal* made suggestions for a complete plan of public education. He also began the publication of his rich collection of material bearing upon popular training at tionai material. home and abroad. But he was more a scholar and literary man than an educational statesman like Mann. He succeeded in getting the legislature to pass several reforms and a general revision and codification of the school laws, and in arousing several towns to amend their educational plans, although the crucial difficulty of the 'school societies' could not be touched, and within four years the conservatives succeeded in legislating him out of office and in undoing all his reforms.

**Commissioner of Common Schools in Rhode Island.** - This gave Barnard an opportunity to pursue his favorite investigations, and for about a year and a half he was engaged in collecting material for a history of education in the United States. Then he was persuaded by the governor of Rhode Island to become the first Commissioner of Common Schools for that state. While he found in Rhode Island a better educational sentiment and less opposition than in Connecticut, the actual condition of the decentralized and individualistic schools was far worse (see p. 269). But, through his assemblies of Radical re- teachers and parents and his educational treatises, he soon began to convince the people of the unwisdom of district organization, untrained teachers, short terms, irregular attendance, poor buildings and ventilation, and meager equipment. He also continued to publish his collection of educational material through the foundation of the *Rhode Island School Journal.* As a result of his efforts, when failing health compelled him to resign in 1849, the state no longer regarded wilfulness and personal opinion as praiseworthy independence, and he could honestly claim that Rhode Island had at the time one of the best school systems in the United States.

**State Superintendent of Schools in Connecticut.** - But the *clientele* that Barnard had built up in Connecticut continued his reforms and constructive work after his departure, and improved upon them. In 1851, they even succeeded in having him recalled virtually to his old duties. He was designated as State Superintendent of Common Schools, as well as Principal of the State Normal School, which had been established through the efforts of his adherents. The state had now learned its error in mingling politics with education, and Barnard was able to carry out his reforms unmolested. Through the normal school he sent out a great body of trained teachers. He revised the school code, checked the power of the 'school societies,' consolidated and simplified the organization and administration of public education, made a more equitable distribution of the school fund, and encouraged local taxation. But his most distinctive work, as might be expected, was on the literary side. He prepared a valuable series of documents upon foreign education, normal schools, methods of teaching, school architecture, and other topics, and a long report upon *The History of Legislation in Connecticut Respecting Common Schools up to 1838.*

***Barnard's American Journal of Education.*** - It was, too, during the last days of his Connecticut superintendency that Henry Barnard suggested the establishment of a national journal of education. He first broached the matter to the 'American Association for the Advancement of Education' at its meeting in Washington, December, 1854. But the association soon found itself unable to pursue this enterprise for lack of financial support, and in May of the next year Barnard began the publication of the *American Journal of Education* at his own expense. It was at first planned to run the journal for five years only, but, although the work was somewhat interrupted upon occasions by other duties, it continued for more than a generation, until at length thirty-one large octavo volumes, averaging about eight anr|efiity-twoS hundred pages each, had been issued. In addition, fifty-two special treatises reprinted from articles in the journal brought the material together in a connected way. Besides giving nearly all his time to editing this *magnum opus,* Barnard sank his entire fortune of \$50,000 in its publication. This great treasury of material includes every phase of the history of education from the earliest times down into the latter half of the nineteenth century. It furnishes accounts of all contemporaneous systems in Europe and America, descriptions of institutions for the professional training of teachers, and essays upon courses of study for colleges and technical schools, the education of defectives and delinquents, physical education, school architecture, great educators, and a large variety of other themes. While it is always most reliable in its treatises upon foreign education, of even greater value is its practical grasp of educational life in America from the beginning. It contains the greatest collection of interesting monographs upon the development of ideals and organization in the various states, and gives the most complete description in literature of the educational life of a nation.

**First United States Commissioner of Education.** - In 1867 Barnard was appointed the first United States Commissioner of Education. This office he had been constantly trying to have established ever since he had found, as Secretary of the Connecticut Board, how absolutely lacking the federal government was in school statistics and documents. He hoped that, through the agency of the government, facilities might be secured to collect and publish trustworthy educational statistics, and to issue a library of independent treatises. The bureau was not created for many years, and then through the immediate initiative of another, but when Barnard was called to the commissionership, he organized the office practically upon the lines he had previously suggested. He suspended his *Journal* and used the product of his investigations in the annual reports of the office. He started that searching inquiry into the administration, management, and instruction of institutions of every grade, and into all educational societies, school funds, legislation, architecture, documents, and benefactions that has since been maintained by the Bureau of Education. However, within three years a change in politics brought a new incumbent into the commissionership, and Barnard gave his literary efforts once more to his beloved *Journal.*

**Value of Barnard's Educational Collections.** - Hence, Barnard's real life work may be considered the collection of a great educational compendium. By temperament, native ability, and habit, he proved himself well fitted to be the leading representative of the literary side of the awakening. Through his work American education awakening, was, in its period of greatest development, granted the opportunity of looking beyond the partial and local results of the first half century of national life. It was enabled to modify and adapt to its own uses the educational theories, practices, and organizations of the leading civilized peoples, and to bring together for a comparative view sections and states that were widely separated. *Barnard's American Journal of Education* was not intended to be a universal encyclopaedia of education, but often includes a condensation of important works or a presentation of highly scientific methods and profound philosophic systems in popular form. It was not possible, either, to classify and work out a connected and complete historical account, when there were no reliable records or collections of materials in existence. It was necessary that some one should first gather the information from newspapers, pamphlets, memorials, monographs, and plans, and publish it as it was found. In this way he accomplished a more valuable work than if he had published a systematic history of education in the United States.

**Educational Development in New England since the Revival.** - This great storehouse of information published by Barnard and the virile efforts of Mann and other practical leaders were but prominent evidences of The 'revival' the progress that was at the time sweeping over the but ftsresuits entire country. The educational awakening of 183 5-1860 strikinghiNew was general and proved one of the most fruitful in history. England. jts influence was felt in every state, and it led to the third period of American education, which has been characterized by the expansion of public schools and state educational systems. During this period new ideals of democracy have come to be felt in American education, and a rapid advance has taken place in the evolution of that unique product, the American public school. In describing this development, we may turn first to New England.

In Massachusetts Horace Mann has been followed in the central administration by a succession of seven scholarly and experienced educators, who believed as firmly as he that all stages of education below the college should be open at public expense without let or hindrance to the richest and poorest child alike. Since the revival the state has seen a steady growth of sentiment for universal education and improved schooling, and never again has such an upheaval of the educational strata been necessary. The income of the state school fund and additional appropriations have been steadily increased, their apportionment among the towns has been rendered more equitable from time to time, and an effort has constantly been made to distribute them in such a way as to encourage local effort and cooperation. The school term has been lengthened to ten months and the average attendance of pupils to seven years. The improvements in school buildings, sanitation, and equipment have steadily advanced. The district system died hard, and not until 1882 was it altogether forced out of existence.

Most of the academies, too, which proved such a hindrance to the development of public secondary education, gradually died or were merged in the public system as high schools. By means of state aid, it has been possible since 1903 for the smallest towns to afford a high school training for their children at public expense. Supervision has also become universal during the past quarter century. Springfield first introduced a superintendent of schools in 1841, Gloucester in 1850, Boston in 1851, and the other cities much later, but since 1888, through increasing state aid and the combination of smaller towns into a district superintendency, expert supervision has become possible everywhere, and during the last decade it has been compulsory. The normal schools, which have now increased to ten, have brought about a striking improvement in teaching. It is practically impossible at present for an untrained teacher to secure a position in the elementary schools of Massachusetts, and, through a system of examinations and investigations, teachers of exceptional ability have, since 1896, been granted an extra weekly allowance by the state. Since the middle of the century, the state board has been permitted to appoint a number of agents, to assist in inspecting and improving the schools, especially in the smaller towns and rural districts.



The course of development since the awakening has been very similar in the other New England states. The successors of Barnard in the central administration both in Rhode Island and Connecticut have been skilled and earnest educators, and, while their reports lacked his literary touch, they were of rather more practical character. Until 1856, Connecticut made no attempt to return from the parish to the town organization. Even then, as well as later, legislation on the subject was 'permissive,' and not until the twentieth century was the 'school society,' or district system, given up in half of the towns. In Rhode Island, even after Barnard's reforms, almost one-third of the districts did not own their school buildings, owing to the survival of the method in use when the schools were private, but this condition has gradually been remedied. Likewise, the number of towns levying sufficient local taxes to secure a share in the state apportionment rapidly grew, and the state appropriation itself doubled and quadrupled within a generation. In Vermont, New Hampshire, and Maine, owing to insufficient wealth, infertility of soil, and sparseness of population, effective public education has been reached only by slow and cautious steps. But even these states have gradually centralized their educational administration through the abolition of the district system and the creation at various times of a state superintendent, a state commissioner, or a state board and secretary. This reorganization has been followed by increased state school funds and appropriations, more systematic statistics and reports from the schools, and great advances in universalizing and improving all stages of public education.

**Influence of the Awakening upon the Middle States.** - Although this awakened sentiment for education and progress in the common school has been most patent and spectacular in New England, it has not been peculiar to that part of the country. Nearly all of the other states seem to have felt the influence of the awakening. In close conjunction with the revival in New England, states, the movement appeared in New York, especially the western part, and was more or less evident in Pennsylvania, New Jersey, and Delaware. But because of its cosmopolitanism and the need of fusing so many different political, religious, and industrial traditions, the older parts of New York, where the school system had until the awakening been rather in advance of other states, did not progress as rapidly in the development of public education as Massachusetts and Connecticut. It had, however, by the time of the Civil War, succeeded in working over its heterogeneous people into a unified civilization and in causing their children to be educated together for a common citizenship.

The most distinct advances during this period of final organization have been in the establishment of state normal schools, instead of subsidizing academies to train teachers, in the administration and supervision of the system, and in the methods of state support of education. The first state normal school was opened at Albany in 1844, and this pioneer institution has eventually been followed by ten others. In 1854 the state superintendency had once more been separated from the secretaryship of state, with which it had been combined for thirty-five years (p. 259). In 1856 local supervision was established through the appointment of school commissioners for the cities and villages. In the same year, a three-quarters of a mill tax was placed upon the property valuation of the state, and during the next dozen years many improvements were made in the disbursing and accounting of public funds. At length, in 1867, the long fight that had been made for entirely free education was successful. Until then nearly fifty thousand children had been deprived of all education, because their parents were too proud to secure payment of their tuition fees by confessing themselves paupers. It was during this era of progress, too, that New York City was, in 1842, allowed to place the direction of its schools in the hands of a board of education, elected by the people, instead of giving over the city's share of the state funds to a quasi-public society, controlled by a close corporation. For eleven years, however, the Public School Society refused to give up its work, but by 1853 it decided to disband and merge its buildings and funds with those of the city school system (see p. 261).

Pennsylvania was slower than New York in showing the effects of the educational awakening, but the leaven was at work. While a number of progressive governors and other statesmen continually recommended the development of public education, and the 'Pennsylvania Society for the Promotion of Common Schools' had been organized, the towering leader in this movement was Thomas H. Burrowes. As secretary of state and *ex officio* superintendent of schools (1836-1838), as a public speaker and educational journalist (1838-1860), and as state superintendent (1860-1862), he constantly urged a complete system of public education, the establishment of normal schools, a separate state department of education, and the organization of state and county supervision. In 1849 the 'permissive' feature of the law of 1834 was abolished, and the two hundred districts that had thus far refused to establish public schools were forced to do so under the new provisions. In 1854 a revised school law was passed, which, after twenty years, now made the state system of education complete. It established in the secretary of state's office a deputy superintendent of schools, who had virtually a separate department, and provided for county superintendents. Three years later the state educational department became absolutely independent under the care of a superintendent, and provision was made for a system of normal schools. These institutions were to be established at first by private enterprise and without state subsidy. By 1877 there were ten in operation, largely maintained by the state. Three others have since been added, and the state has begun to take over into its own hands the entire support and control of them all.

Educational progress in New Jersey also took some time to get under way, but when the reforms once started, they continued until an excellent system of common schools had been inaugurated. In 1838 the limitation of state funds to the education of the poor was removed, and the apportionment of the income from them was thereafter applied only to public schools. Since 1848, when a state superintendency was established, the development has been more rapid. County supervision has been introduced, state normal schools have been established at Trenton and Upper Montclair, and appropriations have been greatly increased. In 1911 a state commissioner of education with an efficient corps of deputies was provided. Delaware, on the other hand, failed to live up to the possibilities under her early 'permissive' laws. Even the organization of 'the friends of common school education' showed itself very conservative, and would not advocate the creation of a state superintendency or the establishment of state normal schools. In fact, Delaware did not organize a complete state system until after the war. Even then, while a state board and state superintendency were established in 1875, there were no county superintendents, and when county supervision was introduced in 1888, the state superintendency was abolished. It was not reestablished until 1912, but since then the state system has made evident progress.

**Public Education in the West.** - The budding of a common school system, which had just begun to appear in the new commonwealths of the Northwest before 1840, rapidly unfolded into full blossom during this educational springtime. Through this awakening the common school advocates in Ohio, Indiana, and Illinois were greatly aided in their struggle to overcome the opposition of settlers from the states not committed to public education (see p. 272), and they were favored to some extent by accessions of emigrants from the home of the public school movement. During the decade just preceding the middle of the century, there was a decided elevation of public sentiment going on. Under the leadership of Samuel Lewis and Samuel Galloway in Ohio, Caleb Mills in Indiana, and Ninian W. Edwards in Illinois, the friends of public education had marshalled themselves for battle. Reports and memorials were constantly presented to the legislatures of these states, and public addresses in behalf of common schools were frequent in most large communities. A group of devoted schoolmen appeared, who were as successful in lobbying for good legislation as they were with institutes and public lectures. While reactions occasionally happened, like that in Ohio between 1840 and 1845, when the state superintendency was temporarily abolished, public education gradually came to be regarded as something more than merely free education for the poor, and public school funds were no longer granted as a subsidy to private institutions. After a quarter century of 'permissive' laws, local taxation and free common schools were fully realized in all three states early in the fifties. The contest, of course, was not ended, as reactionary elements, with selfish, local, and sectarian interests, still remained, but their contentions have never again been more than partially successful. New features of the common schools, such as efficient teachers for the rural districts, county supervision, state normal training, and free higher education in state universities, have gradually rendered the state systems more consistent and complete.

In Michigan, on the other hand, where there was not such a mixture of population, and a complete sympathy with the common school idea appeared, there was almost unhampered progress from the beginning of statehood. Under the first constitution (1837), there was provision made for a permanent school fund and for a local tax in every district, although the schools were partly maintained until 1869 by 'rate bills' collected from the pupils. In accordance with the grant of two townships of land by Congress in 1826 for a university, the first legislature of the new state established the University of Michigan (Fig. 42), and its doors were open to students in 1841. It soon became the most prominent of the state universities. There was also provided a system of 'branches' of the university, whereby a liberal grant was made for an academy in any county that would furnish suitable buildings and a sum equal to the appropriation from the state. As this proved a dissipation of the university funds, it was gradually stopped, and between 1852 and 1860 'union' and high schools were rapidly developed to supply the means of fitting for the university. In 1850 a state normal school was founded, and four ethers have since been added.

In all the other territory acquired or purchased by the United States in its westward expansion, the educational history has been very similar to that in the first states of the Northwest. Progress in common school sentiment has been made *pari passu* with the settlement of the country. Each state, upon admission, has received its sixteenth section of school land and two townships for a university, and in the states admitted since 1848 the endowment of schools has been increased to two sections, while Texas, which had been an independent republic (1836-1845), stipulated before becoming a state that it should retain sole possession of its public lands, and has set aside for education nearly two and one-half millions of acres. Hence in the first constitution of each state, permanent school and university funds, together with a regular organization of the schools of the state, have generally been provided. In few cases have sectarian interests been able to delay or injure the growth of common schools in any of the later commonwealths, and the interpretation of public education as schools for the children of paupers has never seriously influenced the West.

**Organization of State Systems in the South.** - Thus through the awakening of common schools that occurred throughout the union from 1835 to i860 was the oldtime country and city district school of the North gradually lifted up to the present system of graded free elementary, secondary, and normal schools, together with city and state universities. But these results were not at first as fully realized in the South, because of the approach and precipitation of the dreadful internecine conflict that weighed down and finally prostrated the resources of that section. However, except for this impending calamity, the conditions in the South were not essentially different from those in any other section. During the earlier years of the awakening, and in some states up to the very verge of the Civil War, great progress in public education was noticeable. The attendance in the common schools, established in several states by 'permissive' legislation, had been rapidly growing for a score of years, and there was an increasing body of prominent men desirous of enlarging popular education. During the early forties there were many efforts and suggestions for a system of public schools, and several conventions were held in the interest of such institutions. North Carolina actually established a state system in 1839. Tennessee (1838-1843) and Kentucky (1838) made less enduring efforts toward a similar organization, and as late as 1858 Georgia took a distinct step forward in this direction. Moreover, even in their secession conventions some states, like Georgia, adopted resolutions or constitutional amendments looking to the education of the people, and North Carolina in 1863, with the union army actually at its doors, undertook to grade the schools and provide for the training of teachers. But, in general, as the impending conflict drew near, attention to educational progress was forced to give way to the preservation of state and home, and after the war, which crushed and ravaged nearly every portion of the South, educational facilities had for the most part been totally wrecked.

Nevertheless, in the end the war served as a stimulus to common schools. It brought about a complete overturn of the old social and industrial order, and the South realized more fully than ever that it could arise from its desperate material and educational plight only through the institution of universal education. As early as 1865, school systems were organized in the border states, - Maryland, Kentucky, Missouri, and West Virginia, and even during the harsh and unhappy days of 'reconstruction' (1867-1876), efforts were made in other states to build up systems of free public education. The organization of education became more thorough and mandatory than before the war. All children, white and colored, were to attend school between six and twentyone, and the term was to last from four to six months each year. Property and poll taxation were established for the support of the schools. A state superintendent and state board of education, county commissioners and a county board, and trustees in each district, were provided for. Text-book commissions were often established, and free books were granted to poor children. The foundation for a real system was thus laid.

This was a tremendous undertaking, and shows the greatest courage and executive ability upon the part of the South. Property had been diminished in valuation to the extent of nearly two billion dollars, and there were two million children to be educated. Moreover, under the reconstruction regime, the tax on property was often not collected, and the appropriations for education remained on paper. Indifference and inexperience were aggravated by the fear that 'mixed' schools would be forced upon the white population by a reconstruction legislature or a Congress with millennial zeal in behalf of universal brotherhood. These obstacles, together with misdirected effort upon the part of Northern missionaries, and other serious interferences, for fully a decade constituted an enormous stumbling-block. Several factors, however, aided and encouraged the South in its efforts. Of these the most important was the foundation in 1867 of the Peabody Educational Fund of cationai Fund \$2,000,000, well characterized as "a gift to the suffering South for the good of the Union." This fund was placed in the management of the wisest and most sympathetic agents, who appealed to the higher sentiment of the communities and the states, and granted the assistance necessary to stimulate local effort in education. When the fund proved insufficient for the great task, the trustees pleaded with Congress for an additional subsidy, and made the whole country aware of the crying needs of education in the South. Through these appeals, more than ten million dollars from various sources have since been granted to the different grades of public education.

Despite the tremendous rally during the seventies, struggle won however, the struggle for public education in the South was not won for twenty years, but complete systems of common schools have now at length been generally established. With the cessation of the reconstruction influence and the subsidence of the dread of mixed schools, attendance and appropriations have greatly increased, schools for the education of colored children have been furnished, and provision has been made for training and stimulating teachers of both races. Separate state institutions for higher education, cultural and vocational, have been established to furnish a broad education for both whites and negroes. Since 1890 there has been an ever increasing interest in improving the public school in all respects, and the expenditures and facilities for education have been constantly increasing.

**Development of the American System of Education.** - With its final development in the South during the last decade of the nineteenth century, the distinctly American public school system may be said to have been fully elaborated. The educational ideals and institutions imported from Europe in the colonial period have gradually been modified and adapted to the needs of America. Schools have become public and free in the modern sense. The control of education has passed from private parties and even quasi-public societies to the state. The schools have likewise come to be supported by the state, and are open to all children alike without the imposition of any financial obligation. In secondary education, and state unithe academies, which supplanted the 'grammar' schools, ushed. first became 'free academies' and made no charge for tuition from local patrons, though remaining close corporations, and then were in time replaced by the true American secondary institution, - the high school (Fig. 41). Colleges became largely non-sectarian, even when not nominally so, and state universities were organized in all except a few of the oldest commonwealths (Fig. 42). Thus has the idea of common schools and the right to use the public wealth to educate the entire body of children into sound American citizenship been made complete. Although the system is still capable of much improvement, it is expressive of American genius and development. It is simply the American idea of government and society applied to education. It is the educational will of the people expressed through the majority, and the resultant of the highest thinking and aspirations of a great nation made up of the most powerful and progressive elements from all civilized peoples.

**Supplementary Reading**

Graves, *In Modern Times* (Macmillan, 1913), chaps. VI and VIII, and *Great Educators* (Macmillan, 1912), chap. XIII; Parker, *Modern Elementary Education* (Ginn, 1912), chap. XII. For the details of the life and work of Mann in brief form, read Hinsdale, B. A., *Horace Mann and the Common School Revival* (Scribner, 1899), or the readable little work on *Horace Mann the Educator* (New England Publishing Co., 1896) by Winship, A. E. Monroe, W. S., has briefly recounted *The Educational Labors of Henry Barnard* (Bardeen, Syracuse, 1893), and a longer account of *Henry Barnard* is that of Mayo, A. D., in *Report of U. S. Commissioner of Education,* 1896-1897, vol. I, chap. XVI. For the development of public education in the various parts of the country during this third period, see Martin, G. H., *Evolution of the Massachusetts Public School System* (Appleton, 1894), lects. IV-VI; Steiner, B. C, *History of Education in Connecticut (U. S. Bureau of Education, Circular of Information,* No. 2, 1893), chaps. III-V; Stockwell, T. B., *History of Public Education in Rhode Island* (Providence Press Co., Providence, 1876), chaps. VI-X; Randall, S. S., *History of the Common School System of the State of New York* (Ivison, Blakeman, Taylor, New York, 1871), third and fourth periods; Wickersham, J. P., *History of Education in Pennsylvania* (Lancaster, Pennsylvania, 1886), chaps. XVII-XVIII; Mayo, A. D., *The Development of the Common Schools in the Western States (Report of the U. S. Commissioner of Education,* 1898-99, vol. I, pp. 357-450); Boone, R. G., *History of Education in Indiana* (Appleton, 1892), chaps. IV and VIII-XXXIII; Smith, W. L., *Historical Sketch of Education in Michigan* (Lansing, 1881), pp. 17-38, 49-57, and 78-109; Knight, E. W., *The Influence of Reconstruction on Education in the South* (Columbia University, *Teachers College Contributions,* No. 60,1913) and *The Peabody Fund and Its Early Operation in North Carolina (South Atlantic Quarterly,* vol. xiv. no. 2). Mayo, A. D., *Education in the Several Status, Education oj the Colored Race,* and *The Slater Fund (Report of the U. S. Commissioner of Education* 1894-95, XXX, XXXI, and XXXII).

Fig. 42. - The University of Michigan in 1855. (The oldest picture of the first prominent state university; established by the legislature in 1837, and opened in 1841.)