# 24. Development of Education Practice

**Outline**

-   Of the two aspects to Pestalozzi's educational positions, Froebel stressed development from within, and Herbart development from without.
-   Through an early tutorial experience Herbart developed his pedagogy, but afterward invented an ingenious psychology upon which to base it. He undertook to show how the mind of the pupil is largely built up by the teacher, and he held to the moral aim of education. To accomplish this, he advocated 'manysided interest,' and, while recognizing the value of both 'historical' and 'scientific' subjects, emphasized the former. But he also held that all subjects should be unified through 'correlation,' and formulated the 'formal steps of instruction.' The value of his work has been obscured by the formal interpretations of disciples, but he contributed greatly to the science of education. Herbartianism, developed by Ziller and others, spread throughout Germany; through the Herbart Society, it has greatly influenced educational content and methods in the United States.
-   Through his university environment, Froebel developed a mystic philosophy, but made it the basis of remarkable educational practices. He held to organic 'unity' in the universe, and to the general method of 'self-activity.' Besides this (1) 'motor expression,' he also stressed (2) 'social participation,' and attempted to realize both principles in (3) a school without books and set tasks, - the 'kindergarten.' The training here has consisted chiefly in 'play-songs,' 'gifts,' and 'occupations.' The chief weakness of Froebelianism is its mystic and symbolic theory, but it has comprehended the most essential laws of education at all stages. The kindergarten was spread through Europe largely by Baroness von Biilow, and through the United States by Elizabeth P. Peabody and others.
-   Few tendencies in educational practices to-day cannot be traced back for their rudimentary form to Herbart and Froebel, or their master, Pestalozzi.

**Froebel and Herbart as Disciples of Pestalozzi.** - In the discussion of observation and industrial training, we have noted the suggestions for improvement in educational practice that arose through Pestalozzi. While somewhat vague and based upon sympathetic insight rather than scientific principles, the positions of Pestalozzi not only left their direct influence upon the teaching of certain subjects in the elementary curriculum, but became the basis of the elaborate systems of Herbart and Froebel. These educators may be regarded as contemporary disciples of the Swiss reformer, who was born a generation before, but they continued his work along rather different lines. Each went to visit Pestalozzi, and it would seem from their comments upon what they saw that each found in the master the main principie which appealed to him and which he afterward developed more or less consistently throughout his work.

For there were two very definite aspects to Pestalozzi's positions, which may at first seem opposed to each other, but are not necessarily contradictory. On the one hand, Pestalozzi seems to have held that education should be a natural development from within; on the other, that it must consist in the derivation of ideas from experience with the outside world. The former point of view, which is apparent in his educational aim and definition of education (seep. 285), would logically argue that every characteristic is implicit in the child at birth in the exact form to which it is afterward to be developed, and that the teacher can at best only assist the child's nature in the efforts for its own unfolding. This attitude Pestalozzi apparently borrowed from the psychology implied in Rousseau's naturalism. The other conception, that of education as sense perception, which is evident in Pestalozzi's observational methods (see p. 286), depends upon the theory that immediate and direct impressions from the outside are the absolute basis of all knowledge, and holds that the contents of the mind must be entirely built up by the teacher. Some such naive interpretation has been common since speculation began, especially among teachers, and had been formulated before Pestalozzi's day by Locke, Hume, and others. In the main, Froebel took the first of these Pestalozzian viewpoints and rarely admitted the other, but the latter phase was developed by Herbart to the almost total disregard of the former. Hence we find that the one educator lays emphasis upon the child's development and activities, and the other concerns himself with method and the work of the teacher. The original contributions of both reformers to educational practice, however, were large, and are deserving of extended description.

**The Early Career and Writings of Herbart.** - Johann Friedrich Herbart (1776-1841) both by birth and by education possessed a remarkable mind, and was well calculated to become a profound educational philosopher. He came of intellectual and educated stock, and at the gymnasium and university displayed a keen interest in philosophy, Greek, and mathematics. Each of these subjects, too, was destined to play a part in his educational theories. Just before graduation (1797), however, Herbart left the university to become private tutor to the three sons of the governor of Interlaken, Switzerland, and during the next three years he obtained in this way a most valuable experience. The five extant reports that he made on the methods he used and on his pupils' progress reveal thus early the germs of his elaborate system. The youthful pedagogue seems to have recognized the individual variations in children, and to have shown a due regard for the respective ages of his pupils. He also sought, by means of his favorite work, the *Odyssey*, to develop in them the elements of morality and a 'many-sided interest.' This early experience, rather than his ingenious system of psychology and metaphysics, which he afterward developed in explanation, was the real foundation of his pedagogy, and furnished him with the concrete examples of the characteristics and individualities of children that appear in all his later works. He ever afterward maintained that a careful study of the development of a few children was the best preparation for a pedagogical career, and eventually made an experience of this kind the main element in his training of teachers.

While still in Switzerland, Herbart met Pestalozzi and was greatly attracted by the underlying principles of that reformer. He paid a visit to the institute at Burgdorf in 1799, and during the next two years, while at Bremen completing his interrupted university course, he undertook to advocate and render more scientific the thought of the Swiss educator. Here he wrote a sympathetic essay *On Pestalozzi's Latest Writing, 'How Gertrude Teaches Her Children,'* and made his interpretation of *Pestalozzi's Idea of an A BC of Observation* (see p. 286). Next Herbart lectured on pedagogy at the University of Gottingen. The treatises he wrote there seem to have become more critical toward the Pestalozzian methods, and he no longer strives to conceal their vagueness and want of system. Sense perception, he holds with Pestalozzi, does supply the first elements of knowledge, but the material of the school course should be definitely arranged with reference to the general purpose of instruction, which is moral self-realization. This position on the moral aim of education he made especially explicit and complete in his work on *The Science of Education* (1806).

**His Work at Konigsberg and Gottingen.** - In 1809 Herbart was called to the chair of philosophy at Konigsberg, and there established his now historic pedagogical seminary and the small practice school connected with it. The students, who taught in the practice school under the supervision and criticism of the professor, were intending to become school principals and inspectors, and, through the widespread work and influence of these young Herbartians the educational system of Prussia and of every other state in Germany was greatly advanced. In his numerous publications at Konigsberg, Herbart devoted himself chiefly to works on a system of psychology as a basis for his pedagogy. After serving nearly a quarter of a century here, he returned to Gottingen as professor of philosophy, and the last eight years of his life were spent in expanding his pedagogical positions. Here he issued the first edition of his *Outlines of Educational Doctrine* (1835), which gives an exposition of his educational system when fully matured. It contains brief references to his mechanical metaphysics and psychology, but is a most practical and well-organized discussion of the educational process.

**Herbart's Psychology.** - Herbart's metaphysical psychology seems to have been an after-thought developed to afford a basis for the method of pedagogical procedure that he had worked out of his tutorial experience and his acquaintance with the Pestalozzian practice. But some explanation of this elaborate psychology may serve to make clearer his educational principles. For the most part he holds that the mind is built up by the outside world, and he is generally supposed to have left no place for instincts or innate characteristics and tendencies. With him the simplest elements of consciousness are 'ideas,' which are atoms of mind stuff thrown off from the soul in endeavoring to maintain itself against external stimuli. Once produced by this contact of the soul with its environment, the ideas become existences with their own dynamic force, and constantly strive to preserve themselves. They struggle to attain as nearly as possible to the summit of consciousness, and each idea tends to draw into consciousness or heighten those allied to it, and to depress or force out those which are unlike. Each new idea or group of ideas is heightened, modified, or rejected, according to its degree of harmony or conflict with the previously existing ideas. In other words, all new ideas are interpreted through those already in consciousness. In accordance with this principle, which Herbart called 'apperception,' the teacher can secure interest and the attention of the pupil to any new idea or set of ideas and have him retain it, only through making use of his previous body of related knowledge. Hence the educational problem becomes how to present new material in such a way that it can be 'apperceived' or incorporated with the old, and the mind of the pupil is largely in the hands of the teacher, since he can make or modify his 'apperception masses,' or systems of ideas.

**The Aim, Content, and Method of Education.** - Accordingly, Herbart holds that the purpose of education should be to establish moral and religious character. He believes that this final aim can be attained through instruction, and that, to determine how this shall furnish a 'moral revelation of the world,' a careful study must be made of each pupil's thought masses, temperament, and mental capacity. There is not much likelihood of the pupil's receiving ideas of virtue that will develop into glowing ideals of conduct when his studies do not appeal to his thought systems and are consequently regarded with indifference and aversion. They must coalesce with the ideas he already has, and thus touch his life. But Herbart does not limit 'interest' to a temporary stimulus for the performance of certain school tasks; he advocates the building up by education of certain broad interests that may become permanent sources of appeal in life. Instruction must be so selected and arranged as not only to relate itself to the previous experience of the pupil, but as also to reveal and establish all the relations of life and conduct in their fullness.

In analyzing this 'many-sided interest,' Herbart holds that ideas and interests spring from two main sources, – 'experience,' which furnishes us with a knowledge of nature, and 'social intercourse,' from which come the sentiments toward our fellowmen. Interests may, therefore, be classed as belonging to (1) 'knowledge' or to (2) 'participation.' These two sets of interests, in turn, Herbart divides into three groups each. He classed the 'knowledge' interests as (a) 'empirical,' appealing directly to the senses; (b) 'speculative,' seeking to perceive the relations of cause and effect; and (c) 'aesthetic,' resting upon the enjoyment of contemplation. The 'participation' interests are divided into (a) 'sympathetic,' dealing with relations to other individuals; (b) 'social,' including the community as a whole; and (c) 'religious,' treating one's relations to the Divine. Instruction must, therefore, develop all these interests, and, to correspond with the two main groups, Herbart divides all studies into two branches, - the (1) 'historical,' including history, literature, and languages; and the (2) 'scientific,' embracing mathematics, as well as the natural sciences. Although recognizing the value of both groups, Herbart especially stressed the 'historical; on the ground that history and literature are of greater importance as the sources of moral ideas and sentiments. But, while all the subjects, 'historical' and 'scientific,' are needed for a 'many-sided interest,' and the various studies have for convenience been separated and classified by themselves, Herbart holds that they must be so arranged in the curriculum as to become unified and an organic whole, if the unity of the pupil's consciousness is to be maintained. This position forecasts the emphasis upon 'correlation,' or the unification of studies, so common among his followers. The principle was further developed by later Herbartians under the name of 'concentration,' or the unifying of all subjects around one or two common central studies, such as literature or history. But the selection and articulation of the subject matter in such a way as to arouse many-sidedness and harmony is not more than hinted at by Herbart himself. He specifically holds, however, that the *Odyssey* should be the first work read, since this represents the interests and activities of the race while in its youth, and would appeal to the individual during the same stage. He would follow this with other Greek classics in the order of the growing complexity of racial interests depicted in them. This tentative endeavor of Herbart, in the selection of material for the course of study, to parallel the development of the individual with that of the race, was continued and enlarged by his disciples. It became especially definite and fixed in the 'culture epochs' theory formulated by Ziller and others.

But to secure this broad range of material and to unify and systematize it, Herbart realized that it was necessary to formulate a definite method of instructing the child. This plan of instruction he wished to conform to the development and working of the human mind, and on the basis of what he conceived this activity to be, he mapped out a method with four logical steps: (1) 'clearness,' the presentation of facts or elements to be learned; (2) 'association,' the uniting of these with related facts previously acquired; (3) 'system,' the coherent and logical arrangement of what has been associated; and (4) 'method,' the practical application of the system by the pupil to new data. The formulation of this method was made only in principle by Herbart, but it has since been largely modified and developed by his followers. It was soon felt that, on the principle of 'apperception,' the pupil must first be made conscious of the existing stock of ideas so far as they are similar to the material to be presented, and that this can be accomplished by a review of preceding lessons or by an outline of what is to be undertaken, or by both procedures. Hence Herbart's noted disciple, Ziller, divided the step of 'clearness' into 'preparation' and 'presentation,' and the more recent Herbartian, Rein, added 'aim' as a substep to 'preparation.' The names of the other three processes have been changed for the sake of greater lucidity and significance by still later Herbartians, and the 'five formal steps of instruction' are now given as (1) 'preparation' (2) 'presentation,' (3) 'comparison and abstraction,' (4) 'generalization,' and (5) 'application.'

**The Value and Influence of Herbart's Principles.** - On all sides, then, as compared with Pestalozzi, Herbart was most logical and comprehensive. Where Pestalozzi obtained his methods solely from a sympathetic insight into the child mind, Herbart sought to found his also upon scientific principles. The former was primarily a philanthropist and reformer; the latter, a psychologist and educationalist. Pestalozzi succeeded in arousing Europe to the need of universal education and of vitalizing the prevailing formalism in the schools, but he was unable with his vague and unsystematic utterances to give guidance and efficiency to the reform forces he had initiated. While he felt the need of beginning with sense perception for the sake of clear ideas, he had neither the time nor the training to construct a psychology beyond the traditional one of the times, nor to analyze the way in which the material gained by observation is assimilated. Herbart, on the other hand, did create a system of psychology that, while fanciful and mechanical, worked well as a basis for educational theory and prao tice. In keeping with this psychology, he undertook to show how the ideas, which were the product of the Pestalozzian 'observation,' were assimilated through 'apperception,' and maintained the possibility of making all material tend toward moral development. This, he held, could be accomplished by use of proper courses and methods. In determining the subjects to be selected and articulated, he considered Pestalozzi's emphasis upon the study of the physical world to be merely a stepping-stone to his own 'moral revelation of the world.' While the former educator made arithmetic, geography, natural science, reading, form study, drawing, writing, and music the object of his consideration, and is indirectly responsible for the modern reforms in teaching these subjects, Herbart preferred to stress history, languages, and literature, and, through his followers, brought about improved methods in their presentation. He also first undertook a careful analysis of the successive steps in all instruction, and by his methodical principles did much to introduce order and system into the work of the classroom, although it is now known that his conception of the way in which the human mind works is hardly tenable.

A great drawback to the Herbartian doctrines is found in their formalization and exaggeration. For these tendencies his enthusiastic and literal-minded followers, rather than Herbart himself, have probably been to blame. He was himself too keen an observer to allow his doctrines to go upon all fours. He is ordinarily credited by Herbartians with a psychology that takes no account of the innate characteristics of each mind, and holds that the mind is entirely built up by impressions from the outside, but, while this is his main position, he occasionally recognizes that there must be certain native predispositions in the body which influence the soul in one direction or another. This limitation of complete plasticity by the pupil's individuality, and of the consequent influence of the teacher, causes him to perceive that "in order to gain an adequate knowledge of each pupil's capacity for education, observation is necessary - observation both of his thought masses and of his physical nature." Again, while Herbart holds that every subject should, if possible, be presented in an attractive, interesting, and 'almost playlike' way, he does not justify that 'sugar-coated interest' which has so often put Herbartianism in bad odor. "A view that regards the end as a necessary evil to be rendered endurable by means of sweetmeats," says he, "implies an utter confusion of ideas; and if pupils are not given serious tasks to perform, they will not find out what they are able to do." Often, he realizes, "even the best method cannot secure an adequate degree of apperceiving attention from every pupil, and recourse must accordingly be had to the voluntary attention, i. e., to the pupil's resolution." Moreover, 'correlation' between different subjects, as well as between principles within the same subject, was advocated by Herbart, but he felt that the attempt to make such ramifications should not be unlimited. Further, while Herbart made some effort in shaping the course of study to parallel the development of the individual with that of the race, it was Ziller that erected this procedure into a hard and fast theory of 'culture epochs.' But most common of all has been the tendency of his disciples to pervert his attempt to bring about due sequence and arrangement into an inflexible *schema* in the recitation, and to make the formal steps an end rather than a means. Whereas, there is reason to believe that Herbart never intended that all these steps should be carried out in every recitation, but felt that they applied to the organization of any subject as a whole, and that years might even elapse between the various steps.

**The Extension of His Doctrines in Germany.** - At first the doctrines of Herbart were little known, but a quarter of a century after his death there sprang up two flourishing contemporary schools of Herbartianism. In its application of Herbart's theory, the school of Stoy for the most part held closely to the original form; but that headed by Ziller departed further and gave it a devdoiS\^and more extreme interpretation. Tuiskon Ziller (1817- popularized. 1882), both as teacher in a gymnasium and as professor at Leipzig, did much to popularize and develop Herbart's system. Through him was formed the Herbartian society known as the 'Association for the Scientific Study of Education,' which has since spread throughout Germany. He it was that elaborated the doctrines of 'correlation' and 'concentration,' and first definitely formulated the'culture epochs' theory. "Every pupil should," he writes, "pass successively through each of the chief epochs of the general mental development of mankind suitable to his stage of development. The material of instruction, therefore, should be drawn from the thought material of that stage of historical development in culture, which runs parallel with the present mental stage of the pupil." All these principles Ziller worked out in a curriculum for the eight years of the elementary school, which he centered around fairy tales, *Robinson Crusoe, *and selections from the *Old* and *New Testaments.* He, moreover, developed Herbart's 'formal stages of instruction' by dividing the first step and changing the name of the last.

Karl Volkmar Stoy (1815-1885), the founder of the other school, gave himself simply to a forceful restatement of the master's positions, but also established a most influential pedagogical seminary and practice school upon the original Herbartian basis at Jena. And eleven years later, Wilhelm Rein (1847- ), who had been a pupil of both Stoy and Ziller, succeeded the former in the direction of the practice school, and introduced there the elaborate development that had taken place since Herbart's time. He adopted Ziller's 'concentration,' 'culture epochs,' and other features, but made them a little more elastic by coordinating other material with the 'historical' center in the curriculum. Through him Jena became known as the great seat of Herbartianism. Other Germans to develop the principles of Herbart have been Lange and Frick. The *Apperception* of Karl Lange is an excellent combination of scientific insight and popular presentation. Otto Frick, director of the 'Francke Institutions' at Halle (see p. 176), inclining more to the close interpretation of Stoy, devoted himself to applying Herbartianism to the secondary schools, and outlined a course for the gymnasium.

A throng of other German schoolmasters and professors have further adapted the doctrines of Herbart to school practice, and while their theories differ very largely from one another, from their common basis they are all properly designated 'Herbartian.' As a result of this continuous propaganda, the content and methods of the school curricula in Germany have been largely modified. Herbart's emphasis upon the importance to the secondary schools of literary and historical studies as a moral training has been adapted to the elementary schools by the later Herbartians in the form of story and biographical material. History has consequently attained a more prominent place in the curriculum, and is no longer auxiliary to reading and geography. It is regarded as a means of moral development, and the cultural features in the history of the German people are stressed more than the political. Ziller's plan for concentrating all studies about a core of history and literature, on the ground of thus producing 'a moral revelation of the world' for the pupil, is in evidence everywhere. A twofold course, - Jewish history through Bible stories, and German history in the form of legends and tales, appears in every grade of the elementary school after the first two, and even in these lower classes there is some attempt to utilize literature as a moral training through the medium of fairy stories, fables, moral tales, *Robinson Crusoe,* and the various stories of the philanthropinists (see p. 225).

**Herbartianism in the United States.** - Next to the land of its birth, the United States has been more influenced by Herbartianism than any other country. Before 1880 there were but few notices of Herbartianism in American educational literature, and not many appeared during the following decade. The movement was fostered largely by American teachers that were studying with Rein at Jena during the last two decades of the century. Before 1890 nine Americans had taken their degree there, and by the twentieth century more than fifty. These young men came back filled with the enthusiastic belief that Herbartian principles could supply a solution in systematic form for the many complicated problems with which American education was then grappling, and began at once to propagate their Northern faith. The movement centered chiefly in northern Illinois and was especially strong in the normal schools.

The staff of the State Normal University at this time included Charles DeGarmo, afterward professor of Education at Cornell, Frank M. McMurry, now of the Teachers College, Columbia University, and his brother, Charles A. McMurry, now of the faculty of the George Peabody College for Teachers; and the practice school at the Normal University was the first to be established upon Herbartian principles. The Schoolmasters' Club of Illinois gave much of its time to a discussion of Herbartian principles, and the first Herbartian literature in the United States was rapidly produced. During the last decade of the century there appeared large numbers of articles, textbooks, treatises, and translations, including *The Method of the Recitation* and a variety of other works upon general and special methods by the McMurrys. In 1892 The Herbart Club was founded to promote a study of Herbartian principles and adapt them to American conditions, and during the first three years it spent its efforts in translating the words of Herbart The Herbart an(i in discussing Herbartian topics only. In 1895 the *Year Book.* name of the club was changed to the Herbart Society for the Scientific Study of Education, many nonHerbartians were admitted, the scope of the discussions was enlarged, and the publication of a *Year Book* was begun.

Then began the period of criticism and the formulation of American Herbartianism. The movement was vigorously opposed by many on the ground that it was Opposition, a foreign importation, was based upon absurd metaphysical presuppositions, or contained nothing new, but the disciples of Herbart stood valiantly by their guns. Although not always certain in their own minds, they endeavored to clear up all misunderstanding and confusion in the doctrines and to keep them practical through developing them in connection with actual experiments in teaching. They showed that the fanciful psychology of Herbart did not hold a determining place in his educational thought, and that it might be rejected, without affecting the merit of his pedagogy. One by one the doctrines were introduced in the order of their concreteness, - five formal steps, apperception, concentration, interest - and little attempt was made to weave them into a single system. The critical season did not long endure, and the movement soon spread widely. By the close of the first year the Herbart Society had a membership of seven hundred, and the Herbartian principles were everywhere studied by local clubs and taught in schools and universities. In the report of the United States Commissioner of Education for 1894-1895, Dr. Harris stated: "There are at present more adherents of Herbart in the United States than in Germany." This, he believed, was due to the greater freedom of discussion that was allowed. The movement not only became an educational awakening, but it attained almost to the proportions of a cult. Moreover, many who hardly considered themselves Herbartians undertook to modify and adapt the Herbartian principles, especially 'correlation' and 'concentration.' Francis W. Parker of Chicago, for example, among the phases of his educational practice (cf. pp. 293 and 364), approached concentration so closely as to center the entire course of study around a hierarchy of natural and social sciences. And the Committees of Ten and Fifteen, appointed by the National Education Association to report upon secondary and elementary education respectively, showed a strong Herbartian influence in their recommendations of correlation.

Largely in consequence of the development of Herbartianism, an increased amount and larger utilization of historical material became general also in American elementary schools. A wide appreciation of the growth of morality, culture, and social life, rather than merely the development of patriotism, became the object in studying this subject. English and German history, as well as American, which alone was formerly taught, and sometimes Greek, Roman, and Norse, appear in the curricula of many elementary schools, and, instead of being confined to the two upper classes, historical material is often presented from the third grade up. Biographical and historical stories are largely employed in the lower classes, while in the upper some attempt is made to use European history as a setting for American. A similar development in the amount and use of literature also has appeared in the course of the elementary schools, partly as a result of the Herbartian influence. Instead of brief selections from the English and American writers, or the poorer material that formerly appeared in the school readers, complete works of literature have begun to be studied in the elementary curriculum, and a wide and rapid survey of the great English classics has been encouraged in the place of merely reading for the sake of oral expression. Even in the lowest grades some attempt to introduce the classics of childhood has been made.

While in these ways all elementary, and to some extent secondary, schools have been affected, Herbartianism pure and simple has largely been abandoned for less dogmatic methods. Even the Herbart Society has ceased to foster a propaganda, and has since 1901 dropped the first part of its name and been known as 'The National Society for the Scientific Study of Education.' The later works of DeGarmo and Frank M. McMurry claim to be quite emancipated from Herbartianism. But, although professed Herbartians are now almost unknown in the United States, no other system of pedagogy, except that of Pestalozzi, has ever had so wide an influence upon American education and upon the thought and practice of teachers generally.

**Froebel's Early Life.** - Let us now turn to Froebel, the other great successor of Pestalozzi, and to his development and extension of the master's principle of 'natural development.' Friedrich Wilhelm August Froebel (17821852) was born in a village of the Thuringian forest. He tells us that this environment started within him a search for the mystic unity that he believed to exist amid the various phenomena of nature, but it is more likely that this attitude was developed through a brief residence (1799-1800) at the University of Jena. The atmosphere about this institution was charged with the idealistic philosophy, the romantic movement, and the evolutionary attitude in science. Froebel could not have escaped the constant discussions upon the philosophy of Fichte and Schelling. He must likewise have fallen under the spell of the Jena romanticists, - the Schlegels, Tieck, and Novalis. The advanced attitude in science at Jena may also have impressed the youth. While much of the science instruction failed to make clear that inner relation and mystic unity for which he sought, he must occasionally have caught glimpses of it in the lectures of professors belonging to the school of *Natur-philosophie.*

**His Experiences at Frankfort, Yverdon, and Berlin.** - After leaving the university, Froebel was for four years groping for a niche in life. But he eventually (1805) met Anton Gruner, head of a Pestalozzian model school at Frankfort, who persuaded him of his fitness for teaching and gave him a position in the institution. Here he undertook a systematic study of Pestalozzianism, and, through the use of modeling in paper, pasteboard, and wood with his pupils, he came to see the value of motor expression as a means of education. He then withdrew to Yverdon and worked with Pestalozzi himself for two years (1808-1810). There he greatly increased his knowledge of the play and development of children, music, and nature study, which were to play so important a part in his methods. Next, he went to the University of Berlin to study mineralogy with Professor Weiss, and through the work there he finally crystallized his mystic law of 'unity.' He became fully "convinced of the demonstrable connection in all cosmic development," and declared that "thereafter my rocks and crystals served me as a mirror wherein I might discern mankind, and man's development and history."

**The School at Keilhau.** - While at Berlin, he met his lifelong assistants, Langethal and Middendorf, and took them with him when he undertook the education of his five young nephews at Keilhau. Here he founded (1816) 'The Universal German Institute of Education,' in which self-expression, free development, and social participation were ruling principles. Much of the training was obtained through play, and, except that the pupils were older, the germ of the kindergarten was already present. There was much practical work in the open air, in the garden about the schoolhouse, and in the building itself. The children built dams and mills, fortresses and castles, and searched the woods for animals, birds, insects, and flowers. To popularize the institute, Froebel published a complete account of the theory practiced at Keilhau in his famous *Education of Man *(1826). While this work is compressed, repetitious, and vague, and its doctrines had afterward to be corrected by experience, it contains the most systematic statement of his educational philosophy that Froebel ever made.

**Development of the Kindergarten.** - But the school at Keilhau was too radical for the times, and soon found itself in serious straits. Froebel then went to Switzerland and, and for five years (1832-1837) continued his educational experiments in various locations there. While conducting a model school at Burgdorf, it became obvious to him that "all school education was yet without a proper initial foundation, and that, until the education of the nursery was reformed, nothing solid and worthy could be attained." The *School of Infancy* of Comenius (see p. 171) had been called to his attention, and the educational importance of play had come to appeal to him more strongly than ever. He began to study and devise playthings, games, songs, and bodily movements that would be of value in the development of small children, although at first he did not organize his materials into a system. Then, two years later, he returned to Germany, and established a school for children between the ages of three and seven. This institution was located at Blankenburg, two miles from Keilhau, one of the most romantic spots in the Thuringian Forest, and was, before long, appropriately christened 'Kindergarten' (i. e., garden in which children are the unfolding plants). Here he put into use the material he had invented in Switzerland, added new devices, and developed his system. The main features of this were the 'play songs' for mother and child and the series of 'gifts' and' occupations' (see pp. 3 58 f.). During his seven years in Blankenburg, he constantly expanded his material, and the accounts of these additions have been collected in the works known generally as *Pedagogics of the Kindergarten, Education by Development,* and *Mother Play and Nursery Songs.*

While the kindergarten attracted considerable attention, Froebel's want of financial ability eventually compelled him to close the institution. After lecturing with much success for five years upon his system, he settled for the rest of his life near the famous mineral springs at Liebenstein in Saxe-Meiningen. During this period he obtained the friendship and support of the Baroness von Marenholtz-Bulow, who brought a large number of people of distinction in the political and educational world to see his work in operation, and wrote most interesting *Reminiscences* of Froebel's activities during the last thirteen years of his life. But owing to a confusion of his principles with the socialistic doctrines of his nephew, Karl, a decree was promulgated in Prussia by the minister of education, closing all kindergartens there. Froebel never recovered from this unjust humiliation, and died within a year.

**Froebel's Fundamental Concept of 'Unity.'** - While Froebel's underlying principles go back to the developmental aspect of Pestalozzi's doctrines and even to Rousseau's naturalism, his conception of them, his imagery, and statement, seem to be a product of the idealistic philosophy, romantic movement, and scientific attitude of the day. These tendencies seem to have been assimilated by Froebel largely through his residence in Jena and Berlin. His conclusions as to educational theory and practice would have been possible as inferences from a very different point of view, but as he developed them logically and consistently with his metaphysical position, it may be of value to consider briefly the groundwork of the Froebelian philosophy. He regarded the 'Absolute,' or God, as the self-conscious spirit from which originated both man and nature, and he consequently held to the unity of nature with the soul of man. His fundamental view of this organic unity appears in his general conception of the universe: "In all things," says he, "there lives and reigns an eternal law. This all-controlling law is necessarily based on an all-pervading, energetic, living, self-conscious, and hence eternal Unity. This Unity is God. All things have come from the Divine Unity, from God, and have their origin in the Divine Unity, in God alone. All things live and have their being in and through the Divine Unity, in and through God. The divine effluence that, lives in each thing is the essence of each thing." This fundamental mystic principle Froebel constantly reiterates in various forms, and from it derives a number subsidiary conceptions. These, however, play but a small part in his actual practice, and scarcely require consideration here.

**Motor Expression as His Method.** - But Froebel also holds that, "while in every human being there lives humanity as a whole, in each one it is realized and expressed in a wholly particular, peculiar, personal, and unique manner." Thus he maintains that there is in every person at birth a coordinated, unified plan of his mature character, and that, if it is not marred or interfered with, it will develop naturally of itself. While he is not entirely consistent, and at times implies that this natural development must be guided and even shaped, in the main he reiterates Rousseau's doctrine that 'nature is right,' and clearly stands for a full and free expression of the instincts and impulses. Hence he insists that "education in instruction and training should necessarily be *passive, following; not prescriptive, categorical, interfering."* But in his conclusion as to the proper method for accomplishing this 'development,' Froebel naturally holds that it "should be brought about not in the way of dead imitation or mere copying, but in the way of living, spontaneous self-activity." By this principle of 'self-activity' as the method of education Froebel seeks not simply activity in response to suggestion or instruction from parents or teachers, but activity of the child in carrying out his own impulses and decisions. Individuality must be developed by such activity, and selfhood given its rightful place as the guide to the child's powers when exercised in learning. Hence with this idea of development through 'self-activity' is connected his principle of 'creativeness,' by which new forms and combinations are made and expression is given to new images and ideas. "Plastic material representation in life and through doing, united with thought and speech," he declares, "is by far more developing and cultivating than the merely verbal representation of ideas."

**The Social Aspect of Education.** - His emphasis upon this psychological principle of motor expression under the head of 'self-activity' and 'creativeness' is the chief characteristic of Froebel's method. Rousseau had also recommended motor activity as a means of learning, but he had insisted upon an isolated and unsocial education for Emile, whereas Froebel stresses the social aspects of education quite as clearly as he does the principle of self-expression. In fact, he holds that increasing self-realization, or individualization through 'self-activity,' must come through a process of socialization. The social instinct is primal, and the individual can be truly educated only in the company of other human beings. The life of the individual is necessarily bound up with participation in institutional life. Each one of the various institutions of society in which the mentality of the race has manifested itself - the home, the school, the church, the vocation, the state - becomes a medium for the activity of the individual, and at the same time a means of social control. As far as the child enters into the surrounding life, he is to receive the development needed for the present, and thereby also to be prepared for the future. Through imitation of cooperative activities in play, he obtains not only physical, but intellectual and moral training. Such a moral and intellectual atmosphere Froebel sought to cultivate at Keilhau by cooperation in domestic labor, - 'lifting, pulling, carrying, digging, splitting,' and through cooperative construction out of blocks of a chapel, castle, and other features of a village. Similarly, the kindergarten was intended to "represent a *miniature state* for children, in which the young citizen can learn to move freely, but with consideration for his little fellows."

**The Kindergarten.** - Beside his basal principles of motor expression and social participation, Froebel made a third contribution to educational practice in advocating as a means of realizing these principles a school without books or set intellectual tasks, and permeated with play, freedom, and joy. In the kindergarten, 'self-activity' creativeness,' together with social cooperation, found complete application and concrete expression. The training there has always consisted of three coordinate forms of expression: (1) song, (2) movement and gesture, and (3) construction; and mingled with these and growing out of each is the use of language by the child. But these means, while separate, often cooperate with and interpret one another, and the process is connected as an organic whole. For example, when the story is told or read, it is expressed in song, dramatized in movement and gesture, and illustrated by a construction from blocks, paper, clay, or other material.

The *Mother Play and Nursery Songs* were intended to exercise the infant's senses, limbs, and muscles, and, through the loving union between mother and child, draw both into intelligent and agreeable relations with the common objects of life about them. The fifty 'play songs' are each connected with some simple nursery game, like 'pat-a-cake,' 'hide-and-seek,' or the imitation of some trade (Fig. 43), and are intended to correspond to a special physical, mental, or moral need of the child. The selection and order of the songs were determined with reference to the child's development, which ranges from almost reflex and instinctive movements up to an ability to represent his perceptions with drawings, accompanied by considerable growth of the moral sense. Each song contains three parts: (1) a motto for the guidance of the mother; (2) a verse with the accompanying music, to sing to the child; and (3) a picture illustrating the verse.

The 'gifts' and 'occupations' were both intended to stimulate motor expression, but the 'gifts' combine and rearrange certain definite material without changing the form, while the 'occupations' reshape, modify, and transform their material. The emphasis in kindergarten practice has come to be transferred from the 'gifts' to the 'occupations,' which have been largely increased in range and number. Of the 'gifts,' the first consists of a fast, box of six woolen balls of different colors. They are to be rolled about in play, and thus develop ideas of color, material, form, motion, direction, and muscular sensibility. A sphere, cube, and cylinder of hard wood compose the second 'gift.' Here, therefore, are found a second, known factor in the sphere and an unknown one in the cube. A comparison is made of the stability of the cube with the movability of the sphere, and the two are harmonized in the cylinder, which possesses the characteristics of each. The third 'gift' is a large wooden cube third, divided into eight equal cubes, thus teaching the relations of the parts to the whole and to one another, and making possible original constructions, such as armchairs, benches, thrones, doorways, monuments, or steps. The three following 'gifts' divide the cube in various ways so as to produce solid bodies of different types and sizes, and excite an interest in number, relation, and form. From them the children are encouraged to construct geometrical figures and 'forms of beauty' or artistic designs. Beside the six regular 'gifts,' he also added 'tablets,' 'sticks,' and 'rings,' sometimes known as 'gifts seven to nine.' This material introduces surfaces, lines, and points in contrast with the preceding solids, and brings out the relations of area, outline, and circumference to volume. The 'occupations' comprise a long list of constructions with paper, sand, clay, wood, and other materials. Corresponding with the 'gifts' that deal with solids, may be grouped 'occupations' in clay modeling, cardboard cutting, paper folding, and wood carving; and with those of surfaces may be associated mat and paper weaving, stick shaping, sewing, bead threading, paper pricking, and drawing.

**The Value and Influence of Froebel's Principles.** - For one pursuing destructive criticism only, it would not be difficult to find flaws in both the theory and practice of Froebel. In the *Mother Play* the pictures are rough and poorly drawn, the music is crude, and the verses are lacking in rhythm, poetic spirit, and diction (Fig. 43). But the illustrations and songs served well the interests and needs of those for whom they were produced, and Froebel himself was not insistent that they should be used after more satisfactory compositions were found. Other criticism of his material has been made on the ground that it was especially adapted to German ideals, German

Fig. 43. - *Der Zimmermann* (The Carpenter).

(Reproduced by permission ol D. Appleton and Company frora the Eliot and Blow edition of FroebePs *Mother Play.)*

children, and the relatively simple village life of Froebel's experience, and that it needs considerable modification to suit other countries and the industrial organization of society to-day. Also the argument of 'formal discipline' for care and accuracy in the use of the gifts, and the insistence upon the employment of every part of each gift upon all occasions in the exact order mentioned by Froebel, have been shown to violate the principles of modern psychology. His more liberal disciples, however, realize that it is the spirit of his underlying principles, and not the letter of his practice, that should be followed, and have constantly struggled to keep the kindergarten matter and methods in harmony with the times and the environment.

A more serious hindrance to the acceptance of Froebelianism has arisen from his peculiar mysticism and symbolism. Since all things live and have their being in and through God and the divine principle in each is the essence of its life, everything is liable to be considered by Froebel as symbolic in its very nature, and he often resorts to fantastic and strained interpretations. Thus with Froebel the cube becomes the symbol of diversity in unity, the faces and edges of crystals all have mystic meanings, and the numbers three and five reveal an inner significance. At times this symbolism descends into a literal and verbal pun, where it seems to a modern that Froebel can hardly be in earnest. Further, he holds that general conceptions are implicit in the child, and each of these can be awakened by 'adumbration,' that is, by presenting something that will symbolically represent that particular 'innate idea.' Thus, in treating the gifts and games, he maintains that from a ball the pupils gather an abstract notion of 'unity.' Moreover, because God is the self-conscious spirit that originated both man and nature, and everything is interconnected, he believes that each part of the universe may throw light on every other part, and constantly holds that a knowledge of external nature, - such as the formation of crystals, will enable one to comprehend the laws of the mind and of society.

Unfortunately, this mystic symbolism, vague and extreme as it is, is regarded by the strict constructionists among the kindergartners as the most essential feature in Froebelianism, and they expect the innocents in their charge to reveal the symbolic effect of the material upon their minds. There is no real evidence for supposing that such associations between common objects and abstract conceptions exist for children. But such an imaginary symbolic meaning may be forced upon an object by the teacher, and pupils in conservative kindergartens soon learn to adopt certain phrases and attitudes that imply such mystic meaning. This often tends to foster insincerity and sentimentalism rather than to inculcate abstract truth through symbols. Had Froebel possessed the enlarged knowledge of biology, physiology, and psychology that is available for one living in the twentieth century, it is unlikely that he would have insisted upon the symbolic foundations for his pedagogy. His excellent practice is heavily handicapped by these interpretations, and might as easily have been inferred from very different positions in modern psychology.

But Froebel has had a most happy effect upon education as a whole. In some respects he utilized features from other reformers. We can see that he adopted many of Pestalozzi's objective methods in geography, natural history, arithmetic, language, drawing, writing and reading, and constructive geometry; reiterated Rousseau's views upon the infallibility of nature; and advocated the physical training and excursions as a means of study that are stressed by both these reformers. In his use of stories, legends, fables, and fairy-tales, he paralleled his contemporary, Herbart, in his influence upon the curriculum. But in his emphasis upon motor expression and social participation, together with his advocacy of a school without books or set tasks, Froebel was unique, and made a most distinctive contribution to educational practice. And whenever the real significance of his principles has been comprehended, they have been recognized as the most essential laws in the educational process, and are valued as the means of all effective teaching.

Froebel himself never fully worked out his theories in connection with schooling beyond the kindergarten, but all stages of education have now come to realize the value of discovering and developing individuality by means of initiative, execution, and cooperation; and spontaneous activities, like play, construction, and occupational work, have become more and more the means to this end. For example, the 'busy work,' 'whittling,' 'claymodeling,' 'sloyd,' and other types of 'manual training' have to a large degree sprung from the influence of Froebel. Uno Cygttaeus (1810-1888), who started the Cygnaeus manual training movement, owed his inspiration to Froebel and his own desire to extend the kindergarten occupations through the grades. As a result of his efforts, Finland in 1866 became the first country in the world to adopt manual training as an integral part of the course in the elementary and teacher training schools. In 1874, through the visit of Otto Salomon (1849-1007) to Cygnaeus, Sweden transformed its sloyd from a system of teaching the elements of trades to the more educative method of manual training. This use of constructive and occupational work for educational purposes rather than for industrial efficiency soon spread throughout Europe, and was first suggested to the United States by the Centennial Exposition of 1876 at Philadelphia. Various types of modern educational theory and practice, especially those associated with experiments made in the United States, also reveal large elements of Froebelian influence. Among these might be included the work of Colonel Parker (Fig. 40) and of Professor John Dewey. The Froebelian emphasis upon motor expression, the social aspect of education, and informal schooling are evident throughout Parker's work in his elementary school, and are even extended so as to include speech and the language-arts. Similarly, Dewey's occupational work and industrial activities, which were used through the entire course of his 'experimental school' in Chicago, although not copied directly from Froebel, closely approached the modified practice of the kindergarten (see pp. 430 f.).

**The Spread of Froebelianism through Europe.** - Directly after the death of Froebel, the kindergarten began to be spread through his devoted followers, especially Baroness von Bulow. By means of her social position and knowledge of modern languages, she was enabled to become his great apostle throughout Europe. Having failed to obtain a revocation of the edict against the kindergarten (see p. 355) in Prussia, the baroness turned to foreign lands. She visited France, Belgium, Holland, Italy, Russia, and nearly every other section of Europe, and in 1867 was invited to speak before the ' Congress of Philosophers' at Frankfort. This distinguished gathering had been called to inquire into contemporary educational movements, and after her elucidation of Froebelianism, a standing committee of the Congress, known as the 'Froebel Union,' was formed to study the system. The propaganda was soon everywhere eagerly embraced. Kindergartens, training schools, and journals devoted to the movement rapidly sprang up. While the kindergarten was not generally adopted by the governments, it was widely established by voluntary means throughout Western Europe, and has since met with a noteworthy growth. Instruction in Froebelian principles is now generally required in most normal and teacher training institutions there. Sometimes, as in France and England, it has been combined with the infant school movement, and has lost some of its most vital characteristics, but even in these cases the cross-fertilization has afforded abundant educational fruitage. Only in Germany, the native land of the kindergarten, has serious hostility to the idea remained. Kindergartens have, with few exceptions, never been recognized there as genuine schools or part of the regular state system. Even to-day the German kindergarten is regarded as little more than a day nursery or convenient place to deposit small children and have them amused.

**The Kindergarten in the United States.** - The development and influence of the kindergarten have been more marked in the United States than in any other country. First attempts at a kindergarten in America were made shortly after the middle of the nineteenth century by educated Germans, who had emigrated to America because of the unsettled conditions at home. A more fruitful attempt was that of Elizabeth P. Peabody at Boston in the early sixties. Notwithstanding the immediate success of this institution and the evident enjoyment of the children, Miss Peabody felt that she had not succeeded in getting the real spirit of Froebel, and in 1867 she went to study with his widow, who had been settled in Hamburg for several years. Upon her return the following year Miss Peabody corrected the errors in her work and established a periodical to explain and spread Froebelianism. The remainder of her life was spent in interesting parents, philanthropists, and school boards in the movement, and a service was done for the kindergarten in America almost equal to that of Baroness von Biilow in Europe. In 1868 through Miss Peabody the first training school for kindergartners in the United States was established at Boston. A similar institution was opened in New York by 1872 in charge of Maria Bolte, who had also studied with Frau Froebel. The same year saw the beginning of Susan E. Blow's work in St. Louis, where her free training school for kindergartners was opened. Another missionary effort began in 1876 through Emma Marwedel, who was employed to organize voluntary kindergartens and training classes throughout the chief centers of California. The kindergarten movement grew rapidly. Between 1870 and 1890 in all the leading cities of the country subscriptions for kindergartens were raised by various philanthropic agencies, and by the close of the century there were about five hundred such voluntary associations.



But private foundations are restrictive, and it was not until the kindergarten began to be adopted by school systems that the movement became truly national in the United States. Boston in the early seventies added a few kindergartens to her public schools, but after several years of trial gave them up on account of the expense. The first permanent establishment under a city board was made in 1873 at St. Louis through the efforts of Miss Blow. Twelve kindergartens were organized at first, but others were opened as rapidly as competent directors could be prepared at Miss Blow's training school. Within a decade there were more than fifty public kindergartens and nearly eight thousand pupils in St. Louis. San Francisco authorized the addition of kindergartens to the public schools in 1880; and between that date and the end of the century New York, Boston, Philadelphia, Buffalo, Pittsburgh, Rochester, Providence, Milwaukee, Minneapolis, and nearly two hundred other progressive cities made the work an integral part of their system. About twenty of the cities employed a special supervisor to inspect the work. Excellent training schools for kindergartners are now maintained by half a hundred public and quasi-public normal institutions.

**The Relative Influence of Pestalozzi, Herbart, and Froebel.** - It is now obvious how large a part in the development of modern educational practice has been played by Herbart and Froebel. There are few tendencies in the curricula and methods of the schools today that cannot in their beginnings be traced back to them, or to Pestalozzi, their master. But the reforms of all three find their roots in Rousseau (Fig. 44). His 'naturalism' was continued by Pestalozzi (Fig. 45) in his 'development' and 'observation,' which were, in turn, further elaborated by Froebel and Herbart respectively (Figs. 47 and 46). Through his 'observation' methods, Pestalozzi greatly improved the teaching of arithmetic, language work, geography, elementary science, drawing, writing, reading, and music, and, by means of Fillenberg's work, developed industrial and philanthropic training. As a result of Herbart's moral and religious aim, marked advances in the teaching of history and literature have taken place, and, largely through his carefully wrought educational doctrines, order and system have everywhere been introduced into instruction. From Froebel's mystic interpretation of 'natural development' we have obtained the kindergarten training for a period of life hitherto largely neglected, the informal occupations, manual training, and other studies of motor expression, together with psychological and social principles that underlie every stage of education. Pestalozzi's reforms were felt in Europe throughout the first half of the nineteenth century, but did not have any wide effect upon the United States until after the 'Oswego movement' in the sixties. The influence of Froebel appeared in Europe shortly after the middle of the century, and began to rise to its height in America about 1880. The Herbartian theory and practice became popular in Germany between 1865 and 1885, while the growth of Herbartianism in the United States began about five years after the latter date. Hence the development of modern educational practice, due to these three great reformers, falls distinctly within the period of the nineteenth century.

**Supplementary Reading**

Graves, *In Modern Times* (Macmillan, 1913), chap. VII; *Great Educators* (Macmillan, 1912), chaps. X and XI; Monroe, *Textbook* (Macmillan, 1905), pp. 622-673; Parker, *Modern Elementary Education* (Ginn, 1912), chaps. XVII and XVIII. Herbart's *Science of Education* (translated by Felkin), and *Outlines of Educational Doctrine* (translated by Lange and De Garmo, Macmillan, 1909), and Froebel's *Education of Man* (translated by Hailmann; Appleton, 1894), *Pedagogics of the Kindergarten* and *Education by Development* (translated by Jarvis; Appleton, 1897 and 1899), and *Mother Play* (translated by Eliot and Blow, Appleton, 1896), should be read at least cursorily. The best brief treatise on *Herbart and Herbartianism* (Scribner, 1896) is that by De Garmo, C., a graphic description of *The Herbarlian Psychology* (Heath, 1898) is given by Adams, J., in chap. III, and a history of *The Doctrines of Herbart in the United States* as a doctoral dissertation (University of Pennsylvania) by Randels, G. B. A good account of *Froebel and Education by Self-Activity* (Scribner, 1897) has been furnished by Bowen, H. C.; a conservative treatment of *Kindergarten Education (Education in the United States,* edited by N. M. Butler, Monograph No. 1), by Blow, Susan E.; an interesting treatise on *Kindergarten in American Education* (Macmillan, 1908), by Vandewalker, Nina C; and a critical account of *The Psychology of the Kindergarten (Teachers College Record,* vol. IV, pp; 377-408), by Thorndike, E. L.