# 28. Retrospect and Prospect

**Outline**

-   Evolution in education may be interpreted from the standpoint of the development of individualism. Individualism was first fully recognized in the teachings of Christ, but was repressed during the Middle Ages. While it reappeared during the Renaissance, Reformation, and other movements, it soon lapsed, but a complete break from tradition occurred with Rousseau in the eighteenth century.
-   For a time individualism dominated, but education since then has endeavored to afford latitude to the individual without losing sight of the welfare of society.

The Development of Individualism. - The discussion of present day tendencies that has just been given, together with the account of educational evolution in the preceding chapters, serves to show how far modern times have progressed in the ideals and practice of education. This may perhaps be best appreciated from the standpoint of the development of individualism. To follow such an interpretation back to the beginning of the history of education, it may be stated that during the day of primitive man no real distinction was made between \^\^\^MHltic society and the individual, and practically all advance- tendencies

•" 1 during the days

ment was impossible, for no one looked much beyond of primitive the present. With the appearance of the transitional period in the Oriental countries, the individual had begun nations,

Roman civili zations,

Christian de velopment,

to emerge, but was kept in constant subjection to the social whole, for man was quite enslaved to the past.

Athenian and \^^s^ ^tne^ J^ew^ish; Athenian, and Roman civilizations developed, the beginnings of individualism were for the first time clearly revealed, and some regard was had for the future. Then, through the teachings of Christ, there came to be a larger recognition of the principle of individualism and the brotherhood of man. Owing to a necessity for spreading these enlarged ideals among a barbarous horde of peoples, individualism was repressed,

*TM^d^J^he^* ^Middle^ and throughout the Middle Ages the keynote was submission to authority and preparation for the life to come. The cultural products of Greece and Rome largely disappeared, and all civilization became restricted, fixed, and formal.

But the human spirit could not be forever held in bondage, and, after almost a millennium of repression and uniformity, various factors that had accumulated within the Middle Ages produced an intellectual awakening that we know as the 'Renaissance.' Its vitality lasted during the fifteenth century in Italy and to the close of the sixteenth in the Northern countries, but by the dawn of the seventeenth century it had everywhere degenerated into a dry and mechanical study of the classics. This constituted a formalism almost as dense as that it had superseded, except that linguistic and literary studies had replaced dialectic and theology. A little later than the spread of the Renaissance, though overlapping it somewhat, came the allied movement of the 'Reformation.' This grew in part out of the disposition of the Northern Renaissance to turn to social and moral account the revived intelligence and learning. Yet here also the revival failed in its mission, and the tendency to

the Renaissance,

the Reformation,

rely upon reason rather than dogma hardened into

formalism and a distrust of individualism. Again, in

the seventeenth century, apparently as an outgrowth of

the same forces, intellectual activity took the form of a

search for 'real things.' The movement that culminated

in 'sense realism' appeared, but this small and crude ^and^ ^realism^;

beginning of the modern scientific tendency was for some

decades yet held within limits. Associated with this

realistic tendency, on the religious and political sides

also appeared a quickening in such forms as 'Puritanism'

and 'Pietism,' which likewise degenerated eventually into tanism and

*e* ,. . j 1 . Pietism;

a fanaticism and hypocrisy.

The Harmonization of the Individual and Society. - Thus the way was opened for the complete break with JUJJj \^°^u^||f^au^ tradition and authority that occurred in the eight- "trudge

*^J^ ~m~* ° tendency.

eenth century. This tendency, while in France at least most destructive and costly, was the inevitable result of the unwillingness to reshape society and education in accordance with changing ideals and conditions. Hence Rousseau undertook to shatter all educational traditions. But his recommendation of isolated education, so palpable in its fallacies, prepared the ground for the numerous social, scientific, and psychological tendencies (see pp. 218-222) that were destined to spring up in modern education and for the consequent improvement in the aim, organization, content, and method of education. Of course modern education has advanced infinitely beyond anything implied by Rousseau or even the later reformers of the past century, but it is out of his attempts at destruction that has grown this nobler structure. For a time individualism triumphed and

The present

ground authority under its heel, but when this extremity had been passed, the problem became how to harmonize the individual with society, and to develop personality progressively in keeping with its environment. Thus the nineteenth and twentieth centuries have put forth conscious efforts to justify the eighteenth and to bring out and develop the positions barely hinted at in its tendencies in negations. It is not alone the individual as such that

education .

seemtohar- has been of interest in the modern period, but more and dividual more the individual in relation to the social whole to

tho\^ofsodety. which he belongs, as only in this way can the value of his activities be estimated.

This is revealed in the works of those who followed

Rousseau, and especially in the attempts of recent

, , . . educational philosophers to frame a definition of educa

Recent defim- .

tions of educa- tion that shall recognize the importance of affording

tion show this. , . , , ...... .... . , , ,

latitude to the individual without losing sight of the welfare of the social environment in connection with which his efforts are to function. Thus Butler, though recognizing the individual factor, especially stresses the social by declaring education to be "the gradual adjustment of the individual to the spiritual possessions of the race." Then he further declares: "When we hear it sometimes said, 'All education must start from the child,' we must add, 'Yes, and lead into human civilization;' and when it is said on the other hand that 'all education must start from a traditional past,' we must add, 'Yes, and be adapted to the child.'" And the balance between the two factors of the individual and society is even more explicitly preserved in Dewey's statement "that the psychological and social sides are organically related, and that education cannot be regarded as a compromise between the two, or a superimposition of one upon the other." In the same way Bagley has made 'social efficiency' the main aim in educating the individual to-day, and both elements are carefully considered by all modern writers in discussing educational values. Thus the central problem in education of the twentieth and succeeding centuries is to be a constant reorganization of the curriculum and methods Jona\^probiem of teaching, and this reconstruction must be such as to ^of^ ^the^ ^future^harmonize a due regard for the progressive variations of the individual with the welfare of the conservative institutions of society. It must include a continual effort to hand on the intellectual possessions of the race, but also to stimulate all individuals to add some modification or new element to the product. In this way there may develop unending possibilities for both the individual and society.

**Supplementary Reading**

Graves, F. P., *History of Education before the Middle Ages* (Macmillan, 1909), chap. XII; *History of Education during the Transition* (Macmillan, 1910), chap. XXIII; *History of Education in Modern Times* (Macmillan, 1913), chap. XII; Monroe, P., *Textbook in the History of Education* (Macmillan, 1905), chap. X.