# 3. The Education of the Romans

**Outline**

-   The contribution of the Romans to progress was largely due to their absorption of Greek culture, but their primitive training had an influence in itself. This was mostly civic and practical, and was given informally in the family and the forum.
-   Through amalgamation with the Greek, Roman education maintained three grades of schools: (i) the elementary school or *ludus,* (2) the 'grammar' school, and (3) the rhetorical school. Beyond the education of these schools, a young Roman might attend a university.
-   Schools were gradually subsidized by the emperors, but education eventually deteriorated into a formal qualification for senatorial rank. The practical Romans, however, created a universal empire and legal system, a universal religion, and other institutions for modern society.

**Roman Education Amalgamated with Greek.** - The name of Rome is still suggestive of power and organization. These characteristics seem to have been innate; but the significance of Roman development to the history of progress and education was largely due to the fact that, in her spread over the civilized world, the Eternal City amalgamated the Greek civilization with her own. Until then her ideals of life, while effective in conquest, had been narrow and little adapted to the development of individuality or of cosmopolitanism. Unconsciously realizing the need of broader ideals, she absorbed those of Greece. But Rome could not be Hellenized without making some contributions to the result from her own genius, and for that reason it is important to learn something of Roman civilization and education, crude as they were, before they came into contact with Greek culture.

**Early Education in Rome.** - In the early days Rome was animated by intense patriotism and love for military life, and felt that each citizen was bound to merge his identity in that of the state. In the surrender of individuality they were, to be sure, not unlike the Spartans, although they believed that this subordination should be brought about voluntarily rather than by compulsion of law and state organization. But, with such a love as theirs for mere material achievement, the Athenian ideal of a full and harmonious development of one's whole nature could scarcely be expected to make any appeal. They looked not for harmony, proportion, or grace, but for stern utility. They were sedate, grave, and serious, and their education was practical, prosaic, and utilitarian.

Until the Greek institutions began to be adopted, schools did not exist in Rome, except possibly the *ludus* or elementary school. During this pristine period education consisted in a practical training in Roman ideals and everyday living conducted largely through the family. In childhood the boys and girls alike were given a physical and moral training by their mother, but, as the boy grew older, he went more in the company of his father, and learned efficiency in life informally through his example and that of the older men, while the girl was taught at home by her mother. If the boy belonged to a patrician family, he might acquire much knowledge concerning Roman custom and law by hearing his father advise and aid the family *clients,* or 'dependents,' and by attending banquets with him. He might also receive an apprenticeship training from his parent or some other older man in the profession of soldier, advocate, or statesman. In case he was born in a less exalted station, he might learn his father's occupation at the farm or shop. The girl, whatever her social status, was trained by her mother in the domestic arts, especially in spinning and weaving wool. Through their parents children probably learned to read and write; and they committed to memory stories of Roman heroes, ballads, martial and religious songs, and the *Twelve Tables* of national laws, after these had been codified (451 B. C). Physical exercise was secured largely by games, which were mostly in imitation of future occupations, and gymnastics were employed simply as training for war. The usages of home and public religion also played an important part in the education of the young Romans, especially since almost every activity in life was presided over by some deity, whom it was necessary to propitiate when engaging in it. Thus education in early Rome was practical, and, to some extent, occupational. It was intended to produce efficiency as fathers, citizens, and soldiers. It consisted in training the youths to be healthy and strong in mind and body, and sedate and simple in their habits; to reverence the gods, their parents, the laws, and institutions; and to be courageous in war, and familiar with the traditional agriculture, or the conduct of some business. It did produce a nation of warriors and loyal citizens, but it inevitably tended to make them calculating, selfish, overbearing, cruel, and rapacious. They never possessed either lofty ideals or enthusiasm. Their training was best adapted to a small state, and became unsatisfactory when they had spread over the entire Italian peninsula. The golden age of valor and stern virtue had then largely departed, and they began unconsciously to seek a more universal culture. While such a people regarded the Greeks as visionary, just as the Greeks looked upon them as barbarians, they felt instinctively that only by absorption of the Hellenic ideals could their cosmopolitan ambitions be carried out. On the other hand, it was through the organization which the Romans were able to furnish, that the great ideals formulated by the Greeks were destined to be rendered effective and to become a matter of value and concern to civilization ever since.

**The Absorption of Greek Culture.** - There was a gradual infiltration of Greek culture into Rome from very early days. This received a great impulse through the conquests of Alexander (334-323 B. C) and the absorption of Macedon by Rome (168 B.C.), but it was not until about half a century after Greece itself had become a Roman province (146 B. C.), that the Greek educational ideals and institutions can be said to have been completely absorbed by Rome. This new type of education was thus well established early in the first century B.C. It may be said to have remained almost unmodified until toward the end of the second century A. D., when political conditions at Rome became most unstable and the period of degeneracy set in. During these three centuries of Hellenized Roman education, three grades of schools resulted from the amalgamation. They were the (1) *Iudus* or school of the *litterator,* as the lowest school was called; (2) the 'grammar' school, taught by a *grammaticus* or *litteratus;* and (3) the schools of rhetoric and oratory, which furnished a somewhat higher education.

**The Ludus.** - The ludus, or lowest school, may possibly have existed before the process of Hellenization even began, but if it did, it must have been intended simply to supplement the more informal training of the home. Whenever originated, it probably taught at first only reading, writing, and rudimentary calculation, as in the family, through the medium of historical anecdotes, ballads, religious songs, and the *Twelve Tables.* But as the Greek influence crept in more and more, the literary content was somewhat extended. About the middle of the third century B. C, Livius Andronicus translated the *Odyssey* into Latin; and a number of epics, dramas, and epigrams were soon composed after Greek models. These works, in whole or part, were introduced into the curricula of the *ludi,* and by the beginning of the first century B.C., the *Twelve Tables* had been displaced by the Latinized *Odyssey* of Andronicus. The methods of instruction were *memoriter* and imitative. The names and alphabetic order of the letters were first taught without any indication of their significance or even shape, and all possible combinations of syllables were committed before any words were learned. Reading and writing were then taught by dictation, and, in tracing the letters on wax-tablets with the stylus (Fig. 5), the hand of the pupil was at first guided by the teacher. Calculation was learned by counting on the fingers, by means of pebbles, or upon the abacus, and eventually sums were worked upon the tablets.

Methods so devoid of interest were naturally accompanied by severe discipline. The rod, lash, and whip seem to have been in frequent use, and the names ordinarily applied to schoolmasters in Latin literature are suggestive of harshness and brutality. Moreover, a fresco found at Herculaneum depicts a boy held over the shoulders of another, with the master beating the victim upon the bare back (Fig. 6). Under these circumstances, no real qualifications were required of the teacher, and his social standing was low. The Greek custom of having the boy accompanied to and from school by a slave that was otherwise incapacitated by age or physical disability soon came to be imitated by the Romans. When a special building was employed for the school, it was usually a mere booth or veranda, and the pupils sat on the floor or upon stones.

**Grammar Schools.** - The 'grammar' school grew out of the increasing literary work of the *Iudus.* But, while offering a more advanced course, it would seem to belong in part at least to the elementary stage of education, especially as its work was never sharply divided from that of the *Iudus.* The young Roman might attend both a Greek and a Latin grammar school, but, in case he did, usually went first to the former. The curriculum in each consisted, according to Quintilian, of 'the art of speaking correctly' and 'the interpretation of the poets,' or, in other words, of a training in grammar and literature. 'Grammar' may, however, have included some knowledge of philology and derivations, as well as drill on the parts of speech, inflections, syntax, and prosody, and practice in composition and paragraphing. The literary training was obtained by writing paraphrases of the best authors, textual and literary criticism, commentaries, and exercises in diction and verse-writing. Some other studies, like arithmetic, geometry, astronomy, geography, and music may also have been added in time, from the suggestions of Plato, but the Romans naturally gave them a practical bearing. Some gymnastics, mostly for military training, were often in the course. The methods in the grammar schools were somewhat better than those of the *Indus,* but the commentary of the teacher on the text was usually taken down *verbatim* by the pupil. The discipline, in consequence, was not much in advance of that of the lower schools. But the accommodations for these secondary schools were decidedly superior, and the buildings not only possessed suitable seats for the pupils and teacher, but were even adorned with paintings and sculpture.

**Rhetorical Schools.** - The 'rhetorical' schools were a development of work in debate that had gradually grown up in the grammar schools. The earliest of these institutions at Rome were Greek, but by the first century B. C, there had arisen a number in which Latin was used. While they afforded a legal and forensic training, and seem more professional in spirit than the grammar schools, they were by no means narrow. The orator was for the Roman the typical man of culture and education, and he was supposed not only to have been trained in eloquence and law and history, but to possess wide learning, grace, culture, and knowledge of human emotions, sound judgment, and good memory. Besides a training in oratory, these schools furnished a linguistic and literary education of some breadth. They may be considered as belonging partly to the secondary and partly to the higher stage of education. The youths were exercised first in declamation on ethical and political subjects, which would bring in fine distinctions in Roman law and ethics, and later they were given practice in three types of speeches, - deliberative, judicial, and panegyric. Attention was given to all the various factors in making a successful oration: the matter, arrangement, style, memorizing, and delivery.

**Universities.** - When the young Roman had completed his course at a rhetorical school, he might, if he were ambitious, go to the university at Athens, Alexandria, or Rhodes for a higher training. Later, a university also sprang up at Rome, and before long these institutions spread throughout the empire. The Greek influence caused a large number of these institutions to be established in the East, but some were also located in the West. The latter gave more emphasis to practical subjects. In several instances the universities found their nucleus in one of the many libraries that were started with books brought from the sacking of Greece and Asia Minor.

**Subsidization of Education.** - Thus, through the adoption of the institutions of the Greeks, Roman education became thoroughly Hellenized. Although all the types of schools spread everywhere in the empire, there was, of course, no such thing as a real school system, except as the government gradually came to subsidize all schools. This the different emperors accomplished in various ways, - by contributing to school support, paying a salary to certain teachers, or granting them exemption from taxation and military service, or offering scholarships to a given number of pupils. As a result, schools came to be established in many cases for the purpose of getting these special privileges for the teachers, rather than for promoting education. To stop these abuses, the emperor in 425 A. D. decreed that he had the sole authority to establish schools, and that a penalty would be laid upon anyone else assuming this prerogative. In this way the schools came fully into the hands of the imperial government, and the basis for the idea of public education was laid for the first time in history.

**Decay of Education.** - Before this, however, Roman education had deteriorated. With the political and moral decay that were obvious after the second century superficial A. D., it became a mere form and mark of the aristocracy. The training in oratory was continued, because it was a necessary qualification for entering the senatorial class, but it had lost its real function, since there was no longer any occasion for oratory when the emperor dominated all the government and law. It was not intended to furnish a training of any value in life, and the careful literary preparation was more and more shirked. While the grammarians and rhetoricians were still held in high esteem, they contented themselves with mere display, and wandered from town to town more for the purpose of entertaining than of teaching. Glittering phrases, epigrams, and other artificialities took the place of instruction and argument.

**Influence of Roman Education.** - But the Roman education and civilization had left their impress upon the world. This was accomplished by the practical nature of the Romans, and by their ability to make abstract ideals concrete and embody them in institutions that have been useful to civilization and progress. Through them was created the idea of a universal empire, which has been influential throughout the world's history. Similarly, the concept of law originating with the Greek philosophers became in the hands of the Romans the great system of principles that underlies and guides all our present civilization. And it was the Roman genius for organization that institutionalized a despised religious sect and expanded it into the position of the greatest world religion. If Judaism furnished the world with exalted religious ideals, and if from Hellenism came striking intellectual and aesthetic concepts, the institutions for realizing these ideals originated with Rome.

**Supplementary Reading**

Graves, *Before the Middle Ages* (Macmillan, 1909), chap. XIII; Monroe, *Text-book* (Macmillan, 1905), chap. IV. Interesting brief monographs on the subject are Clarke, G., *Education of Children at Rome* (Macmillan, 1896), and Wilkins, A. S., *Roman Education,* (Cambridge University Press, 1905). See also the treatment in Laurie, *Pre-Christian Education* (Longmans, Green, 1900), pp. 319436.