# 4. The Education of the Early Christians

**Outline**

-   Christianity accomplished much in the reform of the degraded Roman society. The earliest education of the Christians came through their 'otherworldly' life, but actual schools, called 'catechumenal,' before long furnished a moral and religious training.
-   After the amalgamation of Christianity with Grseco-Roman philosophy, 'catechetical' schools furnished a higher training. When higher education came to be utilized by the bishops for training their clergy, institutions known as 'episcopal' or 'cathedral' schools were founded.
-   Later, although opposition grew up among the Christians to the culture of Greece and Rome, its impress was found to have been left upon the doctrines and organization of Christianity.

**The Ideals of Early Christianity.** - The actual social conditions amid which the religion of Christ was born, and which it was destined to reform, were most degraded. The Roman world had become sunk in vice and corruption. The Roman virtues of patriotism, bravery, and service to the state had largely disappeared with the development of the empire, and were impotent in checking the widespread depravity. Nor could the lofty Greek thought accomplish much, since it was too intellectual and philosophic to touch the masses. The debased Eastern religions, which Rome had admitted in her easy-going skepticism, were still less productive of good. While the more philosophic forms of Judaism and the Roman development of Stoicism tended to raise the tone of morals and pave the way for Christianity, not even these forces could have accomplished a successful reform in Roman society, without the stimulus and wide appeal of the Christian teachings. Christianity was the ethical and universal religion needed as a leaven. Its truths were based on faith rather than understanding, and its appeal was to the instinctive promptings and emotions rather than to the intellect. This made it democratic and enabled it to reach the masses, for everybody can feel and have faith, even where he cannot understand.

**Early Christian Life as an Education.** - Thus it came about that, while the earliest Christians were without schools of their own and were largely illiterate, their religion itself served as an education. They were practically deprived of intellectual development, but they received moral training of a very high order. The very dishonor and unpopularity of the Christian religion, and the segregation of their Church membership, gave the Christian life itself all the effect of a species of schooling. The early Christians showed an extreme reaction to the vicious morals of the time, and endeavored to cultivate the higher ideals inculcated by the teachings of Christ. They had gathered from the statements of the Master that he would soon return and this world would come to an end. They, therefore, concerned themselves entirely with a preparation for 'Jerusalem the golden' and 'the life everlasting,' and the ideal of this most primitive Christian training may be described as 'other-worldly.'

**Catechumenal Schools.** - Early in the second century, however, when the Church began to extend itself rapidly, it seemed necessary to insist upon some sort of formal instruction as preliminary to Church membership. It was also deemed wise to fix a period of probation after the profession of one's faith in Christ, in order that informers might not be admitted to the services, or the Church disgraced by apostasy or the lapses of those who had not well considered the step. These demands were met by the gradual institution of popular instruction in Christian principles for the Jewish and pagan proselytes, who were known as *catechumens.* While some effort was made to lift the pupils of these 'catechumenal' schools from the bondage of ignorance, they were primarily trained in the things needful for their souls' salvation, and the ideal of Christian education remained prevailingly 'otherworldly.' The instruction was carried on in the portico or other special portion of the church; and consisted in moral and religious teachings, reading and memorizing the Scriptures, together with some training in early psalmody. The course usually lasted three years, and while some distinction was made between the general division of catechumens and those almost ready for baptism, there is little ground for supposing that the schools were divided into actual classes. The meetings in the church were held several times a week, or even every day.

**Amalgamation of Christianity with Graeco-Roman Philosophy.** - But while the Christian ideals and training were developing and crystallizing, the Greek philosophy in its Roman form was being continued and expanded. This movement has been seen to be very different from early Christianity in its general purpose. It concerned itself chiefly with life in this world. The problem it attempted to solve was how one should live so as to get the most satisfaction out of life. The Hellenized Roman schools may, therefore, be accounted as 'worldly' as the Christian schools were 'otherworldly' in their aim. A general feeling of this marked difference in purpose and organization between Christianity and the contemporaneous Graeco-Roman culture was destined to cause an opposition to pagan learning to spring up among the Christians. But for two or three centuries this is scarcely noticeable, especially in the Eastern empire, where it was felt that philosophy was, like Christianity, a search after truth; and, as far as it went, confirmed the Bible. There was even a tendency to unite the two movements. As the new religion spread throughout the Roman world, and was compelled to defend itself against charges of immorality, atheism, and treason, the educated converts attempted to set forth the Christian teachings in terms of Greek thought, and to solve speculative problems that had never been considered by Jesus and his disciples. The first Hellenizing Christians are known as *Apologists,* since their efforts were directed toward reconciling Christianity with the Graeco-Roman philosophy. In general, they mingled Stoicism with the teachings of Jesus. Later, other Hellenistic philosophers unified Christian doctrine with the principles of Pythagoras, Plato, and Aristotle. Perhaps the most extreme of these philosophic positions within Christianity was a combination with Platonism known as *Gnosticism,* which was intended to be a sort of esoteric knowledge and to show the relation of Christianity to other religions and to the universe.

**Catechetical and Episcopal or Cathedral Schools.** - In this way, during the second and third centuries, all the Christians at Alexandria, which had become the great seat of Hellenistic philosophy, had their theology tinctured with Greek thought. Before long, a sort of theological, or 'catechetical' school, was gradually organized at this center, to counteract the heathen schools there and to afford higher instruction for Christian teachers and leaders. This school had no building of its own, and the students met at the teacher's house, but they were able to take advantage 01 the facilities at the University of Alexandria. In addition to a thorough training in the Bible, the pupils were allowed to study all types of Greek philosophy, except Epicureanism, the whole range of sciences, classical Greek literature, grammar, rhetoric, and other higher subjects of the pagan schools, but from a different point of view. Thus the Graeco-Roman and the Christian movements had formed an alliance in education, and in this catechetical school we find an attempted union of the 'otherworldly' ideal with the 'worldly.'

The best known heads of this school at Alexandria were Clement (150-215) and Origen (185-253). They were among the most noted of the Eastern Fathers in the philosophic interpretation of Christianity, and their work contributed not a little to heretical doctrine. Origen may even have been expelled for heresy. At any rate, he opened a new school of the same sort at Caesarea, where he was kindly received. Other catechetical schools sprang up rapidly at Antioch, Edessa, Nisibis, and elsewhere throughout the East. Later the accession of the followers of Nestorius, whose Hellenized theology had in 431 been proscribed by the Church at the Council of Ephesus, very greatly increased the importance of these cities as intellectual centers. In addition to the translations already there, the Nestorian Christians accumulated a larger range of the original Greek treatises on philosophy, science, and medicine.

But before this, higher training of the Hellenic type came to be regularly used by the bishops in training their clergy, and promotion in the Church began to depend upon having had this education. So higher schools of this sort were gradually instituted in every bishopric at the see city, and became known eventually as 'episcopal' or 'bishop's' schools, or, from their location at the bishop's church, as 'cathedral' schools. These cathedral schools became the most important educational institutions of the Middle Ages. From them were derived all the schools of Western Europe, but the bishop soon became too busy to attend to them himself and was forced to commit them to various officials. Thus they developed in time into at least three types, - the 'grammar' school, taught by one of the cathedral canons, known as the *scholasticus;* the 'song' or music school, taught by the *cantor* or *precentor;* and the 'chorister's' school, which offered a combination of the training in the two other schools. Thus the cathedral schools virtually took the place of the old pagan schools supported by the Roman emperors.

**Influence of Graeco-Roman Culture upon Christianity.** - However, by the century after the foundation of the catechetical school at Alexandria, the Christians had begun to grow suspicious of Graeco-Roman culture and the 'worldly' ideal in education. Even the Eastern or Greek Fathers of the Church appear to have cooled considerably in their attitude toward philosophy, and the Western or Latin Fathers were more pronounced in their opposition. Roman Christians could not forget the immorality of those who had been connected with this culture, nor the abuse and insults that these pagans had heaped upon them. They felt, too, that the one great mission of the Church was ethical, and that Christ's second coming was at hand, and that all philosophy and learning were somewhat impertinent.

Nevertheless, despite this growth of opposition to pagan philosophy, primitive Christianity could not endure in its simplicity after it had been in contact with the advanced intellectual concepts of the Greeks, as modified by the organizing genius of the Romans. Both Greece and Rome left a permanent impress upon Christianity; and, though dead, they yet live in the Christian Church. The influence of Greek philosophy is seen in the formulation of a system of Christian doctrine. This appears in the development of the *Aposiles' Creed* during the second century, in the selection of a canon of sacred writings or *New Testament* during the third century, and still more in the *Nicene Creed* (325), which was not formulated until Christianity had been largely Hellenized. Similarly, the Greek tendency to attribute universal validity to their sacred writings, and the pomp, ceremonies, and mysteries of the Hellenic worship, are more or less apparent in the various ecclesiastical tenets and usages. On the other hand, the Roman concepts of administration appear in the organization of the Church, which seems to have closely paralleled the Roman civil polity. By the third century priests and bishops had largely come to be similarly located, and to correspond in control, to the Roman district and city magistrates respectively. And in 445 the recognition of the supremacy of the Bishop of Rome established a visible head of the entire Church, corresponding to the position of the emperor on the civic side.

**Rise of the Monastic Schools.** - Thus it has been seen how the two great movements of Graeco-Roman culture and Christian teaching arose independently, in time united and later separated, although, after separation, the Christian doctrines were somewhat affected by their long association with pagan philosophy. Eventually the pagan schools were suppressed by the edict of Justinian in 529 A. D., and the Christian education was left alone in the field. It then found an additional means of expression in the 'monastic' schools, in which there was naturally a tendency to revert to an ascetic or 'otherworldly' ideal, and to leave intellectual attainments largely out of consideration. But these monastic institutions are to be grouped with mediaevalism and belong more distinctly to the next chapter.

**Supplementary Reading**

Graves, *Before the Middle Ages* (Macmillan, 1909), chap. XII; Monroe, *Text-book* (Macmillan, 1905), pp. 221-243. For the moral effect of Christianity, see Lecky, W. E. H., *History of European Morals* (Appleton, 1869), vol. II, pp. 1-100. Other places in the chapter will be illumined by reading Ayer, J. C, Jr., *Catechutnenal Schools* and *Catechetical Schools* (Monroe Cyclopaedia of Education, vol. I); Dill, D., *Roman Society in the Last Century of the Western Empire* (Macmillan, 1899), especially book V; Hatch, E., *The Influence of Greek Ideas and Usages upon the Christian Church* (Hibbert Lectures, 1888, Williams, London, 1891); Hodgson, G., *Primitive Christian Education* (Clark, Edinburgh, 1906); and Leach, A. F., *Bishop's Schools* and *Cathedral Schools* (Monroe Cyclopaedia of Education, vol. I).