# 5. The Monastic Education

**Outline**

-   During the Middle Ages the German hordes absorbed ancient civilization under the authoritative guidance of the Church, and the chief means of leavening the barbarian lump was found in the cathedral and monastic schools.
-   Monasteries grew up to counteract the prevailing worldliness. To keep the monks busy, Benedict prescribed the copying of manuscripts, and this literary work rendered schools necessary. In these monastic schools were taught the 'seven liberal arts' by catechetical methods.
-   Thus monasticism helped preserve learning and education, although it was somewhat hostile to the classics and science.

**The Middle Ages as a Period of Assimilation and Repression.** - The Middle Ages may be regarded as an era of assimilation and of repression. On the one hand, the rude German hordes, who had by the sixth century everywhere taken possession of the decadent ancient world, were enabled during this period to rise gradually to such a plane of intelligence and achievement that they could absorb the Greek, Roman, and Christian civilization, and become its carriers to modern times. On the other hand, that this absorption might take place, it was necessary that the individual should conform to the model set, and it was inevitable that a bondage to authority, convention, and institutions should ensue.

The main power in effecting this subservience on the part of mediaeval society was the Christian Church. For it was but natural during the period of assimilation that the Church, which had become completely organized and unlimited in power, should stand as the chief guide and schoolmaster of the Germanic hosts. By the decree of Justinian in 529 A. D., which closed the pagan schools and marks the beginning of the Middle Ages, Christian education was left without a rival. Hence the cathedral and monastic schools became almost the sole means of leavening the barbarian lump. Contrary to the view commonly accepted, the educational activities of the cathedral institutions were more important and general than those of the monastic schools. But the former have already been somewhat discussed, and so much relating to the course and services of the latter will also apply to them that we may now turn to a detailed description of the monastic schools.

**The Evolution and Nature of Monasticism.** - To understand these schools, it will be necessary to examine the movement out of which they arose. Monasticism grew up through the corruption in Roman society and the desire of those within the Church for a deeper reUgious life. Christianity was no longer confined to small extra-social groups meeting secretly, but was represented in all walks of society, and mingled with the world. It had become thoroughly secularized, and even the clergy had in many instances yielded to the prevailing worldliness and vice.

Under these circumstances there were Christians who felt that the only hope for salvation rested in fleeing from the world and its temptations and taking refuge in an isolated life of asceticism and devotion. This led eventually to the foundation of monasteries, in which the monks lived apart in separate cells, but met for meals, prayers, communion, and counsel. Monasticism started in Egypt, but soon spread into Syria and Palestine, and then into Greece, Italy, and Gaul. But in the West monasticism gradually adopted more active pursuits and milder discipline, and the monks turned to the cultivation of the soil and the preservation of literature.

**Benedict's 'Rule' and the Multiplication of Manuscripts.** - These monastic activities were especially crystallized and promoted by the Benedictine 'rule.' This was a code formulated by St. Benedict in 529 for his monastery at Monte Cassino in Southwest Italy, and it was generally adopted by the monasteries of Western Europe. In the forty-eighth chapter of the 'rule' he commanded that the monks each day engage in manual labor for at least seven hours and in systematic reading for at least two hours. The requirement of daily reading led to the collection and reproduction of manuscripts, and each monastery soon had a *scriptorium,* or 'writingroom,' in one end of the building (Fig. 7). Most of the works copied were of a religious nature and were limited in number, but the monks were occasionally occupied with the Latin classics, and they also became the authors of some original literature, which included histories of the Church, the monasteries, and the times, as well as works upon religious topics.

**Amalgamation of Roman and Irish Christianity.** - This preservation of learning and development of literature was especially apparent in the monasteries of England. It came about through the amalgamation at the Council of Whitby, in 664, of the Roman Church in England, with Irish Christianity, which had preserved an unusually high order of learning after its isolation. An immense enthusiasm for the Church, culture, and literature of Rome resulted from this merging of the rival organizations, and the English monasteries, such as Jarrow and Wearmouth, and cathedral schools, like York, became the great educational centers for Europe.

**The Organization of the Monastic Schools.** - The literary work of the monasteries soon led to the establishment of regular schools within their walls (Fig. 8). The course in these monastic schools may often have lasted eight or ten years, as boys of ten or even less were sometimes received, and no one could become a regular member of the order before he was eighteen. By the ninth century the schools sometimes also admitted pupils who never expected to enter the order. These latter were called *externi* in distinction to the *oblati,* who were preparing to become monks. Some training was also given women in convents for nuns, such as that established by the sister of Benedict.

**The 'Seven Liberal Arts' as the Curriculum.** - The curriculum of the monastic schools was at first elementary and narrow. It included only reading, in order to study the Bible; writing, to copy the sacred books; and calculation, for the sake of computing Church festivals. But after a while the classical learning was gradually introduced in that dry and condensed form of the 'seven liberal arts', which was also used by the cathedral schools. This mediaeval canon of studies was a gradual evolution from Graeco-Roman days. The discrimination of these liberal subjects may be said to have begun with Plato, whose educational scheme included a higher group of studies, consisting of arithmetic, geometry, music, and astronomy; and during the later days of Greece and Rome these 'liberal' subjects of Plato were combined with the 'practical' studies of the sophists, - grammar, rhetoric, and dialectic. These 'seven liberal arts' were definitely fixed during the fifth and sixth centuries A. D., through several treatises by such writers as Martianus, Capella, Boethius, and Cassiodorus; and the grammar, rhetoric, and dialectic eventually became classed as the *trivium* or lower studies, and the arithmetic, geometry, music, and astronomy as the *quadrivium* or higher (Fig. 9). While this curriculum was not a broad one, the scope was much wider than would be supposed. 'Grammar' was an introduction to literature, 'rhetoric' included some knowledge of law and history, 'dialectic' paved the way for metaphysics, 'arithmetic' extended beyond mere calculation, 'geometry' embraced geography and surveying, 'music' covered a broad course in theory, and 'astronomy' comprehended some physics and advanced mathematics.

**The Methods and Texts.** - The general method of teaching in the monastic schools was that of question and answer. As copies of the various books were scarce, the instructor often resorted to dictation, explaining the meaning as he read, and the pupils took the passage down upon tablets and committed it. The reading books preparatory to the study of literature, many of which are still extant, were generally arranged by each teacher, and careful attention was given to the etymological and literary study of the authors to be read. As to texts, the leading works upon grammar were at first the elementary work of Donatus (fourth century) and the more advanced treatise of Priscian (sixth century), but by the thirteenth century there had sprung up a series of simplified grammars, which, for the sake of memorizing, were often written in verse. As rhetoric was no longer much concerned with declamation, Cicero and Quintilian were rarely used as texts, but various mediaeval treatises upon official letters, legal documents, and forms came into use. Dialectic was studied through translations of the *Organon* of Aristotle, Euclid furnished the text on geometry, the works of Boethius were generally used for arithmetic and music, and in astronomy adaptations of the treatises of Aristotle and Ptolemy became the texts.

**Effect upon Civilization of the Monastic Schools.** - Thus monasticism accomplished not a little for civilization. While the works produced in the monasteries were uncritical and superstitious, they compose most of our historical documents and sources in the Middle Ages. And, although monastic schools were decidedly hostile to classical literature as representing the temptations of the world, and at all times their rigid orthodoxy prevented every possibility of science and the development of individualism, they, together with the cathedral schools, preserved a considerable amount of GrascoRoman culture. Without the cathedral and monastic schools, the Latin and Greek manuscripts and learning could scarcely have survived and have been available at the Renaissance.

**Supplementary Reading**

Graves, *History of Education during the Middle Ages and the Transition to Modern Times* (Macmillan, 1910), chaps. I-II; Monroe, *Text-book* (Macmillan, 1905), pp. 243-274. For the evolution of the ascetic life, see Lecky, *History of European Morals* (Appleton, 1869), vol. II, pp. 101-274; for the development of monasticism, Taylor, H. O., *The Classical Heritage of the Middle Ages* (Macmillan, 1913), chap. VII, and Wishart, A. W.j *A Short History of Monks and Monasticism* (Brandt, Trenton, 1902). The contribution of Irish monasticism is shown in Healy, J., *Insula Sanctorum et Doctorum* (Sealy, Dublin, 1897), and Zimmer, H., *The Irish Element in Mediaval Culture* (Putnam, 1891). Succinct articles on *Abbey Schools, Bishop's Schools, Church Schools,* and *Cloister Schools* by Leach, A. F. (Monroe Cyclopaedia of Education, vols. I and II), furnish the most accurate ideas of monastic education as far as it is known. An account of the monastic libraries is given in Clark, J. W., *Libraries in the Mediaeval and Renaissance Monasteries* (Macmillan and Bowes, Cambridge, 1894), and Putnam, G. H., *Books and Their Makers during the Middle Ages* (Putnam, 1896). The best account of *The Seven Liberal Arts* in English is that by Abelson, P. (Columbia University, Teachers College Contributions, No. n, 1906).