# 6. Charlemagne's Revival of Education

**Outline**

-   Learning and schools had by the eighth century been sadly disrupted, and, to restore them, Charlemagne invited Alcuin of York to become his adviser in education. Alcuin induced Charlemagne to conduct higher education at the Palace School, and to improve the cathedral, monastic, and parish schools.
-   Even after Alcuin retired from the active direction of education, he continued his educational influence, but he became set and narrow. A broader spirit, however, appeared in his pupils, and intellectual stagnation never again prevailed.

**Condition of Education in the Eighth Century.** - In the course of the seventh and eighth centuries mediaeval education met with considerable retrogression. The learning of the sixth century was disappearing, the copying of manuscripts had almost ceased, and the cathedral and monastic schools had been sadly disrupted. The secular clergy, monks, nobility, and others who might have been expected to be trained, at times seem even to have lost the art of writing, although the leading churchmen must generally have maintained their knowledge of ecclesiastical Latin and some acquaintance with the classical authors and various compilations of the seven liberal arts. Just before this time the Franks had succeeded in establishing a supremacy over the other barbarian tribes and had spread their rule through what is now France, Belgium, and Holland, and most of Western Germany. Under a dynasty of vigorous kings, they now drove back the Moslems, conquered the Lombards and Saxons, and subdued the Slavs and Bohemians, and finally Charlemagne (742-814) even planned to reestablish the Western Roman Empire under his sovereignty. This monarch greatly strengthened and centralized his dominions by a number of improvements in external administration, but, even before his recognition as emperor by the pope (800), he had realized that a genuine unity of his people could be brought about only through a much more effective and universal education. He had a keen sense of the unfortunate educational situation, and made every effort to improve-it. To assist him in his endeavors, in 782 he called Alcuin (735-804) from the headship of the famous cathedral school at York (see p. 56) to be his chief adviser in education.

**Higher Education at the Palace School.** - Through this noted scholar Charlemagne proceeded to revive the cathedral, monastic, and parish schools, and to increase the importance of the 'Palace School.' At this latter school the great king, all his family, and many of his relatives and intellectual friends studied under the Saxon educator. Alcuin must, however, have used a more discursive and less *memoriter* method with his adult students than the formal catechetical plan employed in instructing the youth. Among the subjects taught were grammar, including some study of the Latin poets and the writings of the Church Fathers, rhetoric, dialectic, arithmetic, astronomy, and theology, but Alcuin appears to have had but little command of the Greek learning. Charlemagne himself seems to have become proficient in Latin and other languages, but, in spite of strenuous efforts, he began too late in life to train his hand to write.

**Educational Improvement in the Cathedral, Monastic, and Parish Schools.** - With the cooperation of Alcuin, Charlemagne also did everything in his power to increase facilities and improve standards in the existing types of schools. In 787 he issued an educational 'capitulary' or decree to the bishops and abbots, urging diligence in the pursuit of learning and the selection of teachers for this work who are able, willing, and zealous to learn themselves and to teach others." Two years later he wrote a more urgent capitulary to the bishops and abbots, in which he specified the subjects to be taught in the cathedral and monastic schools and the care to be taken in teaching them. Schools seem to have been everywhere established or revived in the various cathedrals, monasteries, and villages, and the instruction in several places became famous. All these schools came to offer at least a complete elementary course, and some added considerable work in higher education. Reading, writing, computation, singing, and the Scriptures were taught first, but, beyond this, instruction in grammar, rhetoric and dialectic was often given, and at the more noted cathedral and monastic schools the *quadrivium* also appeared in the course. The schools in the villages, under the care of the parish priests, taught only the rudiments, the Lord's Prayer, the Creed, and the Psalms. Tuition was free in all schools for those intending to become monks or priests, but for the higher work a small fee was sometimes paid by the laity. It seems to have been generally intended that education should be gratuitous and open to all. A letter of the Bishop of Orleans required it of his clergy; and through a capitulary in 802 Charlemagne strove to make it compulsory.

**Alcuin's Educational Work at Tours.** - After fourteen years of strenuous service, Alcuin retired from the active headship of the educational system to the abbacy of the monastery at Tours. But even here his educational work did not cease. He soon established a model house of learning and education, whither flocked the most brilliant youths in the empire, and since they rapidly became prominent as teachers and churchmen, his influence upon the schools remained fully as marked as before. He also wrote a number of educational works, mostly on the seven liberal arts, and had a large correspondence about education with kings and the higher clergy. Alcuin, however, was by nature conservative, and with his retirement he became decidedly set and narrow. His fear of dialectic and the more advanced views of certain Irish scholars is almost ludicrous, and his repudiation of the classic poets, even his former favorite, Vergil, is pathetic.

**Rabanus Maurus, Erigena, and Others Concerned in the Revival.** - Fortunately, Alcuin's pupils, who at his death occupied practically all positions of educational importance, retained his broader spirit. This was true in particular of Rabanus Maurus (776-856), whose leadership caused the monastic school at Fulda to become the great center of learning. Rabanus wrote even more prolifically than Alcuin upon grammar, language, and theol6gy, but was not afraid to emphasize the study of classic literature or the new training in dialectic. He also greatly expanded the mathematical subjects of the curriculum, and tended to ascribe all phenomena to natural laws. Rabanus, in his turn, influenced a large number of pupils, and a further impetus was given to the movement by a cross-fertilization of Irish learning, which was also introduced, especially through the mastership of Joannes Scotus Erigena (810-876) at the Palace School.

Thus during the ninth century and the first half of the tenth there arose, through the initiative of Charlemagne and Alcuin, a marked revival in education, and for several generations the cathedral and monastic schools enthusiastically fostered education and learning. Curricula were expanded, and many famous scholars appeared. While, owing to the weakness of Charlemagne's successors and the attacks of the Northmen, learning gradually faded once more, intellectual stagnation never again prevailed. Through the revival of the great Frankish monarch, classical learning had to some extent been recalled to continental Europe from its insular asylum in the extreme West.

**Supplementary Reading**

Graves, *During the Transition* (Macmillan, 1910), chap. III; Monroe, *Text-book* (Macmillan, 1905), pp. 274-279. Read also Gaskoin, C. J. C, *Alcuin, His Life and His Work* (Clay, London, 1904J, or West, A. F., *Alcuin and the Rise of Christian Schools* (Scribner, 1892), and Mullinger, J. B., *The Schools of Charles the Great* (Longmans, London, 1877).