# 7. Moslem Learning and Education

**Outline**

-   Moslemism amalgamated in Syria with Greek philosophy and science, and the Moslem cities there became renowned for their learning.
-   The masses of the Moslems were suspicious of the Greek learning, however, and those who had absorbed the Hellenized philosophy were driven from the Orient into Spain, where they founded Moorish colleges.
-   The Moslems thus stimulated learning in the Christian schools, and introduced Aristotle once more, but, after bringing learning back, Moslemism itself reverted to its primitive stage.

**The Hellenization of Moslemism.** - One of the most important influences in awakening mediaeval Europe was the revival of learning and education that came through the advent of the Moslems. Mohammed, the founder of Moslemism, had been almost illiterate, and the *Koran,* or sacred book, was a curious jumble of Judaistic, Christian, and other religious elements with which Mohammed had become acquainted during his early travels. As long as this religion was confined to the ignorant and unreflecting tribes of Arabia, it served its purpose without modification. But when it spread into Syria and came in contact with Greek philosophy, in order to appeal to the people there, it had to be interpreted in Hellenistic terms, and during the eighth, ninth, and tenth centuries, through the influence of the Nestorian scholars (see p. 46), the Mohammedans were engaged in rendering into Arabic from the Syriac, or from the original Greek, the works of the great philosophers, mathematicians, and physicians. The Mohammedan cities of Syria soon became renowned for their learning. In them arose such scholars as Avicenna (980-1037), who wrote many treatises on mathematics and philosophy, and a *Canon of Medicine* that remained authoritative for five centuries. Similarly, there grew up a society called the 'Brothers of Sincerity,' which in its course of study amalgamated the Moslem theology with Hellenistic philosophy.

**Hellenized Moslemism in Spain.** - But the masses of the Mohammedans were as suspicious of the Greek learning as the orthodox Christians had been, and toward the end of the eleventh century Hellenized Moslemism was driven from the Orient and found a refuge in Northern Africa and in Spain. Here the advanced Mohammedans became known as 'Moors,' and their works were destined to have a pronounced influence upon the Christians. There soon appeared such scholars as Averroes (1126-1198), who became the authoritative commentator on Aristotle for several centuries; and Moorish colleges were founded at Cordova, Granada, Toledo, and elsewhere. In these institutions, while learning was still at a low ebb in the Christian schools, were taught arithmetic, geometry, trigonometry, astronomy, physics, biology, medicine, surgery, jurisprudence, logic, and metaphysics. Arabic notation was also introduced in place of the cumbersome Roman numerals and many inventions and discoveries were made.

**Effect upon Europe of the Moslem Education.** - These schools and colleges of the Moslems soon had their effect upon Christian education. Through their influence, Raymund, Archbishop of Toledo, by the middle of the twelfth century had the chief Arabic treatises on philosophy translated into Castilian by a learned Jew, and then into Latin by the monks; and Frederick II had scholars render the works of Averroes into Latin. Such translations had, however, passed through several media - Greek, Syriac, Arabic, Castilian, Latin - and could not be at all accurate. But, stimulated by this taste of Greek learning, the Christians sought a more immediate version, and a half century later when the Venetians took the city of Constantinople, the works of Aristotle were recovered in the original and translated directly into Latin. Meanwhile the orthodox Mohammedanism had been coming to the front in Spain and overwhelming the Hellenized form, and it was left to Christian schools to continue the work of the advanced Moorish institutions. Moslemism had returned to its primitive stage, but it had helped bring back learning, especially the works of Aristotle, to Christendom. As the classical learning had been restored from the West during the revival of Charlemagne, it now returned from its refuge in the East through the coming of the Moslems.

**Supplementary Reading**

Graves, *During the Transition* (Macmillan, 1910), chap. V; Monroe, *Text-book* (Macmillan, 1905), pp. 331-334- For a further account of Saracen education, see Coppee, H., *History of the Conquest of Spain by the Arab-Moors* (Little, Brown, Boston, 1881), especially bk. X; Davidson, T., *The Brothers of Sincerity* (International Journal of Ethics, July, 1898), and Draper, J. W., *History of the Intellectual Development of Europe* (Harper, 1875), vol. I, chaps. XI and XIII, and vol. II, chaps. II and IV.