# Advantages of Jesuit Schools

We shall find in the former, the spirit of labor more prevalent, and more generally acquiesced in, as the only condition of success. To this, has the pupil been trained from his earliest studies. Tasks disagreeable, and alleviated by few attractions, have been imposed upon him, and he has been compelled to fulfill them. Dry and severe lessons have been the familiar duty of his school life. He has been taught that to know a thing he must learn it, and that in order to learn any thing, he must labor hard and long. The genius of the Romish system is austerity itself. The teachers have, each one in his turn, been subjected to the same process. They have been familiar with men of the highest attainments; they know that labor is the only condition on which eminent scholarship can be acquired, and that the earlier and the more effectually this question can be decided with the pupil, the better will it be for him. They are accustomed, also, to use compulsion, and to exact obedience. Law, — authority that is supreme, decisive, and merciless, — is the very spirit and life of their order. They have learned themselves to obey, and in so doing have learned to command. They know no condition of being, no possibility of life, except in prompt and unquestioning submission; they cannot but exact the same from their pupils.

In the Protestant school or college, it is not so easy to find, or to create the spirit of severe and iron industry. The prevailing notions of the labor required to become a scholar are lamentably inadequate and low. The practice so common in the family and the primary school, of making learning easy to the child, and of deferring till too late a period the severe tasking of the intellect, and the practice which is scarcely less pernicious, of enfeebling the intellect by diluted matter in the form of “books for children,” are all unfavorable to habits of severe intellectual effort. If such efforts are occasionally made, they are not patiently persevered in. They are fitful, self-exhausting, and convulsive. The student is in such eager haste to be in the field of active life, that he must rush rapidly from one study to another, and will only just begin in any, before he applies himself to some new enterprise. To this condition of things our best institutions must adapt themselves. Their students are imperfectly prepared, and much of the business appropriate to the lower school is transferred into the higher seminary or the college. Studies that belong to a later period are crowded upon the attention prematurely.

In respect also to discipline, the Protestant institution cannot maintain that severity of rule, and that rigid authority, to which the Romish system trains its youth and its men. There may be law, and the law may be strictly enacted and severely enforced, but the laws must be reasonable, and their reasonableness must be made apparent. They must justify themselves to the pupil and his guardians. The guardian and his pupil may be entirely incompetent to judge of such subjects, or they may be strongly inclined to judge wrongly. Hence there may be much friction when there is obedience, or an atmosphere of discontent may pervade the institution which will deprive the discipline of its best influences.

And yet on the other hand it is true, that when the student learns at last how much labor is required to attain to eminence, and gives himself to it of his own will, his self-imposed toil has an energy and a fire, which rarely attend those efforts which have been learned by the mechanical drilling of years. When, too, the spirit of order and obedience makes its abode in a Protestant college, it produces a harmony and a confidence which are of higher worth and beauty than any constrained service, however perfect and precise.

The standard of attainment in particular departments of knowledge, which in the Jesuit college is presented to the pupil, may be far higher than that which the Protestant teacher can furnish in his own person. The Jesuit comes from the colleges of Europe. He has been a student from his infancy under exacting and skillful teachers. Labor and obedience are the law of his life; nay, they are hallowed by his religious vows and the spirit of his order. He has been familiar with prodigies of learning from the first; and has been stimulated by an eager competition with them for some scholastic prize, or for fame in the wider world of letters. Such a standard in the person of a living teacher, or in a corps of teachers, is of the highest service to the pupil. The exact and abundant knowledge, the ready command of the powers, the reach of thought, the scholar's enthusiasm which such a teacher exhibits, are of all the means of inspiring to study, as well as of showing what knowledge is, the most effective.

With such standards of scholarship, the methods of instruction will naturally be rigorous and thorough. They are expected from men who themselves are scholars, and they will be endured from them. In the learned languages, especially in the Latin, the student will be instructed most thoroughly in its principles, and will be taught to write and converse in this language of the learned. In the mathematics and the natural sciences, he will be the master of what he professes to know, and in such a sense a master of his knowledge, that it will become a part of himself, and he cannot let it go if he will. In logic and grammar, in geography and history, he will be drilled to such a control of what he learns, that it shall be a possession for life.

In the modern languages, too, he will be taught by scholars who are the masters of the languages which they teach, and who understand the principles of language generally. The majority of the teachers in these institutions are themselves Europeans, to many of whom these languages are vernacular, and all of whom have mastered them in a way which to an American is a marvel and a mystery. The pupil, instead of his smattering in French or German, together with not a little contempt for his untaught and perhaps his charlatan teacher, will learn these languages as a scholar should, and make his study of them an aid to his general training.

The Jesuit teacher has another advantage, if indeed it be an advantage. He makes few experiments in teaching. His attention is not distracted by new devices to make the road to knowledge easier and shorter. He is not tempted to exchange one text-book for another. *His methods have been tested for generations* — his books are the work of the ablest men of his order. For his purposes in instruction, it is probable that little would be gained by any change; but whether there would or not, his attention is rarely directed to a change as possible. His entire energies are devoted to the single effort of making the most of the method and of the authors which are prescribed. These are for him and his pupils fixed and unchangeable. With a definite aim before them, and a prescribed course by which to reach it, the pupil and teacher both give themselves to their work with the utmost energy.

The Jesuit institutions are not limited in the *materiel* of instruction. Money, buildings, apparatus, and libraries are supplied in sufficient abundance. The teachers have no families for which to provide, and no inadequate salaries to eke out, by distracting and life-consuming services. As they are sure of a subsistence for life, and are masters of their own movements to but a limited extent, their business is simple, and that is, to labor with all their might in the study and the classroom. Ample and learned libraries are at their command. Costly and substantial edifices are located in the choicest situations, which are often attractive in their natural beauty, and rendered doubly attractive by art. To add to all this, the instruction is to a certain extent gratuitous, and it may be made so to any degree which plans of proselytism may render desirable.

Last of all, there is no ruinous competition nor degrading jealousies between the several institutions. Their interest is one. Their cause is one. The teachers and the institutions are not dependent on popular favor. They are not crowded and multiplied to the impoverishment of each other, and the degradation of sound learning. But they conspire together, each helping the other with its talent, its skill, and its discoveries. In their united relation to the same object, and in their harmonious co-operation, as they are watched by one eye and moved by one hand, they have in one another, strength and resources which no man can compute.

It is very possible that this view of Jesuit schools, of Jesuit teachers and their pupils, may seem to many too highly colored. There may be some of our readers who will think it poorly corresponds with what they personally know of Jesuit seminaries in this country. Of such we would ask, whether they have ever had personal acquaintance with a scholar trained by Jesuit teachers in Europe or in this country; and whether they have informed themselves with accuracy as to the kind of training which they give, and the rigor and thoroughness with which it is prosecuted. We speak with entire confidence when we assert, that there are colleges in this country, which for a certain kind of education in the classics, the mathematics, the natural sciences and logic, are unmatched by any Protestant institutions. Some of the pupils from these institutions, in respect to habits of iron industry, to a mastery over the knowledge which they possess, as well as in their polished and manly bearing, are unsurpassed, and perhaps unequalled, by any scholars from our best colleges. We have also the personal testimony of an accomplished scholar, who had himself been a pupil and a teacher in that Protestant institution in this country which is most thoroughly European; and who, after being acquainted with the course of instruction in some of the best Jesuit colleges, expressed in the strongest terms his delight and admiration at its superiority.[^23] Many reasons might be given why some of these schools and pupils present an appearance of neglect and vulgarity, and why the number of accomplished scholars which they have produced has been so small.

We do not contend, however, that Jesuit teachers insist on giving to all their scholars an equally thorough education, or that they are not ready to gratify those patrons who may desire for their children a superficial culture. They are so flexible in their disposition, and so politic in all their arrangements, that while they can furnish erudite and rigid teachers for those who wish to be scholars, they can furnish to those who are to be trained for fashion and society, the *petit-maitre* who will teach them little more than fashionable French with music and dancing. If scholars are to be formed, the Jesuits will not be outdone in the appliances which are required. If men of fashion, they will furnish the most elegant and fashionable masters. They know well, also, how to study the tone of society about them; and as, from the first, all that relates to the accomplishments and lighter graces of learning has been embraced within their plan, they will seek to adjust their seminaries to the demands of the community which they seek to draw within their influence.

While we concede to the Jesuits all those points of superiority which they can claim with any show of reason, we assert, on the other hand, that there are important features in which Protestant institutions cannot but surpass them.

[^23]: One cause of the ready impressions which are adopted, to the disadvantage of the Jesuit schools, is the scholastic spirit in which their instructions are given, and the scholastic aspect of many of their text-books. It is readily concluded that their highest aim must be to train accomplished schoolmen, and to sharpen the mind to the arts and resources of a useless logic. It is argued at once, that such ghosts of a past age are not at all to be feared, and that they need only to stalk forth from the cloister, to try their refinements upon our enlightened scholars, to be driven back to their hiding-places with derision. It is forgotten that these studies, which in their first aspect are so unattractive, are yet the most effective discipline that the world has ever seen, to precision of language and precision of thought; and that, other things being equal, the men who have learned to excel in precision of language and precision of thought, have been the men who have ruled the world. The Jesuit understands this advantage — he has often proved its efficiency. He strives to find amends in this superiority for the falsehood of his statements, and the monstrous assumptions of his first principles. It is true at times, that he strives in vain; these falsehoods in principle and falsehoods of fact will roll back and crush, as with a mountain weight, the most nicely adjusted enginery of his logic, and break in pieces all the well-placed securities of definition and of sophistry. But there are times when it is not so; when the worse is made to appear the better reason, as the practiced fencer will overmaster an antagonist who in strength is far his superior. These occasions will be more frequent, if the Jesuit is left alone to his uncouth logic, and the Protestant teacher inflates his pupil with a shallow contempt for the scholasticism which he does not understand. Let a so-called practical education be the watch-word in our seminaries, and the principle of demand and supply shape and regulate the studies of our schools, and we may find, sooner than we anticipate, that there will be a “demand” in the service of the Truth for a kind of men whom we may seek in vain to “supply.”
