# 8. Educational Tendencies of Scholasticism

**Outline**

-   Scholasticism was a peculiar method of philosophic speculation in the later mediaeval period. At first, scholastic philosophers held that faith must precede reason, but eventually reason itself tended to become the means of testing the truth.
-   Scholastic education was organized in the monastic and episcopal schools, and consisted in the limited learning of the times, systematized on the basis of Aristotelian deduction. Scholasticism was extreme in its discussions, but it tended to rationalize the Church doctrines.

**The Nature of Scholasticism.** - One of the movements that most tended to awaken the mediaeval mind, especially during the latter part of the Middle Ages, was the development of the Church philosophy known as 'scholasticism.' This movement does not indicate any one set of doctrines, but is rather a general designation for the peculiar methods and tendencies of philosophic speculation that became prominent within the Church in the eleventh century, came to their height during the twelfth and thirteenth, and declined rapidly the following century. The name is derived from *doctor scholasticus,* which was the title given during the mediaeval period to the authorized teachers in a monastic or episcopal school, for it was among these 'schoolmen' that the movement started and developed. Its most striking characteristics are the narrowness of its field and the thoroughness with which it was worked.

**The History of Scholastic Development.** - The history of scholasticism belongs properly to the field of philosophy, but its influence in bringing on the Renaissance and its effect upon education make a brief consideration of its development necessary here. It began as an effort to vanquish heresy in the interest of the Church dogmas, which until late in the Middle Ages it had not generally been necessary to explain. Even then it was assumed that the Church was in possession of all final truth, which had come to it by Divine revelation, and was in harmony with reason, when fully understood. It was, therefore, the aim of the earlier schoolmen to show how these doctrines were consistent with each other and in accordance with reason. At first, as with Anselm (1033-1109), it was held that faith must precede reason, and where reason was incapable of penetrating the mysteries of revealed doctrine, it must desist from its efforts. But the conviction gradually gained ground that human reason is reliable and that truth can be reached only through investigation. Abelard (1079-1142) declared that the only justification of a doctrine is its reasonableness, that reason must precede faith, and that it is not sinful to doubt.

A new epoch for scholasticism dawned in the twelfth and thirteenth centuries through contact with the Greek philosophy of the Moors in Spain and the subsequent recovery of some original treatises of Aristotle (see p. 67). For a time the Church endeavored to suppress the great philosopher, but, failing to do so, soon utilized his works for its own defense, and even made reason identical with Aristotle, whose authority was not to be disputed. A group of most prominent schoolmen arose, and, as a result of the discussions of Aquinas (1225-1274), Duns Scotus (1274-1308), and William of Occam (1280-1347), it came to be held that truth is established by the *fiat* of God, and that ecclesiastical dogmas are, consequently, not matters of reason, but purely of faith. As a result of this breach between revelation and reason, there arose two types of truth, and a tendency to choose that type which was supported by reason.

**Scholastic Education.** - The schoolmen were thus throughout attempting to rationalize the teachings of the Church, and to present them in scientific form. As an education, scholasticism aimed also at furnishing a training in dialectic and intellectual discipline that should make the student both keen and learned in the knowledge of the times. The scholastic course of study, which was given at first in the monastic and episcopal schools and later in the universities, consisted in the beliefs of the Church and the limited learning of the times arranged in a systematized form largely on the deductive basis of the Aristotelian logic. This knowledge could all be grouped under the head of philosophical theology. The best illustration of the formal and dogmatic way in which these doctrines were usually presented can be found in the *Sententia* of Peter the Lombard (1100-1160) and the *Summa Theologim* of Aquinas (1225-1274), which were the standard texts of the day upon theology. The work of Aquinas has four main parts, under each of which is grouped a number of problems. Every problem is concerned with some fundamental doctrine, and is further divided into several subtopics. After the problem has been stated, first the arguments and authorities for the various solutions other than the orthodox one are given and refuted in regular order, then the proper solution with its arguments is set forth, and finally, the different objections to it are answered in a similarly systematic way. Peter the Lombard's work has a like arrangement.

**Its Value and Influence.** - As a whole, the work of scholastic education has been underestimated. It has been urged that it ruined all spiritual realities by its extreme systemization of religion, that it dealt with mere abstractions, and that it indulged in over-subtle distinctions and verbal quibbles. But the scholastic arguments were not as purposeless or absurd as they seem. For example, the celebrated inquiry of Aquinas as to the number of angels that could stand on the point of a needle is simply an attempt to present the nature of the Infinite in concrete form. It is the characteristic of reasoning beings to analyze, compare, abstract, and classify, and while scholasticism may have carried its abstractions, hairsplittings, and scientific terminology to an extreme, it performed a great service for knowledge. It found a confused mass of traditional and irrational doctrines and practices, made them systematic, rational, and scientific, and greatly assisted accuracy in thinking. The discussions of the schoolmen resulted in liberating philosophy from theology, and, without intending it perhaps, scholastic education aided the cause of human reason against dogmatism and absolute authority. It greatly stimulated intellectual interests, produced the most acute and subtle minds of the age, and helped to prepare the way for the Renaissance.

**Supplementary Reading**

Graves, *During the Transition* (Macmillan, 1910), chap. VI; Monroe, *Text-book* (Macmillan, 1905), pp. 292-313. For a good account of all *The Great Schoolmen of the Middle Ages* (Hodder, London, 1881), see the work of Townsend, W. J.; for the beginnings of scholasticism, Mullinger, J. B., *The University of Cambridge* (Longmans, Green, 1888), vol. I, pp. 47-64; for the life and influence of Abelard, Compayr6, G., *Abelard* (Scribner, 1893), chap. I; McCabe, J., *Abelard* (Putnam, 1901); and Rashdall, H., *The Universities of Europe in the Middle Ages* (Oxford, Clarendon Press, 1895), vol. I, chap. 11.