# 9. The Mediaeval Universities

**Outline**

-   Universities began to spring up toward the close of the Middle Ages. Through local conditions, a course in medicine arose at Salerno; in civil and canon law at Bologna; and in theology at Paris. Bologna became the pattern for numerous universities in the South; and Paris for many in the North.
-   Popes and sovereigns granted privileges by charter to the various universities. The term 'university' originally signified a 'corporation' of students and teachers, and the students were usually grouped according to 'nations.' The teaching body was divided into four or five 'faculties.'
-   The course in arts included the seven liberal arts and portions of Aristotle; in civil and canon law, the *Corpus Juris Civilis* of Justinian and the *Decree* of Gratian respectively; in medicine, the treatises of Greek and other medical writers; and in theology, mostly the *Sententice* of Peter the Lombard. The texts were read and explained by the lecturers, and a practical training in debate was furnished.
-   While the courses and methods were narrow and formal, the mediaeval university contained the germ of modern inquiry and did much to foster independence of thought and action.

**The Rise of Universities.** - A most important effect upon subsequent education came through the foundation of the mediaeval universities. These institutions grew out of the old cathedral and monastic schools, but found their models largely in the liberal and professional courses of the Moorish colleges. In general, they came into existence through the many broadening influences of the later Middle Ages. Their rise was intimately connected with the stimulus of the Moslem presentation of Greek philosophy and science, with the interest in dialectic and theological discussions, which led to the development of scholasticism, with the reaction from 'otherworldliness' resulting from the ideals of chiv- alry, and with the growth of cities and wealth, and the consequent emphasis upon secular interests and knowl- edge (see chap. xi). However, while they were all more or less the product of the same factors, no two sprang from exactly the same set of causes, and special conditions played a part in the evolution of each university.

**The Foundation of Universities at Salerno, Bologna, and Paris.** - The oldest of these institutions, that at Salerno, near Naples, was simply a school of medicine, and originated through the survival of the old Greek medical works in Southwestern Italy, and through the attraction of the mineral springs and salubrity of this particular place. By the middle of the eleventh century Salerno was well known as the leading place for medical study. It was, however, never chartered as a regular university, although in 1231 Frederick II recognized it as the school of medicine for the university he had created at Naples some seven years earlier.

On the other hand, Northern Italy became known as a center for the study of Roman law. The cities here, in order to defend their independence, were led to study this subject, and endeavored to find some special charter, grant, or edict from the old Roman emperors upon which to base their claims. Several northern centers were renowned for their investigation of the Roman civil law, but early in the twelfth century Bologna became preeminent through the lectures of Irnerius. By him the entire *Corpus Juris Chilis,* a compilation of Roman law made by eminent jurists in the sixth century at the command of the emperor Justinian, was collected and critically discussed. Influenced by this example, a monk of Bologna, named Gratian, undertook to codify all edicts and formulations of popes and councils in a convenient text-book. The *Decree* of Gratian, which resulted, was almost immediately recognized as the authority upon the subject, and canon law came to be studied here with the same thoroughness as civil law. The university at Bologna was regularly chartered by Frederick Barbarossa in 1158, probably as a recognition of the services of its masters in support of his imperial claims, and faculties of arts, medicine, and theology were established at various times. It was thus the first real university, and its reputation soon became widespread.

Next in order of foundation came the university at Paris, which was by far the most famous of all. The special interest here, as in this part of Europe generally, was dialectic and scholasticism. The university grew out of the cathedral school at Notre Dame, which had acquired considerable reputation under the headship of William of Champeaux, Abelard, and Peter the Lombard, but it was not until 1200, after canon law and medicine had been added to the liberal arts and theology, that it received complete recognition by the charter of Philip Augustus.

**Bologna and Paris as the Models for Other Universities.** - Salerno, as we have seen, was not a real university, and it did not reproduce its type; but Bologna, and even more Paris, became the mother of universities, for many other institutions were organized after their general plans. At Bologna the students, who were usually ma- ture men, had entire charge of the government of the university. They selected the masters and determined the fees, length of term, and time of beginning. But in Paris, where the students were younger, the government was in the hands of the masters. Consequently, new foundations in the North, where Paris was the type, usually became 'master-universities,' while those of the South were 'student-universities.' During the thirteenth and fourteenth centuries it became fashionable for universities' the authorities, civil and ecclesiastical, to charter existing organizations or to found new institutions on one of these two plans, and by the time the Renaissance was well started about eighty universities had been established in Europe. Not all of these foundations were permanent, however, for some thirty have, in the course of time, become extinct, and those which remain are much changed in character.

**Privileges Granted to the Universities.** - From the time of the earliest official recognition of the universities, a large variety of exemptions, immunities, and other special privileges were conferred upon the organizations or upon their masters and students, by the charters of popes, emperors, kings, and municipalities. The students of the universities were in many instances taken under the immediate protection of the sovereign, and were allowed to be tried in special courts of their own, independent of civil jurisdiction, and to possess complete autonomy in all their internal affairs. Generally masters, students, and their retainers alike were relieved from all taxation and from military service. Likewise, universities were granted the right to license masters to lecture anywhere without further examination *(jus ubique docendi),* and the privilege of 'striking' *(cessatio),* when university rights were infringed. If no redress were given in the latter case, the suspension of lectures was followed by emigration of the university to another town. This could easily be done, since none of the mediaeval universities had buildings of their own, and there was no need of expensive libraries, laboratories, and other equipment.

Through such special rights the universities obtained great power and became very independent. Soon the liberty allowed to students degenerated into recklessness and license, and they became dissipated and quarrelsome. This is especially seen in the life of the so-called 'wandering students,' who migrated from university to university, begging their way, and were shiftless, rollicking, and vicious. The one compensating feature of such degeneracy was their production of jovial Latin and German songs to voice their appreciation of forbidden pleasures and their protest against restraint.

**Organization of the Universities.** - The term *uttiversitas,* or 'university,' did not imply originally, as often claimed since, an institution where 'everything' is taught, but it was used of any legal corporation, and only in the course of time was it limited to an organization of masters and students. The phrase *studium generate* was also often used of a university, to indicate a school where the students from all parts of civilization were received, and to contrast it with a *studium particulare,* which was confined to pupils of a limited neighborhood. The formation of a university had been preceded by the organization of 'nations,' or bodies of students grouped according to the part of Europe from which they came, but these nations soon began to combine for the sake of obtaining greater privileges and power. Every year each nation chose a 'councilor,' who was to represent it and guard its interests. On the side of the masters, the university became organized into 'faculties,' of which there might be at least four, - arts, law, medicine, and theology; and each faculty came to elect a 'dean' as its representative. The deans and the councilors jointly elected the 'rector,' or head of the university.

**Course in the Four Faculties.** - The course of study to be offered by each faculty was largely fixed by papal decree or university legislation during the thirteenth century. The course in arts, which occupied six years, included the texts on the liberal arts mentioned for the monastic schools (see pp. 56 f .)and several of the treatises of Aristotle, as rapidly as they were recovered. In the law course, *Corpus Juris Civilis* was the authorized text for civil law, and the *Decree* of Gratian for canon law. The faculty of medicine utilized the Greek treatises by Medicine. Hippocrates (c. 460-375 B. C.) and Galen (c. 130-200 A. D.), the *Canon* of Avicenna (see p. 66), and the works of certain Jewish and Salernitan physicians. The students of theology put most of their time upon the four books of Peter the Lombard's *Sententia* (Fig. 9), although the *Bible* was studied incidentally.

**The Methods of Instruction.** - The training of a mediaeval student consisted not only in acquiring the subjects mentioned, but in learning to debate upon them. The acquisition of the subject-matter was accomplished through lectures, which consisted in reading and explaining the text-book under consideration (Fig. 10). Beside the text itself, the teacher would read all the explanatory notes, summaries, cross-references, and objections to the author's statements, which often quite overshadowed the original, and might even add a commentary of his own. The passage was read slowly and repeated whenever necessary. The whole exercise was carried on in Latin, which had to be learned by the student before coming to the university. The training in debate was furnished by means of formal disputations, in which one student, or group of students, was pitted against another (Fig. 11). In these contests, which also were conducted in Latin, not only were authorities cited, but the debaters might add arguments of their own. Thus, compared with the memorizing of lectures, debating afforded some acuteness and vigor of intellect, but by the close of the fifteenth century it had become no longer reputable. The aim came to be to win and to secure applause without regard to truth or consistency.

**Examinations and Degrees.** - At the close of the course, the student was examined in his ability to define and dispute; and if he passed, he was admitted to the grade of master, doctor, or professor. These degrees seem originally to have been about on a par with each other, and signified that the candidate was now ready to practice the craft of teaching. The baccalaureate was at first not a real degree, but simply permission to become a candidate for the license to teach. During the thirteenth century, however, it came to be sought as an honor by many not intending to teach, and eventually became a separate degree.

**The Value and Influence of the University Training.** - Obviously the mediaeval universities had most of the defects of their times. From a modern point of view, the content of their course of study was meager, fixed, and formal, and the methods of teaching were stereotyped and authoritative. They largely neglected the real literature of the classical age, and permitted but little that savored of investigation or thinking. Yet the universities were a product of the growing tendencies that later burst the fetters of mediaevalism. They were a great encouragement to subtlety, industry, and thoroughness, and their efforts toward philosophic speculation contained the germs of the modern spirit of inquiry and but somewhat rationality. They were even of immediate assistance in inquiry and promoting freedom of discussion and advancing democracy, and to their arbitration were often referred disputes between the civil and ecclesiastical powers. Thus they aided greatly in advancing the cause of individualism and carrying forward the torch of civilization and progress.

**Supplementary Reading**

Graves, *During the Transition* (Macmillan, 1910), chap. IX; Monroe, *Text-book* (Macmillan, 1905), pp. 313-327. Standard works on the universities in general are Laurie, S. S., *The Rise and Early Constitution of Universities* (Appleton, 1886), and the more complete and accurate *Universities of Europe in the Middle Ages* (Oxford, Clarendon Press, 1895), by Rashdall, H. For a brief source account of the privileges, courses, methods, and student life of universities, see Norton, A. O., *Readings in the History of Education; Mediceval Universities* (Harvard University, 1909), or Munro, D. C, *The Mediceval Student* (Longmans, Green, 1899). For the history of individual universities, see Compayre, G.,<span id="ch9.xml#para.125.1.0.box.327.250.1048.219.q.50" class="gtxt_body"> *Abelard and the Origin and Early History of Universities* (Scribner, 1893); Lyte, H. C. M., *A History of the University of Oxford* (Macmillan, 1886); Mullinger, J. B., *University of Cambridge* (Longmans, London, 1888); and Paulsen, F., *The German Universities* (Macmillan, 1895; Scribner, 1906).</span>