# Will the Jesuits be Felt in this Country

The question has been seriously agitated, whether or not there is any probability that the institutions of the Jesuits will exert an important influence on the destinies of this country. On the one hand it has been passionately contended that the danger from these institutions is real and great. Some have gone so far as to be seized with a panic, in view of their almost certain supremacy. The most awful forebodings have been indulged, and the most passionate appeals have been made, in view of the threatening evil. These fears have, on the other hand, been derided. It has been argued, that it is quite impossible for this order ever to exert an extensive influence among such a people as ours — so intelligent, so independent, and so averse to constraint, to formality, and rigid rule.

It cannot be doubted, we think, that the Jesuits have thoroughly surveyed this country, and that they have projected an extended system of educational influences. Their veteran in craft, who resides at the seat of government, has visited large portions of the West; has selected his favorite points of influence, and, in many instances, has purchased sites for literary institutions. In many places colleges and seminaries have been erected, and have been opened for pupils. The situation, the grounds, the massive and substantial structures, all indicate that the plans are far-reaching, and that, full of confidence in the triumphs of time, the Jesuits are waiting and hoping to do a great work for the Church of Rome. It is certain — as certain as that the order exists — that its eyes are every where present; that its net-work of plans and projects is thickly spread over this wide country. It is as certain that the energies of this order are yet un-exhausted, and its organization is still incomplete. The moment that there are indications that, in any part of this country, the population will receive the Jesuit schools and colleges with favor, that moment will they start into being, will be completely manned and provided for an efficient activity. The man that doubts this, must be as ignorant of the past, as he is incapable of forecasting the future. A society that is older than three centuries — that has survived the frown of the Pope, the wrath of all the courts of Europe save one, and the rage of the multitude, and that, after nearly half a century of banishment and suspended life, could start at once into being, and fill all Europe with its presence, and could make it vibrate with its power, is not a night-dream, nor a specter, nor a fancy. It is a terrific reality; and if it can find a place, and exert an influence, among us, it will arise and shake itself like a giant refreshed with sleep.

The only question worth considering is. Will it find or make to itself a place among us? Will its peculiarities attract, or will they repel, the American people?

First. Can the Jesuit system accomplish any thing in our older settlements, which are already provided with colleges and schools? At present, the few institutions which they have are chiefly sustained by Romanists. But it is to be remembered, that there is increasing among these settlements a large and still larger number of men of easy religious faith, and of a thoughtless and ignorant neglect of religious truth. They are men of wealth and fashion, and, to some extent, of liberal culture, who are admirers of intellectual accomplishments, and ambitious of a European education for their children. In respect to the religious bearings of this education, they would despise the consideration of them, as illiberal or sectarian, or think it very vulgar to give themselves any concern about such a matter. Or, it may be, they would be cozened into the belief, that gentlemen so accomplished as this society can furnish, would be quite above any interference with the religious opinions of their pupils — or, which is quite likely to be the case, they would be interested in the earnestness, the propriety of so religious a school, and would be so charmed with this manifestation of the religious sentiment, as even to prefer this religious training for their children. They would think as little of fearing the Pope or the Jesuits, as they would of fearing the devil; for it would be decidedly and equally unfashionable to do the one as the other. Let, then, the accomplishments and high education which can be secured at these schools, as they may become, win over a portion of the fashionable circles — let them be countenanced by a few of the travelled or untravelled literati, and it may easily and swiftly come to pass, that in our oldest and best instructed cities, the Jesuits shall exert a powerful influence. What success they would have with the susceptible children from families with no high religious aims and no earnest religious culture, it is easy to predict. The faith of their fathers would present no obstacle; for the fathers have no faith. All those obstacles, which in other Protestant countries present a barrier so formidable in historical associations, the influence of a court or an aristocracy pledged to a national religion, and in the prevailing sentiment of the people, here have a feeble influence. Do we talk of free principles, and the republican spirit of our countrymen? and do we forget, that with many of the circles whom we describe, republicanism is a jest, and all that smacks of the court and the church, is affected as something peculiar and *distingue*? Do we also forget that to the sensitive and worn-out victims of fashionable life, who have sensibility without affection, and religiosity without religion, institutions like these present strong attractions — that to men of high cultivation, and extensive knowledge of books and society, who have bewildered themselves with a glance at the various religious sects, and have been distracted with the conflicting opinions of others, without earnestly settling their own principles, the oracular dicta of Rome and its imposing and emphatic dogmatism, present a relief from doubt and an end of controversy? Do we not know, that in consequence of these and other attractions which might be named, there are not unfrequent instances of conversions to the church of Rome from among what are called the higher circles of this country, including not a few persons of accomplished education? Do we also forget that such converts to Rome are quite likely to be ardent admirers of the Jesuit — so ardent that they can adopt the language of certain Oxford divines concerning the “illustrious and glorious society of Ignatius, which, next to the visible church, may be considered as the greatest miracle existing in the world.”[^25]

The only remedy against these tendencies, is to preoccupy the ground with colleges and schools of the highest order, in which all the advantages of a thorough and accomplished education may be secured, and which, at the same time, shall teach a positive, earnest, yet catholic Christianity, and shall be pervaded by its free and elevated spirit.

We next inquire: What are the prospects of the Jesuit institutions in the newer settlements? In these settlements there is a large proportion of Catholics, who will, by and by, attain to wealth and influence. These will send their children to the Jesuit seminaries, who will constitute an educated and accomplished class, exhibiting in its members the superiority of the Jesuit education. There is a large and still larger class of people at the West, who are of Protestant descent, but who have no religious faith from personal conviction. Many of them have suddenly risen to wealth, and bring with them all that vulgar arrogance and independent spirit which are the usual consequences. To such men, and to a state of society formed under their influence, the Jesuit teacher, and the Jesuit school is likely to be an object of profound admiration. The external accomplishments to which he forms his pupils, the dexterous logic, the learned air, and the serene self-confidence with which he claims the superiority, are certain to be attractive to those who have no training of their own, little culture, and little knowledge of arts like these. We can hardly conceive to ourselves a finer field for the successful exhibition of a splendid system of Jesuit tactics, than is presented in the unformed society of the West. The agency and the material to work upon, are admirably fitted to each other, and promise the most magnificent results. Is it suggested, that the republican spirit and prejudices of western society will be offended by institutions of so rigid and severe a character? No impression can be more unfounded than this. Men admire that to which they are most unaccustomed. The order and strict regime of a seminary for youth presents no objection, from its anti-republican character, to those who have full confidence in its teachers and guardians. As to the influence of the principles that may be silently inculcated, and of the spirit which may be imparted, these will neither be suspected, nor feared. The patrons will be too ignorant to be instructed by history, or too self-confident to regard its suggestions, or too indifferent to care for the consequences. Besides, nothing is easier for the Jesuit, than to be an ardent republican. The Romish church and its religious orders will delight to assume the patronage of the people; they will be intensely solicitous for the largest political liberty, provided they can control the conscience and thus regulate the elections. A republic is a field far more inviting than a monarchy for the agency of an organization so vast, so secret, so able, and so adaptive as that of the Jesuits. A monarchy has its own organization, its own police, its own secret agents, acting upon matured and far-reaching plans, who will suspect and trace out their secret enemies. But a republic often changes its parties. Their organizations are as shifting as the sands, and their agencies are formed and broken like exhalations of a night. Then there are the interests and unscrupulousness of partisans, who in critical periods will gladly lay hold of such an organization to accomplish their ends. These parties will shelter themselves under the name of toleration and the largest religious liberty, and will reproach their adversaries with sectarian zeal and bigoted prejudice. Against the powerful influence of such an educational system, republican principles and the republican spirit are an unequal defense. The great questions then to be considered for the West, as well as for the East, are: Will these institutions root themselves in American soil: Will they obtain so strong a hold of American society at the West, as to be able to act with energy, and to attract crowds of scholars? Will the attractions which they shall be able hereafter to unfold, gain leave and room to allure, to corrupt, and destroy? The answer to these questions, in respect to the West, is the same as for the East, only it is given with a more startling earnestness, and should be pondered with a graver consideration. If Western society is left destitute of seminaries of a decidedly Protestant character, the Jesuits will occupy the field. There is no escape from this alternative. If the West is provided with those of an inferior character, which shall be slowly furnished with the means and the men required, and these shall be inferior in kind, the Jesuit will rejoice at the competition, perhaps even more than if the field were left entirely vacant.

[^25]: Lives of the English Saints, vol. vi. p. 120.
