# 11. The Burgher, Gild, and Chantry Schools

**Outline**

-   In the later Middle Ages the commerce of Europe was greatly increased. Soon the towns received a large impulse from serfs that flocked into them, and before long an influential 'burgher class' arose.
-   There also sprang up merchant and craft gilds, which afforded an industrial training through apprenticeship, and a more formal education through 'gild schools.' As the gilds merged with the town, these institutions became 'burgher schools,' and afforded a practical education in reading, writing, and reckoning. Various 'adventure,' 'chantry,' and other schools were also absorbed by the burgher schools.
-   Thus these institutions came to represent the educational interests of the industrial classes, and paved the way for the civic control of education.

**The Rise of Commerce and Industry.** - A most important influence in producing a transition from the mediaeval to modern times is found in the increase of commerce during the later Middle Ages. From the Roman days down, trade had never died out in Western Europe, especially Italy, despite the injuries wrought by barbarian invasions, as the nobles had always need of luxuries, and the Church of articles of utility in its services. But the demand for vessels and transports during the Crusades, and the desire for the precious stones, silks, perfumes, drugs, spices, and porcelain from the Orient afterward, gave a tremendous impulse to commercial and industrial activity. The people of Europe began to think of what articles others outside their own little groups might want in exchange for these luxuries, and to strive to produce such commodities. They also undertook themselves to make some of the new articles, such as light and gauzy cotton and linen fabrics, silks, velvets, and tapestries. Thus the means of communication between the European states was greatly facilitated, new commercial routes and new regions were opened, geographical knowledge was increased, navigation was developed, maritime and mercantile affairs were organized, manufactures and industries were enlarged, currency was increased, and forms of credit were improved. All this tended toward a larger intellectual view and a partial dissipation of provincialism and intolerance.

**Development of Cities and the Burgher Class.** - The most noteworthy consequence of this industrial and commercial awakening was the growth of towns and cities. There was little town life in Western Europe during the Middle Ages before the twelfth century, as the old Roman towns had, through the invasions of the Germans, largely disintegrated, and but few new organ- izations had sprung up in their place. While some towns still existed in Italy and Southern France, most of the people of Europe lived in the country upon feudal es- tates. These little communities were largely isolated and independent of the rest of the world. They pro- duced among themselves all that their members needed, and little or no money was necessary for their crude forms of exchange. Their life was unbroken in its monotony, there was little opportunity for them to better their condition, and their industries were carried on in a perfunctory and wasteful fashion. But with the growth of commerce and population, these serfs began to find it more profitable to work in the towns and compensate the lord of the manor with money rather than work, and the lords, in turn, found it of advantage to accept money in lieu of services, especially as many of them had been impoverished by the Crusades. Great bodies of serfs flocked to the towns, and new centers sprang up around the manorial estates and monasteries as manufactures, trades, and commerce increased.

Feudalism thus began to be threatened as early as the twelfth century, and within a hundred years the extinction of serfdom was assured. The people soon rebelled against the rule of their lords and either expelled them altogether or secured from them for a monetary consideration a charter conferring more liberal rights and privileges. By these charters, the lord agreed to recognize the gild of merchants, and to permit the people to govern themselves. As industries, trade, and commerce continued to develop, the craftsmen and merchants grew rapidly in wealth and importance. They were soon enabled to rival the clergy in education, and the nobility in the luxury of their dwellings and living. They began to read, and books were written or adapted for their needs. The 'burgher class' came to have a recognized position by the side of the clergy and nobility; and the king, in order to retain their support, was forced to take counsel with them. This development of industry and commerce, growth of town and city life, and rise of a 'third estate' is one of the most noteworthy changes of the late Middle Ages.

**The Gilds and Industrial Education.** - Such a new social attitude naturally gave rise to new forms of education. An informal type of training soon sprang up in connection with the development of 'gilds.' Besides the original gild of merchants, through which the town had presented a united front and gained its privileges, separate gilds for the various crafts had been established in each town. These craft gilds were the sole repositories of the traditional lore of the vocations, and became the chief channel for transmitting it. While their number and variety differed in each town, all the gilds sought to prevent anyone who had not been regularly approved and admitted to the corporation from practicing the trade he represented. In consequence of this attempt at regulation, industrial training in the craft of each gild grew up through an apprenticeship system. This was provided upon a domestic basis. The 'apprentice' entered the household of his 'master,' and learned the craft under his direction (Fig. 15). The time necessary for this varied greatly in different crafts. For example, in Paris it took two years to learn to become a cook, eight years an embroiderer, and ten years a goldsmith. While the apprentice received no wages during this period, he was under the protection of the gild, and might appeal to the organization against ill-treatment or defective training. At the end of his apprenticeship, he became a 'journey-man' and could earn wages, but only by working for a master, and not through direct service for the public. After an examination by the gild, which might include the presentation of a 'masterpiece,' or sample of his work, the journeyman eventually became a master. In other ways, the organization regulated and protected its craft. In order that journeymen and masters might not become too numerous, all masters, save those on the governing board of the gild, were forbidden to take more than one apprentice. The methods of practicing each trade and the hours to be devoted to it each day were specified, and the handiwork of each man carefully scrutinized. In many instances, the gild put its own stamp upon good work, and might often seize products that it considered defective.

**Gild Schools.** - In this way there grew up a species of industrial education, with three definite stages in its organization and with inspection at every point, more formal Before long, too, the gilds developed a more formal means of education. The existing ecclesiastical schools did not altogether meet the needs of the gilds, and they undertook the establishment of additional institutions for this purpose. Where the gilds had retained one or more priests to perform the necessary religious offices for their members, before long they also utilized these functionaries to keep a school for the benefit of their own and sometimes other children in the town. Later, endowments were furnished especially for a priest to teach school, or an amount sufficient for the purpose was paid out of the common funds of the gild. Some of these gild schools, like 'Merchant Taylors'' of London, or the Grammar School at Stratford-on-Avon, where Shakespeare was educated (Fig. 16), still survive as secondary institutions. Many instances, too, are recorded where the members of a certain gild were appointed trustees of a school established by an individual, and were granted the right of appointing and dismissing the master, admitting the pupils, managing the property, and formulating statutes. In some such fashion Colet later vested the management of the famous St. Paul's school (see p. 118) in the gild of mercers.

**Burgher Schools.** - As the gild organizations gradually merged with those of the towns, the gild schools were generally absorbed in the institutions known as 'burgher' or town schools. At first these burgher schools were not very dissimilar to those established by the Church, except that they were more conveniently located, but later various types of vernacular schools arose to meet special practical demands, especially writing and reckoning. The Latin burgher schools were also somewhat practical in their course, and often admitted some pupils who desired to learn only to read, write, and reckon. Writing had become an important vocation, since printing had not yet been invented; and there was a definite demand for writers in public offices, private secretaries, letter writers for the illiterate, and teachers of writing. Reckoning grew directly out of the new commercial life, and was often taught in the writing schools. It was not taught from the standpoint of theory or discipline, as was the arithmetic in the Latin schools, but for the sake of practical calculation and bookkeeping. But even all the facilities of the regular Latin and vernacular schools of the town were not sufficient to meet the demand for a more practical education. In consequence, private 'adventure' schools, taught by wandering teachers or by women, likewise often sprang up, and some teachers were even licensed by the town authorities to teach the vernacular. In most instances, however, these institutions were also combined with the burgher schools.

**Chantry Schools.** - Another type of institution that came into prominence toward the close of the Middle Ages was the 'chantry school.' Schools of this sort at first arose out of bequests by wealthy persons to support foundations for priests who should 'chant' masses for the repose of their souls. Since these religious duties did not absorb all the time of the priests, they were able to do some teaching. And before long, the founders of chantries themselves came to direct that the priests carrying out their will should be required to teach. Often two chantry priests were provided, one to teach a 'grammar' school, and the other a 'song' or vernacular school. From the first most of these chantry schools were free of all tuition charges, the priest being requested to "teach gratis, without asking anything beyond his stipend for his pains," but occasionally they were gratuitous only to the children of his parishioners or to poor children whose parents or guardians asked for the privilege.

**Influence of the New Schools.** - The chantry schools likewise were often united with various other schools within a town, and became jointly known as 'burgher schools.' Many new foundations of a similar nature were also made. These burgher schools were largely controlled and supported by the public authorities, although still generally taught by the priests. They came to represent the interests of the mercantile and industrial classes, and gave instruction in subjects of more practical value than had any of the schools hitherto. Such institutions sprang up everywhere during the later Middle Ages. They were often strongly opposed by the ecclesiastical authorities, who struggled hard to abolish them or bring them under control, but they continued to grow and hold their own. The number of lay teachers in them gradually increased, and thus paved the way for the tendency toward the secularization and civic control of education that appeared later on. The new schools, therefore, that arose in connection with the development of commerce and industry and the growth of towns, were one of the largest factors that led into the broadening of outlook known as the Renaissance.

**Supplementary Reading**

Graves, *During the Transition* (Macmillan, 1910), chap. X; Monroe, *Text-book* (Macmillan, 1905), pp. 337-339. Adams, G. B., *Civilization during the Middle Ages* (Scribner, 1894), furnishes an illuminating chapter (XII) upon the *Growth of Commerce and Its Results.* The development of towns and gilds in various countries of Europe is described in detail by Ashley, W. J., *English Economic History and Theory* (Putnam, 1892), vol. I, chap. II; Green, Alice S., *Town Life in the Fifteenth Century* (Macmillan, 1894); Gross, C., *The Gild Merchant* (Oxford, Clarendon Press, 1890); Staley, E., *The Guilds of Florence* (Methuen, London, 1906); and Unwin, G., *The Gilds and Companies of London* (Methuen, London, 1908; Scribner, 1909). Accounts of the new types of schools are found in Leach, A. F., *English Schools at the Reformation* (Constable, 1896), chaps. 7-9; Nohle, E., *History of the German School System* (Report of the U. S. Commissioner of Education, 1897-1898, vol. I), pp. 22-26; and Watson, F., *English Grammar Schools to 1660* (Cambridge University Press, 1909), chap. VII.