# 14. Early Realism and the Innovators

**Outline**

-   The intellectual awakening that appeared in the Renaissance and the Reformation found another avenue for expression in early realism.
-   This movement had two phases: (i) humanistic realism, which emphasized the content of classical literature; and (2) social realism, which strove to adapt education to actual life. But the two phases generally occurred together, and the classification of a treatise under one head or the other is largely a matter of emphasis.
-   The influence of the two phases was mostly indirect, but through social realism a special training arose in the *Ritterakademien* in Germany, while Milton's humanistic realism was embodied in the 'academies' of England, and afterward of America.

**The Rise and Nature of Realism.** - By the seventeenth century it is obvious that humanism was everywhere losing its vitality and declining into a narrow 'Ciceronianism,' and that the Reformation was hardening once more into fixed concepts and a dogmatic formalism. The awakened intellect of Europe, however, was tending to find still another mode of expression in the educational movement that is usually known as 'realism.' The process of emancipating the individual from tradition and repressive authority had not altogether ceased, but it was manifesting itself mainly through a rather different channel. The movement of realism implied a search for a method by which 'real things' may be known. In its most distinct and latest form, - 'sense realism,' it held that real knowledge comes through the senses and reason rather than through memory and reliance on tradition, and in this way it interpreted the 'real things' as being individual objects. Educational realism, therefore, concerned itself ultimately with investigation in the natural sciences; and it might well be denominated 'the beginnings of the scientific movement,' were it not that such a description and the earlier neglects the earlier phases of the realistic development.

**Humanistic Realism.** - For, even before objects were regarded as the true realities, there seems to have been an effort among some later humanists to seek for the 'real things' in the ideas that were represented by the written words. This broader type of humanism, in consequence, tended to break from a restriction to words and set forms and return to the interest in the content of classical literature that marked the Renaissance before its decline into formalism. It may, therefore, properly be called 'humanistic realism.' With its emphasis upon content usually went a study of social and physical phenomena, \*in order to throw light upon the passages under consideration. Illustrations of this humanistic realism are found in many writers of the sixteenth and seventeenth centuries. Milton (1608-1674), for example, while a remarkable classicist himself, in his *Tractate of Education* objects to the usual humanistic education with "its gramma tic flats and shallows where they stuck unreasonably to learn a few words with lamentable construction"; and says of the pupil, "if he have not studied the solid things in them as well as the words and lexicons, he were nothing so much to be esteemed as any yeoman or tradesman competently wise in his mother dialect only." And he would teach the Latin writers on agriculture, and the Greek writers on natural history, geography, and medicine for the sake of the subject matter.

**Social Realism.** - But there was another phase of early realism, which often appeared in conjunction with humanistic education, and may be called 'social realism.' Its adherents strove to adapt education to actual living in a real world, and to afford direct practical preparation for the opportunities and duties of life. It generally recommended as the means of education for all members of the upper social class. It sought to combine with the literary elements taught the clergy in the Middle Ages and the scholar in the Renaissance, certain remnants of the old chivalric education as the proper training for gentlemen. It held schools to be of less value as an agency for educating the young aristocrats than training through a tutor and travel. Hence an education in social realism usually included a study of heraldry, genealogy riding, fencing, and gymnastics, and involved a study of modern languages and the customs and institutions of neighboring countries.

A good illustration of this type of education is found in the educational essays of Montaigne (1533-1592). In the *Education of Children* he holds that virtue comes from experience and breadth of vision rather than from reading, and declares: "I would have travel the book my young gentleman should study with most attention; for so many humors, so many sects, so many judgments, opinions, laws, and customs, teach us to judge aright of our own, and inform our understanding to discover its imperfection and natural infirmity." This training, too, he feels, should be under the care of a tutor, who is to be a man of the world, one "whose head is well tempered, rather than well filled." While a gentleman has need of Latin and Greek, Montaigne maintains that one should first study his own language and those of his neighbors. He also stresses physical exercise, and fears the training of boys near their mothers, who "will not endure to see them mount an unruly horse, nor take a foil in hand against a rude fencer."

An educational work based on social realism that has been studied even more than the *Essays* of Montaigne is *Some Thoughts concerning Education* by John Locke (1632-1704). Locke states the aims of education in order of their value as *'Virtue, Wisdom* (i. e., worldly wisdom), *Breeding,* and *Learning'*; and holds that such a training can be secured by the young gentleman only through a tutor, who "should himself be well-bred, understanding the Ways of Carriage and Measures of Civility in all the Variety of Persons, Times and Places, and keep his Pupil, as much as his Age requires, constantly to the Observation of them." In considering the subjectmatter of the training, he maintains that "besides what is to be had from Study and Books, there are other *Accomplishments* necessary for a Gentleman, - dancing, horseback riding, fencing and wrestling."

**The Relations of Humanistic to Social Realism.** - Humanistic and social realism, however, constantly appear together in the works of the same author, and it is often difficult to distinguish a writer as advocating one type or the other. The differentiation seems to be largely a matter of emphasis. While one element or the other may seem to be more prominent in the treatise of a certain author, the two phases of education are largely bound up in each other. While Milton, for instance, is in the main a humanistic realist and advises an education in languages and books, he recommends that considerable time be given, toward the end of the course, to the social sciences - history, ethics, politics, economics, theology - and to such practical training as would bring one in touch with life. He also specifically advocates the experience and knowledge that would come from travel in England and abroad; and defines education as "that which fits a man to perform justly, skillfully, and magnanimously all the offices both private and public of peace and war." On the other hand, Montaigne, the social realist, seems quite as strenuous in urging a more realistic humanism. In his essay, *On Pedantry,* he launches most vigorous ridicule against the prevailing narrow humanistic education, with its memorizing of words and forms, and insists: "Let the master not only examine him about the words of his lesson, but also as to the sense and meaning of them, and let him judge of the profit he has made, not by the testimony of his memory, but that of his understanding."

And it is equally difficult to state whether humanistic or social elements prevail in Locke's *Thoughts,* the *Gargantua* of Rabelais (1495-1553), the *Positions* of Mulcaster (1530-1611), and other treatises of the period. It is true, of course, that in certain other works written upon the training of the aristocracy, social realism is more exclusively stressed. The titles of most of these reveal their content, as can easily be seen in the case of such productions as Castiglione's *The Courtier* (1528), Elyot's *The Governour* (1531), Peacham's *The Compleat* '*Gentleman* (1622), and Brathwaite's *The English Gentleman* (1630). But, in most of the early realistic works, humanistic and social elements are inextricably interwoven; and humanistic and social realism, taken together, seem to constitute a natural bridge from humanism over to sense realism.

**The Influence of the Innovators upon Education.** - There is, however, a variety of other brilliant educational suggestions in each of these early realists. All of them hold to a broader and better rounded training and more natural and informal methods than those in vogue. Mulcaster even advocates universal elementary education, the professional training of teachers, and the education of girls, and undertakes to make a naive analysis of the mind as the basis of a philosophy of education. So suggestive have the recommendations of the early realists proved to modern education that these authors are often known as the 'innovators.' Yet their theories do not seem to have affected greatly the educational practice of the times. They did tend to disrupt traditionalism and the formal humanism, to bring education into touch with society and preparation for real life, and to popularize a wider content and a more informal procedure, but their influence appeared through their successors and later education rather than directly in the schools of the period. Locke, for instance, in addition to the influence he had upon Rousseau, Pestalozzi, and other reformers, must in some measure have been responsible for the great development of the physical and ethical sides of education in the public and grammar schools of England, together with the tendency of these institutions to consider such aspects of rather more importance than the purely intellectual. His plea for a tutor as the means of shaping manners and morals has also probably had its effect upon the education of the English aristocracy.

**The Ritterakademien.** - In the German states, on the other hand, there arose at the courts during the seventeenth century an actually new type of educational institution as the outgrowth of social realism. Here, in place of the old humanistic education, there was developed a special training for the young nobles in French, Italian, Spanish, and English, in such accomplishments as courtly conduct, dancing, fencing, and riding, and in philosophy, mathematics, physics, geography, statistics, law, genealogy, and heraldry. The educational institutions in which this training was embodied were known as *Ritterakademien* or 'academies for the nobles.' Such academies were founded at Colberg, Luneberg, Vienna, Wolffenbuttel, and many other centers before the close of the century. They originally covered the work of the gymnasia, although substituting the modern languages, sciences, and the knightly arts that have been mentioned for the Greek and Hebrew, and adding a little from the course of the university. Gradually, however, they became part of the regular secondary system.

**The Academies in England.** - Milton's suggestions were ultimately materialized in an even more influential type of school. In the *Tractate* he had recommended that his ideal education be carried out in an institution to be known as an 'academy.'. Such a school was to be erected 'in every city throughout this land.' It should train boys from the age of twelve to twenty-one, and should provide both secondary and higher education. 'Academies,' based very closely upon "this plan, were about a generation later actually organized in a number of places by the Puritans. Under the harsh Act of Uniformity (1662) two thousand non-conforming clergymen were driven from their parishes, and in many instances found school-teaching a congenial means of earning a livelihood, and at the same time of furnishing higher education to the young dissenters, who were excluded from the universities and grammar schools. The first of these academies was that established by Richard Frankland at Rathmill in 1665, and this was followed by the institutions of John Woodhouse at Sheriffhales, of Charles Morton at Newington Green, and of some thirty other educators of whom we have record at other places. These academies were largely humanistic in their realism, and, since their chief function was to fit for the ministry, they included Latin, Greek, and Hebrew in their course, but they were also rich in mathematics, natural and social sciences, modern languages, and the vernacular. The new tendency was also broadened and amplified by Locke's *Thoughts* (1693), which became the great guide for the managers of the Puritan academies. In 1689, when the Act of Toleration put non-conformity upon a legal footing, the academies were allowed to be regularly incorporated.

**The Academies in America.** - Academies arose also in America. When the number of religious denominations had greatly increased and the demands upon secondary education had expanded, the 'grammar schools' (see pp. 120 f.), with their narrow denominational ideals and their limitation to a classical training and college preparation, proved inadequate, and efforts were made to organize academies as a supplement. Their may have been earlier academies in America, but the first well-known suggestion of an academy was made in 1743 by Benjamin Franklin. He wished to inaugurate an education that would prepare for life, and not merely for college. Accordingly, he proposed for the youth of Pennsylvania a course in which English grammar and composition, penmanship, arithmetic, drawing, geography, history, the natural sciences, oratory, civics, and logic were to be emphasized. He would gladly have excluded Latin and other languages altogether, but for politic reasons these courses were allowed to be elective. Through the efforts of a number of leading citizens, such an academy was opened at Philadelphia in January, 1750 (although not chartered until July, 1753). During the next generation a number of similar institutions sprang up, especially in the middle and southern colonies. A great impulse was given the movement by the foundation of the two Phillips academies, - one in 1780 at Andover, Massachusetts, and the other the next year at Exeter, New Hampshire. The Dummer Grammar School was reorganized as an academy in 1782, and the movement spread rapidly throughout New England during the last two decades of the eighteenth century.

Shortly after the Revolution, owing in part to the inability or unwillingness of the towns to maintain grammar schools, and in part to the wider appeal and greater usefulness of the academies, the latter institutions quite eclipsed the former, and became for about half a century the prevailing type of secondary school in the United States. They were usually endowed institutions managed by a close corporation, but were often largely supported by subscriptions from the neighborhood, and sometimes subsidized by the state. Located in small towns or villages, they served a wide constituency and made provision for boarding, as well as day pupils. Unlike the grammar schools, they were not originally intended to prepare for the learned professions exclusively, but, as time passed, they tended more and more to become preparatory schools for the colleges, instead of finishing schools for the middle classes of society. The academies were also the first institutions of secondary education to offer opportunities to women. Many of them were co-educational, and others, frequently burdened with the name of 'female seminary' were for girls exclusively. Academies for some time likewise furnished the only means of training teachers for the elementary schools, and have generally played an important part in education in the United States.

**Supplementary Reading**

Graves, *During the Transition* (Macmillan, 1910), chap. XVII; and *Great Educators of Three Centuries* (Macmillan, 1912), chaps. I and V; Monroe, *Text-book* (Macmillan, 1905), pp. 442-460. An excellent edition of Milton's *Tractate of Education* is that by Morris, E. E. (Macmillan, 1895); of Montaigne's *Education of Children* that by Rector, L. E. (Appleton, 1899); of Locke's *Thoughts concerning Education,* and of Mulcaster's *Positions,* those by Quick, R. H. (Cambridge University Press, 1895, and Longmans, 1888, respectively); and of Rabelais' *Gargantua,* that by Besant, W. (Lippincott, Foreign Classics for English Readers). The works of Castiglione, Elyot, Peacham, Brathwaite, etc., are also extant. For an account of the *Ritterakademien,* see Nohle, E., *History of the German School System* (Report of the U. S. Commissioner of Education, 1897-98), pp. 41 f., and Paulsen, F., *German Education* (Scribner, 1908), pp. 112-116; and of the academies, Brown, E. E., *The Making of Our Middle Schools* (Longmans, Green, 1902), chaps. VIII and IX.