# 17. Education in the American Colonies

**Outline**

-   The schools of the American colonies closely resembled those of the European countries from which the colonists came, and were influenced by the various religious conceptions of education that were current in each case. In general, where the Calvinistic attitude prevailed, the colonies attempted universal education, but where the Anglican communion dominated, the aristocratic ideal of education was in evidence.
-   Three types of colonial school organization appeared: (1) *laissez {aire* in Virginia; (2) 'parochial' in New Netherlands; and (3) governmental activity in Massachusetts. The South generally followed the same plan as Virginia, and New York (after the English occupation) and Rhode Island also developed on this basis. The other Middle and New England colonies followed the parochial and governmental patterns respectively.

American Education a Development from European. - We have hitherto had little occasion to speak of American education, except by way of anticipating certain great waves of influence and important institutions that have come into America from Europe. But we have now reached the period when the New World began to be extensively colonized, and in the rest of our study educational practices in America will become increasingly distinctive and influential. The schools of America are the offspring of European institutions, and have their roots deep in the social soil of the lands from which the colonists came. While the universal, free, and secular schools of the United States are a natural accompaniment of its republican form of government, like the new democracy itself, this development of popular education was not reached at a bound. At first the American schools resembled the institutions of the Mother Country as closely as the frontier life would permit. The seventeenth century was, therefore, for American education distinctly a period of 'transplantation of schools,' with little or no conscious change; and it is only toward the middle of the next century, as new social and political conditions were evolving and the days of the Revolution were approaching, that there are evident the gradual modification of European ideals and the differentiation of American schools toward an ideal of their own.

Conditions in Europe from Which American Education Sprang. - Hence, in order to understand American education in the colonial period, we must briefly consider the social and educational conditions in Europe during the early part of the seventeenth century, when the colonists began their migrations. The thirteen American colonies were started while the fierce agitations of the Reformation period were still at their height. The settlers, for the most part, were Protestants, and many of them had emigrated in order to establish institutions - political, ecclesiastical, educational - that would conform to their own ideals, and in all cases education in the New World was given a peculiar importance by the dominant religious interests and conflicts of the old. At this time in practically all the states of Europe, educational institutions were controlled and supported

Anglicans.

by\^the Church and religious orders, with the assistance of private benevolence; but a few schools everywhere, and especially in Teutonic countries, were maintained by pre-Reformation craft gilds, and so had a close connection with municipalities (see p. 92). Thus the American schools at first naturally adopted the religious conception of education and religious domination, but had some acquaintance with free schools and municipal .management.

In addition to these characteristics, the religious reformers, like Luther and Calvin, generally held to the Tendency

''° *^J^* toward uni

idea that a system of schools should be supported, or ^v^.ersai educa

tion among

at least established, by the state, and that all children Caivinists, but should have an opportunity to secure an education ideals among sufficient to make them familiar with the Scriptures. If people were to be guided by the word of God, they must all be able to read it. But this view of education was not held by those for whom, as in the English Church, the Reformation was not primarily a religious and theological, but rather an ecclesiastical and political revolt. In Holland and Scotland, for example, where Calvinism prevailed, universal education was upheld by the mass of the people, but in France and England only a small minority, the Huguenots and Puritans respectively, adopted this attitude. Hence it happens that, wherever in America the influence of Puritanism, the Dutch Reformed religion, Scotch Presbyterianism, or other forms of Calvinism was felt, the nucleus of public education appeared, while in the colonies where the Anglican communion was dominant, the aristocratic idea of education prevailed and training of the masses was neglected. However, even among the Calvinists, who held that

elementary education should be universal, and that the State as well as the Church should hold itself responsible for its being furnished, the logical solution of the problem was not perceived for scores of years. In the Calvinistic colonies it was not at first believed that education should be the same in character for all or that the State should bear the expense through taxation. This distinctively American interpretation of public education did develop later, but in the beginning even the most advanced colonies to some extent placed the financial responsibility upon the parent or guardian.

Colonial School Organization: The Aristocratic Type in Virginia. - As a result of these general traditions and characteristics, there would seem to have been three chief types of school organization in the colonies. These Spra ^ch!ef^ were (1) the *laissez faire* method, current in Virginia and the South; (2) the parochial organization of New Netherlands and the Middle Colonies in general; (3) the governmental activity in Massachusetts and most of the other New England colonies. We may profitably discuss these typical organizations in order. Turning first to the aristocratic colonies of the South, we may seiecUvf^mi^edu- ^se^l^ect^ Virginia, the oldest of these provinces, as represented from sentative of the type. That colony constituted the first England. attempt of England at reproducing herself in the New World, and here are found an order of society, form of government, established church, and distinction between I classes, similar to those of the Mother Country. For some time there existed a sharp line of demarcation between the gentry, or landowning class, and the masses, which 1 included the landless, indentured servants, and other dependents. In education, the colonists had brought

\\

with them the idea of a classical higher and secondary training for the upper classes in the semi-monastic type of university and the (Latin) grammar school (see pp. 120 f.), and but little in the way of elementary education, except private 'dame' schools and the catechetical training by the clergy. There were, in addition, the family 'tutorial' education, both secondary and elementary, for the children of the wealthy, and evident attempts at perpetuating the old English industrial training through apprenticeship for orphans and children of the poor. But no such institution as a public elementary school was at first known. In consequence, the educa- \^\^j"TM! tional legislation in colonial Virginia is concerned mainly legislation. with (a) the organization of a college or university, (b) individual schools of secondary grade, and (c) apprenticeship education for the poor.

During the first quarter of a century most educational efforts in Virginia were in behalf of the foundation of found VcoUege an institution of higher learning, and were aided by the king, the Anglican bishops, and the London Company. By 1619 over £2000 and a grant of ten thousand acres of land had been obtained for a University at Henrico, but this rather indefinite plan was brought to a violent end by the Indian massacre of 1622, and the funds were diverted to a school in the Bahamas. An even more fruitless endeavor to found a college was made in 1624 by Sir Edwin Palmer upon an island in the Susquehanna. During this period also there was at least one abortive attempt to establish a school by collections and gifts, and during the second quarter century of the colony there were chartered a number of secondary schools, and secondary

~\>~ -\_" *..'■* schools.

endowed with bequests of land, money, cows, horses,

slaves, or other property. These schools, however, were local, and resembled the endowed Latin schools of England, except that they may sometimes have been obliged by circumstances to include more or less elementary instruction. In 1660 there was also a renewed attempt to establish by subscriptions a college and "free (secondary) school for the advance of learning, education of youth, supply of the ministry and promotion of piety." But none of the efforts at founding schools could have been very successful, for, a decade later, when interrogated as to what kind of education existed in the colonies, Governor Berkeley made his famous reply: "The same course that is taken in England out of towns; every man according to his ability instructing his children. ... I thank God there are no free schools, and I hope we shall not have them these hundred years; for learning has brought disobedience and heresy and sects into the world."

However, despite these biased remarks of the testy governor, by 1692 the constant efforts to obtain an institution of learning were finally rewarded. Through the management of the Reverend James Blair, D. D., the bishop's commissary in Virginia, a charter for the College of William and Mary, a gift of £2000 and of twenty thousand acres of land, and the right to certain colonial taxes were obtained from the king, and large donations were made by the planters and additional support provided by the assembly. In fact, the college was munificently endowed for the times, and it did a great work in training the greatest scholars, statesmen, judges, military officers, and other leaders during the struggle for independence. Moreover, 'free\^\_schools<span id="ch17.xml#para.248.1.0.box.135.239.1262.955.q.60" class="gtxt_body"> now greatly increased in number and their courses were much improved. But education was throughout this Apprenticeship early period regarded as a special privilege, and the the poor, masses were mostly employed in making tobacco, and other manual pursuits. For the sons of these people the only educational legislation was that provided between 1643 ^an^d 1748 in various acts concerning the industrial training of the poor, apprentices, wards, and orphans. In keeping with English precedents, these children were taught a trade by the masters to whom they were indentured, or trained in the flax-house established by public funds at James City. Thus, by the middle of the eighteenth century a fair provision of secondary and higher education had been voluntarily made in various localities, but as yet no real interest in common schools had been shown by the responsible classes in Virginia. Education was there predominantly *'*selective' in character.</span>

The Parochial Schools in New Netherlands. - A second type of colonial organization of education appears in the New Netherlands, as the country between the Delaware and Connecticut rivers was called during the period of Dutch control (1621-1674). In contrast to the *laissez faire* attitude of Virginia, the foundation of schools wasjDarochial. Instead of the chance endowment of schools wherever the benefactors happened to be located, a school was founded in connection with every church. This arrangement grew out of the Cal- Calvinistic

■\^\^y,\_ *^a^ "~m~* conception of

vinTsHc conception of universal education, which formed universal eduan essential part of the social traditions in Holland during Holland, the seventeenth century. Long before the Dutch came to America, the parochial school, as a means of preserv

ing the Reformed faith, had become an indispensable part of church organization. But the Dutch state also had concerned itself with the facilities for education. The Reformed Dutch Church was granted the right to examine teachers, enforce subscription to the creed, and, in the case of the elementary schools at least, largely determine the appointments, but the legal support and control of education were vested in the civil authorities. Hence there early arose in New Amsterdam and the villages of New Netherlands a parochial school system and a distribution of control between Church and State prayers^15^\^ Re- very similar to that in Holland. Besides the ordinary afweu asei?' elementary branches, these parochial schools of the New benches Netherlands taught the 'true\_princjples of Christian

taught. religion,' and the catechism and prayers of the Reformed

Church. Thus the Dutch school differed from those in the Anglican colonies of the South, which stressed secondary education, in being chiefly elementary, although some attempt at conducting a Latin or '\_grammar' (see p. 120) school was also made in New Amsterdam from 1652 on. However, after the English took permanent possession of New York (1674), the parochial school of the city was limited to the support of the Reformed Church, and, as a result of its long refusal to adopt the English language, its possible influence toward the realization of universal education was completely But, with Eng- lost. While the Dutch schools of the villages generally tion, replaced retained the joint control and support of the local court conization"\* and church, with a constantly increasing domination of the former, as a whole the English occupation of New York would seem to have set public education back about a hundred years. At any rate, by the eighteenth<span id="ch17.xml#para.250.1.0.box.101.249.1045.206.q.70" class="gtxt_body"> century colonial New York seems to have fallen into the same *laissezfaire* support of education that prevailed in the Southern colonies. The policy of universal education by means of parochial schools no longer existed.</span>

Sectarian Organization of Schools in Pennsylvania. - As a colony, Pennsylvania developed a church school organization, similar to that of the New Netherlands, except that it was carried on in connection with a number of creeds, and that the municipality was seldom a coiirdinate factor. Pennsylvania was more heterogeneous More ^sect^? ?°^d^

*^J^* ° the mumci

in population than New York, as the tolerant attitude P\^1y ^not^,

coordinated.

of the Quaker government had attracted a large variety of German sects, Swedes, Dutch, English, Welsh, and Scotch and Irish Presbyterians, and each was devoted to its own denominational schools. Early in the eighteenth century all Protestant religious bodies were authorized by statute to conduct schools and to receive bequests and hold land for their support. Even before this the Friends had started the 'Penn Charter School,' Friends, which, while itself a secondary school, soon established elementary schools as branches\_. throughout the city upon various arrangements. In keeping with the conclusions of various 'Yearly Meetings' (1722, 1746, etc.), the Friends also provided elementary, and to some extent secondary, schools in close proximity to all meetinghouses throughout the colony. Similarly, the Lutheran Lutherans, congregations, for example, each set up a school alongside of the church as early as possible. Likewise the Mennonites included in their system the famous schools Mennonites, of Christopher Dock, who in 1750 produced the first elaborate educational treatise in America. There was also some attempt at 'grammar' schools (see p. 120)

Broader attempts.

and others. or secondary education, especially in the case of the well-known Moravian institutions at Bethlehem, Nazareth, and Lititz, and the Presbyterian Log College at Neshaminy, which became the cradle of Princeton, Washington and Jefferson, Hampden-Sidney, and Union Colleges.

A somewhat broader spirit was manifest in the voluntary 'neighborhood' schools of Western Pennsylvania and elsewhere, in the attempts at universal education of the Connecticut colonists in the Wyoming Valley, and in the 'academy' (see p. 159) set up at Philadelphia through Franklin, to train public men and teachers, and fuse the various nations in a common citizenship. But, as a whole, parochial schools exerted the greatest influence in the colony of Pennsylvania.

Town Schools in Massachusetts. - The third type of colonial school organization appeared first in Massachusetts. As compared with the *laissez faire* and the parochial methods, governmental activity here prevailed. Accordingly, Massachusetts may be said to have inaugurated the first real system of public education in America. The character of the schools in this colony developed from its peculiar form of society and government. It was democratic, concentrated, and homogeneous, as

geneous society compared with the cosmopolitan and sectarian social

produced gov- ... .

ernmentai ac- structure in the Middle colomes, or the class distinctions and scattered population of the South. While there were some servants and dependents in the Massachusetts Bay Colony and a distinction was made between 'freemen' and others, there were at no time rival elements that were unable to combine. The settlements were not a mere confederation, but the blending of all elements

Democratic and homo

into a single organism, where the individuality of each was merged in a new social whole. This condition was a result of the radical ingrained religious conviction that every one was a child of God, capable of becoming a vital and useful member of society, and that the community was obligated to give him training to that end Jn\_lhe\_\_home~J|~\_the church, and the school.

Out of this Calvihistic attitude sprang a spirit of cooperation and helpfulness, a general participation of all townsmen in local government, and the Massachusetts type of school organization. Common schools seem to have been supported in most towns from the first by voluntaJ3L4ir\_cojripulsory subscriptions, and before the close of the first quarter of a century there had been established by the colony at large an educational system in which every citizen had a working share. Because of I this inclusiveness and unity in matters theological, the/ schools, while religious and moral, could hardly be considered sectarian. The first educational act of the colony, passed in 1642, was similar to the old English appren- ^Acts^ ^of^ ^l6^4\* ticeship law in its provision for industrial education, and, while it was broadened so as to include some literary elements and a rate to procure materials was established, no school is mentioned in it. But in 1647 each ^and^ ^l647^ town of fifty families was required, under a penalty of £5, tomamFain an elementary school (Fig. 22), and every one of a hundred families a (Latin) 'grammar' (Fig. 23) school. These schools might be supported in part by tuition fees, as well as by the town rate, and the obligation seems to have still rested on the parents to see that the children did 'resort' to the school, but the germs of the present common school system in the United States

appear in the educational activity of the legislature in colonial Massachusetts. The 'grammar' schools were to prepare boys for Harvard College (Fig. 24), which had been founded in 1636.

Education in the Other Colonies. - In general, the

organization of education in the remaining nine colonies

can be classed under one of the three types, described

above, but there are various modifications and some

exceptions to be noted. The *laissez faire* foundation

of schools and colleges during the colonial period, which

was evident in Virginia, seems to be characteristic of

the four other colonies of the South. But the problems

were in every case a little different, and in each there

in°MaTyiand° were variations in development. Maryland, for example,

while mainly following the same random foundation of

schools as Virginia, also seriously endeavored (1696)

to support schools in every county by a general colonial

?^a^south^Ch^°°^ls^ ^tax^- South Carolina likewise made an unsuccessful

Carolina. attempt (1 722) at establishing a county system ofschools,

and, a decade before, it undertook to subsidize a school

financed by "\> ^e^%^cn^ parish. Georgia, on the other hand, until the

parliament. Revolution, had its entire budget, including the items

for education, financed by the English parliament.

Democratic And North Carolina, through a large number of Irish

tendencies in '° °

North Caro- and Scotch Presbyterians, German Protestants, and

una.

other immigrants, mostly from Pennsylvama, after 1728 began to break away from the aristocratic policy.

Moreover, after the permanent occupation (1674) by the English, New York went over to the *laissez faire* plan (see p. 194). And, although in the remaining 'middle' colonies, New Jersey and Delaware, something was accomplished by the parochial schools of the

Fig. 24. - The buildings of Harvard College (founded 1636) erected in 1675, 1699, and 1720.

various sects, much of the school organization there was ^Ra^"^doi^p ^or^:

'° gamzation in

*laissez (aire.* Likewise, Rhode Island, dominated by a New York and

. , ~r~ t11 Rhode Island.

fanatical devotion to freedom in thought and speech, failed throughout colonial days to pass any general regulations on education, like those of Massachusetts, and followed more closely the random organization of schools in Virginia. But the other New England colonies, Connecticut and New Hampshire, when it separated from Massachusetts, tended to provide schools after the Massachusetts plan. The Hartford colony of Con- Governmental

• 111. activity in

necticut i n its statutes of 1650 copied almost *verbatim* New England, the phraseology used by Massachusetts in the establishment of schools. It remains for later chapters to show how the practices suggested by this type of organization have eventually overcome those of the other two, for that did not come to pass until after the colonial period.

**Supplementary Reading**

Graves, *History of Education in Modern Times* (Macmillan, 1913), chap, iv; Clews, Elsie W., affords primary source material in *Educational Legislation and Administration of the Colonial Governments* (Columbia University, Department of Philosophy and Psychology, No. 6). The interpretation of educational organization in *Colonial Schools* used in this chapter is furnished by Monroe and Kilpatrick in the Monroe *Cyclopaedia of Education* (Macmillan, 1910-14). For conditions in the various colonies, consult Dexter, E. G., *History of Education in the United Stales* (Macmillan, 1904), chaps. I-VI; Jackson, G. L., *The Development of School Support in Colonial Massachusetts* (Columbia University, Teachers College Contributions, No. 25, 1909); Kilpatrick, W. H., *The Dutch Schools of New Netherland* (Bulletin, U. S. Bureau of Education, 1912); McCrady, E., *Education in South Carolina* (Collections of the Historical Society of South Carolina, vol. IV); Smith,<span id="ch17.xml#para.257.1.0.box.257.234.1051.404.q.50" class="gtxt_body"> C. L., *History of Education in North Carolina* (U. S. Bureau of Education, Circular of Information, no. 2, 1894); Steiner, B. C, *History of Education in Connecticut* (U. S. Bureau of Education, Circular of Information, no. 2, 1893) and *History of Education in Maryland* (U. S. Bureau of Education, Circular of Information, no. 2, 1894), chaps. I-IV; Stockwell, T. B., *History of Public Education in Rhode Island* (Providence Press Co., Providence, 1876), pp. 281-404; and Wickersham, J. P., *History of Education in Pennsylvania* (Lancaster, Pennsylvania, 1886), chaps. I-XII.</span>