# 18. Growth of the Democratic Ideal in Education

**Outline**

- During the eighteenth century, there appeared the climax to the revolt against absolutism.
- This movement was directed against repression of intellect in the first half of the century, and against repression of political rights in the second half. The former phase, through Voltaire, made reason the basis of society and education, but introduced the tyranny of an intellectual few; the latter, through Rousseau, promoted an emotionalism and 'naturalism' that were in keeping with the sentiments of the times.
- The early treatises of Rousseau advocated a complete return to nature, but his later works somewhat modified this attitude.

**The Revolt from Absolutism.** - The ideal of universality and of state control in the education of America and other countries was greatly assisted by the climax to the general revolt against absolutism and ecclesiasticism that appeared in the eighteenth century. During this period of time most strenuous efforts were made to interpret life from a more reasonable and natural point of view and to overthrow all customs and institutions that did not square with these tests. This century marked the climax of the rebellion against authority and against the enslavement of the individual that had been manifesting itself in one form or another from the close of the Middle Ages. One revival after another - the Renaissance, the Reformation, realism, Puritanism, Pietism - had burst forth only to fade away or harden into a new formalism and authoritative standard. Yet with each effort something was really accomplished for freedom and progress, and the way was paved for the seemingly abrupt break from tradition that appears to mark the period roughly included in the eighteenth century. At this point despotism and ecclesiasticism were becoming thoroughly intolerable, and the individual tended more and more to assert his right to be an end in himself. At times all institutional barriers were swept aside, and in the French Revolution destruction went to an extreme. The logical consequence of these movements would have been complete social disintegration, had not the nineteenth century happily made conscious efforts to justify the eighteenth, and bring out the positions that were only implied in the negations of the latter. Thus the revolutionary tendencies and destruction of absolutism in the eighteenth century led to evolutionary movements and the construction of democracy in the nineteenth.

**The Two Epochs in the Eighteenth Century.** - But this revolt of the eighteenth century from absolutism in politics, religion, and thought falls naturally into two parts. During the first half of the century the movement was directed against repression in theology and intellect, and during the second half against repression in politics and the rights of man. The former tendency appears in the rationalism and skepticism of such men as Voltaire and the 'encyclopedists,' while the latter becomes evident chiefly in the emotionalism and 'naturalism' of Rousseau. Although these aspects of the revolutionary movement somewhat overlapped each other and had certain features in common, they should be clearly distinguished. The one prepared the way for the other by seeking to destroy existing abuses, especially of the Church, by the application of reason, but it gave no ear to the claims of the masses, and sought merely to replace the traditionalism of the clergy and monarch with the tyranny of an intellectual few. In distinction to this rule of 'reason,' 'naturalism' declared that the intellect could not always be trusted as the proper monitor, but that conduct could better be guided by the emotions as the true expression of nature. It opposed the control of intellectual aristocracy and demanded rights for the common man.

**Voltaire and the Encyclopedists.** - The rationalistic and scientific tendency was chiefly developed by Diderot, Voltaire, Condillac, D'Alembert, and others interested in the production of the French *Encyclopedie* Of all these 'encyclopedists' the most keen and brilliant was Voltaire (1694-1278), who may well serve as the type of the whole movement. With matchless wit and literary skill, in a remarkable range of poems, epistles, epigrams, and other writings, he championed reason against the traditional institutions of State and Church. His chief object of attack was the powerful Roman Catholic Church, which seemed to him to stand seriously in the way of all liberty, individuality, and progress, and the slogan with which he often closed his letters was, - "crush the infamous thing." The Protestant beliefs he likewise condemned as hysterical and irrational. While an exile in England, as the result of a quarrel with a member of the nobility, he became acquainted with the work of Newton, Harvey, Bacon, Locke, and others (see pp. 164 f.), and undertook to transplant the English English scientific movement to France, and make it the basis of a new regime in society, religion, and education.

The other rationalistic writers had similar doctrines and purposes, and, although details of their ideas are hardly worthy of consideration here, most of them produced treatises upon education. In these they freely criticised the traditional school systems, and proposed new theories of organization, content, and method, which must later have assisted to demolish the existing theory and practice in France. Thus rationalism sought to destroy despotism and superstition, and to establish in their place freedom in action, social justice, and religious toleration. But in casting away the old, it swung to the opposite extreme and often degenerated into skepticism, anarchy, and license. In their fight against despotic ecclesiasticism, the rationalists often failed to distinguish it from Christianity, and they opposed the Church because it was irrational rather than because it was not sincere. They felt that it might have a mission with the masses who were too dull and uneducated to be able to reason. So while rationalism wielded a mighty weapon against the fettering of the human intellect, it cared little about improving the condition of the lower classes, who were sunk in poverty and ignorance, and were universally oppressed.

**Rousseau and His Times.** - In opposition to this intellectualistic and rationalistic attitude, Jean Jacques Rousseau (1712-1778) developed his emotionalism and 'naturalism.' The social and educational positions of this reformer find a ready explanation in his antecedents and career. From his father he inherited a mercurial temperament, love of pleasure, and irresponsibility, and from his mother a morbid and emotional disposition. His tendency toward sentimentalism, idleness, and want of control was also strengthened by the indulgent aunt that brought him up, and by low companions during his trade apprenticeships in the city of Geneva. At sixteen he ran away from the city, and spent several years in vagrancy, menial service, and dissoluteness. A love of nature was impressed upon him by the wonderful scenery of the country in which he spent his boyhood and his years of wandering. He also learned to sympathize with the poor and oppressed, whose condition was at this time forced upon his attention. He received some sporadic instruction, but his education was inaccurate and unsystematic.

At twenty-nine Rousseau settled down in Paris, but his days of vagabondage had left an ineffaceable stamp upon him. His sensitiveness, impulsiveness, love of nature, and sympathy for the poor were ever afterward in evidence. These characteristics blended well with a body of inchoate sentiments and vague longings of this period. It was the day of Louis XV and royal absolutism, when affairs in the kingdom were controlled by a small clique of idle and extravagant courtiers. A most artificial system of conduct had grown up in society. Under this veneer the degraded peasants were ground down by taxation and forced to minister to the pleasure of a vicious leisure class. But against this oppression there had gradually arisen an undefined spirit of protest and a desire to return to the original beneficent state of nature from which it was felt that man had departed. Hence it happened that Rousseau, emotional, uncontrolled, and half-trained, was destined to bring into consciousness and give voice to the revolutionary and naturalistic ideas and tendencies of the century.

Rousseau's Works. - In 1750 he first crystallized this spirit of the age and resultant of his own experience in a discourse on *The Progress of the Arts and Sciences.* In this he declared with much fervor and conviction, though rather illogically, that the existing oppression and corruption of society were due to the advancement of civilization. Three years later he wrote his discourse on *The Origin of Inequality among Men.* Here again he held that the physical and intellectual inequalities of nature which existed in primitive society were scarcely noticeable, but that, with the growth of civilization, most oppressive distinctions arose. This point of view in a somewhat modified form he continued in his remarkable romance, *The New Heloise,* published in 1759, and three years afterward in his influential essay on political ethics, known as the *Social Contract,* and in that most revolutionary treatise on education, the *Emile.* The *New Heloise* commends as much of primitive conditions as the crystallized institutions of society will permit. In the *Social Contract,* Rousseau also finds the ideal state, not in that of nature, but in a society managed by the people, where simplicity and natural wants control, and aristocracy and artificiality do not exist. But the work that has made the name of Rousseau famous is the *Emile.* This, while an outgrowth of his naturalism, assumes the modified position of the later works, and undertakes to show how education might minimize the drawbacks of civilization and bring man as near to nature as possible. But the educational influence of the *Emile* has been so far-reaching that we must turn to another chapter to study the positions of Rousseau and the effects of naturalism in education.

**Supplementary Reading**

Graves, *During the Transition* (Macmillan, 1910), pp. 311-313; *History of Education in Modern Times* (Macmillan, 1913), pp. 110; and *Great Educators* (Macmillan, 1912), pp. 77-85; Monroe, *Text-book* (Macmillan, 1905), pp. 533-542. See also Boyd, W., *The Educational Theory of Rousseau* (Longmans, Green, 1911); Morley, J., *Voltaire* and *Rousseau* (Macmillan).