# 19. Naturalism in Education

**Outline**

- Rousseau attempts in the *Emile* to outline a natural education from birth to manhood. The first book takes Emile from birth to five years of age, and deals with the training of physical activities; the second, from five to twelve, treats of body and sense training; the third, from twelve to fifteen, is concerned with intellectual education in the natural sciences; the fourth, from fifteen to twenty, outlines his social and moral development; and the fifth describes the parasitic training of the girl he is to marry.
- The *Emile* is often inconsistent, but brilliant and suggestive; and, while anti-social, the times demanded such a radical presentation. Through it Rousseau became the progenitor of the social, scientific, and psychological movements in education.
- The first attempt to put the naturalism of Rousseau into actual practice was made by Basedow. He suggested that education should be practical in content and playful in method, and he produced texts on his system, and started a school known as the 'Philanthropinum.' He planned a broad course, and taught languages through conversation, games, and drawing, and other subjects by natural methods. The Philanthropinum was at first successful, and this type of school grew rapidly, but it soon became a fad.

**The Influence of Rousseau's Naturalism.** – The influence of Rousseau's *Emile* upon education in all its aspects has been tremendous. It is shown by the library of books since written to contradict, correct, or disseminate his doctrines. During the quarter of a century following the publication of the *Emile,* probably more than twice as many books upon education were published as in the preceding three-quarters of a century. This epochmaking work forced a rich harvest of educational thinking for a century after its appearance, and has affected our ideas upon education from that day to this.

**Naturalistic Basis of the *Emile.*** – In the *Emile* Rousseau aims to replace the conventional and formal education of the day with a training that should be natural and spontaneous. Under the existing *regime* it was customary for boys and girls to be dressed like men and women of fashion (Fig. 25), and for education to be largely one of deportment and the dancing master. On the intellectual side, education was largely traditional and consisted chiefly of a training in Latin grammar, words, and *memoriter* work. Rousseau scathingly criticises these practices, and applies his naturalistic principles to an imaginary pupil named Emile "from the moment of his birth up to the time when, having become a mature man, he will no longer need any other guide than himself." He begins the work with a restatement of his basal principle that "everything is good as it comes from the hands of the Author of Nature; but everything degenerates in the hands of man." After elaborating this, he shows that we are educated by "three kinds of teachers - nature, man, and things, and since the cooperation of the three educations is necessary for their perfection, it is to the one over which we have no control (i. e., nature) that we must direct the other two." Education must, therefore, conform to nature.

**The Five Books of the *Emile.*** - Now the natural objects, through which Emile is to be educated, remain the same, but Emile himself changes from time to time. In so far, therefore, as he is to be the guide of how he is to be educated in a natural environment, his impulses must be examined at different times in his life. Hence the work is divided into five parts, four of which deal with Emile's education in the stages of infancy, childhood, boyhood, and youth respectively, and the fifth jwith the training of the girl who is to become his wife. The characteristics of the different periods in the life of Emile are marked by the different kinds of things he desires.

In the first book, which takes him from birth to five physicai^1C^ac- y^ears^ of age, his main desire is for physical activities, tivities. ~an~d jj~e~ should, therefore, be placed under simple, free,

and healthful conditions, which will enable him to make the most of these. He must be removed to the country, where he will be close to nature, and farthest from the contaminating influence of civilization. His growth and training must be as spontaneous as possible. He must have nothing to do with either medicine or doctors, "unless his life is in evident danger; for then they\_can do nothing worse than kill him." His natural movements must not be restrained by caps, bands, or swaddling clothes, and he should be nursed by his own mother. He should likewise be used to baths of all sorts of temperature. In fact, the child should not be forced into any fixed ways whatsoever, since with Rousseau, habit is necessarily something contrary to impulse and so unnatural. "The only habit," says he, "which the child should be allowed to form is to contract no habit whatsoever." His playthings should be such simple products of nature as "branches with their fruits and flowers, or a<span id="ch19.xml#para.270.1.0.box.138.224.1053.42.q.70" class="gtxt_body"> poppy-head in which the seeds are heard to rattle."</span>

Language thMissimple, plain, and hence natural, should

be used with him, and he should not He hurried beyond

nature in learning to talk. He should be restricted to a

few words that express real thoughts for him.

The education of Emile during infancy is thus to be

'\_negative Land purely physical. The aim is simply to

keep his instincts and impulses, which Rousseau holds

to be good by nature, free from vice, and to afford him

the natural activity he craves. Next, in the period of

childhood, between the years of five and twelve, which i^n^ childhood, T' . '\_ ., ,"; ^llmb^ ^and^ ^sense^

is treated in the second book, Emile desires most to development,

exercise his legs and arms, and to touch, to see, and in other ways to sense things. This, therefore, is the time for training his li\^absjand senses. "As all that enters the human understanding comes there through the senses, the first reason of man is a sensuous reason. Our first teachers of philosophy are our feet, our hands, and our eyes. ... In order to learn to think, we must then exercise our limbs, our senses, and our organs, which are the instruments of our intelligence." To obtain this training, Emile is to wear short, loose, and scanty clothing, go bareheaded, and have the body inured to cold and heat, and be generally subjected to a 'hardening process' similar to that recommended by Locke (see p. 181). He is to learn to swim, and practice long and high jumps, leaping walls, and scaling rocks. But, what is more important, his eyes and ears are also to be exercised through natural problems in weighing, measuring, and estimating masses, heights, and distances. Drawing and constructive geometry are to be taught him, to render him more capable of observ

no geography, history, or reading,

though moral training through 'natural consequences.'

ing accurately. His ear is to be rendered sensitive to harmony by learning to sing.

This body and sense training should be\^ the nearest approach\_JxL\_&n\_ intellectual, training aLJthis.\_period. Rousseau condemns the usual unnatural practice of requiring pupils to learn so much before they have reached the proper years. In keeping with his 'negative' education, he asks rhetorically: "Shall I venture to state at this point the most important, the most useful, rule of all education? It is not to gain time, but to lose it." During his childhood Emile is not to study geography, history, or languages, upon which pedagogues ordinarily depend to exhibit the attainments of their pupils, although these understand nothing of what they have memorized. "At the age of twelve, Emile will hardly know what a book is. But I shall be told it is very necessary that he know how to read. This I grant. It is necessary that he know how to read when reading is useful to him. Until then, it serves only to annoy him."

Incidentally, however, in order to make Emile tolerable in society, for he cannot entirely escape it, he must be given the idea of property and some ideas about conduct. But this is simply because of practical necessity, and no moral education is to be given as such, for, "until he reaches the age of reason, he can form no idea of moral beings or social relations." He is to learn through 'natural consequences' until he arrives at the age for understanding moral precepts. If he breaks the furniture or the windows, let him suffer the consequences that arise from his act. Do not preach to him or punish him for lying, but afterward affect not to believe him even when<span id="ch19.xml#para.272.1.0.box.139.243.1048.304.q.60" class="gtxt_body"> he has spoken the truth. If he carelessly digs up the sprouting melons of the gardener, in order to plant beans for himself, let the gardener in turn uproot the beans, and thus cause him to learn the sacredness of property. As far as this moral training is given, then, it is to be indirect and incidental.</span>

However, between twelve and fifteen, after the demands of the boy's physical activities and of his senses *}^n^* boyhood,

*^J^ ^r^ ^J^* , intellectual

have somewhat abated, there comes "an interval when training

..... . , , . , . ,, through curi

his faculties and powers are greater than his desires, osity concernwhen he displays an insistent curiosity concerning nat- 'phenomena. ural phenomena and a constant appetite for rational knowledge. This period, which is dealt with in his third book, Rousseau declares to be intended by nature itself as thfiJimje for instruction. But as not much can be learned within three years, the boy is to study only those subjects which are useful and not incomprehensible and misleading, and so is limited to the natural sciences. Later in this third book, in order that Emile may informally learn the interdependence of men and may himself become economically independent, Rousseau adds industrial experience and the acquisition of cabinetmaking to his training. The most effective method of instruction, Rousseau holds, comes through appealing fo the curiosity and interest in investigation, which are so prominent in the boy at this time. He contrasts the current methods of teaching astronomy and geography by means of globes, maps, and other misleading representations, with the more natural plan of stimulating inquiry through observing the sun when rising and setting during the different seasons, and through problems concerning the topography of the neighborhood. Emile

is taught to appreciate the value of these subjects by being lost in the forest, and endeavoring to find a way out. He learns the elements of electricity through meeting with a juggler, who attracts an artificial duck by means of a concealed magnet. He similarly discovers through experience the effect of cold and heat upon solids and liquids, and so comes to understand the thermometer and other instruments. Hence Rousseau feels that all knowledge of real value may be acquired most, clearly and naturally without the use of rivalry or textbooks. But he finds an exception to this irrational method' in one book, *Robinson Crusoe,* "where all the natural needs of man are exhibited in a manner obvious to the mind of a child, and where the means of providing for these needs are successively developed with the same facility."

The fourth book takes Emile from the age of fifteen in youth, sex to twenty. At this period the sex interests appear and

interests, as r- - - , \~, • - . *\^\~,\~,*

basis of should Jie\_4irQp£rly\_guided and trained, especially as

Sdai training, they are the basis of social and moral relationships. Emile's first passion calls him into relations with his 'species, and he must now learn to live with others. "We ihave formed his body, his senses, and his intelligence; it / remains to give him a heart." He is to become moral, affectionate, and religious. Here again Rousseau insists that the training is not to be accomplished by the formal method of precepts, but in a natural way by bringing the youth into contact with his fellowmen and appealing to his emotions. Emile is to visit infirmaries, hospitals, and prisons, and witness concrete examples of wretchedness in all stages, although not so frequently as to become hardened. That this training may not render him cynical<span id="ch19.xml#para.274.1.0.box.156.222.1047.475.q.60" class="gtxt_body"> or hypercritical, it should be corrected by the study of history, where one sees men simply as a spectator without feeling or passion. Further, in order to deliver Emile from vanity, so common during adolescence, he is to be exposed to flatterers, spendthrifts, and sharpers, and allowed to suffer the consequences. He may at this time also be guided in his conduct by the use of fables, for "by censuring the wrongdoer under an unknown mask, we instruct without offending him."</span>

Emile at length becomes a man, and a life companion The passive

. and parasitic

must be found for him. A search should be made for a education of suitable lady, but "in order to find her, we must know her." Accordingly, the last book of the Emile deals with the model Sophie and the education of woman. It is the weakest part of Rousseau's work. He entirely misinterprets the nature of women, and does not allow them any individuality of their own, but considers them as simply supplementary to the nature of men. Like men, women should be given adequate bodily training, but rather for the sake of physical charms and of producing vigorous offspring than for their own development. Their instinctive love of pleasing through dress should be made of service by teaching them sewing, embroidery, lacework, and designing. They ought to be obedient and industrious, and they ought early to be brought under restraint. Girls should also be taught singing, dancing, and other accomplishments. They should be instructed dogmatically in religion, and in ethical matters they should be largely guided by public opinion. A woman may not learn philosophy, art, or science, but shf\^should stnHy m\^n. "She must learn to penetrate their feelings through their conversation, their actions,

I their looks, and their gestures, and know how to give / them the feelings which are pleasing to her, without even 'seeming to think of them."

Estimate of the *Emile.* - Such was Rousseau's notion of the naturaHndiYidualistic education for a man and the passive and repressive training suitable for a woman, and of the happiness and prosperity that were bound to ensue. To make a fair estimate of the Emile and its Defects out- influence is not easy. It is necessary to put aside all of

weighed by '*^J^ ^r^*

merits. one's prejudices against the weak and offensive person

ality of the author, and to forget the inconsistencies and contradictions of the work itself. The *Emile* has always been accounted a work of great richness, power, and underlying wisdom, and each of its defects is more than balanced by a corresponding merit. Moreover, the most fundamental movements in modern educational progress - sociological, scientific, and psychological - may be said to have germinated through the *Emile.* The Sociological Movements in Modern Education. - The most marked feature of the Rousselian education and the one most subject to criticism has been its ex

Reyoit from treme revolt against civilization and all social control. 'A state of nature is held to be the ideal condition, and all social relations are regarded as degenerate. The child is to be brought up in isolation by the laws of brute necessity and to have no social education until he is fifteen, when an impossible set of expedients for bringing him into touch with his fellows is devised. One should remember, however, that the times and the cause had<span id="ch19.xml#para.276.1.0.box.151.236.1266.1392.q.60" class="gtxt_body"> he was able to emphasize the crying need of a natural development of man, and to tear down the effete traditions in educational organization, content, and methods. And many of the social movements in modern educational organization and content were made possible and even suggested by him, after having thus cleared the ground. He held that all members of society should be trained industrially so as to contribute to their own support and should be taught to be sympathetic and benevolent toward their fellows. Thus through him education has been more closely related to human welfare. The in- followed <span style="font-variant:small-caps;">Rou\^ </span>dustrial work of Pestalozzi and Fellenberg, the moral aim socr~a~i^stressed^ of education held by Herbart, the 'social participation' in ^activitiea^the practice of Froebel, and the present-day emphasis upon vocational education, moral instruction, and training of defectives and of other extreme variations, alike find some of their roots in the *Emile.* In fact, the fallacy involved in Rousseau's isolated education is too palpable to mislead anyone, and those who have best caught his spirit and endeavored to develop his practice have in all cases most insistently stressed social activities in the training of children and striven to make education lead to a closer and more sympathetic cooperation in society. The Scientific Movement in Modern Education. - Moreover, since Rousseau repudiated all social traditions SSw'buteS and accepted nature as his only guide, he was absolutely P^hasi^j?d ot\></span>

but extreme need of just so extreme a doctrine. Such radical in

doctnne . , - .

needed, dividualism alone could enable him to break the bondage

to the past. By means of paradoxes and exaggerations

*^c^ ^J^* °' *^J^* servational

opposed to all book learning and exaggerated the value ^work^- of observation?"'He consequently neglected the past, and would have robbed the pupil of all the experience of his fellows and of those who had gone before. But he emphasized the use of natural objects in the curriculum and developed the details of nature study and observa-

tional work to an extent never previously undertaken. Partly as a result of this influence, schools and colleges have come to include in their course the study of physical forces, natural environment, plants, and animals. Therein Rousseau not only anticipates somewhat the nature study and geography of Pestalozzi, Basedow, Salzmann, and Ritter, but, in a way, foreshadows the arguments of Spencer and Huxley, and the modern scientific movement in education. The Psychological Movements in Modern Educative ufknowi-^0^" \^^on^' - A matter of even greater importance is Rousedge of chii- ~se~au's belief that education should be in accordance with

dren, Rousseau

saw the need the natural interests of the child. Although his knowl

of studying

them. edge of children was defective, and his recommendations

were marred by unnatural breaks and filled with sentimentality, he saw the need of studying the child as the only basis for education. In the Preface to the *Emile* he declares that "the wisest among us are engrossed in what the adult needs to know and fail to consider what children are able to apprehend. We are always looking for the man in the child, without thinking of what he is before he becomes a man. This is the study to which I have devoted myself, to the end that, even though my whole method may be chimerical and false, the reader may still profit by my observation." As a result of such appeals, the child has become the center of discussion in modern training. Despite his limitations and prejudices, this unnatural and neglectful parent stated many details of child development with much force and clearness and gave an impetus to later reformers.

In this connection should especially be considered Rousseau's theory of stages of development. He makes<span id="ch19.xml#para.278.1.0.box.138.233.1266.1232.q.60" class="gtxt_body"> a sharp division of the pupil's development into definite \^\^iMtur\^ periods that seem but little connected with one another, *^ia^e-'* and prescribes a distinct education for each stage. This seems like a breach of the evolution of the individual, and the *reductio ad absurdum* of such an atomic training is reached in his hope of rendering Emile warmhearted and pious, after keeping him in the meshes of self-interest and doubt until he is fifteen. But, as in the case of his attitude toward society, Rousseau takes an extreme view, and he has thereby shown that there are characteristic differences at different stages in the child's life, and that only as the proper activities are provided for each stage will it reach maturity or perfection. He may, therefore, be credited to a great degree with the increasing tendency to cease from forcing upon children a fixed method of thinking, feeling, and acting, and for the gradual disappearance of the old ideas that a task is of educational value according as it is distasteful, and that real education consists in overcoming meaningless difficulties. Curiosity and interest rather are to be used as motives for study, and Rousseau therein points the way for the Herbartians. It is likewise due to him primarily that we have recognized the need of physical activities Physical ac</span>

*°* ^r^' tivities and

and sense training in the earlier development of the sense training. child as a foundation for its later growth and learning. To these recommendations may be traced much of the object teaching of Pestalozzianism and the motor expression of Froebelianism. Thus Rousseau made a large contribution to educational method by showing the value of motivation, of creating problems, and of utilizing the senses and activities of the child, and may be regarded as the father of the psychological movements in modern

education. He could not, however, have based his study of children and his advanced methods upon any real psychological foundation, for in his day the 'faculty' psychology (see p. 182) absolutely prevailed. Instead of Sympathetic working out his methods from scientific principles, he

understanding *~m~"* ~\#~ . .

of the child, obtained them, as did Pestalozzi afterwards, through his sympathetic understanding of the child and his ability to place himself in the child's situation and see the world through the eyes of the child.

The Spread of Rousseau's Doctrines. - Thus seeds of many modern developments in educational organization, method, and content, were sown by Rousseau, and he is

intellectual ~seen~ t~0~ b~e~ the intellectual progenitor of Pestalozzi,

progenitor of <span style="font-variant:small-caps;">Jt </span>o *i*

modern re- Herbart, Froebel, Spencer, and many other modern

formers, but ' ..... ... ,

influence upon reformers. But his principles did not take immediate mediate. hold on the schools themselves, although their influence

is manifest there as the nineteenth century advanced. In France they were apparent in the complaints and recommendations concerning schools in the lists of desired reforms *(cahiers)* that were issued by the various towns, and afterward clearly formed a basis for much of the legislation concerning the universal, free, and secular organization of educational institutions. In England\^\_ since there was no national system of schools, little direct impression was made upon educational practice. But in America this revolutionary thought would seem to have had much to do with causing the unrest that gradually resulted in upsetting the aristocratic and formal training of the young and in secularizing and universalizing the public school system. The first definite attempt, however, to put into actual practice the naturalistic education of Rousseau occurred in Germany through

the writings of Basedow and the foundation of the fhrough^te^Ba^P^se'Philanthropinum,' and is of sufficient importance to ^dow^demand separate discussion.

Development of Basedow's Educational Reforms. - Johann Bernhard Basedow (1723-1790) was by nature the very person to be captivated by Rousseau's doc- \^-J\^ ~by~ trines. He was talented, but erratic, unorthodox, tact- Rousseau's

doctrines.

less, and irregular in life. He had been prepared at the University of Leipzig for the Lutheran ministry, but proved too heretical, and, giving up this vocation, became a tutor in Holstein to a Herr von Quaalen's children. With these aristocratic pupils he first developed methods of teaching through conversation and play connected with surrounding objects. A few years after this, in 1763, Basedow fell under the spell of Rousseau's *Emile,* which was most congenial to his methods of thinking and teaching, and turned all his energy toward educational reform. As in the case of Rousseau with education in France, he realized that German education of the day was sadly in need of just such an antidote as 'nat- \^"jf"\^\^ uralism' was calculated to furnish. The schoolrooms naturalism. were dismal and the work was unpleasant, physical training was neglected, and the discipline was severe. Children were regarded as adults in miniature (Fig. 25), and were so treated both in their dress and their education. The current schooling consisted largely of instruction in artificial deportment. The study of classics composed the entire intellectual curriculum, and the methods were purely grammatical. As a result, suggestions made by Basedow for educational improvement attained as great popularity as his advanced theological propositions had received abuse.

In 1768 by his *Address on Schools and Studies, and their Influence on the Public Weal,* he called generally upon princes, governments, ecclesiastics, and others in power, to assist him financially in certain definite educational reforms. In addition to suggesting that the schools be made nonsectarian and that public instruction be placed under a National Council of Education, he proposed that, in contrast to the formal and unattractive training of the day, education should be rendered practical in content *<span style="font-variant:small-caps;">Am\^s </span>*°and^S^ ^an^d playful^m^ method. To assist this reform, he planned hU^d^t^U^xt'book? ^to^ b^rul^S ^out^ ^a^ work on elementary education, which he described in outline. Great interest in his proposals was shown throughout Europe by sovereigns, nobles, prominent men, and others desiring a nonsectarian and more effective education, and a subsidy of some ten thousand dollars was speedily raised, to enable him to perfect his plans. Six years later, Basedow completed his promised text-book, *Elementarwerk,* and the companion work for teachers and parents known as *Methodenbuch.* The *Elementarwerk* was accompanied by a volume containing ninety-six plates, which illustrated the subject-matter of the text, but were too large to be bound in with it. While in these manuals Basedow included many naturalistic ideas from Rousseau, he also embodied features from other reformers and even additions of his own. *Elementarwerk* Text-books and Other Works. - The *Elementarwerk* clearly combines many of the principles of Comenius as well as of Rousseau. It has, in fact, been often called 'the *Orbis Pictus* (see p. 170) of the eighteenth century, ' and *Metkoden-* ^anc^\* gl^ves^ ^a^ knowledge of things and words in the form *^buch^-* of a dialogue. The *Methodenbuch,* while not following<span id="ch19.xml#para.282.1.0.box.140.239.1250.1115.q.60" class="gtxt_body"> Rousseau completely, contains many ideas concerning natural training that are suggestive of him. In this study of the nature of children, the book makes some advance upon the Rousselian doctrine by finding that they are especially interested in motion and noise, although Basedow would have shocked Rousseau by being so much under the control of tradition as to suggest using these interests in the teaching of Latin. Later, Basedow, together with Campe, Salzmann, and others of his followers, also produced a series of popular story books especially adapted to the character, interests, and needs of children. These works are all largely filled with \^~k~^u^~s~^Ia^/~0~r^tory^ didactics, moralizing, religiosity, and scraps of scientific children. information. The best known of them is *Robinson der Jungere* (Robinson Crusoe Junior), which was published by Campe in 1779. It seems to have been suggested by Rousseau's recommendation of *Robinson Crusoe* as a text-book, and in turn a generation later it became the model for *Der Schweizerische Robinson* (The Swiss Family Robinson) of Wyss, which has been so popular with children in America and elsewhere.</span>

Course and Methods of the Philanthropinum. - Eight years before this, however, Prince Leopold of Dessau had been induced to allow Basedow to found there a model school called the 'Philanthropinum,' which should embody that reformer's ideas. Leopold granted him a generous salary, and three years later gave him an equip- Salary, equipment of buildings, grounds, and endowment. At first Basedow had but three assistants, but later the number was considerably increased. The staff then included ^teachers^several very able men, such as Campe, formerly .chaplain at Potsdam, and Salzmann, who had been a professor

at Erfurt. The underlying principle of the Philanthropinum was 'everything according to nature.' The natural instincts and interests of the children were only to be directed and not altogether suppressed. They were to and pupils. jj~e~ trained as children and not as adults, and the methods of learning were to be adapted to their stage of mentality. That all of the customary fashion and unnaturalness might be eliminated, the boys were plainly dressed and their hair cut short. cation^rS^but^edu^ While universal education was believed in, and rich social distinc- ~an~d p~00r~ ~a~lik~e~ ~were~ to be trained, the traditional idea

tions. *^r^*

still obtained that the natural education of the one class was for social activity and leadership, and of the other for teaching. Consequently, the wealthy boys were to spend six hours in school and two in manual labor, while those from families of small means labored six hours and training^\*^' studied two. Every one, however, was taught handicrafts, - carpentry, turning, planing, and threshing, as suggested in the third book of the *Entile,* and there were also physical exercises and games for all. On the intellectual side, while Latin was not neglected, considerable attention was paid to the vernacular and French. In keeping with the *Elementarwerk,* Basedow planned a wide objective and practical course very similar to that suggested by Comenius. It was to give some account of man, including bits of anthropology, anatomy, and physiology; of brute creation, especially the uses of domestic animals and their relation to industry; of trees and plants with their growth, culture, and products; of minerals and chemicals; of mathematical and physical instruments; and of trades, history, and commerce. He afterward admitted that he had overestimated the<span id="ch19.xml#para.284.1.0.box.136.234.1049.97.q.70" class="gtxt_body"> amount of content that was possible for a child, and greatly abridged the material.</span>

and wide objective course.

The most striking characteristic of the school, however, was its recognition of child interests and the consequently improved methods. Languages were taught by Jf~u~^n^\^^a^b^es^~con~ speaking and then by reading, and grammar was not versation and brought in until late in the course. Facility in Latin was acquired through conversation, games, pictures, drawing, acting plays, and reading on practical and interesting subjects (Fig. 26). His instruction in arithmetic, geometry, Progressive

, , . methods in

geography, physics, nature study, and history was fully other subjecu. as progressive as that in languages, and, while continuing Rousseau's suggestions, seems to anticipate much of the 'object teaching' of Pestalozzi. Arithmetic was taught by mental methods, geometry by drawing figures accurately and neatly, and geography by beginning with one's home and extending out into the neighborhood, the town, the country, and the continent.

Influence of the Philanthropinum. - The attendance at the Philanthropinum was very small in the beginning, since the institution was regarded as an experiment, but eventually the number of pupils rose to more than fifty. Most visitors were greatly pleased with the school, p\^^1^ ^e^\*P^ec^' especially on account of the interested and alert appearance of the pupils. Kant declared that it meant "not a slow reform, but a quick revolution," although afterward he admitted that he had been too optimistic. While it may not have served well for older pupils, it was certainly excellent in its stimulus to children under ten or ^Stimulus^ ^for^

*^J^* younger

twelve, who can be reached by appeals to physical <span style="font-variant:small-caps;">P^u^p^!'s^- </span>activities and the senses better than by books. Basedow, however, proved temperamentally unfit to

Salzmann,

Similar Jnsti- direct the institution. Joachim Heinrich Campe (1746Campe, 1818), who first succeeded him, withdrew within a year to

found a similar school at Hamburg. Institutions of the same type sprang up elsewhere, and some of them had a large influence upon education. The most striking and enduring of these schools was that established in 1784 by Christian Gotthilf Salzmann (1744-1811) at Schnepfenthal under the patronage of the royal family of SaxeGotha. The natural surroundings - mountains, valleys, lakes - were most favorable for the purpose of the institution, and much attention was given to nature study, 'lessons on things,' organized excursions, gardening, agricultural work, and care of domestic animals. Manual training, gymnastics, sports, informal moral and religious culture, and other features that anticipated later developments in education also formed part of the course. During the decade before the establishment of Salzmann's school, institutions embodying many of Basedow's ideas were also opened at Rechahn and his other Brandenburg estates by Baron Eberhard von Rochow (1734-1805). His schools were simply intended to improve the peasantry in their methods of farming and living, but, when this step toward universal education proved extraordinarily successful, Rochow advocated the adoption of a complete national system of schools on a nonsectarian basis.

In 1793 the Philanthropinum at Dessau was closed

permanently. Its teachers were scattered through

Europe, and gave a great impulse to the new education.

Becomes a fad, Ai^1^ unfortunate result of this popularity was that the

pHshed^C^some Philanthropinum became a fad, and schools with this

good. name were opened everywhere in Germany by educa

and Rochow.

tional mountebanks. These teachers prostituted the system to their own ends, degraded the profession into a mere trade, and became the subject of much satire and ridicule. Nevertheless, the philanthropinic movement seems not to have been without good results, especially when we consider the educational conditions and the pedagogy of the times. It introduced many new ideas concerning methods and industrial training into all parts of France and Switzerland, as well as Germany, and these were carefully worked out by such reformers as Pestalozzi, Froebel, and Herbart. In this way there were embodied in education the first positive results of Rousseau's 'naturalism.'

**Supplementary Reading**

Graves, *In Modern Times* (Macmillan, 1913), chap. II; and *Great Educators* (Macmillan, 1912), chaps. VII and VIII; Monroe, *Text-book* (Macmillan, 190s), chap. X; Parker, S. C, *History of Modern Elementary Education* (Ginn, 1912), chaps. VIII-X. The *Emile* (Translated by Payne; Appleton, 1895) should be read, and the *Elementarwerk* (Wiegandt, Leipzig, 1909) should be examined. A judicial description of the life and work of Rousseau is that by Morley, J. (Macmillan), while Davidson, T., furnishes an interesting interpretation of *Rousseau and Education from Nature* (Scribner, 1902), but the standard treatise on *The Educational Theory of Rousseau* (Longmans, Green, 1911) at present has been written by Boyd, W. A good brief account of *Basedow: His Educational Work and Principles* (Kellogg, New York, 1891) is afforded by Lang, O. H. See also Barnard, H., *American Journal of Education,* vol. V, pp. 487-520.