# 21. The Period of Transition in American Education

**Outline**

-   Between the 'transplantation' period and that of the purely American conception of education was a distinctive stage in American education, - the 'period of transition.'
-   During this period Virginia and the other Southern states began to develop sentiment for universal education, and started permanent school funds and 'permissive' laws for common schools.
-   In the state of New York, appropriations were made for elementary education, but the public system was not really extended to the secondary field; while in New York City the way for universal education was prepared by quasi-public societies. In Pennsylvania, school districts were established at Philadelphia and elsewhere, but not until 1834 was the state system of common schools started. New Jersey and Delaware were even slower in getting their systems started.
-   The generous support of colonial education in Massachusetts was followed by a decline, and the control of schools was transferred from the towns to the districts. Academies were subsidized by the state and took the place of the grammar schools. A similar decline took place in the schools of the other New England states, except Rhode Island, which for the first time began to develop schools at public expense.
-   In the new states erected out of the Northwest Territory during this period there was a prolonged struggle to introduce common schools among those who had come from states not yet committed to this ideal, and state systems of education began to appear toward the close of the first quarter of the nineteenth century.
-   Thus before the educational awakening spread through the land, a radical modification had taken place in the European institutions with which America began its education.

**Evolution of Public Education in the United States.** - We may now return to our discussion of education in America. It has already been seen (chap. XVII) that the organization of schools in the various colonies was largely the result of educational ideals and conditions in the Mother Country. At first the schools of America closely resembled those of the European countries from which the colonists came, and the seventeenth century in American education is largely a period of 'transplantation.' But toward the middle of the eighteenth century, as new social and political conditions were evolving and the days of the Revolution were approaching, there were evident a gradual modification of European ideals and the differentiation of American schools toward a type of their own. America has long stood, in theory at least, for equality of opportunity, and this conception of society is apparent in its views of education. The distinguishing characteristic of the American schools has throughout been the attempt of a free people to educate themselves, and, through their elected representatives, the people of the various states have come, in harmony with the genius of American civilization, to initiate, regulate, and control their own systems of education. While the purely American conception of education cannot be fully discerned until almost the middle of the nineteenth century, there can for three quarters of a century before be clearly distinguished 'a period of transition' from the inherited ideals to those of America to-day. This intervening stage of evolution covers roughly the last quarter century of colonial life and the first half century of statehood. To it we must now direct our attention.

**Rise of the Common School in Virginia.** - By the opening of the period, as we noted (p. 193), Virginia had voluntarily made a fair provision for secondary and higher education in various localities, but as yet no real interest in common elementary schools had been shown by the responsible classes. The nearest approach to such institutions was found in the plantation 'field school.' Organized by a group of neighbors, these schools were supported by tuition fees and were not dependent upon any authority other than the good sense of the parents and pupils. But by the close of the Revolution a desire for genuine public education began to appear. The leader in the movement was the great statesman, Thomas Jefferson. As early as 1770, he first introduced into the legislature a scheme of universal education. His bill proposed to lay off all the counties into small districts five or six miles square, to be called 'hundreds.' Each hundred was to establish at its own expense an elementary school, to which every citizen should be entitled to send his children free for three years, and for as much longer as he would pay. The leading pupil in each school was to be selected annually by a school visitor and sent to one of the twenty 'grammar' (i. e. secondary) schools, which were to be erected in various parts of the state. After a trial of two years had been made of these boys, the leader in each grammar school was to be selected and given a complete secondary course of six years, and the rest dismissed. At the end of this six-year course, the lower half of the geniuses thus determined were to be retained as teachers in the grammar schools, while the upper half were to be supported from the public treasury for three years at the College of William and Mary, which was to be greatly expanded in control and scope.

This comprehensive plan for a system of common schools was, in the face of most discouraging opposition, constantly adhered to by Jefferson, although he did not live to see universal education an accomplished fact. He did, however, stimulate some movements toward this end. In 1796 the legislature passed an ineffective law whereby the justices of each county were permitted to initiate a school system by taxation, and in 1810 a 'literary fund' was established for public education. When, in 1816, this fund had been increased to a million dollars, those in charge of it recommended to the legislature the establishment of "a system of public education, including a university, to be called the University of Virginia, and such additional colleges, academies, and schools as should diffuse the benefits of education through the Commonwealth." This revision of Jefferson's suggestion did not immediately result in any legal steps toward universal education, except the appropriation in 1818 of \$45,000 from the income of the literary fund to have the poor children of each county sent to a proper school, but it did bring about in 1820 the foundation of the University of Virginia and a generous grant for the erection of a set of buildings. In the same year the effectiveness of the 'permissive' law for common schools of 1796 and of the appropriation act of 1818 was somewhat strengthened by the division of the counties into districts, among which the appropriation for education of the poor was distributed and managed by special commissioners.

While this law marked one more step in advance, it was hampered by several of the features that in various states continually delayed the establishment of common schools at public expense. In the first place, it was based on the conception of public education as poor relief, rather than universal training for citizenship. It was often viewed with hostility or indifference by the wealthy, cation, who felt that they were paying for that from which they received no benefit, and with pride and scorn by the poor, who refused to be considered objects of charity. Moreover, the sum distributed (\$45,000) was totally inadequate for over one hundred thousand children, and every variety of school, private as well as public, was subsidized without distinction. The system lacked a strong central organization, and the commissioners, often appointed by the county judges from the classes most opposed to the arrangement, were notoriously inefficient. The teachers also were generally incompetent, as it was practically impossible to persuade college or academy graduates to undertake the instruction of the poor. Nevertheless, under this apology for a people's common school, the state went on for a score of years, and there was a steady growth in the literary fund, the appropriations, the length of the school term, and the number of pupils who were willing to take advantage of such opportunities as it afforded. State officials of wide vision, moreover, sought in every way to improve the teaching corps and the defective administration. While the great majority of the school children still attended the denominational, private, and 'field' schools (see p. 253), this system of subsidies was educating public opinion for something better. By the close of the first half century of statehood, while Virginia was not yet ready to establish a complete system of public education, we shall later (seepp.327f.) find that the ground had been prepared for the development of common schools that was spreading throughout the country.

**Similar Developments in the Other Southern States.** - This advance toward the common school in Virginia is typical of the South. The development in Maryland was very similar to that of Virginia. The state began to move slowly toward universal education by subsidizing the education of the poor (1816), and by the passage of a 'permissive' law for common schools in the counties (1825). In South Carolina an annual appropriation for 'free schools' was started in 18.11. A law was passed establishing a number of schools in each election district equal to that of its members in the legislature and providing \$300 for each school. But these schools were largely regarded as pauper institutions, and, because legislative representation was based upon property, the distribution of the appropriation was very inequitable, for the inland parts of the state, which most needed assistance, received least. Yet the amount of appropriation gradually increased, and sentiment for universal education steadily developed. Within the first half dozen years of statehood, Georgia began the provision of land endowment for schools, and the organization of a state system under the title of the 'University of Georgia.' While the value of the land was too small to establish a genuine system of public education so soon, before the close of the transition period, a permanent school fund had been started, and sentiment for public education had begun to grow. North Carolina made even earlier progress toward common schools. The constitution of 1776 provided for the establishment of schools, and, by 1817, at the request of the legislature, Judge Archibald D. Murphy, a statesman with broad educational traditions, even formulated an elaborate plan for a complete system of public schools. This scheme failed, because it proposed to 'maintain,' as well as educate, the children of the poor. But the suggestions of the Murphy committee shortly brought about the establishment of a 'literary,' or common school fund (1825), the income of which was to be used for the support of public schools.

In the case of the other Southern commonwealths, which were admitted after the union had been formed, there was similarly a very gradual growth of sentiment and afterward for universal education. In every state there appeared an alliance between far-sighted statesmen and educators and the great middle class of citizens for the purpose of establishing common schools for all white children, and the old ecclesiastical and exclusive idea of education was beginning to fade. By the close of the first half century of national existence, a public system had not actually materialized in any of the states, but most of them had begun to create 'literary funds,' subsidize schooling for the poor, and enact 'permissive' laws for establishing public schools. Except in Virginia and South Carolina, provisions had been made for general administration in state, county, and district; and in North Carolina the organization of a complete common school system awaited only a first hint of the great educational awakening (1835-1860). Moreover, most of the larger cities -  Baltimore, Charleston, Louisville, Nashville, Memphis, Mobile, New Orleans - had already organized a regular system of public schools, and all of the older commonwealths had made some attempt at supporting a state institution of higher learning, which was virtually the head of a public school system. The various denominations had begun to found colleges in some numbers, but even these institutions were not so strictly ecclesiastical as William and Mary started out to be, and assumed a wider function than merely training for the ministry, while the aristocratic and classical 'grammar' schools had largely given way to the 'academies' (Fig. 32), which were nonsectarian, democratic, and more comprehensive in their curriculum.

**Evolution of Public Education in New York.** - After the English took possession of New York, we have seen (p. 195) how that territory lapsed into the *laissez jaire* support of education. The upper classes of society largely sought their education abroad or through tutors and the clergy, although in 1754 King's College (now Columbia University) was founded, and during the century a number of secondary schools were organized and granted gratuities by the legislature. The few elementary schools that existed were either private or maintained by some church or philanthropic society. As already shown (pp. 234 ff.), this was the period distinguished for the schools founded by the Society for the Propagation of the Gospel. At the close of the Revolution, however, the various elements of the population had been welded together in the common struggle, and a sentiment for public education began to prevail over vested interests and sectarian jealousies. A series of broad-minded governors - the Clintons, Lewis, Tompkins, and Marcy - constantly reminded the legislature of its duty to establish common schools. In 1787 a system of public education was theoretically organized under the management of a Board of Regents, with the title of 'The University of the State of New York,' but it did not include elementary schools. Two years later in each township were set apart for the endowment of common schools, and in 1795 it was enacted that the sum of \$50,000 for five years should be distributed for the encouragement of elementary education in counties where the towns would raise by taxation half as much as the amount of their share. This arrangement was not carried on beyond the five years, but in 1805 the proceeds from 500,000 acres of land were appropriated for a com- mon school fund, which was not to be used until the interest reached \$50,000 per annum.

In 1812 further organization was enacted whereby a state superintendent of common schools was to be appointed, and the county unit replaced by a more democratic town and district basis. But it had been supposed that the state fund would provide for the entire support of the schools, and there still remained an obstinate opposition to local taxes. The towns, however, were gradually persuaded to raise the amount required to secure their share of the state donation. Much progress was brought about through the first superintendent, Gideon Hawley, and while, after eight years of service, he was removed by political manipulation and the office combined with the secretaryship of state, each of his successors undertook to distinguish the educational side of his administration by some marked advance or improvement in the common schools. But for a generation the academies and colleges remained under supervision of the regents, and, except for state appropriations to academies, no one undertook to extend the public system into secondary and higher education. Moreover, the professional training of teachers in the academies was encouraged by the state, and thereby the organization of normal schools was delayed. Hence, while New York started the first system of public education adjusted to the political and social conditions of the new nation, and probably had the most effective schools of the times, not until the great period of common school development (1835-1860) were its people fully willing to contribute for a general school system, make it entirely free, or develop it consistently in all directions.

**New York City.** - Meanwhile, an interesting development of educational facilities was taking place in New York City. In 1805 the opportunities offered in the private, church, and charity schools were seen by certain of the most prominent citizens to be totally inadequate for a city of seventy-five thousand inhabitants, and a 'Free School Society' was founded to provide for the boys who were not eligible for these schools. The president was De Witt Clinton, afterward governor, and in 1806 the first school was opened, from motives of economy, upon the monitorial basis (see p. 241). The state fund did not reach a sufficient amount to be available until 1815, but special gifts were made to the school society from time to time by the legislature, the city, and private individuals, and there was a rapid increase in the number of the society's schools during the first quarter of a century. In 1826 the legislature authorized the organization to charge a small tuition fee and change its name to the 'Public School Society.' While the fee system was soon found to injure the efficiency of the work, and was abolished within six years, the new title persisted, as it did not suggest pauperism in the way the old name had. In 1828 the society was allowed the benefit of a small local tax. For quite a time the work of the association was unhindered, but in 1820-1825 a vigorous effort was made to obtain a share of the state appropriation for the sectarian schools of the Bethel Baptist Church. This move was finally defeated, but the Roman Catholics made a more successful protest fifteen years later by indicating that the society, while nominally nonsectarian, was really Protestant. To settle this dispute, the legislature in 1842 established a city board of education, and after eleven years the institutions of the Public School Society were merged in this city system. Thus was the way prepared for a public school system in New York City, and this development was typical of the training of educational sentiment through quasi-public societies that took place in Buffalo, Utica, Oswego, and several other cities.

**Development of Systems of Education in Pennsylvania and the Other Middle States.** - The rise of public systems in the other Middle states was also gradual. In Pennsylvania, the state system slowly arose through a prolonged stage of 'poor schools.' The new constitution (1790) of the state declared: "The legislature shall, as soon as conveniently may be, provide by law for the establishment of schools throughout the State, in such manner that the poor may be taught gratis." Men of broad vision, like Franklin, Benjamin Rush, and Timothy Pickering, had striven hard to have popular education introduced, but the general sentiment of the times could not reach beyond providing free education for the poor. Moreover, although this moderate constitutional provision was a compromise, it was not until some years later (1802, 1804, and 1809) that the legislature passed acts to make it effective. Even then public institutions to fulfill the legislation were not established, but it was arranged that the tuition of poor children should be paid for at public expense in private, church, and neighborhood schools, and the proceeds of the sixty thousand acres of land appropriated for 'aiding public schools' went to subsidize private institutions. But the idea of common schools continued to develop, and governors and other prominent men constantly called attention to the need of universal education. Philadelphia was the first municipality to be converted, and in 1818, under a special act of the legislature, it became 'the first school district of Pennsylvania,' with the power to provide a system of education on the Lancasterian plan at public expense. After three or four years this special legislation was extended to five more 'districts', and in 1824 a general law permitting the establishment of free schools in any community was enacted, though soon repealed.

Finally, in 1828, 'the Pennsylvania Society for the Promotion of Common Schools,' after demonstrating the ineffectiveness of the 'pauper school' law in a series school fund of memorials, succeeded in having a state school fund established, and in 1834, "an act to establish a general system of education by common schools" was passed. This law established a state system of schools under the general superintendency of the secretary of state. For this system it appropriated \$75,000 per annum from the income of the state school fund, and permitted the wards, townships, and boroughs, which it constituted school districts, to share in this, provided they levied local taxes for schools. The Northern counties, settled mostly by New England colonists, and the Western portion of the state, with its large element of Scotch-Irish Presbyterians, ardently favored this encouragement of universal education, but the law was only 'permissive' and was bitterly opposed by the Quaker and German inhabitants of 'old' Pennsylvania, who feared that their own parochial schools would be replaced. The wealthy classes were also hostile to the new law, on the ground that they ought not to be taxed to educate other people's children. In a vigorous campaign to repeal the act, however, the opponents of the law, largely through the eloquent speech of Thaddeus Stevens, were defeated the following year (1835), and the desire to establish public schools was greatly increased in 1836 by the passage of a new law, which enlarged the annual appropriation to \$200,000, in which the school districts might participate only on condition of local taxation. Even then not more than one-half the districts took advantage of the opportunity, and it was several years before most of them claimed their share. Hence, while the battle was won by 1835, the consummation of public education in Pennsylvania did not take place until the great awakening of common schools had swept over the country. After the formation of the Union, New Jersey and Delaware met with the same kinds of hindrance to the development of common schools as did Pennsylvania, and they were even slower in getting a system established.

In both commonwealths a state school fund was started early in the nineteenth century, but it was not distributed for about a dozen years, and then it was used mostly for the education of paupers in subsidized private schools. Some 'permissive' legislation for the organization of school districts and commissioners and the establishment of public schools was also passed, but it accomplished little before the middle of the century.

**Decline of Education in Massachusetts.** - In Massachusetts, on the other hand, efforts for the provision of universal training degenerated during the eighteenth century. The generous support of public education that had been started in 1647 was followed by a period of decline for about a century and a half. The causes of this decadence of local interest in education were rather complicated. In the first place, the complete domination of Calvinism gradually disintegrated and was replaced by a toleration of several creeds. The non-Puritans, who were constantly increasing in numbers, were obliged by the law of 1638 to preserve an outward conformity to the Calvinistic regime under penalty of banishment, but by 1662 a compromise was granted, whereby persons not conforming in every respect might be admitted to all church privileges, except communion, and the persecution of Quakers, Baptists, and other sects was largely abandoned. In 1670 came the successful secession of the Old South Church from the original church of Boston, as the result of a quarrel concerning this very compromise, and within a decade the Baptists were permitted to build a meeting-house in Boston. By 1692 recognition had been largely granted to all Protestant beliefs, and to be a 'freeman,' or voter on all colonial questions, it was no longer necessary to be a member of a Puritan church. While every town was still required to support by tax an orthodox pastor, by 1728 the Episcopalians, Quakers, and Baptists were permitted to pay their assessments to their own ministers, and the alliance of the State with a despotic Church, which had made possible the system of public education, was largely broken.

Moreover, there was a decided lowering of intellectual standards upon the part of the colonists. The hard struggle to wring a living from an unpropitious soil, and the disturbances due to wars, Indian skirmishes, and the difficulties of pioneer life greatly lessened their feeling of need for a literary training. Another reason for the educational decline was the dispersion of the population in the towns. At first, because of possible attacks by the Indians, a law forbade any dwelling to be built more than half a mile from the church and school, and not infrequently the school was equipped with a watchtower (Fig. 22). But, as the best land near the center was more and more taken up, the towns spread out in various directions, and the intervening hills, streams, swamps, and poor roads, together with the fear of Indians and wild animals, greatly hindered those on the outskirts in reaching the church and school of the town. As a result of all these conditions, the towns, most of which had been eager to establish schools even before being compelled to do so, began to seek various methods of evading the school law without incurring the fine. The minister was at times made the nominal schoolmaster, or a teacher was even employed during the session of the 'General Court' (i. e., legislature) and discharged upon adjournment. Laws were enacted against these subterfuges, greater vigilance was exercised, and the fine was increased first to £10 (1671) and then to £20 (1683), with a progressive increase where the number of families ran over one hundred (1712). Thus the fine came to be almost sufficient to support a schoolmaster, and it was made more and more unprofitable for a town to disobey the law.

Under these circumstances it became advantageous to many citizens, especially those at the center of a town, to have the entire support of the school come through general taxation rather than partially by means of tuition fees. But the people in the more distant portions of the town refused to vote a rate from which they themselves obtained no profit. They demanded that, in return for their taxes, the public school should be brought nearer to them. Probably they were influenced in this stand by the fact that private 'dame' schools, and possibly elementary schools, had for some time been opened in various parts of the town conveniently near their homes. Another factor that may have aided in suggesting this solution was the legal recognition of various remote settlements within the town, known as 'parishes' or 'districts,' through the grant of self-government, separate church organizations, and other privileges similar to those of the town as a whole, though on a smaller scale. At any rate, we find that in the early part of the eighteenth century, wherever a rate was adopted as the sole means of school support, it was agreed that, instead of holding the town school for twelve months in the center alone, opportunities should be offered for a fraction of that period in various portions of the town. Usually the compromise at first took the form of having one town master teach in different districts through the year, and the result was known as a 'moving' school. This necessitated holding the school in a number of isolated communities, and the temple of learning often came at first to be located in a private house, usually in the kitchen. And although, in time, another room was added to the farm house for the accommodation of the school, the institution has since then been known as a 'kitchen school' (Fig. 30). But, by a later development, when separate schools under different masters or mistresses came to be taught at the same time, the town school was said to be'divided.' Then in the winter, when the big boys were out of the fields and came to school, the session was held in the center of the town, and usually required the brawn of a man. But in summer, when only the younger children could attend, schools were held in various parts of the town and were taught chiefly by women (Fig. 31). The divisions of the town that thus came to be recognized were allowed more and more control of their schools until they practically became autonomous. Before the time of the Revolution 'divided schools' were recognized as a regular institution, and, together with other customs that had grown up during the eighteenth century, they were given legal sanction and denominated 'district schools' in the law of 1780. By 1800 the districts were not only allowed to manage their own share of the town taxes, but were authorized to make the levy themselves; in 1817 they were made corporations and empowered to hold property for educational purposes; and in 1827 they were granted the right to choose a committeeman, who should appoint the teacher and have control of the school property.

Thus the year 1827 "marks the culmination of a process which had been going on for more than a century, - the high-water mark of modern democracy, and the low-water mark of the Massachusetts school system." The district system did in its earlier stages bind the families of a neighborhood into a corporation whose intent was the most vital of human needs, - education, and the people came to feel the necessity of supporting it by their own generous contributions. But in the course of time the districts became involved in private and petty political interests, and had but little consideration for the public good. The choice of the committeeman, the site, and the teacher caused much unseemly wrangling, and as each received only what it paid in, the poor district obtained only a weak school and that for but a short term. The increasing expense of the district system had also made it impossible for any except the larger towns to support the old-time 'grammar' school, and this part of the old school requirements had fallen into disuse before the close of the eighteenth century. To meet the needs of secondary education, the policy of endowing 'academies' (Fig. 32) with public lands, in Maine had gradually grown up, and this custom was legalized in 1797. Seven academies, - four in Massachusetts proper and three in the province of Maine, had originally been endowed with a township apiece, and some fourteen more had been chartered by towns at an early date, and empowered by the state to hold educational funds. By the time of the educational awakening there were some fifty of these private secondary institutions subsidized by the state, although managed by a close corporation. The first public high school had been established in Boston (1821), but this type of secondary school had not begun to have any influence as yet. Into such a decadence had the liberally supported system of public education fallen, before the rapid development in common schools began and the influence of Horace Mann and other reformers was felt.

Fig. 32. - The first 'academy,' founded by Benjamin Franklin at Philadelphia in 1750, and later developed into the University of Pennsylvania.

(Fig. 41)

**Developments in the Other New England States.** - The development of common schools in Massachusetts may be considered typical of New England in general, except Rhode Island. Connecticut similarly degenerated into a district system, which was recognized by law in 1794, and was destined later to constitute one of the greatest problems during the period of educational development (see pp.313 and 320). Vermont likewise made provision for town and district schools, and eventually established a state school fund and school commissioners, but this legislation was soon repealed, and the schools of the state were in a parlous condition when the awakening found them. New Hampshire and Maine also present very similar features. In Rhode Island the voluntary organization of education continued throughout the eighteenth century. In 1800 a law permitting each town to maintain 'one or more free schools' was passed, but no municipality availed itself of this permission, except Providence, and the act was repealed in 1803. The basal state law for common schools was not passed until 1828, when at length \$10,000 was appropriated, and each town was required to supplement its share by such an amount as should annually be fixed in town meeting.

**The Extension of Educational Organization to the Northwest.** - It is thus evident that by the close of the first half century of the republic, there was everywhere slowly growing up a sentiment for public education. The development of common schools had, however, been greatly hindered in the Southern states by the separation of classes in an aristocratic organization of society. Yet the superior class had shown no lack of educational interest in their own behalf and had through the facilities offered reared a group of intellectual leaders, some of whom, like the far-sighted Jefferson, had caught the vision of universal education. The great diversity of nationality and creed in the Middle states, on the other hand, had fostered sectarian jealousies and the traditional practice of the maintenance of its own school by each congregation. This had proved almost as disastrous to the rise of a system of public schools, although Pennsylvania, and even more New York, had well begun the establishment of a public system. In both sections of the country public education was at first viewed as a species of poor relief, and the wealthy were unable to see any justice in being required to educate the children of others. As a result, the young 'paupers' at times had their tuition paid in private schools, and these institutions were not infrequently allowed to share in public funds. The New England states, however, as a result of the homogeneity of their citizens, had early adhered to a system of public schools for all, organized, supported, and supervised by the people. While the efficiency of their common schools was eventually crippled by the grant of autonomy to local districts and the arising of petty private and political interests, they had initiated this unique American product, - a public system for all, dependent upon local support and responsive to local wishes.

This growth of a 'common schools consciousness' was destined, as the result of a great educational awakening, to increase rapidly during the second quarter of the nineteenth century in the Middle and Southern, as well as the New England, states. But before describing this development further, it is important to see the effect of the ideals of these three sections of the country when introduced into a new part of the United States by emigrants from the older commonwealths. The new domain referred to was those large tracts of unsettled territory, belonging, according to claims more or less overlapping, to six or seven of the original states, and finally (1781), in settlement of these disputes, ceded to the federal government, with the understanding that the territory should be 'formed into distinct republican States.' After much discussion and various acts of Congress for half a dozen years, the famous 'Ordinance of 1787' was passed for the government of this 'Northwest Territory.' An earlier act (1785) had divided the entire territory into townships, six miles square, after the New England system, and of the thirty-six sections into which each township was subdivided, section sixteen was reserved for the support of public schools. A special contract also started the practice of providing two townships for the establishment of a university in each state. These provisions were later extended to the vast territory purchased from France in 1803 and known as ' Louisiana,' and to all the other territory afterward annexed to the United States. This federal land endowment gave an additional stimulus to the establishment of public education in the four commonwealths - Ohio, Indiana, Illinois, and Michigan - that were admitted from the Northwest Territory before 1840. But the final system of public education in these new states took form slowly for various reasons. The settlers were poor; incessant Indian wars, the wilderness, wretched roads, and lack of transportation facilities tended to repel immigrants and leave the country sparsely settled; the large tracts of school land were slow in acquiring value, and, to attract settlers, were often leased at nominal rates or sacrificed at a small price; and social distinctions and sectarian jealousies persisted among the immigrants. As a whole, immigration from the earlier commonwealths had followed parallels of latitude, and the northern parts of Ohio, Indiana, and Illinois were occupied mostly by people from New England and New York, and the southern by former inhabitants of Virginia, Kentucky, Tennessee, Louisiana, and other states where the public school system was not yet as well developed. In Michigan, however, because of its northerly location, the great influx throughout the state had come from New York, New England, and Northern Ohio.

Consequently, the history of public education in the first three of the new states seems to be in each case largely a record of a prolonged struggle to introduce common schools among those of the people who had come from states not yet committed to this ideal, but Michigan, whose inhabitants had migrated from states where public education was in vogue, showed the germs of a public system even before statehood was conferred. The history of the common schools in Ohio, Indiana, and Illinois is very similar in general outline. Each one started off by claiming two townships of land for a university and the sixteenth section for schools, and the state constitution committed it to equal school opportunities for all. But not until the close of the first quarter of the nineteenth century was a system of common schools, with the organization of districts, appointment of school officers, and local taxation provided by the legislature. Even then the acts were largely 'permissive,' the tax was not exacted from anyone who objected, and for some time various laws allowed public funds to be paid to existing private schools for the tuition of the poor. The complete system with a state superintendent was first organized in Ohio by 1836, but a similar stage of development was not reached by the other two states until after the great wave of common school development (1835-1860) had passed over the country. Michigan, on the other hand, as early as 1817 established a 'catholepistemiad,' which was to include a university and a system of schools of all grades, and a dozen years later in its revision of the school laws provided for a department of Education at the university and a territorial superintendency of schools. While under this law of 1829 tuition fees were to be required, except from the poor, by the first state constitution in 1837 the school lands were taken over from the wasteful management of the towns, and a public school was required to be open for three months in every district. The state superintendency was also established, and before 1840 Michigan was well started with a complete system of common schools.

**Condition of the Common Schools Prior to the Awakening.** - Thus, while some of the New England states, New York, and Ohio possessed the only definitely organized systems of public education, the movement for common schools had made some progress in all sections of the country even before the educational awakening spread through the land. A radical modification had taken place in the European institutions with which education in the United States began. To meet the demands of the new environment, education had become more democratic and less religious and sectarian. Wealth had become much greater and material interests had met with a marked growth. The old aristocratic institutions had begun to disappear. Town and district schools had been taking the place of the old church, private, and 'field' schools, and in some of the cities the foundation for public education was being laid by quasipublic societies or even through local taxation. The academies (Fig. 32) had replaced the 'grammar' schools, and the colleges had lost their distinctly ecclesiastical character. State universities were starting in the South and Northwest. All these evidences of the growth of democracy, nonsectarianism, and popular training in education were destined to be greatly multiplied and spread before long. Such an awakening will be found to be characteristic of the great development of common schools that took place in the decades around the middle of the nineteenth century. But, before pursuing the subject further, we must direct our attention to some new reforms in method and content that were being introduced by Pestalozzi into education in Europe and were destined to produce a great stimulus in the public systems of the United States.

**Supplementary Reading**

Graves, *In Modern Times* (Macmillan, 1913), chap. IV; Parker. *Modern Elementary Education* (Ginn, 1912), chap. XII. A general, but not always accurate account of the period has been contributed by Mayo, A. D., to the Report of the U. S. Commissioner of Education, 1893-94, XVI; 1894-95, XXVIII; 1893-96, VI and VII; 1897-98, XI; and 1898-99, VIII. For the special states, see Adams, H. B., *Thomas Jefferson and the University of Virginia* (United States Bureau of Education, Circular of Information, 1888, no. 1); Boone, R. G., *History of Education in Indiana* (Appleton, 1892), chaps. I - III, and V-VII; Johnston, R. M., *Early Educational Life in Middle Georgia* (Report of the U. S. Commissioner of Education, 1894-95, XVI, and 1895-96, VII); Martin, G. H., *Evolution of the Massachusetts Public School System* (Appleton, 1894), lect. III; Palmer, A. E., *The New York Public School* (Macmillan, 1905); Randall, S. S., *History of the Common School System of the Slate of New York* (Ivison, Blakeman, Taylor, New York, 1871) Second Period; Smith, C. L., *History of Education in North Carolina* (U. S. Bureau of Education, Circular of Information, no. 2,1888); Smith, W. L., *Historical Sketch of Education in Michigan* (Lansing, 1881), pp. 1-7, 39-49, and 57-78; Steiner, B. C, *History of Education in Connecticut* (U. S. Bureau, Circular of Information, no. 2, 1893), and *History of Education in Maryland* (U. S. Bureau, Circular of Information, no. 2, 1894), chaps. II-IV; Stock well, T. B., *History of Public Education in Rhode Island* (Providence Press Co., Providence, 1876), chaps. II-V; Updegraff, H., *The Origin of the Moving School in Massachusetts* (Columbia University, Teachers College Contributions, no. 17, 1907), chaps. V-X; Wickersham, J. P., *History of Education in Pennsylvania* (Lancaster, Pennsylvania, 1886), chaps. XIII-XVII.