# 25. The Development of Modern Systems of Education

**Outline**

-   The leading states of Western Europe and of Canada have, during the past century and a half, organized systems of education, which may prove suggestive.
-   In Prussia, owing to a strong line of monarchs, state control has taken the place of ecclesiastical through a series of decrees and enactments. The people's schools are quite separate from the secondary schools. Three types of secondary institutions have developed, - the 'gymnasium,' with the classics as staples; the 'real-school,' with modern languages and sciences; and the 'realgymnasium,' with its compromise between the other two. The universities have likewise been emancipated from ecclesiastical control.
-   In France, a highly centralized system has been developed. Napoleon united secondary and higher education in a single corporation; under Louis Philippe, an organization of elementary schools was made; and, during the third republic, elementary education has been made free, compulsory, and secular. The present secondary system - *lyctes* and communal colleges - began with Napoleon, and has now been differentiated into several courses. One-half of the universities established by Napoleon were suppressed during the Restoration, but since 1896 there has been a university in each of the sixteen 'academies,' save one.
-   In England national education has grown out of the conflict of a number of social elements. The sentiment for universal training appeared toward the close of the eighteenth century, but not until 1870 were 'board schools' established. In 1899 a central Board of Education was created; and the Act of 1902, while permitting voluntary schools to share in the local rates, unified the system and established secondary education at public expense. During the nineteenth century also the classical and ecclesiastical monopoly in secondary and higher education was largely broken.
-   In Canada there have developed two types of educational control, - (1) the closely centralized system of public schools in Ontario, and (2) the public supervision of ecclesiastical schools In Quebec.

National Systems of Education in Europe and Canada. - In previous chapters (XVII, XXI, XXIII) we have witnessed the gradual evolution in America of state systems of universal education out of the unorganized and rather aristocratic arrangement of schools that had first been transplanted from Europe in the seventeenth century. But development of a centralized organization of public schools has not been confined to the United States. During the past century and a half, the leading powers of Western Europe and Canada have likewise organized state systems of education, similar in some respects to those of the American union. All of these states educatfonfree, have now established universal elementary education free oF1\^tuitous to all, although as yet in few instances are secondary g\^f~s~^ar^\^~nd~ schools also gratuitous, and only Canada has welded her France alone

, - , secularized.

elementary and secondary systems. France alone has completely secularized its system, but the public schools of the other nations, while still including religious instruction, have been emancipated from ecclesiastical control, and are responsible to the civil authorities. In all of them school attendance is compulsory. Yet the educational system in none of these countries is identical with that in the United States, but has been adapted in each case to the genius and social organization of the people concerned. Its characteristics must, therefore, be considerably modified, in order to be utilized or to prove suggestive to the United States or other nations, and can be understood only in the light of the educational history of the particular country to which it bewfen\^under- longs. For an intelligent appreciation of these modem toricaiiy^8^ school systems, we must, therefore, trace the gradual development to their present form in response to the changing ideals of successive periods.

The Beginning of State Control in Prussia. - We may look first at Germany. Up to the later years of the eighteenth century all stages of education in the various German states remained almost entirely under ecclesiastical control, but during this period the schools and universities were taken over by the state from the church, although the clergy still exercised a few prerogatives, and centralized national systems were gradually organized. Among these states of Germany the first and most influential in the organization of universal education was Prussia. While each of the others is characterized by an educational history and peculiarities of its own, this state may be taken as an illustration of the Rise of Prus- evolution of German school systems. The rise of Prussia,

sian education

due to eniight- educationally as well as politically, seems to have been ^cspo^'' due to the strong Hohenzollern monarchs, - despotic, but thoroughly awake to the interests of their people. Although for nearly two centuries state control of education was carried on more or less through the medium of the church, its development was well under way by the seventeenth century. While the 'consistory,' or board of supervision, was still composed largely of the clergy, the schools were soon (1687) declared not to be simply church organizations, but to belong to the state, and some attempt was made to extend schools to the villages as well as cities. But the first noteworthy attempt to establish compulsory attendance occurred during the reign of Frederick William I. In 1717 that monarch decreed that, wherever schools existed, children £ornpu1S\>TM ^f^°^r^ should be required to attend during the winter, and in |\*\^\^"Jfvn the summer whenever they could be spared by their Bam 1 in 1717; parents, which must be at least once a week. He also founded the first teachers' seminary at Stettin from his own private means (1735), and the next year had a definite law passed, making education compulsory for children from six to twelve years of age.

Educational Achievements of Frederick the Great. - His most important contribution, however, consisted in preparing the way for an educational movement that was to be greatly developed through his more able son, Frederick the Great. Frederick began by improving the administration of secondary education, and requiring that all vacancies on crown lands be filled by graduates from Hecker's normal school at Berlin. But the great step toward a national system was taken in 1763, when Frederick issued his *General School Regulations for* W *General*

....... *School Regula*

*ble Country.* This decree required children to attend *tions* decreed

school from five until thirteen or fourteen, and until in 1763, they "know not only what is necessary of Christianity, fluent reading, and writing, but can give answer in every- thing which they learn from the school books prescribed and approved by our consistory." If any pupils should arrive at this state of proficiency before thirteen or four- teen, they could even then leave school only through the official certification of the teacher, minister, and

inspector. Provision was also made for the attendance of children who had to herd cattle or were too poor to pay the school fees. Sunday continuation schools were to be established for young people beyond the school age. Teachers must have attended Hecker's seminary and had to be examined and licensed by the inspector. This decree was two years later supplemented with by^P^ReT/o/i^?^TO5 ^s^TMil^ar^ *Regulations for the Catholic Schools in Silesia, Schools\^\*"* drawn up by Abbot Felbiger. The carrying out of the decree was, however, stubbornly opposed by many teachers, who could not meet the new requirements; by farmers, who objected to the loss of their children's time; and by the nobles, who feared the discontent and uprising of the peasants, in case they were educated. The execution of the regulation was still in the power of the clergy, and for some time it proved but little more than a pious wish. But Frederick strove hard to have it enforced, and it became the foundation for the more effective laws that have since become embodied in the Prussian school system.

Educational Influence of Zedlitz. - After 1771 the educational work of Frederick was substantially aided by the appointment of Baron von Zedlitz as head of the Department of the Lutheran Church and School Affairs. This great minister had been much impressed by Basedow's principles and experiments and by Rochow's application of the 'naturalistic' training, and through him village schools were greatly strengthened and enriched, a regular normal school was opened at Halberstadt, and the humanistic ideal of secondary education revived.

\(3) Establishment of Central Board of

Administra- under the reactionary monarch, Frederick William II,

ment of Cen- A year after Frederick's death Zedlitz succeeded, even

tral Board of"

in further developing the nationalization of education, tion under

Frederick Wil

In 1787 an *Oberschulcollegium,* or central board of school Ham 11 in administration, was appointed instead of the former ^I7^ ^7^' church consistories. However, while the organization was supposed to be made up of educational experts, and Zedlitz was actually made chairman, the membership was mostly filled from the clergy, and the king refused to extend its jurisdiction to the higher schools.

Despite the reactionary policy of the sovereign, the culmination of the attempts to establish a national nonsectarian system of education occurred during this reign. In 1794 there was published the *General Code,* in which £f Ge\^\^aSe the chapter upon education declared unequivocally that^in^ '794; "all schools and universities are under the supervision of the state, and are at all times subject to its examination and inspection." Teachers were, therefore, not to be chosen without the consent of the state, and where their appointment was not vested in particular persons, it was to belong to the state. Teachers of all secondary schools were to be regarded as state officials. No child was to be excluded from the schools because of his religion, nor compelled to stay for religious instruction when it differed from the belief in which he had been brought up.

Foundation of the Ministry of Education and Further Progress. - While this comprehensive code met with much opposition from the clergy and the ignorant masses, and the next king, Frederick William III, weakly yielded at first, the humiliation of Prussia by Napoleon (1803) brought the country to a realization of the need of a centralized organization of the school system. The *Oberschulcollegium* was abolished, to get rid of the clerical<span id="ch25.xml#para.451.1.0.box.85.234.1259.42.q.60" class="gtxt_body"> (5) Creation of domination that had crept in, and a Bureau of Educa</span>

a Bureau of , . \_ .

Education in tion was created as a section of the Department of the Inlater'became a terior in 1807. The Bureau was within a decade erected istryandthen into a separate Department or Ministry of Education, organized\*\* Eight years later (1825) the state was divided into educational provinces; and a *Schulcollegium,* or administrative board, with considerable independence, but subject to the minister, was established over each province. Since then there have been many further developments, and provinces themselves are now divided into 'governments,' each of which has a' school commission' over it, and every government is divided into 'districts,' whose chief officer is a 'school inspector.' Under the district inspector are local inspectors, and each separate school also has a local board, to take charge of repairs, supplies, and other external matters.

Thus the supreme management of the schools has been gradually coming into the hands of the state for nearly two centuries. The decrees of 1717 and 1763, the establishment of the *Oberschulcollegium* in 1787, the General Code promulgated in 1794, the foundation of a distinct civic administration of education in 1807, are the milestones that mark the way to state control. But, while the influence of the church has been constantly diminishing, many of the board members are ministers or priests and the inspectors come mostly from the clergy. Moreover, religious instruction forms part of the course in every school, although it is given at such an hour that any pupil may withdraw if. the teaching is contrary to the faith in which he has been reared. The secondary schools are largely interdenominational, but in elementary education there are separate schools<span id="ch25.xml#para.452.1.0.box.111.220.1047.88.q.70" class="gtxt_body"> for Catholics and Protestants, alike supported by the state.</span>

The Elementary System. - Prussia, like most of the principal states of Europe, as a result of their educational history, has its elementary and secondary systems quite separate and distinct from each other (Fig. 48). The universities continue the work of the gymnasiums and real-schools, but these two latter institutions parallel the work of the *Volksschiden* (people's schools), rather than *Voiksschacn,* supplement it. The course of the secondary school ordinarily occupies the pupil from nine to eighteen years of age, while that of the elementary school carries him from six to fourteen, and after the first three years it is practically impossible to transfer from the elementary to the secondary system. A pupil cannot enter a gymnasium or real-school after completing the people's school, and the only further training he can obtain is that of the *Fortbildungschulen,* or 'continuation schools,' which supple- 'Continuation

schools \*

ment the system (seep. 420). The people's schools are gratuitous and are attended mostly by the children of the lower classes, while the gymnasiums charge a tuition fee and are patronized by the professional classes and aristocracy. Hence the line between elementary and secondary education in Prussia is longitudinal and not latitudinal, as it is in the United States; the distinction is one of wealth and social status rather than of educational grade and advancement. There are also some *Mittelschulen* (middle schools) for the middle ^and^ *urna*classes of people, who cannot send their children to the secondary schools, and yet can afford some exclusiveness. They have one more class than the people's schools, include a foreign language during

the last three years, and require teachers with a better training. The Secondary System. - The main types of secondary foSSSi,\^ ^schools^ ^in^ Prussia are the *Gymnasien* (see p. 114), with the classic languages as the main feature of their course, and the *Realschulen,* or real-schools (see p. 176), characterized by larger amounts of the modern languages, mathematics, and the natural sciences. For more than a century after the first real-school was opened in Berlin by Hecker (1747), this type of institution had only six years in its course, and was considered inferior to the gymnasium. By the ministerial decree of 1859, however, two classes of real-schools were recognized, and those of the first class had a course of nine years, and included Latin, but not Greek. They were given full standing as secondary schools, and graduates were granted admission to the universities, except for the study of theology, medicine, or law. The course of the second class of these institutions contained no Latin, and was but six years in length. In 1882 the compromise character of the course of the first class of institutions led to their being designated as *Realgymnasien,* while the second class in some instances had their work extended to nine years and became known as *Oberrealschulen.* The graduates were then allowed the privilege of studying at the universities in mathematics and the natural sciences. Since 1901 the university courses have been thrown open to graduates of any of the three types of secondary schools, except that, to be eligible for theology, one must have completed the course of a gymnasium, and for medicine, the course of a real-gymnasium at least. Besides these schools that have been mentioned, in rural

*Realgymna sien* and *Oberrealschulen;*

districts where a complete course cannot be maintained, there are often secondary institutions that do not carry the student more than six years. These are known, according to the curriculum, as *Progymnasien, Real-* *progymnasien,* and *Realschulen.* The first two classes are far less common than institutions with the longer course of the same character, but the *Realschulen* are ^six^-y^ear^

'courses;

nearly twice as numerous as the *Oberrealschulen.*

Since these three types of secondary institutions are so distinct from each other (Fig. 48), it is evident that a parent is forced to decide the future career of his boy at nine years, long before his special ability can be known. If he once enters a real-school, he can never transfer to a gymnasium, because the Latin begins in the lowest class of the latter course, nor can he enter the gymnasium from the real-gymnasium, after twelve, since he has had no Greek. To overcome this objection, during the past quarter of a century efforts have been made to delay the irrevocable decision by grouping all three courses as one institution and making them identical as long as possible. In secondary schools of this new sort, French is usually the only foreign language taught for the first three years. Then the course divides, and one section takes up Latin and the other English. After two years more a further bifurcation takes place in the Latin section, and one group begins with Greek, while the other studies English. These institutions are known as *Reformschulen* (Fig. 48), *Mormchuien;* and the plan was first introduced at Frankfort in 1892. The 'reform schools' are now growing rapidly, and there is evident an increasing tendency to postpone the choice of courses as long as possible. The three years of training preliminary to admission to a secondary school of

the *Vorschule.*

Universities state institutions, but controlled by

charters and decrees.

*Tecknische* *Hochschulen.*

any type may be obtained through the people's or the middle schools. But there has also grown up, as an attachment of the secondary schools, a *Vorschule* (preparatory school), to perform this function for pupils of the more exclusive classes.

Higher Education. - Like the other stages of education, the universities are now emancipated from ecclesiastical control, and may be regarded as part of the national system of education. The university is now coordinate and under the same authority with the church, for both are legally state institutions. Universities can, therefore, be established only by the state or with the approval of the state. In general, however, they are not controlled by legislation, but through charters and special decrees of the minister of education. As their income from endowments and fees is very small, they are for the most part supported by the state. They are managed internally by the rector and senate. The rector is annually chosen from their number by the full professors, with the approval of the minister, and the senate is a committee from the various faculties. The professors are regarded as civil servants with definite privileges, and they are appointed by the minister, although the suggestions of the faculty concerned are usually respected.

During the nineteenth century new institutions for the cultivation of science in application to practical and technological purposes have developed from technical schools of a more elementary character. While known as 'technical high schools' *(Tecknische Hochschulen),* they are institutions of higher learning, and exist side by side with the universities. They include schools of

engineering, mining, forestry, agriculture, veterinary medicine, and commerce.

Educational Development in France. - The development of a centralized system of education in France began almost a century later than in Germany. During the eighteenth and the early nineteenth century the different monarchic powers were not at all favorable to training the masses, and popular education was badly neglected. It required several revolutions in government and the establishment of a permanent republic, to break *the* old traditions completely, and to make it evident that universal suffrage should be accompanied by universal education. Just after the middle of the eighteenth century the revolutionary spirit began to First agitation

^0^ \* » *^r^* ° for elementary

manifest itself with the appearance of Rousseau's *Emile* education dur

. . , , . . 111 ing the Revolu

(see p. 222), and, except for the traimng started by the tion. Christian Brothers (see p. 140), the first serious atten- tion was given to elementary education. Holland, to whom a general plan for reorganization had been com- mitted, recommended universal education and an ade- quate number of training schools for teachers. While his proposals were not adopted, they were the basis of much of the short-lived legislation that arose during the Revolution, and of the great principles of educational administration that have since been established.

Napoleon, from the beginning, endeavored to reorganize education upon a better basis, and when he had become emperor, ordered all the lycees, secondary colleges, and faculties of higher education to be united in a single corporation, dependent upon the state and known as the 'University of France' (1808). This decree of Napoleon and

, . , . the University

centralization divided the country into twenty-seven of France.

administrative 'academies,' each of which was to establish university faculties of letters and science near the principal lycees.

This organization, however, did not include elementary education, and little attempt was made to provide for schools of this grade before the reign of Louis Philippe. Upon the advice of his great minister of education, Skc\^rimar Guizot, that monarch organized primary education, schools began, requiring a school for each commune, or at least for a group of two or three communes, and starting higher primary schools in the department capitals and in communes of over six thousand inhabitants (1833). He also instituted inspectors of primary schools, and established department normal schools under the more effective control of the state authorities. The plan for higher primary schools was never fully realized, and the institutions of this sort that had been established disappeared during the second empire. The reactionary law of Falloux (1850) did not even mention these schools, but encouraged the development of denominational schools.

The Primary School System. - Guizot, however, had

given a permanent impulse to popular education, and

during the third republic foundations for a national sys

Under third tem of education have rapidly been laid. Schools have

republic pn- \*'

mary system been brought into the smallest villages, and elementary 'education has been made free to all (1881) and compulsory between the ages of six and thirteen (1882). To provide trained teachers, every department has been

schools^1^ required to provide a normal school for teachers of each

sex; and two higher normal schools, one for men and one for women, to train teachers for the departmental normal schools, have been opened by the state (1882).<span id="ch25.xml#para.460.1.0.box.102.243.1227.901.q.60" class="gtxt_body"> The higher primary schools have been reestablished and Higher priextended (1898), and 'supplementary courses' offered tinuation for pupils remaining at the lower primary schools after *^x^* °°' graduation. The studies in the supplementary courses are technical, as well as general, and some of the higher primary schools have been established for vocational training rather than literary. In addition, there are continuation 'schools of manual apprenticeship' in the various communes, subsidized by the state for industrial and agricultural education, and five large schools for training in special crafts have been organized in Paris. Institutions for children between two and six years of age became part of the primary system in the days of \^S\*^1^ Guizot (1833), and half a century later the present name, *ecoles maternelles* (see p. 244), was adopted (1881), although there have since been marked reforms made in the curriculum.</span>

Secularization of the school system has also gradually Secularization, taken place. First, the courses of study were secularized by the substitution of civic and moral instruction for religious (1881); next, the instructional force was secularized by providing that members of the clergy should no longer be employed in the public schools (1886), and by recognizing public school teachers as state officers (1889); and finally, the schools themselves were completely secularized by compelling the teaching orders to report to the state authorities (1902), and afterwards by closing the free schools directed by them (1904). Thus within a generation universal elementary education has been established in France and brought completely under state control.

The Secondary System. - As in Prussia, the secondary

Development of lycees and communal colleges.

Organization oflycees

and colleges.

school system of France does not connect with the primary, but is quite separate and distinct (Fig. 49). The training has, since the time of Napoleon, been furnished chiefly by the lycees and communal colleges. During the Restoration (1814-1830) and the reign of Louis Philippe (1830-1848) the lycees came to be called 'royal colleges,' but, with the advent of the second republic (1848-1851), the Napoleonic name was restored and the curricula were completely reorganized. By this revision some elasticity was introduced into the last three years of the lycee by a bifurcation into a literary and a scientific course, and during the third republic further elections were introduced, until finally (1902) four distinct courses were established. In the leading lycees and colleges special preparation is also afforded for schools like the military institution of St. Cyr or the Polytechnic of Paris; and in some there is a short course of three or four years in modern languages and sciences that in function closely approaches that of the German real-school.

The boys ordinarily begin the first 'cycle' of the lycee or college at ten years of age, and while they may transfer from the primary system at this stage, in most lycees and colleges there are preparatory classes to train the pupil from six to ten. The second 'cycle,' during which the differentiation in courses largely occurs, takes the pupil from fourteen to seventeen, and leads upon completion to the bachelor's degree. Education in a lycee or college is not gratuitous, but the income from tuition fees is so small as to cover but a small fraction of the cost, and the rest is contributed by the state. The communal colleges differ from the lycees in being local, and they are maintained by the communes, as well as by the state.<span id="ch25.xml#para.462.1.0.box.103.252.1268.368.q.60" class="gtxt_body"> They have not the same standing, and the same attainments are not required of their professors. Until 1880 there were no lycees and communal colleges for girls, and convents and private schools furnished the only means Secondary bof female education. Even now the usual course in the for girls. public secondary institutions for girls is two years shorter than in those for boys.</span>

The Institutions of Higher Education. - More than one-half of the universities established in the various 'academies' by Napoleon were suppressed as soon as andratoration the monarchy was restored. But about half a dozen °.^f^'^he^ univer

•' sities.

were reopened in the reign of Louis Philippe, and were gradually improved by the addition of new chairs. Beginning in 1885, a number of decrees established a general council of faculties in each academy to coordinate the different courses and studies, and in 1896 a law was passed, which established a university in each of the sixteen 'academies,' except one. These universities differ greatly in size, but all grant the *license,* or master's degree, and the doctorate. The university degrees are Degrees, ordinarily conferred in the name of the state and carry certain definite rights with them, but of late years a new type of degree, 'doctorate of the university,' is granted upon easier terms to foreigners more desirous of the degree than of its state privileges. In Paris, besides the university, there is the College of France, which still endeavors to foster freedom of thought (see p. no), and a dozen other institutions of university grade, con- *9°\*TM \*&\*\**

. , , institutions.

nected with some special line, have been established.

Centralized Administration of the French Education. - The centralization of education is even more complete in France than in Germany. The supreme head of the<span id="ch25.xml#para.463.1.0.box.95.217.1263.802.q.60" class="gtxt_body"> Duties of system is the minister of education. He is immediately assisted by three directors, one each for primary, secondrectors, ary, and higher education. A rector is in charge of each of the 'academies,' except Paris, where the minister nominally holds the office and a vice rector performs the duties. The rector has authority over all three fields of education in his academy, but does not appoint the prefects, teachers. That office is performed by the prefect, or head of each civil department, upon the recommendation of the academy inspector. There is also a departmental council, presided over by the prefect, that appoints delegates in each canton, to take charge of the school premises and equipment. Further organization is effected through the maintenance of a complete corps of and inspectors, general, academy, and primary inspectors.</span>

Early Development of English Education. - In England the nationalization of education was delayed even longer than in France. This country was never controlled by enlightened despots, who could, as in Germany, force the growth of public educational sentiment, nor was it overwhelmed by the sweep of a great revolution, destroying, as in France, all opposition to popular progress. National education in England has gradually Slow evolution, grown out of the conflict of a number of elements represented in its society. It has been the product of a series of compromises among many different factors, - the church, state, economic conditions, private enterprise, and philanthropy. For several centuries education was regarded as a function of the church and family, and the nopory^1^ "\^ sentiment for universal training was retarded by the attitude of the upper classes, who strove to keep the poor in ignorance and to maintain the educational control<span id="ch25.xml#para.464.1.0.box.98.226.1243.738.q.60" class="gtxt_body"> of the church. This domination was first seriously challenged in the eighteenth century, and while the training then furnished through the Society for the Promotion of Christian Knowledge, the Sunday schools, and other philanthropic institutions (see pp. 232 ff.), was rather ?\^J^n^S^1Iopic^ meager, these organizations, together with the 'monitorial' instruction of the British and Foreign, and the National Societies (see pp. 240 f.), greatly advanced the cause of universal education. And toward the close of the century there began to appear a new point of view, especially with men like Bentham, Blackstone, Robert Owen, and Adam Smith, who advocated universal education, compulsory attendance, and a national system of schools.</span>

Educational Movements in the Nineteenth Century. - The theory of these great thinkers was somewhat in advance of the times, but, early in the nineteenth century, social changes began to favor better educational First signs of opportunities. The Factory Act (1802) provided for the obligatory training of apprentices; Mr. Whithread introduced (1807) a bill to permit the civic officials of any township or parish to establish schools for the poor wherever none existed; and Brougham, while losing his bill for popular education (1820), previously secured two commissions of inquiry on school facilities. In 1832, the passage of a reform bill, which largely increased the suffrage, aroused Parliament to the need of educating the masses, and the next year the first grant, £20,000, J\^J\^IIjint was made for elementary education. This sum was to <span style="font-variant:small-caps;">^!d^ </span>1833. be used solely to aid in building schoolhouses for which subscriptions had been privately obtained, and so could be passed as a vote of 'supply,' without referring it

to the House of Lords. For lack of a government organization of education, it was apportioned through the National and the British and Foreign Societies (see p. 240). Governmental activities constantly increased. In 1839 the annual grant was increased to £30,000 and allowed to be used for elementary education without restriction. In the same year, a separate comCommittee of mittee of the Privy Council was designated to adin i83g. minister the educational grants; and in 1856 a Vice

President was appointed to act as chairman of this educational committee. Then, in 1861, through another commission on popular education, it was arranged to base the grant to any school upon the results shown by resuits'iii 86 \^ pupils in the governmental examinations. This'payment by results' was intended to increase efficiency, but, used as a sole means of testing, it soon proved narrowing and unfair, and had to be supplemented by the general opinion formed of each school by the inspectors. Yet it somewhat increased the efficiency of the work.

Agitation in behalf of universal education continued, and organizations like the 'Lancashire Public School Association' of Manchester (1847) and 'The League' of Birmingham (1869) spread rapidly through the manufacturing centers. And when the franchise was further extended in 1868, the necessity for preparing millions of the common people for new responsibilities in public in 1870 estab- affairs led in 1870 to the passage of the epoch-making 'board schools', bill of William E. Forster. Under this act'board schools,' local'rates,'as or institutions in charge of a board chosen by the people of the community, were to be established wherever a deficiency in the existing accommodations required it. The 'voluntary,' or denominational schools, most of<span id="ch25.xml#para.466.1.0.box.97.242.1054.693.q.60" class="gtxt_body"> which belonged to the Church of England, were to continue to share in the government grants upon equal terms with the new institutions, but the latter had also the benefit of local 'rates.' Elementary instruction in all schools had to be open to government inspection, and the amount of the grant was partly determined by the report of the inspectors. The board schools were forbidden to allow "any religious catechism or religious formulary, which is distinctive of any particular denomination;" and religious instruction in either type of school had to be placed at the beginning or end of the school session, so that, under the 'conscience clause' of the act, any scholar might conveniently withdraw at that time.</span>

well as grants.

This act of 1870 was, of course, the *magna charta* of national education, and has become the basis of much school legislation. The compromise in the bill that allowed the voluntary schools, with their sectarian instruction, to continue receiving government support, however, prevented a logical and consistent system from being established. The dual system of elementary schools continued to be developed in a variety of enactments. Compulsory attendance laws were passed (1876, StSid^Ulsory^ 1880), the minimum age of exemption was set first at minimum age, eleven years of age, and then raised to twelve (1893, 1899), and an extra grant, to take the place of tuition ^freetmtion^. fees (1891), made it possible for most schools to become absolutely free. Finally (1899), there was created a central Board of Education, which assumed the functions Education! °^f^ of the Committee of Privy Council on Education and similar agencies for managing educational interests.

Subsequent Educational Movements. - Within a generation of existence the board schools met with a phenom<span id="ch25.xml#para.467.2.0.box.296.236.1055.1721.q.60" class="gtxt_body">enal growth, and came to include about seventy per cent of the pupils. They were spending about half as much again upon each pupil as were the voluntary schools, and were able to engage a much better staff of teachers. This .extension of civil influence in education was bitterly opposed by the Established Church, and when the conservatives came into power through the assistance of the clergy, they passed the act of 1902, whereby the denominational schools were permitted to share also in the local rates. While under this act the administration of both board and voluntary schools was now centralized in the county and city councils, the immediate supervision of instruction in the individual schools was placed in the hands of a board of managers; and, despite their receipt of local taxes, the voluntary schools were required to have but two of their managers appointed by the council, and the other four were still selected by the denomination. Serious opposition to the enforcement of the new law arose among nonconformists and others, and coercive measures were taken by the government. The new act, however, while unfair to those outside the Church of England, tended to sweep away the dual system of public and church schools, since both were coming to rest upon a basis of public control and support. Since 1902 all elementary schools have been considered as part of one comprehensive system, and the board schools have been distinguished as 'provided schools' and the voluntary as 'nonprovided.' Moreover, under the legislation of 1902 steps were also taken to coordinate secondary with elementary education, and bring it somewhat within the public system. The board schools had early in their existence begun to develop upward into</span><span id="ch25.xml#para.468.1.0.box.114.234.1264.530.q.60" class="gtxt_body"> secondary education and before long had come to compete with the older grammar and public schools, but in 1900 the 'Cockerton judgment' forbade the use of local rates for other instruction than elementary, and it remained for the new act to impose upon councils the duty to support instruction in subjects beyond the elementary Instruction \^ work. The Board of Education was also empowered to pub\^Spen'se. inspect the work of the great public schools and other endowed secondary institutions, and to allow grants to all schools meeting the conditions of the Board.</span>

In 1902'voluntary' schools also allowed local rates,

but dual system swept away,

After the liberals returned to power, they continued the conservatives' policy of granting local rates to all elementary schools, and of bringing secondary education under public support and control. While the education bill of 1906, which was kept from passage by the House defeated?^06^ of Lords, did not recognize church schools as such, and insisted upon bringing them under the complete control of the public authorities, it made no attempt to return to the former dual system of schools and the isolation of secondary from elementary education. It still held also to religious, and, under safeguards, even to sectarian instruction in the elementary schools, and may yet be passed in a revised form. A voluntary committee for a 'resettlement in English elementary education,' through the mediation of the President of the Board of Education and the Archbishop of Canterbury, has formulated a plan, which concedes the principle of public control and ^but^ ?^ew^ r\>^lan^' support for all elementary schools and religious freedom schools under

1 .1 1 1 • *e* 1 public control.

for teachers and pupils, but provides local option for the continuance of denominational schools. Thus, while England is not prepared to adopt a secular system, like that of France and the United States, and has not yet<span id="ch25.xml#para.469.1.0.box.78.230.1265.476.q.50" class="gtxt_body"> fully articulated its secondary education with elementary, (Fig. 50), it is upon the high road to a complete centralization of school administration in the national government. During the nineteenth century also the classical and eccie^S^sStica°^d^ ecclesiastical monopoly in secondary and higher educaSokenm \^on ^was^ largely broken. All the older public and gramsecondary and ~mar~ schools (see pp. 412 f.) developed 'modern sides,' and tion. during the Victorian era a number of new schools were</span>

founded, which gave considerable attention to the modern languages and the sciences from the start. A recognition of the scientific ideals began also to appear in the curriculum of Cambridge (1851) and Oxford (1853), and the theological requirements for a degree were dropped (1856). By the last quarter of the century actual laboratories had been introduced, and students were freed from all doctrinal tests at both universities. Moreover, new universities, better adjusted to modern demands and more closely related to the school systems and the civil government, began to arise in manufacturing centers. Since 1889 such municipal or 'provincial' institutions as the Universities of Birmingham, Manchester, Leeds, Liverpool, and Bristol have sprung up, and the University of London, started as an examining body in 1836, has become a teaching institution.

Development of Education in the Dominion of Canada. - Canada developed schools in very early days. In the beginning education was cared for in the four provinces separately, and when the Dominion of Canada was finally formed (1867), the federal government left to each province the administration of public education within its borders. The same autonomy was extended

to the provinces that have since been admitted to the federation. Two types of educational control, - state ^Two^ tyi\*^3^and ecclesiastical, have been developing from the first. The former method is best illustrated by the system of Ontario; and the latter by that of Quebec. Ontario d) Ontario and

\(a) Quebec.

was settled mostly by emigrants from England, Scotland, and the United States, and practically all brought with them the concept of public control of education. The French Catholics of Quebec, on the other hand, naturally followed their traditions of parish schools.

The Public School System of Ontario. - The system of schools in Ontario began with the passage of its Common Schools Act in 1846. This was formulated after a careful study of the systems of Massachusetts, New York, and the European states, and included excellent elements from various systems and many original features of value. By 1871 this fundamental law had come to include free tuition, compulsory attendance, county inspection, and uniform examinations. In 1876 an even greater centralization of the provincial system was ef- Universal

^0^ *^r^ ^J^* education, and

fected through substituting for the chief superintendent since 1870

,.. ,, .... great centrah

a minister of education with much larger powers, and zation through bringing all stages of public education, - elementary, secondary, and higher schools, into much closer relationship. The minister now has many assistants, including an Advisory Council of Education; and he initiates and directs all school legislation, decides complaints and disputes, sets examinations for the high, elementary, model, and normal schools, prescribes the courses of study, chooses the text-books, and appoints the inspec- , , ,.

. . and subordi

tors. The system is further administered by subordinate nate authoriauthorities elected in the localities, whose duties are

Unification of the several stages of education.

Inspectors.

'Separate schools.'

clearly defined by law. The province is for educational purposes divided into counties, which are in turn divided into townships, and subdivided into sections and incorporated cities, towns, and villages. The central and local administrations are wisely balanced, and while the one determines scholastic standards through its professional requirements, the other establishes schools and appoints teachers.

The system of elementary schools, high schools, and universities, is fully unified, and the work of each stage fits into the others even more exactly than in the 'ladder' system of the United States. The training of teachers is cared for through the departments of Education in the universities, the eight provincial normal schools, and a model school in each county. The teachers for secondary institutions are prepared at the universities, the normal schools grant a life certificate to teach in the elementary schools, while the model schools afford fourteen weeks of training for country teachers. The buildings, equipment, courses, and instruction of the high, elementary, and model schools are each reported upon by inspectors of assured scholarship and experience. Since 1863 permission has been granted to establish 'separate schools' for any peculiar creed or race, wherever there are five families requesting it. This opportunity to have schools of their own faith has not been embraced by any save the Roman Catholics. Any one paying toward the support of a 'separate school' is exempt from taxation for the regular public schools. Special provincial inspectors report upon these schools, but in the same way as for the public schools.

The System of Ecclesiastical Schools in Quebec. - <span id="ch25.xml#para.474.1.0.box.93.248.1275.1452.q.60" class="gtxt_body"> The Ontario system may be considered typical of the educational administration in the various provinces of Canada, except Quebec. Every other province has j\^fJJJJ\^ ~t~ sought uniformity of school provision and educational Ontario, standards through government control, although none of them grant their central official quite as much power as Ontario. Alberta and Saskatchewan likewise permit 'separate schools,' and they existed in Manitoba until 1890. But the type of control in Quebec is very different from that of the other provinces. There in 1845 the in Quebec parish was by law made the unit of school administration. But seven years later government inspectors were estab- but since 1859 lished, and in 1859 a central organization was completed Public inwith a Council of Public Instruction. This authority is ^s^ ^ruc^ ^10n^ composed of two divisions, a Roman Catholic and a Protestant, which sit separately and administer the schools of their respective creeds. The provincial super- ^and^ superintendent of schools, appointed by the lieutenant gover- schools, nor, is *ex officio* chairman of both divisions, but he can vote only with the division to which he belongs by religion. Each division makes regulations for the instruction and tests of its own schools, and appoints inspectors School support of its own faith. The proceeds from the general public school fund or from any educational legacies are divided in proportion to the Catholic and Protestant inhabitants, but the regular school rate may be assigned to whichever of the two school systems the taxpayer wishes.</span>

**Supplementary Reading**

Graves, *In Modern Times* (Macmillan, 1913), chap. IX; Parker, *Modern Elementary Education* (Ginn, 1912), chaps. X and XI. The following works throw light upon various phases of the respective<span id="ch25.xml#para.475.1.0.box.288.231.1059.1275.q.50" class="gtxt_body"> countries: Nohle, E., *History of the German School System (Report of the U. S. Commissioner of Education,* 1897-1898; vol. I, pp. 2644); Paulsen, F., *German Education* (Scribner, 1908); Russell, J. E., *German Higher Schools* (Longmans, Green, 1896); Paulsen, F., *The German Universities* (Macmillan, 1895; Scribner, 1906); Kandel, I. L., *The Training of Elementary School Teachers in Germany* (Columbia University, *Teachers College Contributions,* No. 31, 1910); Brown, J. F., *The Training of Teachers for Secondary Schools in Germany* (Macmillan, 1911); Beard, Mary S., *Hcoles maternelles of Paris (Great Britain, Board of Education, Special Reports on Educational Subjects,* vol. VIII, no. 8); Farrington, F. E., *French Secondary Schools* (Longmans, Green, 1910) and *The Public Primary System of France* (Columbia University, *Teachers College Contributions to Education,* no. 7, 1906); Smith, Anna T., *Education in France (Reports of the United States Commissioner of Education,* 1890 to 1914, see tables of contents); Greenough, J. C, *The Evolution of the Elementary Schools of Great Britain* (Appleton, 1903); Montmorency, J. E. G. de, *State Intervention in English Education* (Macmillan, 1903); Sharpless, I., *English Education in Elementary and Secondary Schools* (Appleton, 1892); Smith, Anna T., *Education in England (Monroe Cyclopadia of Education,* vol. II); Sandiford, P., *The Training of Teachers in England and Wales* (Columbia University, *Teachers College Contributions,* no. 32, 1910); Coleman, H. T. J., *Public Education in Upper Canada* (Columbia University, *Teachers College Contributions,* no. 15, 1909); Ross, G. W., *The School System of Ontario* (Appleton, 1896); Smith, Anna T., *Education in Canada (Monroe Cyclopadia of Education,* vol. I).</span>